### ISSUE TITLE
allow phoenix_html 4.0 in oban_web 

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#1008]
I'm not sure what `oban_web` exactly uses from `phoenix_html`, but it should probably also allow v4.0?

**Comment by sorentwo** [comment]
Web is a full LiveView application and uses various features from `phoenix_html` to function, i.e. escaping html and building forms.

[Web v2.10.2 is out now](https://oban.pro/releases/web#2.10.2) with support for both `phoenix_html` 3.3 and 4.0.
