### ISSUE TITLE
Queue allowlist/denylist support for Lifeline Plugin

### ISSUE THREAD

**Issue by beeberino** [sorentwo/oban#1018]
An issue that we have is that we are unable to enable/disable queues using the lifeline plugin.

We have for instance a workflow with:

Event 1 -> Notification job for event 1 [state1]
Event 2 -> Notification job for event 2 [state2] (job is orphaned)
Event 3 -> Notification job for event 3 [state3]
Notification job for event 2 [state2] rescued and sends outdated data

We would like a queue-based allowlist/denylist so that we can prevent the Lifeline plugin from rescuing jobs on this queue.

As far as I am aware, that isn't possible to configure now (or possibly it isn't documented).  If there is a better solution available, we would also be very interested.

**Comment by sorentwo** [comment]
The `Lifeline` plugin is simplistic with minimal functionality. As noted in the [module docs](https://hexdocs.pm/oban/Oban.Plugins.Lifeline.html):

> This plugin may transition jobs that are genuinely `executing` and cause duplicate execution. For more accurate rescuing or to rescue jobs that have exhausted retry attempts see the `DynamicLifeline` plugin in [Oban Pro](https://getoban.pro/docs/pro/Oban.Pro.Plugins.DynamicLifeline.html).

If the `DynamicLifeline` isn't a viable alternative, you may need to build something custom to handle your use case.
