### ISSUE TITLE
Oban.Pro.Worker Hook Docs

### ISSUE THREAD

**Issue by nbw** [sorentwo/oban#1056]
Small typo, but since Pro isn't a public repo I'm logging it here.

- https://oban.pro/docs/pro/0.12.9/Oban.Pro.Worker.html#module-worker-hooks

- https://gist.github.com/sorentwo/80bf3dbf568e12bb5d44a2ff84af9b30#file-hooks-md

The line:
```elixir
extra = Map.take([:attempt, :id, :args, :max_attempts, :meta, :queue, :worker])
```

Should be:
```elixir
extra = Map.take(job, [:attempt, :id, :args, :max_attempts, :meta, :queue, :worker])
```

**Comment by sorentwo** [comment]
Thanks for the report. This is fixed in [current versions of the docs](https://oban.pro/docs/pro/1.3.5/Oban.Pro.Worker.html#module-defining-hooks)—there's a lot of new features and improvements since v0.12.9 🙂
