### ISSUE TITLE
`not_null_violation` Postgres error for Oban scheduled job

### ISSUE THREAD

**Issue by whatyouhide** [sorentwo/oban#1061]
### Environment

- PostgreSQL Version: 13.2
- Elixir: 1.16.1
- Erlang: 26.0.2
- Oban:

![CleanShot 2024-03-26 at 13 09 40@2x](https://github.com/sorentwo/oban/assets/3890250/2d93131e-f505-49e7-98be-5794a1b2b987)

### Current Behavior

We got many of these errors in Sentry (redacted actual worker name with `MyWorker`):

```
ERROR 23502 (not_null_violation) null value in column "id" of relation "oban_jobs" violates not-null constraint

    table: oban_jobs
    column: id

Failing row contains (null, available, default, MyWorker, {}, {}, 0, 1, null, null, null, null, null, null, null, {}, {"uniq_key": 101711374}, null).
```

The worker is configured like this:

```elixir
plugins: [
  {Oban.Plugins.Cron,
   crontab: [
     {"* * * * *", MyWorker},
     # ...
   ]}
]
```

The stacktrace of the error doesn't involve any of our app, only Oban, which is why I thought to report this:

![CleanShot 2024-03-26 at 13 16 16@2x](https://github.com/sorentwo/oban/assets/3890250/18edb8aa-7610-4292-8728-86e2bbc6530e)

It could totally still be something wrong we're doing, but I figured I'd give this a try here too 🙃

**Comment by sorentwo** [comment]
Does the original `MyWorker` have any unique configuration?

**Comment by sorentwo** [comment]
Some more follow up questions as I'm not able to recreate the exception:

1. Was this a rash of errors all at once, or is it an ongoing occurrence?
2. Is that worker also inserted as a regular job, not via cron?

**Comment by whatyouhide** [comment]
@sorentwo 

1. No, ongoing occurrence.
2. No, only via cron.

**Comment by whatyouhide** [comment]
Hi @sorentwo any updates on this? We're still seeing this, with around 1.4k occurrences in the past 24h if that helps. Let me know if there is any more context I can provide.

**Comment by sorentwo** [comment]
@whatyouhide We've been traveling since last week. I can check it out now that we've made it to Lisbon 🙁

**Comment by whatyouhide** [comment]
@sorentwo sounds perfect. Welcome to Europe if you're not from this side of the world! 🇪🇺

**Comment by sorentwo** [comment]
@whatyouhide After our discussions on Slack determining that this is limited to a staging environment I'm going to close this out. I'm willing to keep troubleshooting the environmental issue, but seeing as we're not able to recreate it I'd rather not have it looming.
