### ISSUE TITLE
Config for Oban.Met? Not seen this before from AppSignal 

### ISSUE THREAD

**Issue by ghenry** [sorentwo/oban#1063]
<h1 style="color: rgb(33, 55, 90); font-family: Helvetica, Arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 20px; font-weight: 700; line-height: 24px; margin: 0px 0px 10px;"><span style="color: rgb(210, 3, 37);">Exception:</span><span> </span>RuntimeError - Untriaged</h1><p style="color: rgb(33, 55, 90); font-family: Helvetica, Arial; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-top: 0px; line-height: 1.4;">Occurred in Oban.Web.DashboardLive#mount on<span> </span><strong>resi_switch</strong><span> </span>(prod) in live_view<br><span style="color: rgb(107, 123, 150);">on April 03, 2024 at 21:11 (UTC)</span></p><h2 style="font-family: Helvetica, Arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 12px; line-height: 1.4; color: rgb(107, 123, 150); font-weight: 700; margin: 0px 0px 12px;">MESSAGE</h2><pre style="white-space: pre-wrap; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(2, 73, 102); font-family: Monaco, &quot;Courier New&quot;, Courier, monospace; font-size: 11px; word-break: break-all; margin: 0px;">** (RuntimeError) no config registered for [Oban, Oban.Met] instance</pre><br style="color: rgb(33, 55, 90); font-family: Helvetica, Arial; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="font-family: Helvetica, Arial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 12px; line-height: 1.4; color: rgb(107, 123, 150); font-weight: 700; margin: 0px 0px 12px;">SUMMARY</h2>
File: | lib/oban/web/dashboard_live.ex:171 in Oban.Web.DashboardLive.await_init/3
-- | --
d89169dae4d4d8
 

<br class="Apple-interchange-newline">

**Comment by ghenry** [comment]
I must have missed these two plugins when I first set Oban Web up https://getoban.pro/docs/web/2.9.6/installation.html#configuration

**Comment by ghenry** [comment]
Actually, I was reading old docs. My config is correct as per:

https://getoban.pro/docs/web/2.10.3/installation.html#configuration

Will see if this was a one-off and keep this closed until then.

**Comment by sorentwo** [comment]
There have been intermittent reports of this issue, which seems to be a race condition in Oban Met's auto-start mechanism. It's possible to add `Oban.Met` as an Oban plugin and disable auto_start to work around it (which is documented in the next Met release):

```elixir
config :oban_met, auto_start: false
```

**Comment by ghenry** [comment]
Thanks. Will do if it comes up again.

**Comment by ghenry** [comment]
Yeah, seeing lots of this now, so doing as you suggest:

2024-04-04T16:26:43.628 app[d89169dae4d4d8] lhr [info] ** (RuntimeError) no
config registered for [Oban, Oban.Met] instance
