### ISSUE TITLE
Oban Pro v1.4 Workflow migration fails on Postgres 13 trigger creation

### ISSUE THREAD

**Issue by shamanime** [sorentwo/oban#1071]
### Environment

- Oban Version: 1.4.4
- PostgreSQL Version: 13
- Elixir & Erlang/OTP Versions (`elixir --version`): 1.16 OTP 26

### Current Behavior

Postgres 13 does not support `OR REPLACE` for triggers.

```
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "TRIGGER"

    query: CREATE OR REPLACE TRIGGER oban_workflow_trigger
AFTER DELETE ON "public".oban_jobs
FOR EACH ROW
WHEN (
  OLD.state::text NOT IN ('cancelled', 'completed', 'discarded')
  AND OLD.meta ? 'workflow_id'
)
EXECUTE FUNCTION "public".oban_workflow_cleanup();
```

### Expected Behavior

Migration should work with Postgres 13.

**Comment by sorentwo** [comment]
Thanks for the report! Fixed in the just-released [Pro v1.4.5](https://getoban.pro/docs/pro/1.4.5/changelog.html#v1-4-5-2024-04-22)
