### ISSUE TITLE
Support Stream in `Oban.Pro.Workers.Batch.new_batch/2`

### ISSUE THREAD

**Issue by up2jj** [sorentwo/oban#1090]
Currently, `Oban.Pro.Workers.Batch.new_batch/2` accepts list of args/jobs so it is not possible to prepare batch in streaming fashion like this:

```elixir
csv
|> download()
|> stream_csv_records()
|> MyBatchJob.new_batch()
|> Oban.insert_all(timeout: 60_000)
```
I made a workaround by adding `batch_id` manually:

```elixir
csv
|> download()
|> stream_csv_records()
|> Stream.map(fn row ->
  company_id
  |> create_job(row, operation)
  |> put_batch_id(batch_id)
end)
|> Oban.insert_all(timeout: 60_000)
```
and it seems to work, but I have mixed feeling about this as this approach relies on Oban's internals (meta, batch_id, etc.). I know that `new_batch/1` can be overridden but I believe it should be handled natively.

**Comment by up2jj** [comment]
Thanks for the explanation 👍🏻

**Comment by sorentwo** [comment]
This is on main for oban_pro and will be out soon (🤞) with v1.5
