### ISSUE TITLE
Oban.Pro.Workers.Workflow documentation typos

### ISSUE THREAD

**Issue by esambo** [sorentwo/oban#1118]
It would be nice to clean up some minor typos in the documentation

https://getoban.pro/docs/pro/1.4.10/Oban.Pro.Workers.Workflow.html#module-usage
```
- As a trivial example, we'll define an `EchoWorker` that only inspects that `args`, [...]
+ As a trivial example, we'll define an `EchoWorker` that only inspects the `args`, [...]
```

https://getoban.pro/docs/pro/1.4.10/Oban.Pro.Workers.Workflow.html#module-dynamic-workflows
```
- [...] The key us using Enum.reduce to accumulate a workflow with interpolated names [...]
+ [...] The key is using Enum.reduce to accumulate a workflow with interpolated names [...]
```

**Comment by sorentwo** [comment]
Thanks for the report. Fixed on main for the next release 👍
