### ISSUE TITLE
Jobs that exit with `{:error, ...` are logged at `info` level.

### ISSUE THREAD

**Issue by jozuas** [sorentwo/oban#1125]
### Environment

- Oban Version 2.17.11
- PostgreSQL Version 16
- Elixir & Erlang/OTP Versions (`elixir --version`): Erlang/OTP 26, Elixir 1.15.7.

### Current Behavior

```elixir
defmodule Tp.Smth do
  use Oban.Worker,
    queue: :testing,
    max_attempts: 1

  @impl Oban.Worker
  def perform(%Oban.Job{args: _args}) do
    {:error, "sample error message"}
  end
end
```

Produces the log at info level

```
18:15:45.963 pid=<0.923.0>  [info] {"error":"** (Oban.PerformError) Tp.Smth failed with {:error, \"sample error message\"}","args":{},"id":159,"meta":{},"state":"discard","max_attempts":1,"queue":"testing","worker":"Tp.Smth","source":"oban","attempt":1,"tags":[],"duration":3141,"event":"job:exception","queue_time":27019}
```

### Expected Behavior

Produces the log at error level

```
18:15:45.963 pid=<0.923.0>  [error] {"error":"** (Oban.PerformError) Tp.Smth failed with {:error, \"sample error message\"}","args":{},"id":159,"meta":{},"state":"discard","max_attempts":1,"queue":"testing","worker":"Tp.Smth","source":"oban","attempt":1,"tags":[],"duration":3141,"event":"job:exception","queue_time":27019}
```

**Comment by sorentwo** [comment]
The default logger outputs all events at the same level. Many error handlers (e.g. Sentry, HoneyBadger, AppSignal) will automatically report for any message at the `error` level, and they'll _also_ use telemetry info to report Oban errors.

The logger is built on telemetry data, so you can build a custom logger with various levels if desired.
