### ISSUE TITLE
Patch to support providing Oban name at runtime for Oban Web router

### ISSUE THREAD

**Issue by RobinBoers** [sorentwo/oban#1127]
Hi!

We're building an application where we start separate supervision trees (including Oban) for multiple tenants based on some configuration only available at runtime. When trying to mount the Oban Web router in our project, we had the problem that it required the Oban name at compile-time, while we only had it available at runtime (because we lookup the correct Oban instance based on the hostname).

To work around this, I created this patch that modifies the Oban Web router to also accept an MFA triple that returns the name, which I then sent to my coworkers:

```patch
From 0a213178ec73d77782d31c4c920dcf607eb9eb67 Mon Sep 17 00:00:00 2001
From: Robin Boers <robin@qdentity.nl>
Date: Thu, 25 Jul 2024 11:41:04 +0200
Subject: [PATCH] Add support for MFA triples as names in router.ex

---
 lib/oban/web/router.ex | 19 +++++++++++++++++--
 1 file changed, 17 insertions(+), 2 deletions(-)

diff --git a/lib/oban/web/router.ex b/lib/oban/web/router.ex
index 609bc82..18ad135 100644
--- a/lib/oban/web/router.ex
+++ b/lib/oban/web/router.ex
@@ -252,6 +252,12 @@ defmodule Oban.Web.Router do
 
     csp_keys = expand_csp_nonce_keys(csp_key)
 
+    oban =
+      case oban do
+        {m, f, a} -> apply(m, f, a)
+        oban when is_atom(oban) -> oban
+      end
+
     %{
       "prefix" => prefix,
       "oban" => oban,
@@ -288,11 +294,20 @@ defmodule Oban.Web.Router do
     end
   end
 
+  defp validate_opt!({:oban_name, {m, f, a} = name}) do
+    unless is_atom(m) and is_atom(f) and is_list(a) do
+      raise ArgumentError, """
+      invalid mfa-triple for :oban_name, expected
+      {module, function, args}, got: #{inspect(name)}
+      """
+    end
+  end
+
   defp validate_opt!({:oban_name, name}) do
     unless is_atom(name) do
       raise ArgumentError, """
-      invalid :oban_name, expected a module or atom,
-      got #{inspect(name)}
+      invalid :oban_name, expected a module, atom,
+      or mfa-triple; got #{inspect(name)}
       """
     end
   end
-- 
2.45.1
```

I wondered whether something like this could be merged into the upstream, so that it's available for everyone.

(I already sent you an email, but @dvic said I should have created an issue because then it's Googleable, sorry for the duplicate! :)

**Comment by sorentwo** [comment]
Hi @RobinBoers! Sorry, we didn't receive an email. If it had a patch in it perhaps it was flagged as spam?

That's a clever workaround. However, we have a different direction planned for the next version that will obviate the need to specify a name at all 😎
