### ISSUE TITLE
Documentation request: What happens if a job times out?

### ISSUE THREAD

**Issue by kybishop** [sorentwo/oban#1136]
[The documentation on timeouts](https://hexdocs.pm/oban/Oban.html#module-limiting-execution-time) does a great job of explaining how to add a timeout to a job, but does not explain what happens if a timeout occurs. Does it return `{:error, :timeout}`? Does it simply fail?

Would love to see the consequences of adding a timeout so we can plan accordingly in our error handlers 🙇

**Comment by sorentwo** [comment]
> Does it return {:error, :timeout}? Does it simply fail?

The short answer is that it errors with an `Oban.TimeoutError`. We'll update the docs with that info.
