### ISSUE TITLE
Oban Web - Very slow query on Jobs page

### ISSUE THREAD

**Issue by maennchen** [sorentwo/oban#1140]
### Environment

- Oban Version: `2.18.1`
- Oban Pro Version: `1.5.0-rc.1`
- Oban Web Version: `2.10.5`
- PostgreSQL Version: `15.1-1.pgdg20.04+1`
- Elixir & Erlang/OTP Versions (`elixir --version`): `1.17.2` on OTP `27.0.1`

### Current Behavior

I have a lot of jobs (currently sitting at 5M+) which I scheduled quickly and oban is now slowly executing for me. To check how far along it is, oban web would be great. Unfortunately, it is so slow that it result in a timeout of the query.

Offending Query:

```sql
SELECT o0."id", o0."args", o0."attempt", o0."attempted_by", o0."worker", o0."queue", o0."max_attempts", o0."meta", o0."state", o0."inserted_at", o0."attempted_at", o0."cancelled_at", o0."completed_at", o0."discarded_at", o0."scheduled_at" FROM "public"."oban_jobs" AS o0 WHERE ($1 AND (o0."state" = $2)) ORDER BY o0."attempted_at" LIMIT $3
```

Query Execution Plan: https://explain.dalibo.com/plan/b72a7bgc873cfe8f

I quickly attempted to just create an index on `state` & `attempted_at`. Unfortunately because of `$1`, that doesn't work.

When checking the code, i can see that `Oban.Web.Query.all_jobs/3` does an `Enum.reduce` on the parameters with an initial accumulator. I therefore assume that `$1` is just `TRUE`.

### Expected Behavior

With such a large amount of jobs, it is completely understandable if the page doesn't allow me to filter / sort around everything and still expect good performance. However the page in its default settings should load in a reasonable amount of time.

**Comment by sorentwo** [comment]
> I quickly attempted to just create an index on state & attempted_at. Unfortunately because of $1, that doesn't work.
>
> When checking the code, i can see that Oban.Web.Query.all_jobs/3 does an Enum.reduce on the parameters with an initial accumulator. I therefore assume that $1 is just TRUE.

You're correct that `$1` is `true`, but it doesn't appear to have any impact on the query plan. Creating an index for the `executing` state and `attempted_at` yields the expected index backed query plan (using `completed` instead because it has many more jobs locally):

```
                                                                       QUERY PLAN
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
 Limit  (cost=0.42..7.53 rows=30 width=426) (actual time=0.023..0.094 rows=30 loops=1)
   ->  Index Scan using oban_jobs_completed_at on oban_jobs o0  (cost=0.42..186844.57 rows=788546 width=426) (actual time=0.021..0.090 rows=30 loops=1)
 Planning Time: 0.228 ms
 Execution Time: 0.119 ms
(4 rows)
```

Perhaps it needed a `VACUUM ANALYZE` or app restart to force Ecto to get a new prepared plan?

Here's a list of partial indexes that cover all of the states and default sorting options:

```
-- executing
CREATE INDEX oban_jobs_attempted_at ON oban_jobs (state, attempted_at) where state = 'executing';

-- completed
CREATE INDEX oban_jobs_completed_at ON oban_jobs (state, completed_at) where state = 'completed';

-- available
CREATE INDEX oban_jobs_scheduled_at ON oban_jobs (state, scheduled_at) where state in ('available', 'retryable', 'scheduled');

-- cancelled
CREATE INDEX oban_jobs_cancelled_at ON oban_jobs (state, cancelled_at) where state = 'cancelled';

-- discarded
CREATE INDEX oban_jobs_discarded_at ON oban_jobs (state, discarded_at) where state = 'discarded';
```

We're hesitant to add more indexes to the `oban_jobs` table by default, but this is certainly a case where we should promote some indexes to improve the baseline performance.

We'll add a section to the web docs about additional indexes for dashboard performance 🙂

**Comment by sorentwo** [comment]
There's also a [`jobs_query_limit` callback](https://oban.pro/docs/web/2.10.5/Oban.Web.Resolver.html#c:jobs_query_limit/1) that you can use to limit the queried jobs for each state. By default, it only limits `completed` to the most recent 100k, but the other states are unlimited.

With 5 million incomplete jobs, you may want to apply a limit for all states, something like this:

```elixir
  def jobs_query_limit(_state), do: 250_000
```

**Comment by maennchen** [comment]
@sorentwo Thanks. I’ll try the callback omce my queue has filled up again 😊
