### ISSUE TITLE
Add build_job/3 as new test helper

### ISSUE THREAD

**Issue by viniciussbs** [sorentwo/oban#1147]
### Is your feature request related to a problem? Please describe.

I have some jobs that have their IDs stored somewhere when they're performed - for specific business rules. I would like to test this behaviour using existing test helpers, but `perform_job/3` only returns the result, not the job itself.

### Describe the Solution You'd Like

- Extract from `perform_job/3` the code that builds the job to a new function called `build_job/3`
- Add `perform_job/1` that would receive a job as argument and just execute it
- Make `perform_job/3` just `worker |> build_job(args, opts) |> perform_job()`

### Describe Alternatives You've Considered

1. Make existing `perform_job/3` return both the job and the result, but this would be a breaking change that can be avoided.
2. Change return type of my jobs to also return their IDs.

### Additional Context

I know we have `with_testing_mode/2`, but I believe simple helpers are more straightforward.

**Comment by sorentwo** [comment]
It's a good suggestion, and something I'm sure many people could have used in the past.

**Comment by sorentwo** [comment]
Done. This will be available in Oban v2.19

**Comment by viniciussbs** [comment]
Thank you so much!
