### ISSUE TITLE
[UI] assign @flash not available in eex template

### ISSUE THREAD

**Issue by jaimeiniesta** [sorentwo/oban#119]
Hi! I've had some crashes on Oban Web 0.6.2, on development and on production, that seem related to closed connections (for example when I restart the dev server due to a recompile, or after sleeping the laptop with an open tab on the Oban UI, and reconnecting hours later).

Nothing breaks on the UI (which is great) but I see this exception:

```
#470 GenServer terminating (ArgumentError): assign @flash not available in eex template. Please make sure all proper assigns have been set. If this is a child template, ensure assigns are given explicitly by the parent template as they are not automatically forwarded

Traceback (most recent call last):
File lib/phoenix_live_view/engine.ex line 769 in Phoenix.LiveView.Engine.fetch_assign!/2 (phoenix_live_view)
File lib/oban_web/templates/dashboard/index.html.leex line 1 in ObanWeb.DashboardView."index.html"/1 (oban_web)
File lib/phoenix_live_view/utils.ex line 70 in Phoenix.LiveView.Utils.to_rendered/2 (phoenix_live_view)
File lib/phoenix_live_view/channel.ex line 441 in Phoenix.LiveView.Channel.render_diff/2 (phoenix_live_view)
File lib/phoenix_live_view/channel.ex line 180 in Phoenix.LiveView.Channel.maybe_call_mount_handle_params/2 (phoenix_live_view)
File lib/phoenix_live_view/channel.ex line 523 in Phoenix.LiveView.Channel.verified_mount/4 (phoenix_live_view)
File lib/phoenix_live_view/channel.ex line 32 in Phoenix.LiveView.Channel.handle_info/2 (phoenix_live_view)
File gen_server.erl line 637 in :gen_server.try_dispatch/4 (stdlib)

GenServer terminating (ArgumentError): assign @flash not available in eex template.

Please make sure all proper assigns have been set. If this is a child template, ensure assigns are given explicitly by the parent template as they are not automatically forwarded.

Available assigns: [:socket]
```

**Comment by axelson** [comment]
I've been running into this too

**Comment by jaimeiniesta** [comment]
I've verified that this keeps happening in 0.6.2 - to reproduce it, just launch the app and with an open browser on the UI, exit the app and restart it. The UI reestablishes the connection, but this error appears on the logs.

**Comment by sorentwo** [comment]
Strangely I'm having trouble recreating this. I'll keep looking and get back to you.

**Comment by jaimeiniesta** [comment]
Thanks, for development I'm using Elixir 1.8.1, OTP 22, phoenix 1.4.11 on macOS 10.15.1, chrome 78.

**Comment by balexand** [comment]
I can reproduce this consistently by following these steps:

1. Start dev server
2. Visit Oban UI dashboard (http://localhost:4000/oban) in Google Chrome
3. Stop dev server (crtl-c in terminal)
4. Start dev server again while the browser window in step 2 is still open

**Comment by balexand** [comment]
In the meantime, you can work around the bug by always closing browser tabs that are on the Oban UI before restarting any servers.

**Comment by sorentwo** [comment]
I've managed to recreate this issue a couple of times, but not reliably. Anyhow, ObanWeb has a fix on master. It will be in `v0.6.3`.

**Comment by axelson** [comment]
Great, thanks!
