### ISSUE TITLE
Postgres schemas

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#12]
Does Oban support Postgres schemas (`:prefix` in Ecto) or are there plans to support them?

**Comment by sorentwo** [comment]
Oban doesn't yet support schemas, but it is on the immediate roadmap to support them. Thanks for opening an issue, it will push schema support along!

**Comment by sorentwo** [comment]
Update: v0.4.0 was just released prefix/source support didn't make the cut. However, I finally figured out a clean way to do it and it will be one of the primary features in v0.5.0.

**Comment by sorentwo** [comment]
Update (Again): v0.5.0 was also released without prefix/source support. I've made two attempts at adding prefix/source support so far and have made headway. Part of that is learning what _not_ to do, and what other things need to change. This is now slated for v0.6.0.

It hasn't been forgotten!
