### ISSUE TITLE
Worker unique period not respected for crontab job

### ISSUE THREAD

**Issue by DavidOliver** [sorentwo/oban#120]
Hi, and thanks for Oban, which I'm in the process of adding to an app for the first time, in an Umbrella project with some Phoenix apps. (Apologies if I'm doing something wrong or misunderstanding intended operation.)

It seems like the `Worker`-config unique job period is not being enforced, at least for the `crontab`-set jobs I'm starting with.

The following results in the job being executed only once every approximately five minutes, as expected.

```elixir
config :my_app, Oban,
  repo: MyApp.Repo,
  prune: {:maxlen, 100_000},
  queues: [default: 8, email_sending: 4, external_services: 4],
  crontab: [
    {
      "* * * * *",
      MyApp.ExternalServices.QueueWorker,
      [
        args: %{job: "get_qbo_items"},
        max_attempts: 2,
        unique: [period: 299]
      ]
    }
  ]
```

```elixir
defmodule MyApp.ExternalServices.QueueWorker do
  use Oban.Worker, queue: "external_services"

  @impl Oban.Worker
  def perform(%{"job" => "get_qbo_items"}, _job), do: MyApp.ExternalServices.get_qbo_items
end
```

However, this results in the job being executed once every minute.

```elixir
config :my_app, Oban,
  repo: MyApp.Repo,
  prune: {:maxlen, 100_000},
  queues: [default: 8, email_sending: 4, external_services: 4],
  crontab: [
    {
      "* * * * *",
      MyApp.ExternalServices.QueueWorker,
      [
        args: %{job: "get_qbo_items"}
      ]
    }
  ]
```

```elixir
defmodule MyApp.ExternalServices.QueueWorker do
  use Oban.Worker, queue: "external_services", max_attempts: 2, unique: [period: 299]

  @impl Oban.Worker
  def perform(%{"job" => "get_qbo_items"}, _job), do: MyApp.ExternalServices.get_qbo_items
end
```

Edit: I'll be setting the crontab to `*/5 * * * *` which has the intended effect, but I used `* * * * *` to test the unique job functionality.

### Environment

- Oban 0.12.0
- PostgreSQL 21.1
- Elixir 1.9.4, Erlang/OTP 22
- Ecto 3.2.5
- Ubuntu 18.04

**Comment by sorentwo** [comment]
@DavidOliver Thanks for the report! I was aware of this as a subtle behavior bug, though I thought the documentation was enough to provide a work around. After reading your issue I was confused by the subtle differences between the two examples and it became clear that it could use a proper fix.

The linked commit fixes this problem by deep merging `unique` options 👍 

> Edit: I'll be setting the crontab to `*/5 * * * *` which has the intended effect, but I used `* * * * *` to test the unique job functionality.

Glad to see you're using a more appropriate schedule! I'm still glad you ran into the issue and prompted a proper fix though 🙂

**Comment by DavidOliver** [comment]
Nice! Thanks.
