### ISSUE TITLE
What is oban_beats table for and what are beats?

### ISSUE THREAD

**Issue by bartblast** [sorentwo/oban#124]
Can't find any info in the docs about it.

**Comment by sorentwo** [comment]
You're right, there isn't anything in the docs about what beats are. There _is_ information about beats in the [CHANGELOG](https://github.com/sorentwo/oban/blob/master/CHANGELOG.md#added-3), but that's it.

The table holds "heartbeat" updates from each queue in each node. The information is used for two purposes:

1. As a replacement for tracking active jobs through advisory locks. Now, when a job executes it records the node and queue that ran it in the `attempted_by` column. Zombie jobs are found comparing the `attempted_by` values with recent beat records and resurrected accordingly.
2. As a replacement for `gossip` updates, for stats. Each beat has information about the queue such as whether it is paused, what the execution limit is and exactly which jobs are running.

Thanks for pointing out that there isn't an explanation about beats anywhere! I'll put some information in the docs.

**Comment by sorentwo** [comment]
Documentation added. Thanks again @bartblast

**Comment by bartblast** [comment]
@sorentwo Thank you for the info!
