### ISSUE TITLE
[UI] Time column on completed tab shows future date

### ISSUE THREAD

**Issue by balexand** [sorentwo/oban#125]
### Environment

- Oban 0.12.0, Oban Web 0.6.2
- PostgreSQL 11.5
- Elixir 1.9.4, Erlang 22.1.8

### Current Behavior

![Oban_•_Jobs](https://user-images.githubusercontent.com/181187/70841512-48381d80-1dd8-11ea-8d4c-535d780aee03.png)

Visit the Oban UI and click on the completed tab. The time for the job shows "2051:29:57 from now". I've looked up the job in the DB and the timestamps are from 3 months ago. The time on the server is set correctly.

```
iex(10)> DateTime.utc_now 
~U[2019-12-14 01:39:08.043587Z]
iex(11)> Lddr.Repo.all(from(j in "oban_jobs", select: [j.id, j.state, j.completed_at, j.attempted_at, j.inserted_at, j.scheduled_at]))
[
  [2, "completed", ~N[2019-09-19 14:03:48.258530],
   ~N[2019-09-19 14:03:47.835170], ~N[2019-09-19 14:03:47.787431],
   ~N[2019-09-19 14:03:47.787431]]
]
```

### Expected Behavior

The column should say something like "3 months ago". Or it can just display the date in UTC since this UI is targeting developers.

**Comment by sorentwo** [comment]
This was an issue for a while! Fixed with v0.6.3. 👍 

The `executing` column displays a formatted duration, as it did before but without "ago". All other time fields display a relative formatted time and show the absolute timestamp on hover.
