### ISSUE TITLE
Job causing BEAM crash continued to be attempted way beyond max_attempts

### ISSUE THREAD

**Issue by bennelsonweiss** [sorentwo/oban#137]
### Environment

- Oban Version: 0.12.0
- PostgreSQL Version: 9.6ish I believe.
- Elixir & Erlang/OTP Versions (`elixir --version`):  1.8.0 and Erlang/OTP 21

### Current Behavior

An Oban job used too much memory (my fault, not Oban's) and caused the BEAM to crash. 

Since the job was never marked as completed or errored (stayed in state `executing`) it kept attempting to run when the BEAM was brought back online, increasing the number of attempts each time even though it was way beyond the max_attempts threshold, and re-crashing the BEAM.

By the time the job was manually removed it had 32 attempts on a 1 max_attempts job.

### Expected Behavior

I would expect that the executor would first check that the job's attempts do not exceed the job's max attempts, and to error if they do, or that the potential of attempts exceeding max attempts be otherwise guarded against.

**Comment by sorentwo** [comment]
@bennelsonweiss Thanks for the report. I'm simultaneously impressed and saddened that the BEAM crashed on you repeatedly!

Anyhow, there is a fix for this on master now 👍

**Comment by bennelsonweiss** [comment]
@sorentwo Should the discard in `rescue_orphaned_jobs` also set `completed_at`?

**Comment by sorentwo** [comment]
I don’t believe that it should. In fact, I’m not sure that the regular discard action should set `completed_at` either. Both variants should probably set a `discarded_at` timestamp and not mess with `completed_at` at all.
