### ISSUE TITLE
Additional telemetry events

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#138]
The job execution and circuit breaker telemetry events are great and there are a number of other places where measurements would be helpful.

Add new telemetry events around functionality that interacts with the database:

- [ ] Inserting (`Oban`)
- [ ] Batch Inserting (`Oban`)
- [x] Pruning Jobs (`Oban.Pruner`)
- [x] Descheduling (`Oban.Queue.Producer`)
- [x] Dispatching (`Oban.Queue.Producer`)

Each of the new events needs documentation in `Oban.Telemetry` as well.

**Comment by devstopfix** [comment]
I may be able to assist this - we are currently investigating if we can use oban in our production application that already uses telemetry. Looking good so far! I will keep in touch.

**Comment by sorentwo** [comment]
@devstopfix That would be great. Let me know if you have any questions.

**Comment by devstopfix** [comment]
@sorentwo Thank you - I will! The library looks great - I think it will fit our needs very well. I will take a look at this issue on Sunday or next week

**Comment by sorentwo** [comment]
Closed with 6cdf6e7, skipping `insert` and `insert_all` instrumentation because they happen in client applications and there hasn't been any other movement on this for 6 months.
