### ISSUE TITLE
Requeue jobs via UI

### ISSUE THREAD

**Issue by ckruse** [sorentwo/oban#140]
### Is your feature request related to a problem? Please describe.

Sometimes a job fails and gets discarded. I have to create a new job with the same parameters to get it executed.

### Describe the Solution You'd Like

When I resolve the problem it would be nice if I could re-queue the job via the web UI so that it gets executed.

### Describe Alternatives You've Considered

Creating a new job with the same parameters.

**Comment by ckruse** [comment]
Sorry, I can't add a label…

**Comment by sorentwo** [comment]
Great timing! This change is in the new details view. Leaving this open until that version is released.

**Comment by ckruse** [comment]
Great!

**Comment by sorentwo** [comment]
ObanWeb v0.7.0 is out!
