### ISSUE TITLE
MFA config for cron/scheduled jobs.

### ISSUE THREAD

**Issue by dgmcguire** [sorentwo/oban#143]
### Is your feature request related to a problem? Please describe.

I initially was wanting to define a worker module on NodeB and have NodeA be responsible for creating jobs via a cron-like configuration.  Currently Oban expects the worker module to be defined on the same Node that will be creating the jobs (specifically the jobs created on a schedule via the cron configuration)

### Describe the Solution You'd Like

It might make sense to configure cron/scheduled work to be executed by a worker that is defined using an [mfa](https://hexdocs.pm/elixir/typespecs.html#built-in-types).  Of course the trade-off would be that you could no longer ensure the worker module exists at compile time.

### Describe Alternatives You've Considered

Alternatively you could just expect Oban users to always define workers on the same node that creates the jobs and honestly that's probably perfectly fine.  I just didn't expect that to be the case when I was building out my worker/scheduler.

**Comment by sorentwo** [comment]
We discussed this briefly on the forum before @dgmcguire opened the issue. My opinion is that the safety from ensuring that a module adheres to the worker behaviour at startup is more valuable than the convenience of scheduling jobs with an mfa.

I'm curious to hear what others think and if there are differing opinions.

**Comment by sorentwo** [comment]
It's been just over a week and there isn't any feedback on this. I'm still in favor of validating crontab modules, even if that means using a stub, so I'm going to close this.

Thanks for the discussion! 💛
