### ISSUE TITLE
Environment-Specific Cron config Reco?

### ISSUE THREAD

**Issue by coladarci** [sorentwo/oban#144]
Let's say I want to use your cron-like setup but have it behave differently in staging versus production (maybe run a different frequencies or turn off certain checks for various reasons)? 

We use releases + env vars to do this w/ other features, but given the complexity of the cron-syntax, it presents some interesting challenges.
 
Do you have a reco on how to pull this off?

Thanks!

**Comment by sorentwo** [comment]
To run different workers/frequencies in staging I recommend dynamically selecting a different crontab when the application boots. I'd use env vars to determine which crontab to use, but I wouldn't try and parse anything from the environment.

Something like this in `application.ex`:

```elixir
  defp oban_opts do
    environment = System.get_env("ENVIRONMENT")

    :my_app
    |> Application.get_env(Oban)
    |> Keyword.put(:crontab, crontab(environment))
  end

  defp crontab("staging") do
    [
      {"* * * * *", MyApp.WorkerA},
      {"* * * * *", MyApp.WorkerB},
      {"* * * * *", MyApp.WorkerC}
    ]
  end

  defp crontab(_environment) do
    [
      {"0 * * * *", MyApp.WorkerA},
      {"* 6-9 * * *", MyApp.WorkerB},
      {"*/15 * * * *", MyApp.WorkerC}
    ]
  end
```

Let me know if that works or what you come up with. This could be a nice addition to the guides.

**Comment by coladarci** [comment]
Thank you! This is interesting - the only thing that is less than ideal is that, ideally, this could be controlled externally so each env can configure the crons however they want by providing some sort of config file. I am looking into https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-config-providers as a potentially way of maybe solving this...

**Comment by sorentwo** [comment]
> I am looking into https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-config-providers as a potentially way of maybe solving this...

Interesting. Keep me posted 👍

**Comment by sorentwo** [comment]
There aren't any actionable items from this issue so I'm going to close it. Please post an update if you come up with a config provider solution. 💛
