### ISSUE TITLE
Update Cron Settings?

### ISSUE THREAD

**Issue by andyl** [sorentwo/oban#146]
I've seen how to configure cron settings that are registered at startup.

Question: Is there a way to update cron settings in a live Oban process?

**Comment by sorentwo** [comment]
Discussion is on Slack https://elixirforum.com/t/oban-reliable-and-observable-job-processing/22449/151?u=sorentwo

**Comment by andyl** [comment]
I'll take a crack at this by adding a new function `Oban.update_cron` and support to dynamically update `Config` state.

**Comment by andyl** [comment]
@sorentwo Here's a simple commit to update the crontab dynamically.

https://github.com/andyl/oban/commit/3ea7dc7ae5c2c80d0325b58888e4c3b1a3f7cf9f

I believe this will work for a single node.

I could use some guidance on broadcasting notifications for a multi-node scenario.  You said to emulate the `start_queue` and `stop_queue` methods, and I can see how the notifications are sent.  But I have not been able to find where the notification handlers are defined.  Could you give me some direction re: location of the notification handlers?

After I have the broadcast notification working I'll submit a PR.

**Comment by andyl** [comment]
I've got some other work coming up and won't have time to work on this over the next few weeks.  I'm going to close this issue, but we can re-open if/when there is time and interest.

**Comment by sorentwo** [comment]
@andyl Thanks for taking a shot at this. It's a pretty tricky thing to orchestrate (and I believe it would need at least three separate functions to be truly usable). If you get time in the future, or there is renewed interest, I'll make sure we can get it built out 👍

**Comment by andyl** [comment]
@sorentwo sounds good.  When we come back to it, here are other features that would IMO be useful to add:
- start scheduled jobs at the top of the minute - Quantum does this and it makes debugging easier
- return a list of cronjobs that use the input cron expression rather than the parsed version as given in `Oban.config()`
- let it be possible to 'tag' a scheduled job - to identify the job owner or job category
