### ISSUE TITLE
assert|refute_enqueued matches completed jobs

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#15]
The `assert|refute_enqueued` helpers are super handy, but they match completed jobs, which was a bit confusing. Semantically, I think of `enqueued` as "will possibly run in the future" but of course `completed` jobs won't ever be executed again.

This kept failing...
```elixir
refute_enqueued(
  worker: MyApp.Workers.NotifyUser,
  args: %{user_id: userid}
)
```
I couldn't figure out why the job was being queued up, since my logic to queue the job in the first place was limited on the size of an array, and that part was right.

After this change...
```diff
refute_enqueued(
  worker: MyApp.Workers.NotifyUser,
-  args: %{user_id: userid}
+  args: %{user_id: userid, state: "available"}
)
```
my test passed.

So, my question is, should `assert|refute_enqueued` match `completed` jobs?

**Comment by sorentwo** [comment]
> So, my question is, should `assert|refute_enqueued` match `completed` jobs?

No, those should definitely _not_ match `completed` jobs. Working on a quick fix for that now.

**Comment by sorentwo** [comment]
This has been fixed up. Thanks for the report @jc00ke!
