### ISSUE TITLE
Job maximum allowed execution time

### ISSUE THREAD

**Issue by benwilson512** [sorentwo/oban#154]
Hey @sorentwo 

We have only a few jobs remaining on our hand rolled job runner, and I'd like to move them to Oban. The only thing I'm not seeing so far is an ability to set the maximum execution time for a job, where if the job exceeds the allowed runtime, it is terminated.

Is this an existing feature and I just missed it?

Thanks!

**Comment by sorentwo** [comment]
> The only thing I'm not seeing so far is an ability to set the maximum execution time for a job, where if the job exceeds the allowed runtime, it is terminated.
> 
> Is this an existing feature and I just missed it?

No, you aren't missing anything, that isn't an existing feature. In fact, allowing unlimited execution is something I worked to make possible! I can imagine this being useful for certain workflows.

What type of API are you imagining for this? To me it makes the most sense as a callback on the worker module, similar to `backoff/1`.

**Comment by benwilson512** [comment]
> What type of API are you imagining for this?
Something like backoff would work, but I think the argument may need to be more comprehensive. The functionality I currently have merely has a fixed timeout per worker type, so you could even just have it on the `use Oban.Worker` callsite. However I like the idea of parameterizing it by _job_ instead of by worker, so a `def timeout(args)` might work.

**Comment by sorentwo** [comment]
I think we'd parameterize by job, but the function definition would be on the worker. The worker callback would look like this:

```elixir
@callback timeout(job :: Job.t()) :: timeout()
```

The default definition would return `:infinity`.

**Comment by benwilson512** [comment]
Makes sense, I might take a crack at this later today if you're interested.

**Comment by sorentwo** [comment]
Closing in favor of the PR, #156
