### ISSUE TITLE
create queue on-the-fly

### ISSUE THREAD

**Issue by ehayun** [sorentwo/oban#158]
Is there a way to create a queue without putting its name in the config?
I want to open a queue for every one of my users but I really don't know how many I have until runtime
Is it possible?

**Comment by sorentwo** [comment]
You can start queues dynamically with [Oban.start_queue/2,3](https://hexdocs.pm/oban/1.0.0-rc.2/Oban.html#start_queue/3) and stop them dynamically with [Oban.stop_queue/2,3](https://hexdocs.pm/oban/1.0.0-rc.2/Oban.html#stop_queue/2).

There will be a recipe/guide about this workflow soon.

**Comment by ehayun** [comment]
Great. Thanks
