### ISSUE TITLE
Job fail after queue_resume

### ISSUE THREAD

**Issue by ehayun** [sorentwo/oban#164]
### Precheck
didn't find any bug like that

### Environment

- Oban Version : rc-2
- PostgreSQL Version : 11.5
- Elixir & Erlang/OTP Versions (`elixir --version`) OTP: 22 Elixir: 1.10

### Current Behavior
I created a small worker that only display values
```
use Oban.Worker

  def perform(%{"id" => id} = args, job) do
    :timer.sleep(3_000)
    IO.inspect(args, label: "=======================")
    IO.puts("Just work #{id}")
    IO.inspect(job, label: "=======================")
  end
```

I created a queue on the fly and make it pause
```
Oban.start_queue(:new_q, 10)
Oban.pause_queue(:new_q)
...
start a 10 jobs (same job every time)

%{"id" => 1} |> App.Jobs.Test.new(queue: :new_q)
%{"id" => 1} |> App.Jobs.Test.new(queue: :new_q)
...
%{"id" => 1} |> App.Jobs.Test.new(queue: :new_q)
...
Oban.resume_queue(:new_q)
```
The 1st job run OK but the 2nd has error (reminder: all job are the same)

### Expected Behavior

All job will run successfuly

**Comment by sorentwo** [comment]
I've replicated your setup in a test script and I don't see any issues. Here is the script:

```elixir
Oban.Test.Repo.start_link()
Oban.start_link(repo: Oban.Test.Repo)

defmodule PrintWorker do
  use Oban.Worker

  def perform(%{"id" => id}, _job) do
    Process.sleep(1000)

    IO.puts("working on #{id}")
  end
end

Oban.start_queue(:new_queue, 10)
Process.sleep(100) # allow the queue to start and start listening for pause
Oban.pause_queue(:new_queue)

for _ <- 1..5 do
  %{id: 1}
  |> PrintWorker.new(queue: :new_queue)
  |> Oban.insert!()
end

Oban.resume_queue(:new_queue)
```

Pasting that set of commands into an `iex` session gives this output:

```
iex(11)> Oban.resume_queue(:new_queue)
:ok
working on 1
working on 1
working on 1
working on 1
working on 1
```

There are two things I noticed about your example:

1. There isn't any delay between starting the queue and pausing the queue. New queues start very quickly, but they still require a few milliseconds to subscribe to pubsub notifications (which is how pause/resume/scale work across all nodes).
2. None of your jobs are inserted into the database, they are only prepared. Namely:

  ````elixir
  # This
  %{"id" => 1} |> App.Jobs.Test.new(queue: :new_q)

  # Needs to be this
  %{"id" => 1} |> App.Jobs.Test.new(queue: :new_q) |> Oban.insert()
  ```

**Comment by ehayun** [comment]
yes, I just forgot to insert into the db
Thanks
