### ISSUE TITLE
Node name not correctly populating on Heroku

### ISSUE THREAD

**Issue by bgentry** [sorentwo/oban#170]
Hi @sorentwo 👋

Noticed a minor issue in our Oban deployment so I thought I'd file a bug for it.

### Environment

- Oban Version: `master` (using the deadlock fix which appears to be working well :pray:)
- PostgreSQL Version: `11.6`
- Elixir & Erlang/OTP Versions (`elixir --version`):

   ```
   Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
   
   Elixir 1.10.0 (compiled with Erlang/OTP 22)
   ```

### Current Behavior

I have two worker dynos on Heroku. In Oban Web, this only shows up as a single `worker@127.0.0.1` node. That's despite [this block of code](https://github.com/sorentwo/oban/blob/c9655dc8dbe62d4f6eabce2642348d5a2678c67c/lib/oban/config.ex#L80-L94) which looks like it's intended to utilize Heroku's `DYNO` variable to populate the node name with i.e. `worker.1`, `worker.2`, etc.

<img width="321" alt="Screen Shot 2020-02-12 at 10 36 40 AM" src="https://user-images.githubusercontent.com/114033/74366136-46f98180-4d84-11ea-9954-42a1425090f4.png">

### Expected Behavior

I had expected that each worker process would be shown separately with a unique name.

**Comment by sorentwo** [comment]
Hmm, that's not good. A few questions to narrow down the issue:

- How are you deploying to heroku? Directly by running `mix phx.server`, distillery or with mix releases?
- Are you deploying with docker? 
- Are you setting an `sname` at boot?

**Comment by bgentry** [comment]
@sorentwo ugh, I think this is being caused by us directly setting `--name worker@127.0.0.1` when starting our workers 🤦‍♂  I believe this was done for some legacy reason with a previous queueing system.

I'll see what I need to do to remove that param and will report back if it doesn't resolve this issue. Consider this a non-issue in the mean time, sorry for the noise!

**Comment by sorentwo** [comment]
Non issues are my favorite!
