### ISSUE TITLE
Ability to access error collection when jobs fail during testing

### ISSUE THREAD

**Issue by paulsullivanjr** [sorentwo/oban#180]
### Is your feature request related to a problem? Please describe.

When calling Oban.drain_queue in tests successes and failures are reported but I don't have a way to examine the errors being returned.

### Describe the Solution You'd Like

Return a collection of details (job name and error) with the failure count. 

### Describe Alternatives You've Considered

I haven't considered any alternatives yet.

### Additional Context

N/A

**Comment by sorentwo** [comment]
@paulsullivanjr I've looked into this a little and it seems unnatural to return an additional mapping of jobs with pre-formatted error traces. Instead, what if `drain_queue` accepted an additional option that caused jobs to run purely inline? That way any crashes or errors would bubble up into your tests.

The interface would be something like `Oban.drain_queue(:some_queue, unsafe: true)`; I'm not set on the option name.

**Comment by paulsullivanjr** [comment]
@sorentwo i can see how it wouldn’t be natural to return the jobs with errors. I like the option of running the jobs inline. That would work. Thanks.

**Comment by sorentwo** [comment]
@paulsullivanjr Changes are on master!
