### ISSUE TITLE
Public interfaces to subscribe  job events

### ISSUE THREAD

**Issue by chulkilee** [sorentwo/oban#183]
### Is your feature request related to a problem? Please describe.

There are cases when  an application needs to know when job status is changed (e.g. not necessarily success)

- Wrap async job processing within a blocking call
- Handle job results without polling

### Describe the Solution You'd Like

It would be ideal if I can get a message when an event happens for certain jobs (e.g. by job id, or job status..)

Once Oban provides public interfaces, we may introduce other integration in *separate* library, such as for [broadway](https://hex.pm/packages/broadway).

I'm not sure what would be the good level of abstraction. 

### Describe Alternatives You've Considered

Polling job status :) I've used [Postgrex.Notifications](https://hexdocs.pm/postgrex/Postgrex.Notifications.html) for similar purposes as well.

### Additional Context

See [Elixir Forum - Using Oban on functions that return](https://elixirforum.com/t/using-oban-on-functions-that-return/29283).

**Comment by sorentwo** [comment]
@chulkilee There will be Some follow up documentation (probably a guide) that illustrates how to combine telemetry and notifications to achieve the non-polling notification flow you are aiming for.
