### ISSUE TITLE
Improve job-focused telemetry events for span timing

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#185]
### Is your feature request related to a problem? Please describe.

Integrating with external monitoring/profiling services such as NewRelic requires the notion of a "transaction". Transactions require a `start` event, followed by a `stop` or `fail` event. Currently, we only emit `success` and `failure` events after a job is finished.

### Describe the Solution You'd Like

- Add namespaced job events as `[:oban, :job, event]` and introduce a `:started` event. This would soft deprecate (i.e. hide) the existing `[:oban, :success | :failure]` events but keep emitting them.
- Emit a `:success` event when jobs are killed currently nothing is logged or recorded for manually discarded jobs.

### Additional Context

Inspired by the discussion and changes proposed in these telemetry issues:

beam-telemetry/telemetry#57
beam-telemetry/telemetry#59

/cc @coladarci

**Comment by sorentwo** [comment]
To anybody who comes across this in the future, note that I _did not_ change the event names. It didn't seem worth the complication or performance impact of maintaining both, and changing them would be breaking, so they were left as is.

**Comment by coladarci** [comment]
Any interest in cutting a release for this? I'm pretty pumped to try this out in production... 😁

**Comment by sorentwo** [comment]
@coladarci Definitely interested in cutting a release for this. I have one other change to get in for #180 and then I'll release `1.2.0`.
