### ISSUE TITLE
Oban Web UI: Change "Retry" to create a new job

### ISSUE THREAD

**Issue by bradleyrubin** [sorentwo/oban#193]
### Is your feature request related to a problem? Please describe.

It's possible to click "Retry" on the Oban Web UI on a job that has successfully completed, and this will enqueue the same job to be run again, with the same job id. This leads to many of the columns being overwritten during the retry, such as attempt, inserted_at, completed_at, etc. Since these columns are overwritten, the previous values for those columns are lost.

### Describe the Solution You'd Like

Instead of having a "Retry" button on the Oban Web UI, there could be a "Requeue" button that would enqueue a new Oban job, with a new job id, with the same parameters as before (worker, args). After clicking "Requeue", the Oban Web UI would show you the new job.

### Describe Alternatives You've Considered

Retrying an existing job might be a valid option for jobs that have failed, but in order to have a record of all the different times a job has been queued, I think it's best to keep it simple and only be able to retry a job by enqueueing a duplicate job.

### Additional Context

![image](https://user-images.githubusercontent.com/5961342/76549919-9e643d80-6467-11ea-9bd3-fbd44a2d80d1.png)

**Comment by sorentwo** [comment]
Thanks for the thoughtful request. The goal of `Retry` is to recycle a job and to force an automated retry early. It is possible to support this with custom tooling if necessary. In the future the UI may get a "clone" button, but not now.
