### ISSUE TITLE
Provide context to backoff callback

### ISSUE THREAD

**Issue by antogon** [sorentwo/oban#197]
### Is your feature request related to a problem? Please describe.

Today, Oban provides the ability to override the `backoff` function on a per-worker basis so that we can fine-tune the retry logic for our applications.  This is highly useful.  It would, however, be convenient for us to have information about the previous failures for a particular job as well in the backoff handler so that we could further fine-tune the logic based on the type of failure we experienced.

### Describe the Solution You'd Like

Provide context information to the `backoff/1` callback by making it `backoff/2`, where the second parameter would be an `Oban.Job` struct populated with information about the currently executing job so that we can make more informed decisions on backoff intervals.

### Describe Alternatives You've Considered

- take scheduling of the job when we experience certain failures into our own hands by scheduling a new copy of the job with the extra failure information in the parameters (attempting to manually increment the `attempt` param of the Job on enqueue, scheduling it at a time later than the regular backoff would), and returning an {:ok, _} tuple to prevent the current instance of the Job from retrying.

### Additional Context

The current situation we're facing is in a worker we've got that:

- opens a transaction with our database
- makes an API call to a 3rd-party provider
- does some work in the database
- commits the transaction

When each of these steps subsequently is successful, all is well.  There are, however, times when the API call to the 3rd-party provider take longer than the timeouts we have configured.  Currently, we configure:

- a 30s timeout for the API call
- a 35s timeout for the database transaction

If the API call times out, we roll the transaction back and raise so that the job retries.  Sometimes, though, even if we cancel the HTTP call on our end, it doesn't mean the processing stops on the 3rd-party provider's end.  In this situation, the job could retry early and a duplicate HTTP call could be issued in the retry before the 1st request has finished processing on the 3rd-party provider's end and their GET API (which would show that the 1st call had succeeded by showing its results) had updated.

Unfortunately, the 3rd-party provider does not indicate a max timeout on their API, nor does it appear that their API terminates requests at a particular timeout.  This would indicate that we should increase our backoff time in the event that the API timed out.  But, it would be unfortunate for us if we had to increase the backoff for _all_ retries regardless of cause because there are certainly other types of failures we'd prefer to retry faster.

**Comment by sorentwo** [comment]
Very nice writeup of your issue! Thank you for putting so much thought into it. This seems like it would dovetail nicely with the changes I proposed in #190 

I can see this going two ways:

1. Change the signature of `backoff/1` to accept an attempt (integer) or a job struct, and deprecate the use of the attempt. This would need a deprecation cycle, but seems cleaner in the end
2. As proposed, add `backoff/2` that accepts the attempt and the job struct

One other thing: what type of information are you looking for on the job itself? The args, tags, errors? Currently the errors are formatted and stored as part of recording the failure. The formatted errors wouldn't be available yet.

**Comment by antogon** [comment]
@sorentwo I think we'd be after the information in the errors field, but it would be convenient if it were also stored in the `errors` array unformatted (as just the error module name perhaps) -- parsing what is stored today seems a bit clumsy for the type of decision-making we're looking for.

**Comment by sorentwo** [comment]
Hmm. It wouldn't be possible (or backward compatible) to store those in the database. The cleanest I way I can think of to handle this is to set the errors on the job as a virtual field and then use that to populate the errors that get put in the database.

There are three properties of every catch/exception: kind, error and stacktrace. The field would need to contain all three values, something like `unsaved_errors: %{kind: :error, error: %RuntimeError{}, stack: [...]}`.

**Comment by bgentry** [comment]
> This seems like it would dovetail nicely with the changes I proposed in #190

FYI it seems likely that this is not the correct issue where you proposed backoff changes.

**Comment by sorentwo** [comment]
Nope, #190 is definitely the wrong issue. That should point to #192

**Comment by sorentwo** [comment]
The first step to supporting error context in `backoff/1` is in with 64de41e. Support for `unsaved_errors` still to come.

**Comment by sorentwo** [comment]
@antogon The final change for contextual backoff is in!

**Comment by antogon** [comment]
@sorentwo 🙏 Thank you so much for this addition!  Will be sure to upgrade and put this to work very soon :)
