### ISSUE TITLE
ObanWeb does not load with PhoenxLiveView v0.10

### ISSUE THREAD

**Issue by bgentry** [sorentwo/oban#201]
Hi @sorentwo :wave: It appears that once again ObanWeb is not compatible with the latest LiveView release 🙁

### Environment

- Oban Version: `v1.2.0`
- ObanWeb Version: `v1.3.0` or `v1.3.1`
- PhoenixLiveView Version: `v0.10.0`
- Elixir & Erlang/OTP Versions (`elixir --version`): `v1.10.2` and `Erlang/OTP 22`

### Current Behavior

After upgrading to the latest Phoenix LiveView (`v0.10.0`), the ObanWeb dashboard does not load correctly. Instead, the initial request hangs right after this output:

```
iex(1)> [info] Received GET /oban
[debug] Processing with Phoenix.LiveView.Plug.Elixir.ObanWeb.DashboardLive/2
  Parameters: %{}
  Pipelines: [:admin, :browser]
```

Beyond this output, I see regularly streaming database query logs as though the dashboard process is in fact updating itself; yet the HTML page has never loaded and those updates are not visible. There are no errors or anything in the Phoenix logs to indicate an issue.

### Expected Behavior

The ObanWeb dashboard should load even on the latest Phoenix LiveView version.

**Comment by sorentwo** [comment]
Thanks for the report! They got me again 😞. Fixed with v1.4.0, which doesn't have any other changes, just a compatibility update.

**Comment by sorentwo** [comment]
Changelog updated as well (https://oban.dev/docs/changelog)

**Comment by bgentry** [comment]
hah, seems they're still far from concerned about breaking changes 🤷‍♂ Thanks, I can confirm that v1.4.0 works with liveview v0.10.0 :v:
