### ISSUE TITLE
`Oban.delete`

### ISSUE THREAD

**Issue by brentjanderson** [sorentwo/oban#204]
### Why this would be helpful

I'm using Oban to schedule future commands to run against the system. Sometimes, however, I need to cancel those commands.

[Per this conversation](https://elixirforum.com/t/oban-reliable-and-observable-job-processing/22449/203?u=brentjanderson), I am deleting the job manually from the `oban_jobs` table by inspecting the `args` JSON (That's the reliable way to tell which job needs cancelling - I'm afraid I can't do it with just the job ID).

### Describe the Solution You'd Like

It would be nice to be able to delete jobs by either ID or some arbitrary criteria. I can imagine the following:
* `Oban.delete/1` to delete by id
* `Oban.delete_where/1` where you can supply arguments upon which to match

### Describe Alternatives You've Considered

Updating the docs to explain that it's acceptable to simply delete jobs however you want using normal ecto repo operations would be a helpful alternative. I can see that being preferable to `Oban.delete` beyond some very simple use cases, since production apps will likely need very specific tuning for certain use cases beyond the basics (e.g. indexing `args` which would slow down writes without much benefit for most apps that don't need to delete old jobs).

### Additional Context

No, but Oban is a fantastic piece of software. It was a piece of cake to drop into my system. ❤️

**Comment by v0idpwn** [comment]
Wouldn't it be a better approach (for observability purposes) to update the job state to "discarded"?

**Comment by brentjanderson** [comment]
That could be good too. I'm not an expert on the Oban job state machine, but having some mechanism to try to cancel (`Oban.cancel` might be a more accurate term here?) a job before it runs is the core request here.

I can see it being better to mark a job as `discarded` instead of just deleting it. The important thing is that a job was scheduled but is no longer going to run.

**Comment by sorentwo** [comment]
In the interest of observability, discarding a job is the best approach. There is a PR in progress to add `Oban.discard/2`. However, I think this warrants some documentation, essentially:

1. You probably don't want to delete a job, you want to discard it to prevent it from running
2. If you must delete a job it is ok to use Ecto queries along with `Repo.delete/1`

**Comment by v0idpwn** [comment]
I'd even argue there should be different states for "failed trying" and "failed because was discarded", as "return `:discard` to discard" is coming.

**Comment by sorentwo** [comment]
> I'd even argue there should be different states for "failed trying" and "failed because was discarded", as "return `:discard` to discard" is coming.

Differentiating between intentionally discarding and exhausting retries could be nice. However, I'm extremely hesitant to introduce a new state and timestamp at this point.

**Comment by sorentwo** [comment]
@brentjanderson `Oban.cancel_job/2` is on master!
