### ISSUE TITLE
Custom Pruners

### ISSUE THREAD

**Issue by sescobb27** [sorentwo/oban#209]
I would like to suggest custom pruners, configurable per queue or at startup (spawning multiple pruners and inject custom config to each one). 

why? a lot of services has different kind of queues/jobs, some more important that other ones, it would be nice for example to prune some jobs faster than other jobs, so for example, prune some jobs every hour, prune other jobs every day, and as default prune jobs every week (this is just an example) and so on. my current approach for this is I copy/pasted the current pruner and added some custom logic and it works, but it would be nice to have local support from the lib.

NOTE1: maybe with support for crontabs

**Comment by sorentwo** [comment]
@sescobb27 Making pruning more flexible through a behavior is a great idea. I'll think about this a little and propose a few callbacks to see what you (and others) think.

**Comment by kidbombay** [comment]
Can we set pruning at the worker level?

**Comment by sorentwo** [comment]
Customizable pruning is removed in master in favor of a plugin system. The built-in pruner has a fixed period of 60 seconds for all queues. Without revealing too much I will say that alternate pruning modules will be available soon(ish), with support for custom age, multiple queues, etc.

**Comment by sorentwo** [comment]
I'm closing this one now. The alternate pruning module will be available soon and announced separately. Thanks for report and additional feedback.
