### ISSUE TITLE
GenServer.call `:noproc` error

### ISSUE THREAD

**Issue by axelson** [sorentwo/oban#21]
After running on a server (heroku) for a while I occasionally get the following error:

Erlang error: `{:noproc, {GenServer, :call, [Oban.Queue.Default.Producer, :pause, 5000]}}`
Stacktrace:
```
lib/gen_server.ex:979:in `call/3'
lib/oban/queue/watchman.ex:43:in `terminate/2'
gen_server.erl:673:in `try_terminate/3'
gen_server.erl:858:in `terminate/10'
proc_lib.erl:249:in `init_p_do_apply/3'
```

I believe `:noproc` means that there is not currently a process running with the name `Oban.Queue.Default.Producer` so perhaps there's a race condition with process registration.

Actually I also have the following error in my logs which seems to have happened at roughly the same time (and may predate the `:noproc` error):

Erlang error: `{:timeout, {GenServer, :call, [Oban.Notifier, {:notify, "oban_gossip", %{count: 0, limit: 10, node: "web.1", paused: false, queue: "default"}}, 5000]}}`

```
lib/gen_server.ex:989:in `call/3'
lib/oban/queue/producer.ex:192:in `gossip/1'
lib/oban/queue/producer.ex:86:in `handle_info/2'
gen_server.erl:637:in `try_dispatch/4'
gen_server.erl:711:in `handle_msg/6'
proc_lib.erl:249:in `init_p_do_apply/3'
```

**Comment by sorentwo** [comment]
There do seem to be two issues here:

1. The watchman is trying to pause the producer when the supervisor is going down, but the producer has already crashed. This is a straight forward fix.
2. The notifier call is timing out when it is attempting to broadcast the gossip. That is an extremely fast call and very lightweight, but it does make use of the Ecto connection pool. I'd like to recover from this situation gracefully.

Out of curiosity, how large is your db pool and did this error happen during a busy time?

**Comment by axelson** [comment]
The pool for that server is set to 80, this didn't happen during a busy time, it seems to have happened due to the heroku daily dyno restart.

**Comment by sorentwo** [comment]
@axelson The two linked commits should prevent this issue in the future. The root issue was that the queue producer and the watchman (the thing that attempts to let current jobs finish before shutdown) weren't handling some likely exceptions.

The second commit, 553da67, also eliminates a process bottleneck and may help performance with a lot of different queues.

Let me know if this issue surfaces again!

**Comment by axelson** [comment]
Great, thanks for the quick fix!
