### ISSUE TITLE
Allow :infinity as a unique period

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#210]
### Is your feature request related to a problem? Please describe.

It is often desirable to treat a job like it is unique "forever", where "forever" means as long as there is historical data in the database.

### Describe the Solution You'd Like

Allow specifying `period: :infinity` for worker and job uniqueness. Behind the scenes that would translate to a ludicrously long period of time, e.g. 999 years.

### Describe Alternatives You've Considered

The alternative is to specify a very long number of seconds, `period: 60 * 60 * 24 * 365 * 999`, which is rather verbose.

**Comment by v0idpwn** [comment]
Wouldn't we get problems with pruning?

**Comment by sorentwo** [comment]
This only controls how long a job is considered unique, not how long it is retained in the database. People are welcome to keep jobs in the database for months if they want.
