### ISSUE TITLE
`ObanWeb.Migrations.V2.down` does not complete rollback

### ISSUE THREAD

**Issue by milmazz** [sorentwo/oban#215]
### Environment

- Oban Version 1.2.0, Oban Web: 1.5.0
- PostgreSQL Version: 9.6.17
- Elixir & Erlang/OTP Versions (`elixir --version`): 1.9.0  / 22

### Current Behavior

There is an issue in the `down` function of the `ObanWeb.Migrations.V2` module. When you try to run the rollback, it fails because of a syntax error while executing `DROP FUNCTION IF EXISTS oban_beats_gossip`, the `()` at the end is missing, here is an example:

```console
yellow_pages_dev=# \df oban_beats*
                               List of functions
 Schema |       Name        | Result data type | Argument data types |  Type
--------+-------------------+------------------+---------------------+---------
 public | oban_beats_gossip | trigger          |                     | trigger
(1 row)
yellow_pages_dev=# DROP TRIGGER IF EXISTS oban_gossip ON oban_beats;
DROP TRIGGER
yellow_pages_dev=# DROP FUNCTION IF EXISTS oban_beats_gossip;
ERROR:  syntax error at or near ";"
LINE 1: DROP FUNCTION IF EXISTS oban_beats_gossip;
                                                 ^
yellow_pages_dev=# DROP FUNCTION IF EXISTS oban_beats_gossip();
DROP FUNCTION
```

How do we catch this issue? We have a unit test to check all our rollbacks, so, I'll suggest doing something similar to avoid this kind of issues in the future:

```elixir
defmodule MyApp.EctoRollbackTest do
    use ExUnit.Case, async: false

    alias Mix.Shell.Quiet

    setup do
      on_exit(fn ->
        Quiet.cmd("mix ecto.migrate")
      end)

      :ok
    end

    test "migrations allow to rollback to the beginning of times" do
      assert 0 == Quiet.cmd("mix ecto.rollback --all")
    end
  end
```

### Expected Behavior

The `down` function in the `ObanWeb.Migrations` should complete all the rollback operations.

**Comment by sorentwo** [comment]
The next release of ObanWeb won’t have any migrations at all, so this won’t be a problem. Thanks for the report, but I’m going to close this out.
