### ISSUE TITLE
(ArgumentError) unknown option provided {:plugins, false}

### ISSUE THREAD

**Issue by ZombieHarvester** [sorentwo/oban#216]
Oban 1.2.0
Postgres 12.2
Elixir 1.10.2 (compiled with Erlang/OTP 22)

### Current Behavior

```Elixir
> mix test
** (Mix) Could not start application app: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: Oban
    ** (EXIT) an exception was raised:
        ** (ArgumentError) unknown option provided {:plugins, false}
            (oban 1.2.0) lib/oban/config.ex:210: Oban.Config.validate_opt!/1
            (elixir 1.10.2) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir 1.10.2) lib/enum.ex:783: Enum.each/2
            (oban 1.2.0) lib/oban/config.ex:70: Oban.Config.new/1
            (oban 1.2.0) lib/oban.ex:147: Oban.start_link/1
            (stdlib 3.12.1) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib 3.12.1) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib 3.12.1) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
```

### Expected Behavior

Oban doesn't raise in mix test

### Comments

I just added Oban to my app with default config from readme. `mix test` raises with `unknown option provided {:plugins, false}`.  If I remove `plugins: false` from test config, then it doesn't raise.

**Comment by sorentwo** [comment]
The README is for master, which isn't released yet. Please use the documentation in [hexdocs](https://hexdocs.pm/oban/Oban.html) instead.

**Comment by sorentwo** [comment]
Thanks for the reminder! I've added a comment to that effect in the README with cb8cc0b.
