### ISSUE TITLE
Helper function for unit testing workers

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#228]
I've observed some things through the process of reviewing the implementation/conversion of dozens of workers:

1. We often try to work around the second argument, which doesn't seem like the correct ergonomics
2. Everybody tries to pattern match on atom keys, when string keys are always used during normal execution
3. Figuring out the return type is entirely manual, workers should only return ok or success tuples for normal operations

That's lead to a [proposed change](#223) from `perform/2` to `perform/1`. I'm also proposing the addition of a new testing helper that will mitigate all of those issues. The function will handle and make assertions about the following:

1. Make building an Oban.Job struct easier
2. Assert that the args only have string keys
3. Assert that the return value is :ok, {:ok, value}, {:error, value} etc.

The helper would eliminate most of the things I'm looking for when I do a review!

What should the helper function be called? Some possibilities:

* `perform`
* `perform_job`
* `assert_perform`
* `worker_perform`

**Comment by HangingClowns** [comment]
Since you need to actually pattern match on string keys, then I propose to warn if using atom keys (I was also caught by this) and maybe use default `perform` function that actually fails with a very clear log that says that the pattern was not matched?

When I create my perform functions, I nearly always define a default param with a clear error log so I know that I didn't match my function head from before.

**Comment by sorentwo** [comment]
> Since you need to actually pattern match on string keys, then I propose to warn if using atom keys (I was also caught by this) and maybe use default `perform` function that actually fails with a very clear log that says that the pattern was not matched?

Providing a default clause that warns or errors may be helpful once you have deployed. You wouldn't get feedback telling you the job will never work until you're running jobs for real, which may not be until it hits production.

> When I create my perform functions, I nearly always define a default param with a clear error log so I know that I didn't match my function head from before.

This would be a great thing to have documented as a "best practice" example. I'll keep that in my pocket for the guides.
