### ISSUE TITLE
Inserting a new job with a uniqueness constraint fails when oban is deployed to a non-public schema

### ISSUE THREAD

**Issue by nnasoody** [sorentwo/oban#234]
Oban is deployed to a different schema than the public one and, as a result, new jobs with a uniqueness constraint fail on the read check. The root cause appears to be this [function](https://github.com/sorentwo/oban/blob/1.2/lib/oban/query.ex#L306) in release 1.2 where the table path is not fully qualified. This issue is [fixed](https://github.com/sorentwo/oban/blob/master/lib/oban/query.ex#L250) in the master branch. Just curious if a new minor version will be released soon.

You've built a wonderful piece of software. Great work!

**Comment by sorentwo** [comment]
There are a few other things to sort out before I can get a release out. A new version is slated in the next week or two (before the end of May).

Thanks for asking!
