### ISSUE TITLE
Crontab does not work while all queue-based jobs work correct

### ISSUE THREAD

**Issue by marinakr** [sorentwo/oban#235]
I have oban crontab section in config file:
```
config :my_app, Oban, repo: MyApp.Repo, crontab: [
  {"* * * * *", MyApp.MinuteWorker}
]
```
and I expect `MyApp.MinuteWorker.perform/2` will be executed every minute
```
defmodule MyApp.MinuteWorker do
use Oban.Worker, max_attempts: 3
  
@impl Oban.Worker
  def perform(_, _), do: throw "perform started" # <- just  check crontab job tried to start
```
And after my application started with Oban (Application module)
```
@oban MyAppOban

  def start(_type, _args) do
     children = [Supervisor.child_spec({Oban, Keyword.put(Application.get_env(:myapp, Oban), :name, @oban)}, id: @oban)]
```
Crontab jobs does not run. Rest jobs that run after new job arrived in listened queues work as expected and handles job arguments

**Comment by sorentwo** [comment]
Is that the exact configuration you're using for your app? Do you have a sample application that recreates this issue?

**Comment by marinakr** [comment]
@sorentwo 
:myapp is fake application name, but it reproduces on few our applications
Can you check it?

**Comment by sorentwo** [comment]
Are you running multiple instances of Oban within the same app/umbrella/database? If so you are probably running into a bug that was fixed a few weeks ago related to conflicting transaction locks. There is a fix on master if that is the case.

**Comment by marinakr** [comment]
No. It was isolated before, but now there is only 1 Oban instance. Also, this bug reproduced in project wis 1 oban: 
```
children =
      [
        ObanRepo,
        {Oban, Application.get_env(:oban_worker, Oban)}
      ] ++
```

**Comment by sorentwo** [comment]
I'll need a sample application that reproduces the issue to diagnose the problem. Many applications, including the primary applications I maintain, use the crontab feature without any issue. There may be a configuration issue or an edge case, but I can't diagnose anything without a reproduction.

**Comment by marinakr** [comment]
I'll create new repo that reporoduce issue and send link in 5-6 ours

**Comment by marinakr** [comment]
@sorenone https://github.com/marinakr/oban_sheduler -example of oban cron when perforn/2 is never executed

**Comment by sorentwo** [comment]
I made two changes to get the example app running:

1. Move the `MinuteWorker` from `minute_worker.exs` to `minute_worker.ex`, so that it is compiled and included in the release.
2. Start the default queue. The scheduler inserts jobs into the queue, it doesn't process them.
3. Change the `throw` to a `puts` so I could see the output. The throw is caught and recorded in the `errors` on the job.

Here is the diff:

```diff
diff --git a/config/config.exs b/config/config.exs
index 407ee89..90c4657 100644
--- a/config/config.exs
+++ b/config/config.exs
@@ -4,15 +4,13 @@
 
 config :oban_sheduler, Oban,
   repo: ObanSheduler.ObanRepo,
+  queues: [default: 1],
   crontab: [
     {"* * * * *", ObanSheduler.MinuteWorker}
   ]
 
 config :oban_sheduler, ObanSheduler.ObanRepo,
-  username: "postgres",
-  password: "postgres",
   database: "oban_cron",
-  hostname: "localhost",
   prefix: "oban",
   show_sensitive_data_on_connection_error: true,
   pool_size: 1
diff --git a/lib/minute_worker.exs b/lib/minute_worker.ex
similarity index 51%
rename from lib/minute_worker.exs
rename to lib/minute_worker.ex
index 0b03210..c17f67d 100644
--- a/lib/minute_worker.exs
+++ b/lib/minute_worker.ex
@@ -2,6 +2,5 @@ defmodule ObanSheduler.MinuteWorker do
   use Oban.Worker, max_attempts: 3
 
   @impl Oban.Worker
-  # just  check crontab job tried to start
-  def perform(_, _), do: throw("perform started")
+  def perform(_, _), do: IO.puts "RUN"
 end
```

Here is the output from starting up the app:

```
~/W/C/oban_sheduler (master|✚2…) $ _build/dev/rel/oban_sheduler/bin/oban_sheduler start
RUN
```

There isn't anything wrong with the scheduler system. Check your app for some of the issues I mentioned above and you should be set 👍

**Comment by marinakr** [comment]
Minute worker was already renamed to .ex, the reason was default queue not starter. Thank you!
