### ISSUE TITLE
Proposal: Include current recipes as guides

### ISSUE THREAD

**Issue by milmazz** [sorentwo/oban#241]
### Is your feature request related to a problem? Please describe.

No

### Describe the Solution You'd Like

If #240 is accepted and merged, I would like to propose that we move all the available _recipes_ to the `oban` project and start considering those as initial guides.

I see some advantages of doing this:

* Anyone can create a PR to improve, update, or fix those guides
* It could reduce the burden of maintaining the recipes up to date, at least for @sorentwo 
* The recipes will be available via hexdocs.pm, which is kind of the _standard place_ where you look for Elixir's documentation
* If you prefer, you can download the recipes via: `mix hex.docs offline oban`
* It will provide more visibility for the recipes; not everybody knows that they're currently available at https://sorentwo.com/

### Describe Alternatives You've Considered

Keep googling for "Oban recipes" from time to time, and then check the final recipes, which is now at https://sorentwo.com/

**Comment by sorentwo** [comment]
This is a great idea, and something I'd hoped to do since the recipes were published. Some of them (namely unique jobs) aren't really applicable and will need an overhaul.

The source is here https://github.com/sorentwo/sorentwo.github.io if anybody decides to jump into this.

**Comment by sorentwo** [comment]
Closing in favor of the PR (#247)
