### ISSUE TITLE
Snoozing jobs interferes with backoff calculations

### ISSUE THREAD

**Issue by hez** [sorentwo/oban#245]
ref: https://elixir-lang.slack.com/archives/CRDGH1XCM/p1590454468277200

### Environment

- Oban Version: ref: "c0b84ef"
- PostgreSQL Version: 10.12
- Elixir: 1.10.2
   Erlang/OTP Versions: 22.3

### Current Behavior

We snooze jobs pretty aggressively and have ended up with jobs that are at attempt ~1200. This causes some strangeness with the backoff calculations.

Attached bellow is a backtrace from a job trying to calculate the backoff.

![image (5)](https://user-images.githubusercontent.com/244021/82926244-beb67b00-9f33-11ea-95a8-d8e6a4e5b706.png)

### Expected Behavior

Using snooze should not effect backoff calculations.

**Comment by sorentwo** [comment]
Thanks for the report. Fixed with 3043b89 👍
