### ISSUE TITLE
Job processed by multiple nodes

### ISSUE THREAD

**Issue by ludwikbukowski** [sorentwo/oban#250]
### Environment

- Oban Version: `1.2`
- PostgreSQL Version: `(PostgreSQL) 10.12`
- Elixir: `1.8.2` 
- Erlang: `21`
### Current Behavior

During cluster startup (3 nodes, no erlang distribution), each node creates Oban _unique_ job.
We observe that only one job was inserted into oban table (which is as expected) but then we also observe that sometimes multiple nodes executes that job. Hence, we have a job that is run multiple times!

Tech details:
On startup, each node adds `Supervisor`(after Oban supervisor) with `Task` to its supervisiton tree. The task inserts the oban job:
```elixir
  def start_link do
    Supervisor.start_link(__MODULE__, nil, name: __MODULE__)
  end

  @impl true
  def init(_arg) do
    # By default, the restart type for Task is :temporary
    Supervisor.init([{Task, &schedule_task/0}], strategy: :one_for_one)
  end

  def schedule_task do
    Oban.insert(MyJob.new(%{"type" => "on_reboot"}))
  end
```

`MyJob` worker implementation:
``` elixir
  use Oban.Worker,
    queue: :my_queue,
    unique: [period: 300],
    max_attempts: 5

  require Logger

  @impl Oban.Worker
  def timeout(_job), do: :timer.minutes(10)

  @impl Oban.Worker
  def perform(%{"type" => "on_reboot"}, _job) do
    Process.sleep(10_000)
    Logger.info("Job in progress...")
  end
```
config.exs:
```elixir
config :my_app, Oban,
  repo: MyApp.Repo,
  prune: {:maxlen, 10_000},
  queues: [my_queue: 1]
```

and finally in the logs:
```
node_1  |2020-05-28 12:04:35.998 [info] Job in progress...
node_2  |2020-05-28 12:04:36.221 [info] Job in progress...
node_3  |2020-05-28 12:04:36.515 [info] Job in progress...
```

The job in the database:
```
$ select * from oban_jobs;
686 | completed | my_queue   | MyJob | {"type": "on_reboot"} | {}     |       3 |            5 | 2020-05-28 12:04:25.953577 | 2020-05-28 12:04:25.953577 | 2020-05-28 12:04:26.508505 | 2020-05-28 12:04:36.515926 | {my_node_name@127.0.0.1,my_queue,hi07eqsp} |              |        0 | {}
```
please note, it has `3` attempts (as the number of nodes in the cluster).

Also, **for each** node I see such telemetry events:
```elixir
node_1  | 2020-05-28 12:04:25.995 [info] {"args":{"type":"on_reboot"},"event":"started","queue":"my_queue","source":"oban","start_time":1590667465995734,"worker":"MyJob"}
node_1  | 2020-05-28 12:04:36.005 [info] {"args":{"type":"on_reboot"},"duration":10009957,"event":"success","queue":"my_queue","source":"oban","worker":"MyJob"}
...
```

### Expected Behavior

I expect that job will be processed only once, since I set `unique` interval for 300 seconds. Also, by default it should take args, workers, state etc for uniqueness, which are always the same.

Please point out, where I misunderstood the `uniqueness` of the job, since this seems as very simple example to reproduce...

**Comment by sorentwo** [comment]
Is that an example of the full config from your `config.exs`? Do you happen to have a `prefix` set as well?

**Comment by ludwikbukowski** [comment]
no prefix option set.
In the code i pasted I just removed app specific names from module prefixes e.g for `MyApp.Repo`, `MyJob`, changed the `queue_name` etc.

**Comment by sorentwo** [comment]
Thanks for the offer. No need for you to reproduce something, I'll try to reproduce with a test case or property.

**Comment by ludwikbukowski** [comment]
@sorentwo thanks!

**Comment by sorentwo** [comment]
The commit message and the changelog entry explain this situation in some detail. Essentially if fetching jobs was called outside of a transaction it would ignore the `FOR UPDATE SKIP LOCKED` declaration. It was called outside of a transaction when it received certain messages, such as `:down` or `:inserted`, which is why you would see it after the job was inserted on startup. This was all exacerbated by the fact that it's nigh impossible to replicate in tests. The tests all use the same connection and are effectively serialized, even with concurrent processes.

Thanks for the report and the solid instructions to recreate!

**Comment by ludwikbukowski** [comment]
@sorentwo do you have any plans for new release tag ?

**Comment by sorentwo** [comment]
@ludwikbukowski Yes, I'm releasing an RC for 2.0 soon, probably in the next day or so.
