### ISSUE TITLE
How is pruning meant to work?

### ISSUE THREAD

**Issue by jarvisjohnson** [sorentwo/oban#259]
I see that you've changed the pruning behaviour recently, and it is a 'plugin'.  It sounds like it should be automatically pruning completed jobs from the db table.

Am I correct that this is meant to happen automatically?

I see the current docs still says to use the `:prune` option, but the readme says this is gone.

https://hexdocs.pm/oban/1.2.0/Oban.html#module-pruning-historic-jobs

Just would like to get some clarity about what is the expected behaviour here.  Also, are there any configuration options?  Is there any way to get more info around what 'plugins' are, and how to configure them?  Happy to help update the readme / docs.

Thank you

**Comment by sorentwo** [comment]
Thanks for asking, I’ll try to explain the situation without tipping my hand too much.

The docs on HexDocs are for v1.2.0, which still supports the `prune` option. In the upcoming v2.0.0 that has been removed and replaced with a pruning plugin. That particular plugin is not configurable and retains jobs for approximately 60s. That means in the base Oban version you can either disable pruning altogether or use the `FixedPruner` plugin and keep jobs for a short period.

In the *very* near term I am releasing a collection of more advanced plugins and official workers that will cover this gap.

**Comment by jarvisjohnson** [comment]
Great, thanks @sorentwo - looking forward to v2.0.0
