### ISSUE TITLE
add testing option to count the number of matched messages

### ISSUE THREAD

**Issue by tcoopman** [sorentwo/oban#26]
In my test I sometimes want to check that there is only one message enqueued and not more. A method to test for this would be great.

**Comment by sorentwo** [comment]
I've thought about this a bit today and I believe both #25 and #26 can be accomplished with the addition of a `get_enqueued/1` function. Within tests you would use it like this:

```elixir
# Make an assertion that there is a single job with the args `%{id: 1}`
assert [%{args: %{id: 1}}] = get_enqueued(worker: MyWorker, queue: foobar")

# Make an assertion that there is exactly one matching job
assert [%Job{}] = get_enqueued(worker: MyWorker, queue: "foobar")
```

This is flexible and allows you to make any assertions that you like in your tests.

**Comment by tcoopman** [comment]
That sounds very fine

**Comment by sorentwo** [comment]
Thanks for the suggestion. Between the pattern matching suggestion here and in #25 I believe it is possible to write more robust (though verbose) tests when necessary.

Please take a look at 3c5ed47 and let me know if it works for you.

**Comment by tcoopman** [comment]
Thanks, this is perfect
