### ISSUE TITLE
Update changelog due to new perform/1

### ISSUE THREAD

**Issue by ludwikbukowski** [sorentwo/oban#263]
Would you add new `perform/1` specification to changelog? It's kind of breaking change as it does not keep backward compatibility for old syntax. Also, in changelog still `perform/2` is mentioned.

**Comment by sorentwo** [comment]
@ludwikbukowski That totally slipped past me! Thanks for point it out. The change is now mentioned very prominently and there are some light upgrade instructions.

💛
