### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by lpil** [sorentwo/oban#28]
Hello!

Is there a web-based user interface that we can use to monitor and administrate our oban work queues? :)

Thanks,
Louis

**Comment by jaimeiniesta** [comment]
There's one mentioned in https://elixirforum.com/t/oban-reliable-and-observable-job-processing/22449 but still in the works it seems.

**Comment by sorentwo** [comment]
Thanks for the inquiry @lpil. As @jaimeiniesta there is one in the works, but I'm lagging behind with it. Other work has taken priority and I didn't make the deadline I was shooting for. I'll have a private beta available soon, where "soon" means the next week or two.

I'll leave this issue open for discussion and updates.

**Comment by fuelen** [comment]
any progress in this direction?

**Comment by abitdodgy** [comment]
@sorentwo can we help somehow? We really want to use Oban but the WebUI might be a deal breaker for us. Can we help you somehow?

**Comment by jc00ke** [comment]
I'd love to help with the web UI. We just went live yesterday and more visibility would be great.

**Comment by sorentwo** [comment]
I just announced a private beta on the ElixirForum: https://elixirforum.com/t/oban-ui-private-beta/26182

Here is the tl;dr on how to get access to the web UI:

> Send an email to soren@sorentwo.com or DM me to request access. Please include your GitHub username and a little information about the project you’ll be using the UI for (nothing confidential).

Thanks to everybody who posted or added a +1 to this thread, I really appreciate it. My estimate was only three months off!
