### ISSUE TITLE
Public func to convert module to worker string

### ISSUE THREAD

**Issue by chulkilee** [sorentwo/oban#281]
### Goal

I need to query jobs for specific worker module to cancel the job. To do that, I need to pass worker name as string.

e.g. `MyApp.Worker.HardWork` -> `"MyApp.Worker.HardWork"`.

### Describe the Solution You'd Like

Expose a function to convert module to string value can be used for `worker` column

Pick a good name and expose following private function

https://github.com/sorentwo/oban/blob/v2.0.0-rc.2/lib/oban/job.ex#L297-L301

**Comment by chulkilee** [comment]
I can create PR for this - any thought on the naming?

BTW another workaround to get the value without copying the code is:

```elixir
MyWorker.new(%{}).changes.worker
```

**Comment by sorentwo** [comment]
After experimenting a little I believe the best way to handle this is actually with `inspect/1`, because it does it automatically:

```
iex(2)> to_string(MyApp.MyModule)
"Elixir.MyApp.MyModule"
iex(3)> inspect(MyApp.MyModule)
"MyApp.MyModule"
```

I think the best option here is to document querying the jobs table with this module to string coercion. WDYT?

**Comment by chulkilee** [comment]
For implementation - maybe inspect is better.

However I still think it's better to have func on oban for explicitness, instead of mentioning it only at doc.

Also I'd like to avoid adding oban internal specific code in my code if possible.

**Comment by sorentwo** [comment]
The fact that `Atom.to_string/1`, and thereby `to_string/1` prefixes module names with `Elixir.` is more Elixir specific than Oban specific. Ideally I'd like to see a `Module.to_string/1` implementation that did this naturally rather than having to expose a helper from Oban itself.

In lieu of a `Module.to_string/1` function there may be value in a `Oban.Worker.to_string/1`, but it feels extraneous to me. The difference would look like this:

```elixir
# Using inspect
from j in Oban.Job, where: j.worker == ^inspect(MyApp.MyWorker)

# Using Worker.to_string
from j in Oban.Job, where: j.worker == ^Oban.Worker.to_string(MyApp.MyWorker)
```

**Comment by chulkilee** [comment]
It's more verbose, but more clear and explicit to use oban's helper function instead of using the underlying assumption from documentation.

Also please note that it is technically possible to overwrite the protocol implementation, so `Kernel.inspect/2` is not stable. Thus using `Atom.to_string/1` and transform it for Oban is the best way.

```elixir
defmodule Foo do
end

inspect(Foo)
# "Foo"

defimpl Inspect, for: Atom do
  def inspect(_, _) do
    "bah"
  end
end

inspect(Foo)
# "bah"
```

---

On removing `Elixir.` from `Atom.to_string/1` - oban may need to keep it once it supports erlang module for worker.

**Comment by sorentwo** [comment]
> On removing `Elixir.` from `Atom.to_string/1` - oban may need to keep it once it supports erlang module for worker.

That's an excellent point. So long as a module implements the worker behaviour there isn't anything that prevents Erlang (or even Gleam) workers.

A PR for `Worker.to_string/1` would be entirely welcome.

**Comment by sorentwo** [comment]
Closing in favor of the PR (#284)
