### ISSUE TITLE
Unique worker arg fields

### ISSUE THREAD

**Issue by hfjallemark** [sorentwo/oban#283]
### Is your feature request related to a problem? Please describe.

We are scraping news articles and enqueue each url we find to a separate downloader worker. The issue is that we sometimes find the same url on different places but we only want to enqueue it once… however we include more data than just the url in the args which makes the unique feature of Oban not work.

### Describe the Solution You'd Like

Ideally an additional unique field, like `:keys` that you'd specify in the worker:

```
use Oban.Worker, unique: [period: :infinity, keys: [:url]]
```

### Describe Alternatives You've Considered

Using a partial unique index for the specific unique args but that gets cumbersome since you need to add migration scripts for each worker.

**Comment by sorentwo** [comment]
Closing in favor of #314

**Comment by sorentwo** [comment]
Keys are listed as atoms, but they are converted to strings before checking.

**Comment by marinakr** [comment]
Hi @sorentwo,
```
defmodule MyApp.EventsJob do
use Oban.Worker,
    queue: :outlook_events,
    unique: [
      fields: [:queue, :worker, :args],
      keys: [:id],
      states: [:available, :scheduled, :executing],
      period: :infinity
    ]
```
With this code I expect that new job with same id in args will be not inserted
tests:
```
  %{"id" => event.id}
    |> MyApp.EventsJob.new()
    |> Oban.insert()
   
    # some code
    
   Enum.map(events, & MyApp.EventsJob.new(%{"id" => &1.id}))
    |> Oban.insert_all() #<- I expect job for event.id will be not inserted/performed, but it add new job with same event id
    
```
What do I do wrong?

**Comment by v0idpwn** [comment]
@marinakr see https://github.com/sorentwo/oban/issues/388
