### ISSUE TITLE
Can't view details of all job failures (can't scoll the modal)

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#285]
### Environment

- Oban Web Version: 2.0.0-alpha.0

### Current Behavior

Details modal doesn't scroll, so we can't see the details of all failed attempts.
![image](https://user-images.githubusercontent.com/18191/86407971-ee5f4e00-bc6a-11ea-9088-190214af3e0a.png)

### Expected Behavior

I'd love to see everything, and with a lot of failures I would need to scroll the details in the modal.

**Comment by sorentwo** [comment]
Thanks for the report. The modal is definitely a WIP in the alpha, and it will likely be removed in favor of a more integrated view. I'll leave this open until a fix or an improved experience is out.

**Comment by sorentwo** [comment]
Fixed with ObanWeb 2.0, released today.
