### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by nodeit** [sorentwo/oban#293]
### Current Behavior

Readme currently states "Worker modules do the work of processing a job. At a minimum they must define a perform/2 function, which is called with an %Oban.Job{} struct."

### Expected Behavior

Shouldn't the perform function have an arity of "1"?

**Comment by sorentwo** [comment]
Thanks for pointing that out. You're correct, it should be `perform/1`. I've updated a few of the lingering places where `perform/2` was sticking around.
