### ISSUE TITLE
Clarify usage of IEX checks in README

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#294]
There have been several issues stemming from the suggested code: `Code.ensure_loaded?(IEx) and IEx.started?()`.

1. In development when users start phoenix using `iex -S mix phx.server` Oban is disabled and it appears that Oban doesn't work
2. In production some configurations (i.e. distillery) fail to start Oban entirely due to configuration

I'm opening this issue to see what configuration people use to work around this and to look for suggestions on how to improve the docs. Any configuration examples, experiences or suggestions are welcome.

**Comment by navinpeiris** [comment]
Currently I'm using the following in `application.ex`

```elixir
defp oban_config do
  opts = Application.get_env(:shop, Oban)
  disable_if_iex = Application.get_env(:my_app, :disable_oban_if_iex, false)

  # Prevent running queues or scheduling jobs from an iex console,
  # i.e. when starting app with `iex -S mix`
  if disable_if_iex and Code.ensure_loaded?(IEx) and IEx.started?() do
    opts
    |> Keyword.put(:crontab, false)
    |> Keyword.put(:queues, false)
  else
    opts
  end
end
```

and setting the following in `dev.exs`:
config :my_app,
  disable_oban_if_iex: true
```elixir

I don't really want to be running oban in iex in dev as I usually use that as a scratch pad to test something out, and this config works for me for my dev workflow as well as starting oban properly out in prod with my distillery releases.

**Comment by fuelen** [comment]
I do not disable Oban in iex at all. Starting oban application is controlled explicitly using ENV variables.

**Comment by joshuataylor** [comment]
Yeah, or you can do a mix.env check as well?

**Comment by sorentwo** [comment]
Thank you for the feedback. Since I opened this there have been a few other users that were surprised their jobs aren't running. I think the best solution is to simplify that section of the setup instructions and add some of these suggestions to a guide oriented toward controlling startup and queues.
