### ISSUE TITLE
Add a reason when discarding a job

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#296]
### Is your feature request related to a problem? Please describe.

We would like to track the *why* behind discarding jobs, not just that we discarded one. `{:discard, reason}` would allow us to track that.

### Describe Alternatives You've Considered

For a hot sec I looked at `{:error, reason}` but that would trigger retries.

### Additional Context

Would love to see this info in `Oban.Web` and be able to search by it.

**Comment by sorentwo** [comment]
Closing in favor of the PR.
