### ISSUE TITLE
Ability to declaratively pause queues/scale queues to 0

### ISSUE THREAD

**Issue by shanesveller** [sorentwo/oban#298]
This is an follow-up to an Elixir Slack conversation beginning [here](https://elixir-lang.slack.com/archives/CRDGH1XCM/p1595302247278500). I am a developer at Cars.com but am mostly writing in under my own volition as someone familiar with the emergent behavior we're experiencing, because I'm curious if the situation can be improved. My views expressed here do not necessarily reflect that of the organization, etc. etc.

### Is your feature request related to a problem? Please describe.

We sometimes need to disable queues for operational maintenance or to uphold data integrity during schema evolution, because performing the jobs on the queue would cause conflicts or data loss during those time windows. Letting them buffer up instead is safe for our data model.

We currently disable the queues altogether when this need arises. To do so, we redeploy our Kubernetes containers with an updated environment variable, which is a JSON-encoded Map as a string, and the updated version has omitted the queue name and scale altogether. That envvar is then decoded by our Distillery configuration back into the Keyword list that Oban's modules expect.

### Describe the Solution You'd Like

Being able to leave a queue defined but declaratively disabled (i.e. with scale of `0`, or explicitly starting in a paused state as a node-specific detail) would be helpful for our internal constraints above. We are trying to avoid any imperative management that would require `eval` or RPC-style commands around i.e. `Oban.pause_queue/2` because this approach is somewhat stateful in nature and more challenging to incorporate in our deployment flows. We prefer that this paused/disabled state can be indicated externally from the BEAM through configuration only. In particular, we want the disabled state to persist across restarts of a single container or restarts of all containers, such as during a rolling deployment, and our BEAM nodes are currently not clustered so they all can only respect an external source-of-truth.

Currently a value of 0 is forbidden in 1.x per the typespec [here](https://github.com/sorentwo/oban/blob/v1.2.0/lib/oban/config.ex#L24) and in the Config validation code [here](https://github.com/sorentwo/oban/blob/v1.2.0/lib/oban/config.ex#L226). The same limitations are present in 2.0.0 as well, though we have not upgraded yet.

### Describe Alternatives You've Considered

Omitting the queue name and scale from the hydrated configuration does prevent Jobs from executing, so our hard requirement is satisfied. However, we think being able to define a queue with scale 0 better matches our intent.

### Additional Context

As an implementation detail for how we manage our configuration, we use a baseline configuration and then per-environment overlays. The baseline and overlays are both expressed as YAML files that are combined through the loose equivalent of `Map.merge/2` with last-write-wins and fairly naive recursion, through a tool called Helm. In that definition style, there's basically no good way to express that one key that is present in the base file should be omitted from the merged form, as you can only overwrite its value, and setting `nil` or `null` would have other bad effects. So today, we don't define any Oban queue sizes in the baseline files, and define them exclusively in the per-environment files, so introducing a new one requires making the same edit to N files. Being able to express the diff as something like this instead would be a lot more graceful for us.

```yaml
# base configuration
oban:
  queues:
    a: 1
    b: 2
    c: 3

# environment that needs to disable 'b' queue only
oban:
  queues:
    b: 0
```

We have not yet upgraded to Oban Pro or Oban 2.x and I don't know when we will evaluate that decision. I do not mention this to intentionally apply financial pressure in any way, only to be honest and transparent that we are strictly OSS users today. I don't believe the outcome of this inquiry will have any significant bearing on that evaluation one way or the other.

**Comment by sorentwo** [comment]
This is an exceedingly diplomatic and well structured proposal. As hinted in the original Slack discussion, this seems like a perfectly valid request to me.

I lean very heavily toward accepting `paused: true` as a queue option after the changes in 02ac0ff. That means you could declare queues like this:

```elixir
queues: [
  a: 1,
  b: [limit: 2, paused: true],
  c: 3
]
```

It's a one line code change and some documentation updates.

Whether you're using Oban Pro or not has no bearing on the decision. However, the change would only be available in 2.0 so you'd need to upgrade to get the benefits.
