### ISSUE TITLE
Kubernetes Integration Advice

### ISSUE THREAD

**Issue by ericsullivan** [sorentwo/oban#299]
### Is your feature request related to a problem? Please describe.

We've got a job that's pretty resource intensive, but very sporadically run (every couple weeks). The job is already using flow so we'd like to have it run on a very powerful machine, but they're expensive, especially when it will mostly be idle. We're deploying to kubernetes, so we thought a solution would be to take advantage of automatic scaling (run the job on a cluster that usually has zero instances).

The documentation suggests an approach [https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/], that I think can be accomplished with `Oban.drain_queue`. I believe I'll need to set the retry count to 0 to prevent it from idling if a job fails. Does that approach seem correct? Each additional job added to oban will have to create a kubernetes job. That'll mean there might be multiple processes each calling drain_queue, will they work fine? ex: 3 drain_queue processes are kicked off for a queue with 2 items in it. The first two should processes should perform the job for a while and then terminate on completion, while the third will terminate immediately.

### Describe the Solution You'd Like

I think it'll work as is, I just wanted to reach out for guidance.

**Comment by sorentwo** [comment]
I'm not sure I completely understand your use case / situation, but I'll attempt to provide guidance as best I can!

If you use `Oban.drain_queue` from three processes simultaneously only _one_ of them will process the _all_ the jobs in the queue. The `drain_queue` function greedily consumes every job available for the provided queue, and it is intended for testing purposes. That doesn't mean you can't use it in production, just be aware that it will attempt to process every job in the queue and you won't have any horizontal scaling.

I don't believe you need to use `drain_queue` at all for what you're trying to accomplish. You can put the resource intensive jobs into a queue that is only ran on the powerful machine instances. When that instance type starts up it will work through the jobs. You can set a queue limit of 1 to ensure that only one job runs at a time on each node.

You can use a job (or any bit of code) to start up the large instance. If you use [Oban Pro's batch jobs](https://hexdocs.pm/oban/batch.html#content) you could automatically scale the instance back down after all of the jobs are complete as well. Some psuedo code to demonstrate what I mean:

```elixir
def insert_intensive_batch(args_list) do
  # Scale to the number of jobs in the batch
  args_list
  |> length()
  |> MyApp.InstanceManager.scale_large_instances()

  # Insert jobs into the batch
  args_list
  |> MyApp.IntenseBatch.new_batch()
  |> Oban.insert_all()
end


defmodule MyApp.IntenseBatch do
  use Oban.Pro.Workers.Batch, queue: :intense

  @impl Oban.Worker
  def process(%Job{args: args}) do
    do_something_intense(args)
  end

  @impl Oban.Pro.Workers.Batch
  def handle_exhausted(%Job{}) do
    # Jobs are completed or discarded, we can scale back down now
    :ok = MyApp.InstanceManager.scale_large_instances(0)
  end
end
```

**Comment by ericsullivan** [comment]
I like the exhausted method, but I want to scale to 0 if there are no pending jobs in the queue. 

From the kubernetes docs: 
"Start a Job that works on tasks from the queue. The Job starts several pods. Each pod takes one task from the message queue, processes it, and repeats until the end of the queue is reached:

That's why I thought `drain_queue`, but then we can't horizontally scale. Is there some way to terminate when the queue is empty? Something like an after processing hook, which checks pending length, and if it's 0, terminates with a success code?

**Comment by sorentwo** [comment]
> Is there some way to terminate when the queue is empty?

That is the goal of using a batch with the `exhausted` hook. If that doesn't work for you then you can use a telemetry handler to check that queue, or a periodic job that checks the queue size and scales things down. Either way, you only need a small Ecto query to check the queue size:

```elixir
Oban.Job
|> where(queue: "my-queue-name")
|> select(count())
```

**Comment by ericsullivan** [comment]
Ok, thank you for the help. I believe I can work with that. I'm thinking telemetry to catch completed jobs, and if empty to scale down.

**Comment by sorentwo** [comment]
Great. Let me know how it goes 👍
