### ISSUE TITLE
Crashes on Heroku

### ISSUE THREAD

**Issue by khedaywi** [sorentwo/oban#30]
Oban works great on my development machine, but when I deploy to Heroku the application refuses to start. 

When I remove the line `{Oban, Application.get_env(:myapp, Oban)}` from the children list the application starts normally.

````
def start(_type, _args) do
    children = [
      MyApp.Repo,
      MyAppWeb.Endpoint,
      {Oban, Application.get_env(:myapp, Oban)}
    ]

    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end
````

The config details are: 

```
config :myapp, Oban,
  repo: MyApp.Repo,
  prune: {:maxlen, 100_000},
  queues: [default: 5]
```

The logs given by Heroku don't seem to be helpful. 

Here's a snippet of the logs: 

````
2019-07-16T06:28:37.821079+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-16T06:28:58.301285+00:00 heroku[web.1]: Starting process with command `MIX_ENV=prod mix phx.server`
2019-07-16T06:29:01.467000+00:00 app[web.1]: [heroku-exec] Starting
2019-07-16T06:29:02.466364+00:00 app[web.1]: mix.exs:15
2019-07-16T06:29:02.466366+00:00 app[web.1]:
2019-07-16T06:29:08.000526+00:00 app[web.1]: 06:29:08.000 [info] Running MyApp.Endpoint with cowboy 2.6.3 at :::12628 (http)
2019-07-16T06:29:08.054219+00:00 app[web.1]: 06:29:08.053 [info] Access MyApp.Endpoint at https://myapp.com
2019-07-16T06:29:08.400370+00:00 app[web.1]: 06:29:08.400 [info] Application myapp exited: shutdown
2019-07-16T06:29:09.923062+00:00 app[web.1]: {"Kernel pid terminated",application_controller,"{application_terminated,myapp,shutdown}"}
2019-07-16T06:29:09.923244+00:00 app[web.1]: Kernel pid terminated (application_controller) ({application_terminated,myapp,shutdown})
2019-07-16T06:29:09.923533+00:00 app[web.1]:
2019-07-16T06:29:12.706848+00:00 app[web.1]: Crash dump is being written to: erl_crash.dump...done
````

I've reviewed the `erl_crash.dump`, but didn't notice anything out of the ordinary, albeit the file is super long. 

Thanks for the help!

**Comment by sorentwo** [comment]
There isn't much to go by in those logs, so all I have are some questions and guesses.

1. What version of Oban are you running?
2. Have you ran the migrations in production?
3. Does it work if you disable pruning?

If it still doesn't work after the migrations have ran and the pruning is disabled then maybe you can start it in an iex session and get a more useful crash report.

```
{:ok, sup} = Oban.start_link(Application.get_env(:myapp, Oban))
```

**Comment by sorentwo** [comment]
@khedaywi Have you had any luck or do you have any more information?

**Comment by khedaywi** [comment]
@sorentwo Thanks for following up. 

Running Oban version 0.5.0. DB migrations have been made in production. 

I ran a remote IEx session and ran the following: 

```
iex(2)> {:ok, sup} = Oban.start_link(Application.get_env(:myapp, Oban))
{:ok, #PID<0.547.0>}
** (EXIT from #PID<0.542.0>) shell process exited with reason: shutdown

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, sup} = Oban.start_link([repo: MyApp.Repo, prune: :disabled, poll_interval: 1_000 ,queues: [default: 5]])
{:ok, #PID<0.565.0>}
** (EXIT from #PID<0.563.0>) shell process exited with reason: shutdown

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

I tried running the elixir app in production mode on my dev machine and Oban works fine by running the Oban.start_link/1 function from iex. 

As note, on my dev machine and Heroku I'm running Elixir 1.9.0 and Postgres 11.4. I'm using one Dyno on Heroku. Our Heroku Postgres version allows for 120 connections and has a pool size of 10. I just checked the stats on the Postgres instance and it's sitting at 18/120 connections. 

I thought that maybe there was an issue related to Postgres connection limits, but that doesn't seem to be the case. Difficult to track down without any error messages.

I'll try to debug further. If you have any other suggestions I'll take a look. 

Thanks!

**Comment by sorentwo** [comment]
I'd expect to see _some_ error messages before it just shut down. You said it works in development, so I'm assuming you're modifying the config before pasting it and that your app isn't called `MyApp`.

If I start the supervisor using the same configuration locally, using the wrong value for the repo, I get a list of errors with full stack traces:

```
iex(2)> [error] GenServer Oban.Notifier terminating
** (UndefinedFunctionError) function MyApp.Repo.config/0 is undefined (module MyApp.Repo is not available)
    MyApp.Repo.config()
    (oban) lib/oban/notifier.ex:83: Oban.Notifier.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:start, Oban.Notifier}}
[error] GenServer Oban.Notifier terminating
** (UndefinedFunctionError) function MyApp.Repo.config/0 is undefined (module MyApp.Repo is not available)
    MyApp.Repo.config()
    (oban) lib/oban/notifier.ex:83: Oban.Notifier.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:start, Oban.Notifier}}
[error] GenServer Oban.Notifier terminating
** (UndefinedFunctionError) function MyApp.Repo.config/0 is undefined (module MyApp.Repo is not available)
    MyApp.Repo.config()
    (oban) lib/oban/notifier.ex:83: Oban.Notifier.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:start, Oban.Notifier}}
[error] GenServer Oban.Notifier terminating
** (UndefinedFunctionError) function MyApp.Repo.config/0 is undefined (module MyApp.Repo is not available)
    MyApp.Repo.config()
    (oban) lib/oban/notifier.ex:83: Oban.Notifier.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, {:start, Oban.Notifier}}
[error] GenServer Oban.Queue.Default.Producer terminating
** (UndefinedFunctionError) function MyApp.Repo.update_all/2 is undefined (module MyApp.Repo is not available)
    MyApp.Repo.update_all(#Ecto.Query<from j0 in Oban.Job, where: j0.state == "executing", where: j0.queue == ^"default", where: fragment("  NOT EXISTS (\n    SELECT 1\n    FROM pg_locks\n    WHERE locktype = 'advisory'\n    AND classid = 'oban_jobs'::regclass::oid::int\n    AND objid = oban_wrap_id(?)\n  )\n", j0.id)>, [set: [state: "available"]])
    (oban) lib/oban/queue/producer.ex:147: Oban.Queue.Producer.rescue_orphans/1
    (oban) lib/oban/queue/producer.ex:76: Oban.Queue.Producer.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
** (EXIT from #PID<0.471.0>) shell process exited with reason: shutdown
```

* What version of Erlang are you running?
* What is your log configuration in production?
* Is there anything special about your production repo config?

**Comment by khedaywi** [comment]
Okay, I got it figured out. 

The issue is the elixir buildpack (https://github.com/HashNuke/heroku-buildpack-elixir) used for Heroku defaults to erlang 20. Updating the elixir_buildpack.config file in the root directory with the below contents did the trick:
```
# Elixir version
elixir_version=1.9.0

# Erlang version
erlang_version=22.0.3
```

A list of compatible erlang verisons with this buildpack are listed here: [https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions](https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions)

Thanks for the help! Looking forward to placing Oban into production.

**Comment by khedaywi** [comment]
@sorentwo I'll add a Troubleshooting section to the README in a few if you'd like to include it.

**Comment by sorentwo** [comment]
Erlang 20 would do it! There is ample use of `handle_continue` in Oban, which only works in Erlang 21.0 and up.

A note about the minimum version would be a nice addition to the README.
