### ISSUE TITLE
(undefined_function) function jsonb_to_tsvector(jsonb, unknown) 

### ISSUE THREAD

**Issue by milmazz** [sorentwo/oban#303]
## Environment

- Oban Version: Oban v2.0.0-rc.3, Oban.Web v2.0.0-alpha.1, Oban.Pro v0.2.1
- PostgreSQL Version: 10.11

### Current Behavior

According to the following exception, `Oban.Web.Query` is using the text search function `jsonb_to_tsvector` from PostgreSQL, which was added on PostgreSQL version 11.0

https://sentry.io/share/issue/dabbc718cf644339957edf6debc055d7/

### Expected Behavior

From the Requirements section in the `README` we can find the following:

> Oban has been developed and actively tested with Elixir 1.8+, Erlang/OTP 21.1+ and PostgreSQL 11.0+. Running Oban currently requires Elixir 1.8+, Erlang 21+, and PostgreSQL 9.6+.

So, I would expect that `Oban.Web.Query` uses a method compatible with PostgreSQL version 9.6 or greater. That, or we should update the `README` document to reflect that the minimum PostgreSQL version is 11.0, but that will force a lot of folks to upgrade their systems I guess.

**Comment by sorentwo** [comment]
@milmazz This is _essentially_ fixed. There are dramatic search differences between 10 and 11/12/13 so I've opted to make searching in 10 limited, but crash free. Once your team or others are able to upgrade to 11+ the search experience will improve.

**Comment by milmazz** [comment]
@sorentwo Thanks, I'll try the latest release asap.
