### ISSUE TITLE
Web: Support long polling transport via config

### ISSUE THREAD

**Issue by Bestra** [sorentwo/oban#304]
### Is your feature request related to a problem? Please describe.

Our current deployment environment doesn't support websockets.  We'd like to be able to use the Web UI when our LiveView socket is set up to use the `longpoll` transport.

### Describe the Solution You'd Like

Surface a config option we can set to use longpolling in the Web UI rather than websockets.  

### Describe Alternatives You've Considered
N/A

### Additional Context

We did a little investigation, and I think the LiveSocket setup on the javascript side has to be initialized directly using the LongPoll transport for this to work.

```js
import { Socket, LongPoll } from 'phoenix';
import LiveSocket from 'phoenix_live_view';
 let liveSocket = new LiveSocket('/live', Socket, {
    transport: LongPoll, // etc
  });
```

From what I gather there's no automatic fallback method, at least from https://elixirforum.com/t/live-view-fallback-with-no-websocket/26068/16

**Comment by sorentwo** [comment]
@Bestra Longpoll support is in ObanWeb master and will be in the next release (2.1, early next week).

**Comment by Bestra** [comment]
@sorentwo thank you so much for the quick turnaround!
