### ISSUE TITLE
Batch different job types (oban_pro)

### ISSUE THREAD

**Issue by enewbury** [sorentwo/oban#306]
### Is your feature request related to a problem? Please describe.

I am trying to run two types of jobs in parallel, but then report back to a single callback when both job types are finished. For example: We want to archive an account, which should kicks off jobs, emailing all subscribers to that account, and in parallel, backing up all posts by that user to S3 before deleting.  When both of those parallel job types complete, report back to the account level and remove the account.

### Describe the Solution You'd Like

in BatchManager perhaps instead of getting "worker" off of meta, it could look in the args first to see if it has been configured
```elixir
  def handle_event([:oban, :job, _], _timing, meta, pid) do
    with %{"batch_id" => batch_id} <- meta.args do
      worker = Map.get(meta.args, "callback_worker", meta.worker)
      :ok = GenServer.cast(pid, {:check, batch_id, worker})
    end

    :ok
  end
```
Then within Workers.Batch, new_batch could take a list of changesets, and a callback_worker could be configured in opts.
Then it would have to set the callback_worker as an argument if it is configured, similar to batch_id
```elixir
def new_batch([changeset | _] = changesets, opts \\ []) when is_map(args) and is_list(opts) do
        {batch_id, opts} = Keyword.pop(opts, :batch_id, gen_id())
        {callback_worker, opts} = Keyword.pop(opts, :callback_worker, __MODULE__),

        for changeset <- changesets do
          changeset
          |> Changeset.put_change(:batch_id, batch_id)
          |> Changeset.put_change(:callback_worker, callback_worker)
        end
      end
```
I just hacked this together, as an example, so no idea if it works.
I'd be interested to hear of pitfalls you could anticipate from using this strategy.
### Describe Alternatives You've Considered

At the moment, I'm just doing a batch of the first type, and when that complete, a batch of the second type, but obviously we aren't getting full parallelization this way.

I had also thought about the possibility to structure this as a nested tree structure like a supervision tree, where you could have batches of batches which would allow each batch to be a single type, but it catches the callback, and bubbles it up to the parent batch instead.  This sounded way more complicated, so I have more hope the configurable worker strategy above.

**Comment by sorentwo** [comment]
@enewbury Thanks for the suggestion!

What you're describing looks like a perfect fit for the in-progress "Workflow" worker. In a Workflow you define relationships between multiple jobs and allow them to run in sequence, fan out, fan in, etc; like a directed acyclical graph.

In this particular case you would define four jobs: `Archive`, `Email`, `S3`, `Cleanup` and they would flow like this:

```
             ┌──────────────────────┐             
             │     Archive Job      │             
             └──────────────────────┘             
                         │                        
      ┌───────────┬──────┴──────┬───────────┐     
      │           │             │           │     
      ▼           ▼             ▼           ▼     
┌──────────┐┌──────────┐  ┌──────────┐┌──────────┐
│Email Job ││Email Job │  │  S3 Job  ││  S3 Job  │
└──────────┘└──────────┘  └──────────┘└──────────┘
      │           │             │           │     
      └───────────┴──────┬──────┴───────────┘     
                         │                        
                         ▼                        
               ┌───────────────────┐              
               │    Cleanup Job    │              
               └───────────────────┘              
```

I'll keep your use case in mind and post back here for feedback as the feature progresses.

**Comment by enewbury** [comment]
That sounds awesome, looking forward to hearing more!

**Comment by sorentwo** [comment]
The workflow feature is nearly ready for release and I've posted the preliminary docs as a gist. Any feedback is appreciated! https://gist.github.com/sorentwo/3012c683a74506379913452345a885c6

**Comment by sorentwo** [comment]
This was handled with the workflow feature in Oban Pro 👍

**Comment by enewbury** [comment]
@sorentwo Sorry, I moved to a different client, and never followed up, but the workflow mechanism looks awesome!  Looking forward to using it when I have the opportunity.
