### ISSUE TITLE
Runtime error with config example

### ISSUE THREAD

**Issue by sfusato** [sorentwo/oban#310]
### Environment

- Oban Version: 2.0
- PostgreSQL Version 12.3
- Elixir & Erlang/OTP Versions (`elixir --version`) 1.10.2

### Current Behavior
The 2nd configuration example:
```
queues: [
  default: 10,
  mailers: [limit: 20, poll_interval: :timer.seconds(30)],
  events: [limit: 50, paused: true]
]
```
throws this error: 
```
** (Mix) Could not start application nemo: Nemo.Application.start(:normal, []) returned an error: shutdown: failed to start child: Oban
    ** (EXIT) an exception was raised:
        ** (ArgumentError) expected :queues to be a keyword list of {atom, integer} pairs
            (oban 2.0.0) lib/oban/config.ex:149: Oban.Config.validate_opt!/1
```
The 1st configuration example works fine though:
```
queues: [default: 10, mailers: 20, events: 50, media: 5]
```
### Expected Behavior
Working config examples.

**Comment by sorentwo** [comment]
@sfusato Those config examples are for the unreleased v2.1, not the current v2.0 release. There is a note at the top of the README that explains it:

> _Note: This README is for the unreleased master branch, please reference the [official documentation on hexdocs][hexdoc] for the latest stable release._

v2.1 will be released soon 👍

**Comment by sfusato** [comment]
Thank you for the clarification! I got them from hexdocs (v2.0.0), btw.

**Comment by sorentwo** [comment]
Oh, I see! That's leaking from when I published guide updates via `mix hex.publish docs`. I'll watch out for this in the future when I publish doc updates.
