### ISSUE TITLE
Oban Leaking PG Connections

### ISSUE THREAD

**Issue by bmteller** [sorentwo/oban#313]
### Environment

- Oban Version: 1.2.0
- PostgreSQL Version: 11.4

### Current Behavior

During an error spike in the application caused by insufficient postgresql connections Oban leaked a large number of postgresql connections. They were visible in pg_stat_activity because the last query performed was: 'LISTEN "public.oban_signal"'

### Expected Behavior

Oban doesn't leak connections.

---

If you look at the Oban.Notifier (https://github.com/sorentwo/oban/blob/master/lib/oban/notifier.ex#L195) when it receive 'EXIT' it doesn't check if the pid is actually the pid of the Postgrex.Connection so its possible if something that is not the supervisor signals exit to the Oban.Notifier process that it would leak connections. However, I don't understand under what circumstance this could possibly happen. There doesn't seem to be any calls to Process.exit() inside Oban that could trigger this behaviour. If a supervisor terminates its child terminate() is called instead of handle_info.

**Comment by sorentwo** [comment]
Sorry you ran into that. It was fixed with https://github.com/sorentwo/oban/commit/0e34c451b7722fc38e7f815af126755084cb89bd, which is included in v2.0
