### ISSUE TITLE
oban_pro insert fails for large batches

### ISSUE THREAD

**Issue by enewbury** [sorentwo/oban#319]
### Environment

- oban: 2.0.0, oban_pro: 0.3.1
- PostgreSQL Version: 10.11
- erlang 22.3.1, elixir 1.10.3-otp-22

### Current Behavior

We are attempting to create a large batch, (around 100,000). This is over the limit of a postgres insert query so we get error
```
(Postgrex.QueryError) postgresql protocol can not handle 96930 parameters, the maximum is 65535
```

### Expected Behavior
Under normal situations, we would simply insert jobs in chunks, but because this is a batch, we want them to all go in at once since there is the possibility of a race condition: if part of the jobs are inserted and they are all processed before the next chunk is inserted, then the batch would be considered `complete`, even though there are more that have not yet been inserted.

I'm not 100% on how the triggering mechanism works, but would it work to insert in chunks inside an Ecto multi transaction and get the notify after they are all inserted?

**Comment by enewbury** [comment]
Found this in the pg_notify docs, which I believe is the mechanism that Oban is using.  It sounds like using Ecto.multi would solve our issue, but leaving this open for the sake of documentation
```
NOTIFY interacts with SQL transactions in some important ways. Firstly, if a NOTIFY is executed inside a transaction, the notify events are not delivered until and unless the transaction is committed. 
```

**Comment by sorentwo** [comment]
Batches of 100,000 jobs? Fun! You can accomplish this within a single batch by using a multi. Here is a short pipeline that demonstrates how you'd do it:

```elixir
list_of_args
|> MyBatch.new_batch()
|> Enum.chunk_every(5_000)
|> Enum.with_index()
|> Enum.reduce(Ecto.Multi.new(), fn {changesets, index}, multi ->
  Oban.insert_all(multi, "batch_#{index}", changesets)
end)
|> MyApp.Repo.transaction()
```

A few notes of explanation:

* I chose to chunk every 5,000 jobs, you can use a smaller number but anything under 65,000 should work.
* The `Enum.with_index` call is necessary to provide a unique name for each multi, without that you'll get an error.
* The jobs are all inserted together within a transaction and won't start executing until they all go in.

Let me know if that solution (or another) works for you. This seems like a nice addition to the batch guides.

**Comment by enewbury** [comment]
Works great, thank you! And yes, definitely I think is a good candidate for the guides.

**Comment by sorentwo** [comment]
I've added a section to the guides https://hexdocs.pm/oban/batch.html#inserting-large-batches

**Comment by enewbury** [comment]
@sorentwo Unfortunately in prod I'm still getting the error, and can confirm in the stacktrace that it is running through the multi.  I'm thinking maybe this is because multi still sends all commands in the transaction in one round trip and the payload is still too big for the postgres adapter?  Just a theory, but we're not sure what to try from here. Any thoughts?

**Comment by enewbury** [comment]
Actually, false alarm! I was reading "params" as "rows" so I had my batch limit at 50k, thinking that would be below ~65k, but since each row has a bunch of params, just going to set the limit conservatively.

**Comment by sorentwo** [comment]
@enewbury Whew. Glad to hear it was a batch-size issue and not a more foundational problem.

**Comment by enewbury** [comment]
Well if you don't hear from me tomorrow after the deploy goes out tonight, then all is well :D

**Comment by sergiotapia** [comment]
Thank you @sorentwo for this. I had the same issue inserting 12,000 oban jobs at the same time in Postgres.
