### ISSUE TITLE
Issues with contab and upgrading to 2.0/2.1

### ISSUE THREAD

**Issue by ProtoJazz** [sorentwo/oban#320]
### Environment

- Version 1.2 works, 2.0/2.1 fails
- PostgreSQL Version:  12.3
- Elixir & Erlang/OTP Versions (`elixir --version`)
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 22)

### Current Behavior

Under 1.2 I have this crontab in my config 

```
 crontab: [
    {"0 2 * * WED", MyApp.Workers.Worker, args: %{user: 2}},
   ]
```

Works fine, and matches the docs I think. 

But when I upgrade to 2.1 or 2.0, it throws an error on startup 

```
expected :crontab to be a list of {expression, worker} or {expression, worker, options} tuples
```

### Expected Behavior

Do I need to change how my crontab is defined or something?

**Comment by sorentwo** [comment]
That is a valid cron expression and the options look fine. Is that worker defined in your application? When the app boots it verifies that the worker exists and that it is a defines a `perform/1` function. My guess is that the worker defines `perform/2`, but wasn't upgraded to handle `perform/1`.

**Comment by ProtoJazz** [comment]
Yup, that was it. Updated the workers properly and it works just fine now. Thanks
