### ISSUE TITLE
Storing job metadata

### ISSUE THREAD

**Issue by v0idpwn** [sorentwo/oban#323]
### Is your feature request related to a problem? Please describe.

It's not exactly a problem but, when jobs fail, I wish they had more context.

### Describe the Solution You'd Like

A new :map field for Oban.Job called `metadata`. This would allow me to store all the info I want on a place dedicated to this purpose during the insertion.

### Describe Alternatives You've Considered

- Passing metadata as a param, which I personally think is inadequate
- Using the tag system, which I found out that doesn't work well for this purpose
- Storing on a new table, which I think is sub-optimal

### Additional Context

Example use-case: storing the request id which triggered the job to make debugging easier

**Comment by gugahoa** [comment]
The example use-case is exactly the same I also have.
Right now we use OpenTelemetry at work, and to propagate trace context correctly I'm adding to the job arguments the relevant propagation values, and on `[:oban, :job, :start]` telemetry event I'm injecting that context back.

It would be awesome to be able to somehow add the `metadata` on job insert.
I'll share more on how I'm approaching this tomorrow.

**Comment by sorentwo** [comment]
When I initially introduced the `tags` array I considered adding a `meta` jsonb column instead, but decided against it. My thinking at the time was that anything people would put in `meta` that wasn't some tag-like data could be put into `args`. 

The `args` field is a free form map and as of Oban 2.0 it doesn't have any special handling. You can match on any fields of the `args` map, or ignore the ones you don't care about.

I'm willing to hear more about your requirements and use case. However, adding a new column would require a new migration, which I'm _very_ hesitant to do at this point.

**Comment by gugahoa** [comment]
Almost forgot to post how I'm handling it:

I created a wrapper around `Oban.Worker` to inject the trace context inside `args`, when calling to `new/2`
```elixir
defmodule Tracing.ObanWorker do
  @moduledoc """
  Tracing.ObanWorker is a wrapper around Oban.Worker that defines a
  `new/2` function with span propagation logic
  """

  @doc false

  defmacro __using__(opts) do
    quote location: :keep do
      use Oban.Worker, unquote(opts)

      require OpenTelemetry.Tracer

      @impl Oban.Worker
      def new(args, opts) when is_map(args) and is_list(opts) do
        args = add_trace_context(args)
        Oban.Job.new(args, Keyword.merge(__opts__(), opts, &Oban.Worker.resolve_opts/3))
      end

      defp add_trace_context(args) do
        add_trace_context(args, :ot_propagation.http_inject([]))
      end

      defp add_trace_context(args, []), do: args

      defp add_trace_context(args, trace_context) when is_map(trace_context),
        do: Map.put(args, "trace_context", trace_context)

      defp add_trace_context(args, trace_context) do
        trace_context =
          trace_context
          |> Enum.into(%{})

        add_trace_context(args, trace_context)
      end

      defoverridable Oban.Worker
    end
  end
end
```

Then I created a module, which defines functions that will handle Oban's telemetry events
```elixir
defmodule Tracing.ObanHandler do
  @moduledoc """
  Oban tracing module
  """

  def handle_event([:oban, :started], _, meta = %{worker: worker, args: args}, _) do
    client_attributes =
      if client_id = args["client_id"] do
        [{"app.client_id", client_id}]
      else
        []
      end

    args_attributes = Enum.map(args, fn {key, value} -> {"worker.args.#{key}", value} end)

    attributes =
      meta
      |> Map.drop([:args, :worker])
      |> Enum.map(fn {key, value} -> {"worker.#{to_string(key)}", to_string(value)} end)

    tracer = :opentelemetry.get_tracer()

    trace_context =
      args
      |> Map.get("trace_context")
      |> Map.to_list()

    :ot_propagation.http_extract(trace_context)

    :ot_tracer.start_span(tracer, to_string(worker), %{
      attributes: attributes ++ args_attributes ++ client_attributes,
      kind: :SPAN_KIND_CONSUMER
    })
  end

  def handle_event([:oban, :failure], _, %{kind: kind, error: error, stack: stack}, _) do
    tracer = :opentelemetry.get_tracer()
    span_ctx = :ot_tracer.current_span_ctx(tracer)

    attributes = [
      {"worker.error.kind", kind},
      {"worker.error", error},
      {"worker.error.stack", stack},
      {"error", true}
    ]

    :ot_span.set_attributes(tracer, span_ctx, attributes)
    :ot_tracer.end_span(tracer)
  end

  def handle_event([:oban, :success], _, _, _) do
    tracer = :opentelemetry.get_tracer()
    :ot_tracer.end_span(tracer)
  end
end
```


This has worked so far, although there's a flaw. The context injected inside `args` is not the same context which effectively schedules the job.

For example:
```elixir
# Context 1
job = Job.new(%{foo: "bar"})

# Context 2
Oban.insert!(job)
```

Here the context which will appear on our tooling will be `Context 1` when it should be `Context 2`
This has not been a problem for us, but it's a flaw in how we solved the problem.

**Comment by sorentwo** [comment]
@gugahoa That's another great use case. I don't believe using `meta` would improve your context situation though, as the meta would also be passed to `Job.new`.

Both of the cases presented are definitely "meta" examples. Some recent discussion in Slack have indicated other good uses for a `meta` key as well, e.g., indicating rescued jobs.

**Comment by sorentwo** [comment]
Closing in favor of #332
