### ISSUE TITLE
Dynamic crontab management & whether this would work

### ISSUE THREAD

**Issue by lawik** [sorentwo/oban#324]
### Is your feature request related to a problem? Please describe.

I have a need for running user-defined crontab scheduling. Pretty much #146 

### Describe the Solution You'd Like

I want to be able to change the crontab-definition by adding and removing things or providing a new list at runtime.

### Describe Alternatives You've Considered

I also want to know if my current thinking is feasible.

I'm thinking I would have a separately named Oban instance with a specific queue name/atom that I use only for this purpose.

If I run a DynamicSupervisor that is responsible for keeping the fluctuating list of schedules/crontab definitions and starting the Oban instance with the right name and more importantly perhaps the right queue name/atom. Would stopping and restarting this with a new configuration to update the schedules and have that work with its own queue be fine in a system which runs a normal Oban setup in parallell?

And would these multiple instances play nice with Oban Web/Pro?

This scheduling is currently managed with Quantum which does have an API for managing cron definitions at runtime. But standardizing on Oban would be nice and give a solid case for Oban Pro.

I'm not sure if my understanding that the queue name/atom thing (such as default) is all that's required to keep the supervision trees from stepping on each other's work.
I understand naming the supervision tree will be needed to run multiple instances.

**Comment by sorentwo** [comment]
You could conceivably make that system work, on a single node. By setting `crontab: false` in your main Oban instance and a second instance with `queues: false`, you could restart the second instance when the crontab changes. That seems rather involved, but definitely doable and wouldn't interfere with anything else at all.

The good news is there is work underway to add an improved Cron plugin to Oban Pro that supports dynamic cron management (add, delete, pause, enable, disable, etc).

**Comment by lawik** [comment]
The additions coming to Oban Pro would be very interesting for this project. Yeah.

You are saying on a single node. What are the gotchas around doing this for multiple nodes you think?

Sounds like we should wait for the feature and just use Quantum for these tasks until then.

**Comment by sorentwo** [comment]
To anybody following this conversation,the [DynamicCron](https://hexdocs.pm/oban/dynamic_cron.html#content) plugin is available now in Oban Pro v0.4.0.
