### ISSUE TITLE
Improve error messages raised by configuration

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#325]
### Is your feature request related to a problem? Please describe.

The config validations are thorough, but they don't explain what is missing or what the specific issue is. For example, when a plugin module can't be found it implies that the list format is wrong, it doesn't state that the module isn't loaded.

### Describe the Solution You'd Like

Provide clearer and more verbose error messages for any configuration issues.

### Describe Alternatives You've Considered

Manually supporting people when they open an issue or ask on Slack.

**Comment by v0idpwn** [comment]
I started a commit on this but the specific error handling would get verbose quickly. Do you think it is worth it?

**Comment by sorentwo** [comment]
Sorry, I should have assigned this one to myself. I'm working on this as part of some shared validations as well.
