### ISSUE TITLE
Add support for dynamic repos

### ISSUE THREAD

**Issue by sasa1977** [sorentwo/oban#326]
### Is your feature request related to a problem? Please describe.

The team I'm working with needs to use dynamic databases. Multiple instances of the same repo will be started (and these can change at runtime), and we want to manage an oban queue in each database.

The Ecto approach for dynamic repos is to use [put_dynamic_repo](https://hexdocs.pm/ecto/Ecto.Repo.html?#c:put_dynamic_repo/1) to configure the instance pid for the caller process. From what I can tell Oban currently doesn't support this.

### Describe the Solution You'd Like

I'm not sure about the best course of actions, but clearly we need some way of passing the repo instance pid to Oban. At the moment I'm inclined to propose an option which requires one oban instance per dynamic repo instance. The question is how can we pass the repo pid to the oban instance? One option is to pass the pid via oban startup options. In this case, the oban instance would be tightly coupled with the repo instance. The client code would then have to start the repo instance first, get the instance pid, and then start the oban instance passing it the repo pid. Oban would have to link itself to the repo to make sure it is stopped if the instance stops. 

### Describe Alternatives You've Considered

A variation of this is to have clients pass some logical instance name (e.g. `{:my_tenant, tenant_id}`) and a callback function which can find the repo pid given the name. A theoretical benefit is that we don't need to restart the oban instance if the repo is restarted, but I feel that this benefit is academic, because if the repo is permanently stopped we still want to stop the oban instance, so we don't really remove any work from the client code.

Another option is to use a global oban instance, and expose interface functions such as `add_repo_instance` and `remove_repo_instance`.  As soon as repo instance is added, Oban would start the set of required processes (such as pollers, cleaners, etc.). The client code would need to pass the repo instance as an option when invoking functions such as `insert`. I'm not sure that this would simplify things for clients, and I'm worried it would complicate the implementation of oban significantly, so it's not an option I'm currently inclined to propose.

### Additional Context

Glancing at the code, I feel that Oban is a bit rigid with respect to dynamic instances. If we want to run multiple oban instances we need to provide a locally registered alias as an atom, which is not perfect for dynamic instances. Since the client code needs to provide a unique name, it would have to pass something like `:"tenant_#{tenant.id}" as the name option, which can overflow the atom table and lead to the system crash. 

Admittedly this feels more like a theoretical issue that is unlikely to cause problems in production. According to the current oban code and BEAM system limit defaults, it would take about 250k of different names generated over time to crash the beam.

Regardless, I think that the improvement is not too hard to implement (though I'm not familiar with the code so I might be missing some subtleties), and that it would not cause any breaking changes in the interface. The idea is to extend the support for the `:name` option to support all valid [GenServer aliases](https://hexdocs.pm/elixir/GenServer.html#t:server/0), such as `{:via, Registry, {MyRegistry, instance_name}}` or `{:global, instance_name}`, as well as plain pids. To make that happen, Oban would need to run its own singleton registry where it would use keys such as `{instance_pid, :config}` or `{instance_pid, :notifier}` to discover the desired information. I can give this a stab in a separate, preparatory PR.

**Comment by sorentwo** [comment]
> From what I can tell Oban currently doesn't support this.

That's correct—this is the first time the issue has come up 😄 How many tenants are we talking about?

> At the moment I'm inclined to propose an option which requires one oban instance per dynamic repo instance. The question is how can we pass the repo pid to the oban instance? One option is to pass the pid via oban startup options. In this case, the oban instance would be tightly coupled with the repo instance.

You could certainly run multiple Oban instances, but it would still require a mechanism to "forward" the repo pid to all of the various processes. The pid could be stored in the `Config` instance that is passed around to the child processes, though that presents a few issues:

1. Each of the various call sites would need an update to make use of the updated config (tedious, but doable)
2. All of the processes store the config they are passed at boot time. We'd need a mechanism to propagate config changes at runtime.

> Another option is to use a global oban instance, and expose interface functions such as `add_repo_instance` and `remove_repo_instance`. As soon as repo instance is added, Oban would start the set of required processes (such as pollers, cleaners, etc.). The client code would need to pass the repo instance as an option when invoking functions such as `insert`. I'm not sure that this would simplify things for clients, and I'm worried it would complicate the implementation of oban significantly, so it's not an option I'm currently inclined to propose.

I believe this could be achieved without restarting processes, provided there is a centralized way to update the config and have that propagate out to all child processes. Changing values like the repo pid, or the timezone, or the database prefix is straight forward and wouldn't require any change tracking. Other complex values, such as the plugin list, would be significantly harder to manage.

> Glancing at the code, I feel that Oban is a bit rigid with respect to dynamic instances. If we want to run multiple oban instances we need to provide a locally registered alias as an atom, which is not perfect for dynamic instances.

You're absolutely right. There are considerations for running multiple instances, but not truly _dynamic_ instances like you're talking about. Some of the named process discovery mechanisms are clunky—names like `MyApp.Oban.Notifier` make for nice observer screenshots, yet they require a lot of `Module.concat` action.

> The idea is to extend the support for the `:name` option to support all valid [GenServer aliases](https://hexdocs.pm/elixir/GenServer.html#t:server/0), such as `{:via, Registry, {MyRegistry, instance_name}}` or `{:global, instance_name}`, as well as plain pids. To make that happen, Oban would need to run its own singleton registry where it would use keys such as `{instance_pid, :config}` or `{instance_pid, :notifier}` to discover the desired information.

I'm intrigued by this and would love to see your approach.

**Comment by sasa1977** [comment]
> Other complex values, such as the plugin list, would be significantly harder to manage.

This is precisely why I think that it's much easier to restart the entire Oban instance when something changes. The way I see it, I'd place the repo instance and an associated oban instance under the same (rest_for_one) supervisor. If I have 5 repo instances, I'll have 5 such supervisors. When a tenant is removed, I'll drop the Oban instance too. No point for it to keep on living anyway. The remaining challenge is a repo instance restart, but this happens infrequently and I'm fine with restarting the oban instance too in this case.

> How many tenants are we talking about?

No idea, though I currently expect a small number, single digit or low two digits.

> I'm intrigued by this and would love to see your approach.

I can give it a try, but be aware that you'll lose those nice observer screenshots then, because most processes in the tree will be presented using their PID. I personally think that's fine, but just wanted to warn you upfront :-)

**Comment by sorentwo** [comment]
> I can give it a try, but be aware that you'll lose those nice observer screenshots then, because most processes in the tree will be presented using their PID. I personally think that's fine, but just wanted to warn you upfront :-)

Understood! I was kidding about keeping observer pretty. The manual name construction is a perennial issue.

**Comment by sorentwo** [comment]
@sasa1977 is there anything else you need to try these multi tenancy plans? I'm aiming to release v2.2.0 next week and would love to bundle it all into a single release.

**Comment by sasa1977** [comment]
We're still missing the main part, and that's the ability to somehow pass the Repo instance pid to Oban. I don't think we have agreed on the approach for that, right?

**Comment by sorentwo** [comment]
> We're still missing the main part, and that's the ability to somehow pass the Repo instance pid to Oban

Yes, of course.

>  I don't think we have agreed on the approach for that, right?

Right, we didn't figure that part out. After thinking about this for a little bit this is the approach I came to (not necessarily in this order):

1. Add a `repo_pid` field to `Oban.Config`
2. Add a function to update the stored config. As discussed previously, it would be limited and shouldn't support changing `queues`, `crontab`, or `plugins`.
3. Wrap all repo calls in a helper module, rather than calling `repo.all`, `repo.transaction`, etc. That way we can consistently handle setting the `prefix`, the `log` level, and optionally setting the repo `pid` if it is stored in the config.

For the last item, I'm not sure what the interface would look like exactly. The important part is that it makes all repo calls consistent, and that it can run in _oban land_ or _user land_, as we don't want to taint the calling process with `put_dynamic_repo/1` calls. I imagine the function would look something like this:

```elixir
def call(%Config{repo_pid: nil} = conf, fun, args) when fun in @repo_funs do
  apply(conf.repo, fun, args, prefix: conf.prefix, log: conf.log)
end

def call(%Config{} = conf, fun, args) when fun in @repo_funs do
  orig_pid = conf.repo.get_dynamic_repo()
  repo_pid = conf.repo_pid

  try do
    conf.repo.put_dynamic_repo(repo_pid)

    apply(conf.repo, fun, args, prefix: conf.prefix, log: conf.log)
  after
    conf.repo.put_dynamic_repo(orig_pid)
  end
end
```

That could go in the `Oban.Query` module or another dedicated module.

What do you think?

**Comment by sasa1977** [comment]
If I understand correctly, point 3 is about adding an internal wrapper, right? If so I absolutely agree with it, and that could be done first thing, regardless of the approach take for passing the pid.

When it comes to obtaining the repo pid, I wonder if we could do this via a callback. For example, we could support something like `Oban.start_link(..., get_dynamic_repo: fn -> return_tenant_pid() end)`. This function, if provided, would be called by the wrapper to obtain the pid before executing a repo statement. If the function is not provided, the global repo instance would be used.

If we want to be more in tune with std. OTP, Oban could take a callback module instead. The usage could be something like `Oban.start_link(MyOban, oban_opts)`, and then the user needs to implement e.g. a single callback called `repo_opts/1` in `MyOban`. This function would take `config` as arg and return a keyword with prefix, log level, and pid (all optional). Just like `:get_dynamic_repo` lambda, this callback would be invoked by the wrapper before executing the statement. Note that in this case we need to support passing some optional arg through config (e.g. tenant id), which would allow the callback to resolve the actual pid.

Either way, irrespective of whether lambda or callback module is used, the benefit is that we don't need to implement a manual config update mechanism, because dynamic parameters are late bound, and so the callback has the possibility of providing different parameters at different point in times, like e.g. returning a different pid if repo is restarted.

WDYT?

**Comment by sorentwo** [comment]
> If I understand correctly, point 3 is about adding an internal wrapper, right?

Absolutely right. I numbered them for ease of reference, not necessarily order of implementation 🙂 

> When it comes to obtaining the repo pid, I wonder if we could do this via a callback.

Nice! The callback approach is **much** better than my "store the pid" / "update config" approach. As much as the callback module would be more standard OTP, I _think_ I prefer passing a function to to get the dynamic repo. Setting a prefix and the log level is extremely common and I'd rather that users didn't need to implement a module to support that configuration. I realize it could be done in a backward compatible way, but it doesn't feel cleaner than supporting a pid fetching function (and/or a MFA).

**Comment by sasa1977** [comment]
I definitely wasn't suggesting dropping the current approach where prefix/log level are set globally. I think this should remain the default option, and will serve most needs. Regardless, I think that accepting an anon function is fine in this particular case, since we really care about only one thing - the pid of the dynamic repo instance.

Assuming we have settled on the approach, I'm happy to do the required work. However, I can't commit on the deadline. It's very unlikely I'll be able to start working on this next week, and I also can't make any promises for the short period after that. I'm assuming this feature is not urgent for you (since no one else requested it), while it will definitely become prio for us, so if you're ok with waiting, feel free to assign this issue to me.

**Comment by sorentwo** [comment]
> I definitely wasn't suggesting dropping the current approach where prefix/log level are set globally. I think this should remain the default option, and will serve most needs. Regardless, I think that accepting an anon function is fine in this particular case, since we really care about only one thing - the pid of the dynamic repo instance.

On the surface, without playing with the various implementations, I favor the anonymous function. I'm open to either approach, provided we keep backward compatibility. 

> Assuming we have settled on the approach, I'm happy to do the required work. However, I can't commit on the deadline. It's very unlikely I'll be able to start working on this next week, and I also can't make any promises for the short period after that. I'm assuming this feature is not urgent for you (since no one else requested it), while it will definitely become prio for us, so if you're ok with waiting, feel free to assign this issue to me.

I'm perfectly happy to wait for those changes. As you say, it isn't urgent. The registry work is much more impactful (and necessitates changes to Web and Pro), which is why I'm coordinating a release.

No rush here. I'll assign the issue to you and look out for a PR 👍
