### ISSUE TITLE
Introduce "canceled" state

### ISSUE THREAD

**Issue by ssbb** [sorentwo/oban#330]
### Is your feature request related to a problem? Please describe.

1. It's problematic to find errored jobs when you have a lot of canceled jobs (both marked as discarded).
2. It is not possible to prune only canceled jobs and keep errored.

### Describe the Solution You'd Like

I would like to have `canceled` state.

**Comment by v0idpwn** [comment]
Shall I introduce it in #332, @sorentwo?

**Comment by sorentwo** [comment]
Closing in favor of #332
