### ISSUE TITLE
State :discarded is taken into account when checking for uniqueness

### ISSUE THREAD

**Issue by egidijusz** [sorentwo/oban#337]
### Environment

- Oban Version
2.1.0
- PostgreSQL Version
12.4
- Elixir & Erlang/OTP Versions (`elixir --version`)
elixir 1.10.4, erlang/otp 23

### Current Behavior

Worker module example:
```elixir
defmodule MyApp.ObanWorker do
  use Oban.Worker,
    queue: :test_que,
    unique: [
      period: :infinity
    ]
end
```

When inserting new job (`Oban.insert/1`) with uniqueness enabled (see module example above) - job is **not** inserted if there already is "same" job, but with :discarded state. 

### Expected Behavior

As per [Oban documentation](https://hexdocs.pm/oban/Oban.html#module-unique-jobs) - state :discarded shouldn't be taken into account when checking for uniqueness.
Quote from docs - "By default all states except for :discarded are checked, which prevents duplicates even if the previous job has been completed.".

After explicitly adding `states: Oban.Job.states() -- [:discarded]` (see modified example below) - it works as expected and documented.

Modified worker module example:
```elixir
defmodule MyApp.ObanWorker do
  use Oban.Worker,
    queue: :test_que,
    unique: [
      period: :infinity,
      states: Oban.Job.states() -- [:discarded]
    ]
end
```

Maybe I'm doing something wrong? :thinking:

**Comment by sorentwo** [comment]
This changed in 8683afd0, but the documentation wasn't updated. Previously it wasn't possible to consider `:discarded` for uniqueness at all, which then changed to it being the default. This is a bug.
