### ISSUE TITLE
multiple instances on same node not displayed in Oban Web

### ISSUE THREAD

**Issue by DanielDent** [sorentwo/oban#338]
On a single node, more than one instance of the application may be running. The limit displayed for queues will be the limit of a single of those instances. There is no visibility in the web interface that there are actually two instances of the application on the same node. It will end up showing things like that there are 10 tasks executing simultaneously when the overall limit is showing as 5 (even though it is in fact 2x5).

This is not a high-priority issue for me, but it seems like an oversight.

**Comment by sorentwo** [comment]
This may be an oversight, but there is a workaround for it. Counts are computed using the `node` value, which needs to be unique to properly differentiate between different instances. If you set a unique `node` value for each Oban instance they'll show up properly.

You can see how the node value is typically derived: https://github.com/sorentwo/oban/blob/master/lib/oban/config.ex#L61. The `node_name` function is what is used as a fallback if you don't override it in your config.

**Comment by DanielDent** [comment]
Thanks -- that's good to know.

One thought: from looking at the DB schema, I got the sense that part of how Oban is handling instance failure scenarios is by generating a random instance ID & heartbeating with it. Perhaps appending a 2-3 characters from that into the displayed node info would be helpful?

I understand there's a bit of a simplicity/usability/accuracy trade-off here, perhaps there are reasons this is a bad idea.

**Comment by lawik** [comment]
I have something that I think fits in this general space.

So I'm looking at running two different applications, both using Oban, that are clustered together but have different responsibilities. One of them would run the Oban Web admin UI and expose an endpoint. The other would just be running Oban Web Stats plugin and stuff. Is this feasible or is there another appropriate approach?

**Comment by sorentwo** [comment]
> So I'm looking at running two different applications, both using Oban, that are clustered together but have different responsibilities. One of them would run the Oban Web admin UI and expose an endpoint. The other would just be running Oban Web Stats plugin and stuff. Is this feasible or is there another appropriate approach?

That is entirely feasible. You only need to run the stats plugin on the node that is serving the UI, but you need to run the `Lifeline` plugin on each node. As long as you run the `Lifeline` plugin on each node then the UI can display the proper information.

**Comment by sorentwo** [comment]
> One thought: from looking at the DB schema, I got the sense that part of how Oban is handling instance failure scenarios is by generating a random instance ID & heartbeating with it. Perhaps appending a 2-3 characters from that into the displayed node info would be helpful?

@DanielDent The nonce value is generated per-queue, which is how it can track differences between different instances of the same queue on the same node, i.e. a node restart or a queue crash. The issue here is that if you run the same queue in separate Oban instances on _the same node_ then the node name is the same and it conflates the heartbeats.

I'll have a fix in the next set of Web / Pro releases.

**Comment by sorentwo** [comment]
This took a little bit longer to get around to, but the fix is in the next Pro release.
