### ISSUE TITLE
Jitter for Retries

### ISSUE THREAD

**Issue by coladarci** [sorentwo/oban#340]
### Is your feature request related to a problem? 

yes - we have a job that uses a DB Lock to fail hard if something is already processing that specific ID. We have a spammy stream that makes its way to Oban Jobs and if a bunch fail at the same time and have to retry, they will keep retying together and continue to be locked until "by chance" they make their way through.

### Describe the Solution You'd Like

I would like to be able to configure (globally is fine) a jitter. We previously were using Conduit to retry and their config pattern, we felt, was strong https://hexdocs.pm/conduit/Conduit.Plug.Retry.html in that it was a ratio that gets factored into the retry itself versus a hard-coded jitter MS, for example.

### Describe Alternatives You've Considered

We thought about using Uniq jobs for this to fail the scheduling of two identical jobs (also worth doing).

### Additional Context

You're the best!

**Comment by sorentwo** [comment]
The change is in 👍

**Comment by coladarci** [comment]
🤝
