### ISSUE TITLE
oban web UI not responding to touch events

### ISSUE THREAD

**Issue by DanielDent** [sorentwo/oban#341]
When I click between states ("completed", "executing") on desktop, it is fine. However, tapping on states on mobile does not result in any changes. I am testing on Safari / iOS 14 but had the same issue on iOS 13.

**Comment by sorentwo** [comment]
@DanielDent That's odd. The UI is _meant_ to be used on desktop, but it _should_ also work on tablet/phone. Investigating.

**Comment by DanielDent** [comment]
Your fixes mostly addressed the mobile issues but could use a few improvements still:

1. Make tapping on jobs work. Whatever fixes were applied to make tapping elsewhere functional weren't applied to tapping on jobs.
2. Make it so that it's possible to scroll left-right within the jobs table, much like Bootstrap's  `.table-responsive` class.
3. Make the "queue", "attempt", etc. information on the individual job information screen break across multiple lines if the screen is too narrow to display it all on the same line.
4. (I'm less certain about this) Move the "ATMPT" and "TIME" columns over all the way to the left next to the checkboxes. Possibly even bring the "search for jobs with same worker" button along with them to the right of them (to the right of those columns so that there's lots of space between tapping on that vs tapping on the checkbox on the left of each job).

I know that it currently may be mostly *meant* for desktop. If you fix the tap issue I think it will be fully usable from a phone, and if you can address everything above I think it could be downright mobile *friendly*. Being in a position to get some system observability and even fix some issues with nothing but a phone is a nice position to be in for operations people.

If all you do is just fix the remaining 'tap not working' issue, it will at least be possible to use.
