### ISSUE TITLE
Issue when trying to start app and running test when using oban in umbrella app

### ISSUE THREAD

**Issue by blisscs** [sorentwo/oban#346]
# Environment

- Oban Version
v.2.1.0
- PostgreSQL Version
12.1
- Elixir & Erlang/OTP Versions (`elixir --version`)
elixir 1.8.2, erlang 22.0

# Issue

## Prior to error
Initially I was running the oban in one of the umbrella app. The app could start and the test can be run properly ->
The app configuration looks like below ->

```elixir
# config/config.exs
...
config :app1, Oban,
  repo: App1.Repo,
  queues: [q1: 2, q2: 2]
...
import_config "#{Mix.env()}.exs"

# config/test.exs
config :app1, Oban,
  crontab: false,
  queues: nil,
  plugins: false

# lib/app1/application.ex
...
children = [
  ...
  {Oban, oban_config()}
]
...

defp oban_config(), do: Application.get_env(:app1, Oban)

```

In my test I have several places where I use `Oban.insert/2` to test that I successfully create an oban job.
Everything was running smoothly until I start to add `oban` into another app in the umbrella app.

As per the recommendation on doc we can use `:name` field to make it work. 

so i did adapt the code for `oban_config()` to something like below -> 

```elixir
...
defp oban_config(), do: [name: App1.Oban] ++ Application.get_env(:app1, Oban)
...
```

I am getting the below error 

```elixir
** (exit) exited in: GenServer.call(Oban.Config, {:get, #Function<1.89016239/1 in Oban.Config.get/1>}, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     stacktrace:
       (elixir 1.10.3) lib/gen_server.ex:1013: GenServer.call/3
       (oban 2.1.0) lib/oban.ex:202: Oban.insert/2
```

I have also checkout https://github.com/sorentwo/oban/issues/65 and also try the syntax sample in there but still did not succeeded. 

Please recommend on how to setup properly for umbrella app.

**Comment by sorentwo** [comment]
@blisscs Your configuration looks correct.

All Oban instances have a `:name` attribute, and it defaults to `Oban`. All of the public functions like `Oban.insert/1,2` take the instance name as the first argument and also default to `Oban`. That means you can call `insert` two ways:

```elixir
Oban.insert(changeset)
# or
Oban.insert(Oban, changeset)
```

When your instance is named something other than `Oban` you need to use the `insert/2` instead:

```elixir
Oban.insert(App1.Oban, changeset)
```

**Comment by blisscs** [comment]
Ok, does this also work the same for Oban.insert that takes multi aswell.

I wonder would you take a merge request. that allow me to call `insert/1` instead of `insert/2` for simplicity.


The usage could be -

defmodule Myapp.Oban do
  use Oban.SomeName, name: ProcessName
end

and I can use like.

MyApp.oban.insert(changeset)

which will convert to 
Oban.insert(ProcessName, changeset) internally.

**Comment by sorentwo** [comment]
> Ok, does this also work the same for Oban.insert that takes multi aswell.

Yes, this works for every public function in the `Oban` module.

> I wonder would you take a merge request. that allow me to call `insert/1` instead of `insert/2` for simplicity.

I've resisted introducing a wrapper/callback module like this from the outset. It is fairly simple to do within your application, though, and I encourage you to do so.
