### ISSUE TITLE
Support for overriding default worker settings

### ISSUE THREAD

**Issue by jmnsf** [sorentwo/oban#350]
### Is your feature request related to a problem? Please describe.

Just spotted a job retrying in production almost 2 _weeks_ after it was created. It was a bit of a bug hunt to even get to this conclusion since the job itself was time-sensitive and it made no sense that it was running _now_, but then telemetry showed "20th attempt" and the dominoes came down.

Most of the workers in my app are time-sensitive in the sense that they shouldn't run at all if a significant amount of time has passed. The default of 20 max attempts can add up to a massive (12 days max on the last attempt if my math is right) delay from start, to retry, to permanent failure. So I'll likely go through every Oban worker I've defined and set `max_attempts` to a more reasonable (for my use case) number manually.

This won't be fun and, more importantly, it's hard to enforce for future workers.

### Describe the Solution You'd Like

Ideally, I'd be able to override the defaults for Worker options. The natural Elixir way feels like it'd be through config, either direct on the `Oban.Worker` module, or through a `:worker` key in the already-existing config.

I started working on a PR for this, but because the config is passed via link args, while the worker options are defined at compile time, I'm not sure how to structure this without introducing cyclical dependencies or accessing the config directly via the worker (I'm assuming this wouldn't be an appreciated design since it wasn't done to begin with). I can pick this up again if I'm given some guidance.

### Describe Alternatives You've Considered

Remember to set the value for all the workers or new jobs.

**Comment by sorentwo** [comment]
The `use Oban.Worker` macro is rather small and, as noted, handled at compile time. Worker modules are defined in your application code and only interact with Oban when you insert or execute a job. For those reasons, I suggest defining a function with its own defaults in your application, or an alternate worker module. From there you can access the application config if desired.

It could be something like this:

```elixir
defmodule MyApp.BaseWorker do
  @max_attempts Application.compile_env!(:my_app, [:oban, :max_attempts], 3)

  def new(worker, args, opts \\ []) when is_atom(worker) and is_map(args) do
    standard_opts = Keyword.put_new(opts, :max_attempts, @max_attempts)

    worker.new(args, opts)
  end
end
```

Then you'd call `MyApp.BaseWorker.new/3` where you'd normally call `MyApp.SomeWorker.new/2`:

```elixir
MyApp.BaseWorker.new(MyApp.SomeWorker, args)
# or
MyApp.BaseWorker.new(MyApp.SomeWorker, args, priority: 1)
# or
MyApp.BaseWorker.new(MyApp.SomeWorker, args, priority: 1, max_attempts: 1)
```
