### ISSUE TITLE
Unsorted query in DynamicPruner invalidates 'recent'-guarantee

### ISSUE THREAD

**Issue by jeroenvisser101** [sorentwo/oban#359]
### Environment

- Oban Version (Pro 0.3.2)
- PostgreSQL Version (11.9)
- Elixir & Erlang/OTP Versions (`elixir --version`) (1.11.0/23.1.1)

### Issue
With a maximum length set to `50_000`, the unsorted query passed to `delete_all` could lead to unexpected behaviour.

> A particular output ordering can only be guaranteed if the sort step is explicitly chosen.

In our case, it doesn't keep the most recent 50k, instead, it removes the most recent ones as they complete.

The code below:

```elixir
  defp query_for_mode({:max_len, length}) do
    time = DateTime.utc_now()

    Job
    |> where([j], j.attempted_at < ^time or j.discarded_at < ^time)
    |> offset(^length)
  end
```

...should probably contain an `order_by` clause, as well as the other `query_for_mode` functions.

PS. The guarantee I'm referring to is this one:

> Now the pruner will retain the most recent 50,000 jobs instead.
https://hexdocs.pm/oban/2.2.0/dynamic_pruner.html#using-and-configuring

**Comment by sorentwo** [comment]
The query is always ordered. This is a byproduct of the interaction between limit and offset when the pruner can't catch up with the number of recently completed/discarded jobs. In the short term you can probably alleviate the issue by setting the `limit` to a higher number. By default it only prunes 10k jobs at a time. If you produce more than 10k jobs a minute then it will never keep up.

For example, set the delete limit to 25k (or any number that will work through the jobs produced per-minute):

```elixir
{DynamicPruner, mode: {:max_len, 50_000}, limit: 25_000}
```

**Comment by jeroenvisser101** [comment]
Hey @sorentwo, I'm not sure if I explained the problem we're experiencing correctly, but our expectation was that setting `mode: {:max_len, 50_000}`, the pruner would keep 50k jobs, and whenever this would be exceeded, the oldest jobs would be deleted. This expectation is confirmed when we look at the function, if I understand correctly, uses `offset` to take only the jobs that would exceed the 50k limit. However, I think this function should contain `|> order_by(asc: :completed_at)`, or something similar, to ensure that it actually retains the *most recent* 50,000 jobs.

To be clear, what we saw before we increased the `:max_len`, was that jobs were being deleted shortly after completing while older jobs (>1 month) were still kept around. Is this expected behaviour?

**Comment by jeroenvisser101** [comment]
I just looked again, but I now see that `DynamicPruner.delete_all/2` does order the query, however, the ascending sort on `:id`, combined with the offset would indeed result in the behaviour we're seeing. I think it should sort in descending order, e.g. `[3, 2, 1]`, offset by 2 would leave `[1]` to be deleted, right? I think now it is opposite, and deletes 3 instead.

**Comment by sorentwo** [comment]
@jeroenvisser101 This is fixed in Oban Pro master now. It wasn't as simple as flipping the sort order, since retaining the `max_len` jobs with `offset` requires a different order than deleting the oldest jobs.

To illustrate, imagine you have 9 jobs, with a configuration that keeps three and deletes three. A row with `+` means it is purposefully kept, a row with `-` means it is purposefully deleted, and a row with `|` means it is overflow beyond the delete limit:

```
+ 09 +
+ 08 +
+ 07 +
- 06 -
- 05 -
- 04 -
| 03 |
| 02 |
| 01 |
```

You can see that with that ordering next time it prunes the oldest three are still kept:

```
+ 12 +
+ 11 +
+ 10 +
- 09 -
- 08 -
- 07 -
| 03 |
| 02 |
| 01 |
```

With the new query we will always delete the oldest rows, so our chart looks like this instead:

```
+ 09 +
+ 08 +
+ 07 +
| 06 |
| 05 |
| 04 |
- 03 -
- 02 -
- 01 -

+ 12 +
+ 11 +
+ 10 +
| 09 |
| 08 |
| 07 |
- 06 -
- 05 -
- 04 -
```

In either situation the insert rate exceeds the delete rate—if that is sustained 24 hours a day you **must increase the delete limit** to prevent the table from growing. I've added a new section on [keeping up with inserts](https://hexdocs.pm/oban/dynamic_pruner.html#keeping-up-with-inserts) to the dynamic pruner docs.

**Comment by jeroenvisser101** [comment]
@sorentwo that's awesome! Explanation totally makes it clear. I think deleting the oldest is a nice addition too.

Btw, is there an option for Pro customers to check differences between versions? Maybe a private repo? I guess we could compare the contents of both versions, but that's not super convenient.

Thanks for the fix!

**Comment by sorentwo** [comment]
@jeroenvisser101 No, there isn't a way to diff between versions of private repos. That would require changes to hex and how license are authenticated. It is something we'd _love_ to provide, but don't have a way to do it yet.

**Comment by jeroenvisser101** [comment]
@sorentwo just discovered that diffing on the commandline does support api key auth:

```bash
mix hex.package diff oban_pro 0.4.0..0.4.1 --organization oban
```

That at least helps a bit, although context of those changes might be less clear than with `git blame` ;)

**Comment by sorentwo** [comment]
@jeroenvisser101 Oh, that's fantastic! I hadn't thought to try it from the CLI. 💛

**Comment by jeroenvisser101** [comment]
@sorentwo is there a way for us to use the master version?

**Comment by sorentwo** [comment]
@jeroenvisser101 There isn't a way to use master. I'll have an Oban Pro 0.4.2 out today with the fix.
