### ISSUE TITLE
full timezone edgecase handling

### ISSUE THREAD

**Issue by DanielDent** [sorentwo/oban#360]
An incredibly common source of bugs in applications that deal with future-dated events is failing to consider the impact of changing timezone rules as well as the fact that datetimes can become unrepresentable/ambiguous, even if they didn't start out that way.

It would be neat if application developers could leave all of the heavy lifting involved with future event handling to Oban.

Some decent articles for background on the issues I'm describing:
  * http://www.creativedeletion.com/2015/03/19/persisting_future_datetimes.html
  * https://www.amberbit.com/blog/2017/8/3/time-zones-in-postgresql-elixir-and-phoenix/

I'm submitting this issue so that it's on your radar. Addressing it would likely require schema changes to track data somewhere along the following lines: datetime in original timezone, original timezone, timezone database version used to calculate the initially planned execution time, and whether the job should err on the side of executing early/late/not at all if it's planned execution time becomes unclear.

Implementing a data structure that enables efficiently identifying required schedule changes might be rather non-trivial (you'd probably want to do something like have an index on the job's original timezone database version, timezone, and a lower-cardinality approximate representation of the datetime).

Please don't prioritize this particular issue just because I happen to be a subscriber to Oban Pro/Web. It's not yet a concern with my use cases, and the other things you've mentioned that you are already working on sound more immediately relevant to me anyway.

However it might save somebody some grief to document that these edge cases aren't currently being handled. The documentation currently describes Oban as having timezone support if you've got tzdata around.

**Comment by sorentwo** [comment]
Job management, aside from CRON schedule evaluation, is _always_ in UTC. I have no plans to change that.

However, the plan is to deprecate the top level `:timezone` and `:crontab` options and move them to configuration for a `BasicCron` plugin. That would alleviate any conception that the timezone library is used for scheduling/descheduling jobs.

**Comment by brunolouvem** [comment]
Hello @sorentwo,
I would like to use this issue to clarify some questions about the best way to work with timeone on Oban.
Currently, I have been using timezone UTC-3 and I have some Jobs that have to run hourly, and others that must run in a specific period of time, for example between 9 AM and 5 PM.
Should I do the shift of time manually in the cronjob definition?
I also have been having some problems with the regular Jobs. They always remain stuck in available state for a long time because the schedule_at field is in UTC. However, all Jobs that are in stuck start running when I access the application via IEX. 
Disclaimer:  I have been using the tzdata library for this configuration.

**Comment by sorentwo** [comment]
> Should I do the shift of time manually in the cronjob definition?

No, that isn't necessary if you have the timezone set in your Oban config. In fact, that is _all_ that the timezone setting does. Times are always stored in UTC, but the calculation is done using the provided timezone.

> I also have been having some problems with the regular Jobs. They always remain stuck in available state for a long time because the schedule_at field is in UTC. However, all Jobs that are in stuck start running when I access the application via IEX.

When jobs are in the `available` state the `scheduled_at` time doesn't matter at all—they've already been moved from `scheduled` to `available`. If they start processing when you access with iex then it sounds like the queue wasn't running.
