### ISSUE TITLE
Oban.Testing.perform_job/3 incorrectly modifies provided args

### ISSUE THREAD

**Issue by bitwalker** [sorentwo/oban#363]
### Environment

- Oban Version (2.2.0)

### Current Behavior

When upgrading to 2.2.0, I switched our project to using `perform_job/3` in our test suite, vs calling `perform` directly. A few of our jobs take arguments which are of `DateTime` type, but testing those jobs fails because `perform_job/3` internally runs the arguments through a round of JSON serialization/deserialization, which results in those DateTime values being converted to ISO-8601 formatted string values. Currently I'm working around this by adding a clause which fixes up the arguments to `perform` in the job itself, but this is obviously problematic since in general it means that the arguments given to a job in tests do not match the arguments those same jobs will get in a production environment.

It looks to me like the intent of the JSON serialization was to ensure the keys are formatted as strings, but it has the undesirable side effect of modifying the values as well.

### Expected Behavior

My expectation is that values passed in the `args` parameter are not modified in any way. I think its probably fine to stringify the keys, though in my opinion it would probably be best to instead have `perform_job/3` raise an error if any of the `args` keys are not strings, rather than implicitly transforming them. However, modifying the argument values is definitely unexpected - and in my opinion, undesirable - behavior.

**Comment by sorentwo** [comment]
The args passed to `perform/1` are always deserialized as JSON. The `perform_job/2` function performs a serialize/deserialize sequence to ensure that workers receive args in test the same way they do in production. It isn't only to stringify keys, but to guard against passing unserializable types like tuples, refs, or structs.

Do you have custom Jason handling for DateTime structs? I'm curious how this hasn't come up in production before.

**Comment by bitwalker** [comment]
I suspect I know what's going on here then, the code in question that looks for those args must not be getting called in production, so it hasn't failed, and the way our tests was previously written was setting up the job manually and thus passing a DateTime rather than a string. This is code in a large code base I picked up maintenance of, so I'm still trying to get a sense of what paths in the code are actually taken in practice.

Sorry for the erroneous issue!
