### ISSUE TITLE
[BUG] Jobs stuck in "executing" state perpetually

### ISSUE THREAD

**Issue by deepcut** [sorentwo/oban#364]
Oban version: 2.2.0
Phoenix version: 1.5

Thank you for the great project. As the size of my job load grew, I ran into issues where jobs were not being executed. After further digging, I realized that a number of jobs are stuck in the `executing` state.

Currently I have the queue size config as follows:

```elixir
config :app, Oban,
  repo: App.Repo,
  plugins: [{Oban.Plugins.Pruner, max_age: 60 * 60 * 24 * 21}],
  queues: [default: 10, cron: 5, fetch_data: 5]
```

I have a DB pool size of `10`.

So let's say 10 `fetch_data` jobs are simultaneously enqueued, only 6 of them executed, and the rest are stuck in `executing` perpetually. I don't have a timeout defined, but it's not doing anything that perpetually hangs the job. It's mostly just making simple REST calls.

Am I doing something wrong?

As temporary fix, I'm thinking about increasing queue size to 15 and DB pool size to 20, as well as defining a timeout.

**Comment by sorentwo** [comment]
This can happen when queue producers crash or when your node shuts down, i.e. during restarts. Oban delays node shutdown to give jobs some time to finish (configurable with `shutdown_grace_period`). However, if they can't finish during that time, or if the VM is forcibly shut down, then the jobs are stuck executing—we call these "orphaned" jobs.

You can manually rescue the orphaned jobs and move them back to an available state, or use the [Lifeline Plugin](https://hexdocs.pm/oban/lifeline.html#content) from Oban Pro, which does that automatically.

**Comment by deepcut** [comment]
@sorentwo thanks for the swift response 🙏 . This has been happening consistently whenever the number of queued jobs are more than what the queue size is set at (multiple times a day, everyday). There has not been any crashes or node shutdowns at all. Am I missing something?

Also, would you mind pointing me to the function that can re-activate the "orphaned" jobs? The issue right now is that since they are stuck in "executing", no retries happen. Perhaps I can run a cron job that tries to reactivate the orphaned jobs if any actually happen.

**Comment by sorentwo** [comment]
> This has been happening consistently whenever the number of queued jobs are more than what the queue size is set at (multiple times a day, everyday).

This is an extremely common occurrence, as it is essentially the point of a queue.

> There has not been any crashes or node shutdowns at all.

The node shuts down any time you restart or deploy new code.

> Also, would you mind pointing me to the function that can re-activate the "orphaned" jobs? The issue right now is that since they are stuck in "executing", no retries happen.

Changing the state from `executing` back to `available` will allow the job to be processed again, as long as it hasn't hit the max attempts.

> Perhaps I can run a cron job that tries to reactivate the orphaned jobs if any actually happen.

It is possible to run a cron job that does this, though be aware that you can get false positives. Depending on how variable job execution time is and how frequently you run the cron job you may rescue jobs that are really running and not actually orphaned.

**Comment by deepcut** [comment]
@sorentwo very helpful response, thank you.

> This is an extremely common occurrence, as it is essentially the point of a queue.

I see, so is it safe to assume that orphans jobs will always happen when more jobs are queued up than queue size allows? If so, I'll be sure to watch out for that.

> Changing the state from executing back to available will allow the job to be processed again, as long as it hasn't hit the max attempts.

I wasn't able to find the module/function that updates the `state` of a job. Would you mind pointing me to the right direction? Or is it just a matter of updating the record via Ecto/Changeset?

> It is possible to run a cron job that does this, though be aware that you can get false positives. Depending on how variable job execution time is and how frequently you run the cron job you may rescue jobs that are really running and not actually orphaned.

To be sure, would setting a timeout on the worker file force the job to fail? eg. let's say I set a 15 second timeout for `fetch_data` worker. An orphan job occurs and is left in `executing` state for more than 15 seconds, would it then fail and cause a retry?

**Comment by sorentwo** [comment]
> I see, so is it safe to assume that orphans jobs will always happen when more jobs are queued up than queue size allows? If so, I'll be sure to watch out for that.

No, that isn't what I meant. It is extremely common for jobs to wait in the queue because there isn't enough capacity to run them currently. You can see that in action if you go to https://getoban.pro/oban and scale one of the queue limits down to force a backup. They'll run eventually, and they won't get stuck in an `executing` state.

> Or is it just a matter of updating the record via Ecto/Changeset?

Right. There isn't a function for it. You need to update the record directly through Ecto.

> To be sure, would setting a timeout on the worker file force the job to fail? eg. let's say I set a 15 second timeout for `fetch_data` worker. An orphan job occurs and is left in `executing` state for more than 15 seconds, would it then fail and cause a retry?

No, the timeout has to do with failing a job, at which point it would be `retryable` and not `executing`.

**Comment by deepcut** [comment]
In that case I think the sort of behavior I'm experiencing is a bug. I have jobs that are stuck in `executing` for over 24 hours with just regular usage and it's taken me couple weeks to finally figure out the culprit. The only possible cause I can think of now is sending more jobs to the queue than the queue size limit. I can be sure that it's not due to node restart or code deploys.

If it's important for the developer to know to not send Oban more jobs than the queue limit to prevent this behavior, then it should be in the README. In this case I'm sending maybe 15 jobs with a queue limit of 5. If this was clear, I would've batch them by sending 5 at a time, etc.

It doesn't make sense to me that regular usage can produce such a large amount of orphan jobs with no retrying logic, telemetry events, warnings, or a function that somehow flushes them. But now that it's clear orphan jobs are the ones in `executing` that are long past their `scheduled_at` date, I can do something about flushing them out.

You've designed a great system so I don't mean to question the architecture at all. Just my 2 cents from an end user perspective.

**Comment by sorentwo** [comment]
There is definitely not an issue with inserting more jobs than the queue can process at once. That's the nature of a background job library.

If you are seeing that many stuck executing jobs then there is something else going on, most likely in your system. If you believe it is an issue with Oban then please create a minimal reproduction of the issue and I'll gladly fix it.
