### ISSUE TITLE
Oban Web: Uncaught TypeError preventing some queues from loading in UI

### ISSUE THREAD

**Issue by nodeit** [sorentwo/oban#365]
### Environment

- Oban Version -> 2.0.0
- PostgreSQL Version -> 11.6 
- Elixir & Erlang/OTP Versions (`elixir --version`) -> 1.9.0

### Current Behavior

I get the following in the Chrome Developer Console when clicking on the "Discarded" or "Retryable" tabs on left. Those links don't function and I can not see those queues. 

![oban](https://user-images.githubusercontent.com/9152504/96999087-a0fd3a00-1502-11eb-8d5e-6e5d80280507.png)

oban:623 Uncaught TypeError: Cannot read property '0' of undefined
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)

oban:623 Uncaught TypeError: Cannot read property '0' of undefined
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)
    at e.value (oban:623)

### Expected Behavior

I should be able to view the Discarded/Retryable queues just like the "Executing" and "Available" queues.

**Comment by sorentwo** [comment]
Will you please check whether this issue persists with the latest Oban Web version? Based on the screenshot it looks like you're running slightly older versions of Oban, Web and Pro. Web v2.2.1 in particular has some important markup fixes that may solve this issue.

**Comment by nodeit** [comment]
So it works a bit better in that it will _intermittently_ let me click on the discarded tab. Oddly, if I load the dashboard and immediately click on "discarded" it works, but if i click on completed next I get the same error as before.

I also noticed that if I click on one of the nodes first, it resolves the issue pretty much completely. This is not ideal as i'd obviously like to be able to see all of the job regardless of the node it ran on.

**Comment by sorentwo** [comment]
@nodeit Finally made some headway on this. Which version of LV are you running in your project? Does it happen to be an unreleased version, e.g. from git/github?

**Comment by nodeit** [comment]
Thanks @sorentwo I am using an official release of phoenix_live_view ~> 0.13.1

**Comment by nodeit** [comment]
I'm closing this because it was solved by updating phoenix_live_view to 0.14.8
