### ISSUE TITLE
(FunctionClauseError) no function clause matching in MyApp.Worker.perform/1

### ISSUE THREAD

**Issue by zaherh8** [sorentwo/oban#369]
### Environment

I am using an unpackaged version of Oban. Reference commit: `2e4cc6d`. 
As I need the meta field in the Job Schema for my project.
I declared a worker with no pattern match for the sake of simplification:
```elixir
 @impl Worker
  def perform(payload) do
```

### Current Behavior

The jobs execution is randomly (most of the times it does not work but sometimes it does) returning the following error:

`(FunctionClauseError) no function clause matching in MyApp.Worker.perform/1`

As a  consequence, the perform function does not get called and the job doesn't execute.

I compared the failing jobs that were not getting executed to the one getting executed. I noticed the following:
Succeeded jobs have the meta field unlike the failing jobs.

The `IO.inspect` that I put in the library's code are only getting outputted in the terminal when the job is getting executed as if there are two flows.

PS: because of the` IO.inspect` issue I could not confirm that the jobs are currently being loaded in the drainer.

```elixir
  @spec drain(Config.t(), [drain_option()]) :: drain_result()
  def drain(%Config{} = conf, [_ | _] = opts) do
    queue =
      opts
      |> Keyword.fetch!(:queue)
      |> to_string()

    if Keyword.get(opts, :with_scheduled, false), do: schedule_jobs(conf, queue)

    conf
    |> fetch_jobs(queue)
    |> (&IO.inspect(:stdio, &1, label: "fetch jobs")).()
    |> Enum.reduce(%{failure: 0, success: 0}, fn job, acc ->
      result =
        conf
        |> Executor.new(job)
        |> Executor.put(:safe, Keyword.get(opts, :with_safety, true))
        |> Executor.call()

      Map.update(acc, result, 1, &(&1 + 1))
    end)
  end
``` 

### Expected Behavior
I expect the perform function to run smoothly everytime.

**Comment by sorentwo** [comment]
Which environment are you seeing this issue in? Is this in test, dev, prod? The migration sets the `meta` table with a default empty map, and the field is always defined in the `Oban.Job` schema regardless.

Also, are you sure that is the commit? It doesn't link to anything and locally git says `'2e4cc6d': unknown revision`.

**Comment by jfayad** [comment]
Hi @sorentwo 

I work with Zaher and here are the answers I can supply.

Commit is: https://github.com/sorentwo/oban/commit/2e4cc6dcf9e6fd19e254f380f3a462c4bfa0f7d1
he just shared the first characters of it

this behavior was happening in dev.
Indeed the meta field was correctly added in the DB table by the migration and we can see the schema there.
but for some reasons there are jobs being sent without the meta field.

Here is an example error being stored in the jobs table:

```elixir
** (FunctionClauseError) no function clause matching in Notifications.EmailBusiness.perform/1

The following arguments were given to Notifications.EmailBusiness.perform/1:

# 1
    %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, 
    \"notifications\", 
    \"oban_jobs\">, 
    args: %{
        \"adapter\" => %{
            \"adapter\" => \"Elixir.Bamboo.MailgunAdapter\", 
            \"api_key\" => \"key-654805cea4ad9871aeca247b5745913c\", 
            \"base_uri\" => \"https://api.mailgun.net/v3\", 
            \"domain\" => \"sandboxf094ee0f815c409c8412ca666f1d1ff7.mailgun.org\"
            },
        \"content\" => %{\"html_body\" => \" Hello world!</h1>\", \"subject\" => \"welcome email\", \"text_body\" => \"Hello World\"}, 
        \"from\" => \"hassanzaher11@gmail.com\", \"recipients\" => [\"hassanzaher11@gmail.com\"], \"relay\" => \"mailgun\"
    }, 
    attempt: 1, 
    attempted_at: ~U[2020-10-29 07:06:39.883841Z], 
    attempted_by: [\"notifications@notifications-saas-9cc8f45c8-sqwhf\", \"email\", \"034nsm6v\"], 
    completed_at: nil, 
    discarded_at: nil, 
    errors: [], 
    id: 43, 
    inserted_at: ~U[2020-10-29 07:06:39.596952Z], 
    max_attempts: 20, 
    priority: 0, 
    queue: \"email\", 
    replace_args: nil, 
    scheduled_at: ~U[2020-10-29 07:06:39.596952Z], 
    state: \"executing\", 
    tags: [], 
    unique: nil, 
    unsaved_error: nil, 
    worker: \"Notifications.EmailBusiness\"}

    (notifications 0.1.0) lib/notifications/queue/email_queue.ex:17: Notifications.EmailBusiness.perform/1
    (oban 2.2.0) lib/oban/queue/executor.ex:171: Oban.Queue.Executor.perform_inline/1
    (oban 2.2.0) lib/oban/queue/executor.ex:159: Oban.Queue.Executor.perform_inline/1
    (oban 2.2.0) lib/oban/queue/executor.ex:79: Oban.Queue.Executor.call/1
    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by sorentwo** [comment]
The `meta` field should show in the schema. Can you confirm that you see it listed in the `oban/job.ex` file in your local `deps`?

If it is declared in your local `job.ex` please share the output of this query (using the correct Repo name):

```elixir
IO.inspect(MyApp.Repo.get(Oban.Job, 43))
```

**Comment by jfayad** [comment]
I will let my colleague @zaherh8 answer to that with the output of the inspect. As for the meta field in the schema, yes it ids there.

What we noticed though when I was assisting him was that sometimes the field was there and when it was then the perform function would get called with no issue...

Yet when the field was missing the perform would fail with the above error..

**Comment by sorentwo** [comment]
It sounds to me like different versions of the code loaded in memory, or some other local conflict. It would be great if you could shut down any local servers, clear the _build directory and look again. I have a suspicion that this is due to switching from regular deps to the github version.

**Comment by jfayad** [comment]
Got you, thanks for the hint. we'll try that and put back the result here

**Comment by zaherh8** [comment]
Hello @sorentwo thanks for your replies,
So this is the output of a queried job from the database using the command you supplied
```elixir
%Oban.Job{
  __meta__: #Ecto.Schema.Metadata<:loaded, "oban_jobs">,
  args: %{
    "adapter" => %{
      "adapter" => "Elixir.Bamboo.MailgunAdapter",
      "api_key" => "*******",
      "base_uri" => "https://api.mailgun.net/v3",
      "domain" => "domain.org"
    },
    "content" => %{
      "html_body" => " Hello world!</h1>",
      "subject" => "welcome email",
      "text_body" => "Hello World"
    },
    "from" => "hassanzaher11@gmail.com",
    "recipients" => ["hassanzaher11@gmail.com"],
    "relay" => "mailgun"
  },
  attempt: 3,
  attempted_at: ~U[2020-10-29 15:06:19.431864Z],
  attempted_by: ["notifications@notifications-saas-5666669448-x9whm", "email",
   "p09oill6"],
  cancelled_at: nil,
  completed_at: nil,
  discarded_at: nil,
  errors: [
    %{
      "at" => "2020-10-29T15:05:45.804681Z",
      "attempt" => 1,
      "error" => "** (FunctionClauseError) no function clause matching in Notifications.EmailBusiness.perform/1\n\nThe following arguments were given to Notifications.EmailBusiness.perform/1:\n\n    # 1\n    %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, \"notifications\", \"oban_jobs\">, args: %{\"adapter\" => %{\"adapter\" => \"Elixir.Bamboo.MailgunAdapter\", \"api_key\" => \"\", \"base_uri\" => \"https://api.mailgun.net/v3\", \"domain\" => \"aa\"}, \"content\" => %{\"html_body\" => \" Hello world!</h1>\", \"subject\" => \"welcome email\", \"text_body\" => \"Hello World\"}, \"from\" => \"hassanzaher11@gmail.com\", \"recipients\" => [\"hassanzaher11@gmail.com\"], \"relay\" => \"mailgun\"}, attempt: 1, attempted_at: ~U[2020-10-29 15:05:45.798206Z], attempted_by: [\"notifications@notifications-saas-5666669448-x9whm\", \"email\", \"p09oill6\"], completed_at: nil, discarded_at: nil, errors: [], id: 67, inserted_at: ~U[2020-10-29 15:05:45.460702Z], max_attempts: 20, priority: 0, queue: \"email\", replace_args: nil, scheduled_at: ~U[2020-10-29 15:05:45.460702Z], state: \"executing\", tags: [], unique: nil, unsaved_error: nil, worker: \"Notifications.EmailBusiness\"}\n\n    (notifications 0.1.0) lib/notifications/queue/email_queue.ex:17: Notifications.EmailBusiness.perform/1\n    (oban 2.2.0) lib/oban/queue/executor.ex:171: Oban.Queue.Executor.perform_inline/1\n    (oban 2.2.0) lib/oban/queue/executor.ex:159: Oban.Queue.Executor.perform_inline/1\n    (oban 2.2.0) lib/oban/queue/executor.ex:79: Oban.Queue.Executor.call/1\n    (elixir 1.10.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.2) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"
    }
  ],
  id: 67,
  inserted_at: ~U[2020-10-29 15:05:45.460702Z],
  max_attempts: 20,
  meta: %{"status" => "pending", "unique_id" => "E9V6DM"},
  priority: 0,
  queue: "email",
  replace_args: nil,
  scheduled_at: ~U[2020-10-29 15:06:39.439203Z],
  state: "retryable",
  tags: [],
  unique: nil,
  unsaved_error: nil,
  worker: "Notifications.EmailBusiness"
}
```
As you can see, the error is present in the `errors` field that we already talked about. When querying the job the `meta` field is there.

I also tried deleting the `_build` folder, cleaning all the dependencies, with `mix deps.clean --all --unlock` then running the project again. However always getting the same result.

**Comment by sorentwo** [comment]
The select query that pulls jobs selects the entire row: https://github.com/sorentwo/oban/blob/master/lib/oban/query.ex#L32. I still suspect that another instance is running older code somewhere.

**Comment by zaherh8** [comment]
You were right there was a conflict between two versions. The app running on the test site is connected the same DB and running on the old version of Oban while the one locally is running with the new Oban update.

Thanks for your help! @sorentwo
