### ISSUE TITLE
Increasing Oban extensibility

### ISSUE THREAD

**Issue by gugahoa** [sorentwo/oban#371]
- [Context, Goals and Non Goals](#org0695bac)
  - [Goals](#org44b92d5)
  - [Non Goals](#org46cae76)
- [Design Proposal](#org1474bb1)
  - [Concerns](#org3e0bb95)
    - [Backward Compatibility](#orgac1f778)
    - [Deprecation Warning](#org9e2b597)

<a id="org0695bac"></a>

# Context, Goals and Non Goals

I&rsquo;m creating a library to auto-instrument Oban with [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification). There&rsquo;s 
already some [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#messaging-systems) on how to instrument messaging system.

The proposal here only pertains how to properly instrument the three operations:

-   `send`
-   `receive`
-   `process`

<a id="org44b92d5"></a>

## Goals

-   Give users a way to know when, and optionally modify, a job that&rsquo;s about to be scheduled

<a id="org46cae76"></a>

## Non Goals

-   Give users a way to link processors span with jobs spans. [`Oban.Telemetry`](https://hexdocs.pm/oban/Oban.Telemetry.html)
already gives enough leeway for users to do that.

<a id="org1474bb1"></a>

# Design Proposal

One way to give users the extensiveness mentioned in Goals is to adopt a 
approach similar to [`Ecto.Repo`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex).
At first we could have something similar to  [`default_options`](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L240)

```elixir
defmodule Oban do
  defmacro  __using__ do
     def default_meta(_operation), do: %{}
     defoverridable default_meta: 1

     defp with_default_meta(meta, operation_name) do
       Map.merge(default_meta(operation_name), meta)
     end

     # …

     def insert!(name \\ __MODULE__, changeset) do
       meta =
        changeset
        |> get_field(:meta)
        |> with_default_meta(:insert!)

       case insert(name, put_change(changeset, :meta, meta)) do
        {:ok, job} ->
          job
        {:error, %Changeset{} = changeset} ->
          raise Ecto.InvalidChangesetError, action: :insert, changeset: changeset

        {:error, reason} ->
          raise RuntimeError, reason
       end
     end

     # …
  end
end
```

A user then implements their module like this

```elixir
defmodule MyApp.Oban do
  use Oban

  def default_meta(_operation_name) do
    OpenTelemetryOban.generate_meta_map()
  end

  require OpenTelemetry.Tracer

  import Ecto.Changeset, only: [get_field: 3]
  def traced_insert!(job) do
    queue = get_field(job, :queue)
    Tracer.with_span "#{queue} send" do
      insert!(job)
    end
  end
end
```

<a id="org3e0bb95"></a>

## Concerns

<a id="orgac1f778"></a>

### Backward Compatibility

So that this change is backward compatible, henceforth we can accept both the
actual usage and the new usage. A deprecation warning should be enough, and
updating the docs to recommend the new usage.

<a id="org9e2b597"></a>

### Deprecation Warning

I&rsquo;m not sure where to put the deprecation warning. One approach I could think of
is having a module attribute `@deprecated __MODULE__ == Oban` inside the
`__using__` macro, and warn on every function if `@deprecated` is true.

```elixir
defmodule Oban do
  defmacro __using__ do
    @deprecated __MODULE__ == Oban
    # …
  end
  
  use Oban
end
```

## Alternatives Considered

A approach already in use, but that only populates a job with some metadata, is
to define a base module which overrides the `new/2` function.

Reference to this approach can be found [here](https://github.com/sorentwo/oban/issues/323#issuecomment-688040104)

There's a limitation to that approach, namely two:
- We can't create a span when a job is truly scheduled, only when it's
constructed
- We can only populate the metadata with a best effort approach. We assume that
the span that constructs the job also schedules it. (This has been true for our
case, but it's not always true)

**Comment by sorentwo** [comment]
Great proposal, very nicely laid out!

This would be a huge change and doing it cleanly would probably break existing APIs. Before going down this road I'd like to propose an alternative—why not wrap calls to `Oban.insert!` in your own module?

```elixir
defmodule MyApp.Oban do
  require OpenTelemetry.Tracer

  import Ecto.Changeset, only: [get_field: 3, put_change: 3]

  def traced_insert!(changeset) do
    queue = get_field(changeset, :queue)

    Tracer.with_span "#{queue} send" do
      changeset
      |> put_change(:meta, OpenTelemetryOban.generate_meta_map())
      |> Oban.insert!()
    end
  end
end
```

**Comment by gugahoa** [comment]
As a user, that would be enough, but I want to provide a library that can transparently replace `Oban`, maintaining 100% compatibility but tracing any and all operations.

**Comment by sorentwo** [comment]
If that's the goal then I'd prefer a solution that lets you publish a package that works transparently _with_ Oban and lets you trace all operations.

**Comment by gugahoa** [comment]
@sorentwo The solution has to enable these two scenarios:
- The library should be able to know when a job is properly schedule (e.g. when `insert!` is called)
- The library should be able to modify the job `meta` field prior to insertion/update

I can think of some other ways to achieve that:
- Provide a hook before any operation that inserts/update a job. This would let me know that a job is being scheduled, and let me modify the job `meta` (this could be the `default_meta/1` here, but seems like mixing two responsibilities into a function that does not have that purpose)
- Use telemetry to emit events on all operations, and have a way to define something similar to the `default_meta/1`. This way `default_meta/1` has only one responsibility, and the library can listen to the telemetry events to know when a job is scheduled.

Other approaches would require the user to make significant changes to their code, and would not transparently work with Oban:
- Define a `OpenTelemetryOban.Worker` that replaces `Oban.Worker` to modify the job meta before insertion
- Make users use `OpenTelemetryOban.insert!/2/` when they want a insert to be traced

What do you think about these approaches? Does any other comes to mind?

**Comment by sorentwo** [comment]
> Use telemetry to emit events on all operations, and have a way to define something similar to the default_meta/1. This way default_meta/1 has only one responsibility, and the library can listen to the telemetry events to know when a job is scheduled.

I definitely favor this approach. We can easily emit telemetry events for `insert` and `insert_all` operations.

**Comment by gugahoa** [comment]
To define a `default_meta/1`, would it make sense to be a `{Module, Function, Arity}` passed as option to `Oban.start_link`?

**Comment by sorentwo** [comment]
To support dynamic ecto repos we added support for `get_dynamic_repo` as an anonymous function. That functionality was otherwise impossible to replicate (outside of a callback module), whereas providing default meta is already possible through either:

1. A wrapper function for `insert` or `insert_all`
2. Overriding `new` on workers

A top level function that only sets the default meta isn't versatile enough, IMO.

**Comment by sorentwo** [comment]
Ping @gugahoa. Any other thoughts on this?

**Comment by gugahoa** [comment]
>To support dynamic ecto repos we added support for get_dynamic_repo as an anonymous function. That functionality was otherwise impossible to replicate (outside of a callback module), whereas providing default meta is already possible through either:
>
>    1. A wrapper function for insert or insert_all
>    2. Overriding new on workers

As a user this would be enough, but I want to create a library so that users don't have to do much to start instrumenting `Oban` with `OpenTelemetry`

>A top level function that only sets the default meta isn't versatile enough, IMO.

What do you mean as "isn't versatile enough"?

Thanks for the patience, things have been hectic at work so I haven't been able to come around much to this issue but I want to resolve it soon. If you prefer, you can ping me on Slack and I'll likely see it in the same day

**Comment by sorentwo** [comment]
@gugahoa It has been a while on this one and we didn't come to a resolution. Please start something up on Slack or the forum if you have more ideas and want to discuss further. Thanks!
