### ISSUE TITLE
Read-only observation UI

### ISSUE THREAD

**Issue by shanesveller** [sorentwo/oban#384]
### Is your feature request related to a problem? Please describe.

At Cars.com, our architecture is a little unusual. We author the product in question as a large umbrella repo but deploy independent modular slices of it rather than many replicas of the entirety, with these three categories of umbrella apps being pertinent here:

1. A backoffice Phoenix web UI for internal staff with some simple RBAC, where we'd like to incorporate Oban Web
2. Other web properties as independent Phoenix apps, which should all have the ability to schedule Oban jobs without requiring that they include the modules required to work the inserted jobs and intentionally without working the Jobs themselves
3. Batch job worker app running Oban and Broadway, where we're like to incorporate Oban Pro in a "headless" fashion with no Phoenix code or content

In this constellation of apps, they're each deployed independently as Kubernetes Pods with their own scaling axes, and an Ecto Repository and database cluster are shared and are one of the main ways of coordinating information back and forth because we don't currently use BEAM clustering to date and don't have a near-term desire to do so.

### Describe the Solution You'd Like

We have a desire to expose Oban Web to some internal less-technical staff within the backoffice app, and to have it be largely or entirely read only for them (or for everybody at first) - i.e. no `cancel`/`retry` controls or pause/resume buttons on the queues list. Specifically, since we share a database between some BEAM nodes with all of the necessary modules to execute our Oban Jobs and some BEAM nodes that have none of those modules, it's dangerous for us to call something like `Oban.resume_queue/2` without requiring that every call site include `local_only: true`, or we'll get jobs being pulled in by the insert-only nodes and then immediately failing with exceptions.
 
### Describe Alternatives You've Considered

We can expose any necessary write operations directly in our backoffice app within the context of our internal RBAC and meeting our specific constraints, so I think we could still gain a lot of value from a read-only presentation for everyone, just to be able to quickly see details about queue depth, state counts, and realtime activity. Right now we infer a lot of that from log data and Datadog traces.

### Additional Context

There's no significant urgency to this on our side, especially with the holiday coming up, and if it were in the OSS version we'd probably try to contribute it ourselves since it's a little niche.

We're also a ways out on getting onto LiveView 0.15+ to be able to get on the very latest Pro/Web releases.

All requests for clarification or context will be gladly honored, but may require us to do so privately.

**Comment by sorentwo** [comment]
Amazing write up!

This is the first anybody has requested a fully read only UI, and I can see the merit in it. Previously I've had discussions about disabling queue actions (pause/scale) while still allowing job actions (retry/cancel).

For your use case it seems that a generic read only option is ideal, but I'd like to make it a little more flexible while I'm at it.

**Comment by sorentwo** [comment]
@shanesveller All set, this will be in the next release.

The implementation supports read only mode and fine grained access controls so you can disable pausing or scaling queues for everybody, while still allowing devs/admins to cancel or retry jobs.
