### ISSUE TITLE
Specify default prefix for test module

### ISSUE THREAD

**Issue by giddie** [sorentwo/oban#385]
### Is your feature request related to a problem? Please describe.

When using Oban assertions in tests, it is quite tedious to specify the prefix in each assertion:

```elixir
assert_enqueued(
  prefix: "oban",
  worker: MyApp.Workers.MyWorker,
  args: %{one: 1}
)
```

### Describe the Solution You'd Like

It would be awesome if the default prefix could be pulled from the configuration for the test environment, just as it is for dev and prod.

Alternatively, or in addition: we could specify the default prefix to use for a specific test file at the top:

```elixir
use Oban.Testing, repo: MyApp.Repo, prefix: "oban"
```

**Comment by v0idpwn** [comment]
+1 for specifying in "use"

**Comment by sorentwo** [comment]
Oban testing queries run directly in your test code, they don’t rely on Oban running and therefore can’t check the configured prefix.

Setting the prefix in `use` is a great solution. A PR is welcome!

**Comment by eeue56** [comment]
I'm gonna have a go at implementing this

**Comment by sorentwo** [comment]
@eeue56 Feel free to open a WIP PR if you have any questions or need guidance 👍

**Comment by gfviegas** [comment]
Just bumped in this issue as I haven't found this info on the docs, so I opened #617 to mention how to specify the prefix in the testing section of the docs.
