### ISSUE TITLE
Improve oban_jobs indexes for uniqueness check performance

### ISSUE THREAD

**Issue by jaimeiniesta** [sorentwo/oban#391]
As talked in https://elixir-lang.slack.com/archives/CRDGH1XCM/p1609337835213200, a combination of high peak and a bug in our systems led to almost 2 million jobs being enqueued.

Jobs that used uniqueness checks on the `args` were not being created, as there was a DB timeout due to poor indexes on that table. These are the indexes we had:

```
oban_beats        | oban_beats_inserted_at_index                          | CREATE INDEX oban_beats_inserted_at_index ON public.oban_beats USING btree (inserted_at)
oban_jobs         | oban_jobs_args_vector                                 | CREATE INDEX oban_jobs_args_vector ON public.oban_jobs USING gin (to_tsvector('simple'::regconfig, (args)::text))
oban_jobs         | oban_jobs_attempted_at_id_index                       | CREATE INDEX oban_jobs_attempted_at_id_index ON public.oban_jobs USING btree (attempted_at DESC, id) WHERE (state = ANY (ARRAY['completed'::oban_job_state, 'discarded'::oban_job_state]))
oban_jobs         | oban_jobs_pkey                                        | CREATE UNIQUE INDEX oban_jobs_pkey ON public.oban_jobs USING btree (id)
oban_jobs         | oban_jobs_queue_state_priority_scheduled_at_id_index  | CREATE INDEX oban_jobs_queue_state_priority_scheduled_at_id_index ON public.oban_jobs USING btree (queue, state, priority, scheduled_at, id)
oban_jobs         | oban_jobs_worker_gist                                 | CREATE INDEX oban_jobs_worker_gist ON public.oban_jobs USING gist (worker gist_trgm_ops)
```

Based on this, @sorentwo suggested these changes in the indexes:

> Here are the indexes you can remove, along with one to insert for args:
> The old args vector was for a simpler full text search, the new args gin index is general purpose
> The worker gist isn't necessary, the new search doesn't use an operator covered by the gist index
> The attempted_at index isn't used for most pruning now because of separate discarded and cancelled timestamps

Which are in this migration:

```elixir
defmodule MyApp.Repo.Migrations.ImproveObanIndexes do
  use Ecto.Migration
  @disable_ddl_transaction true
  @disable_migration_lock true

  def change do
    # Drop
    drop_if_exists(index(:oban_jobs, [:args], name: :oban_jobs_args_vector))
    drop_if_exists(index(:oban_jobs, [:worker], name: :oban_jobs_worker_gist))
    drop_if_exists(index(:oban_jobs, [:attempted_at], name: :oban_jobs_attempted_at_id_index))

    # Create
    create(index(:oban_jobs, [:args], using: :gin, concurrently: true))
  end
end
```

I'm opening this issue to propose that either a default index is added, or documentation is updated.

**Comment by blisscs** [comment]
@jaimeiniesta Thanks for putting this up.

I think this could solve the issue that we are having as well.
We sometime, use `dbclient` like tableplus and alternatives to view the oban job table, to see some of the discard tasks.
previously we could use the client to do the sorting and querying very easily, But once we added
oban cron and tasks that need to check on the uniqueness, we could not do much of that in the timely manner.
After clicking or trying query we need to wait for minutes for it to give out the result or sometime it break our dbclient.

Will try out the proposed migration above and see if there are any impact.

**Comment by blisscs** [comment]
I am also wondering after apply the above migration will be any issues with the upcoming oban upgrade in the future?

**Comment by sorentwo** [comment]
@blisscs The migrations always check whether a table/index/column exist before overwriting anything. That gin index on args will _probably_ be in the next migration with the same name, so you're safe if you add it manually.
