### ISSUE TITLE
Workflow testing

### ISSUE THREAD

**Issue by joshuataylor** [sorentwo/oban#399]
### Is your feature request related to a problem? Please describe.

How do we test workflows, as it relies on a plugin, and running without plugins enabled shows:
```
workflow timed out, is the WorkflowManager running?
```

### Describe the Solution You'd Like

Documented workflow testing.

### Describe Alternatives You've Considered

I've tried starting plugins and running jobs manually but the above error appears.

**Comment by sorentwo** [comment]
Thanks for pointing this out. In addition to docs for this I’ll add a helper to facilitate testing pro workers.

For now, you can call `process/1` directly with a job struct:

```elixir
MyWorker.process(%Oban.Job{args: %{“id” => 1}})
```

**Comment by joshuataylor** [comment]
Sorry to bump this, but was easier than opening a new ticket.

I'm still struggling to get a workflow tested in a nice way.

My goal is to run a workflow in a synchronous manner. Kind of like what process does.

I pass it `.process(workflow)` I get back :ok. (where workflow is a list of %Oban.Jobs{} from an insert_all.

The workaround I have for this is to use `Oban.drain_queue(queue: :foobar)`, which will only run correctly if I have the following set in `test.exs`:
```
config :dataclip, Oban,
  repo: Dataclip.Repo,
  queues: false,
  plugins: [Oban.Pro.Plugins.WorkflowManager],
  crontab: false
```

But this will then not work correctly if using `iex -S mix test` (and I believe not a good option over all?):
```
14:01:13.340 erl_level=error domain=otp file=gen_server.erl function=error_info/7 line=953 mfa=:gen_server.error_info/7 module=gen_server pid=<0.623.0> [error] GenServer {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Stager}}} terminating                                                                                 
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.623.0>.
```

What is the recommended approach for this? Test each job inside of a workflow? But I want to check the entire workflow as that's less tedious.

**Comment by sorentwo** [comment]
@joshuataylor Since you posted this I've thought about a clean solution for a while. It seems like enhancing `Oban.drain_queue/1,2` with an option that keeps processing jobs recursively is the best solution. The flag could be something like `with_recursion: true`, which would keep processing jobs until none were available/scheduled.

**Comment by sorentwo** [comment]
@joshuataylor A new `with_recursion` flag was added https://github.com/sorentwo/oban/commit/af8a9c95f88e37ddef38b8f34af7fefa1334e48c
