### ISSUE TITLE
Links in UI to specific Job

### ISSUE THREAD

**Issue by PavelVesnin** [sorentwo/oban#404]
To work with team I'd like to share link to specific Job with others
E.g.: _oban.ui/jobs/:id_

P.S. Thanks for great work!

**Comment by sorentwo** [comment]
This has been on the roadmap for a while. Coming soon(ish) 👍

**Comment by jeroenvisser101** [comment]
I don't intend on hijacking this issue, but better handling of URLs/history in Web in general (be it active queues) would be greatly appreciated. It happens more than once a day that I try to navigate back and here I am, on a blank new tab page.

**Comment by sorentwo** [comment]
@jeroenvisser101 You aren't hijacking, that is definitely part of the plan.

**Comment by sorentwo** [comment]
Thanks for the input! This will be in the next Oban Web release:

<img width="1440" alt="Screen Shot 2021-04-16 at 9 06 58 AM" src="https://user-images.githubusercontent.com/270831/115037158-cbb5c300-9e93-11eb-99ea-f1debcb79b8a.png">

<img width="1440" alt="Screen Shot 2021-04-16 at 9 12 57 AM" src="https://user-images.githubusercontent.com/270831/115037446-16cfd600-9e94-11eb-96ed-13fe292a18bc.png">
