### ISSUE TITLE
Display data related to Jobs on Oban Dashboard

### ISSUE THREAD

**Issue by iautom8things** [sorentwo/oban#412]
### Is your feature request related to a problem? Please describe.

I would like a way to display data related to a job when viewing the job from `oban_web`'s dashboard.

### Describe the Solution You'd Like

It would be great if there was a plugin that worked with `oban_web` where I could map `Oban.Worker` modules to a list of `Phoenix.LiveComponent` modules.

`oban_web` would then provide tabs for each of the components on the _Job Details_ page where the user can toggle between _Job Details_ and the supplied components.

#### Mock up

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/522040/105930096-9a54f600-600e-11eb-9020-69458243c912.png">

`oban_web` would then be modified with the following (horrible) pseudo code (but hopefully you get the intention):

```html
<!-- somewhere in .leex file for dashboard -->
<tabs>
  <tab>
    <title>Job Details</title><content> <!-- ... what you have currently --></content>
  </tab>
  <%= if not is_nil(@web_components[@job.worker_module])  do %>
    <%= for component <- @web_components[@job.worker_module] do %>
      <tab>
        <title><%= component %></title>
        <content>
          <%= live_component @socket, component, id: @job.id %>
        </content>
      </tab>
    <% end %>
  <% end %> 
</tabs>
```

This would allow `oban_web` users to supplement the Oban Dashboard without having to muck with oban's internal datastore.

### Describe Alternatives You've Considered

An alternative would be to store data in the `meta` field of the job.  This would not be ideal for a few reasons, including that you would have to be mindeful that `meta` is indexed, and jsonb so storing large amounts of data could adversely affect the system.

### Additional Context

This desire stems from wanting to view related data to a job.  This isn't necessarily a direct _apples-to-apples_ comparison, but the `phoenix_live_dashboard` project provides a means to augment it.  Those pages typically _stand alone_, though.

**Comment by iautom8things** [comment]
@sorentwo Is there any specific questions you have around this?  This is a pretty important feature request for our needs and I'd like to help in any way to make it work.  Thank you.

**Comment by sorentwo** [comment]
@iautom8things This seems like a rather niche use-case and I'm not comfortable injecting custom live components into the dashboard. It would require me to support the feature indefinitely in some form or another, and prevent me refactoring because the internal assigns/api would be public.

Including the job's results in telemetry and documenting how to augment a job using telemetry events is _definitely_ preferred and something that would be valuable and flexible enough for many use cases.

Let me know if that works for you and we can break this into a new issue.

**Comment by iautom8things** [comment]
Yup, I'm not married to the proposal I gave. I just need some way to be able to attach results to a job.

**Comment by iautom8things** [comment]
@sorentwo What version will this be available? And any ETA for it?  Thanks.

**Comment by sorentwo** [comment]
@iautom8things There are a few features accumulated on master. This change will be in 2.5 and should be out this week.

**Comment by iautom8things** [comment]
Perfect, thank you!
