### ISSUE TITLE
Unable to run v10 migration

### ISSUE THREAD

**Issue by tcitworld** [sorentwo/oban#413]
### Environment

- Oban Version 2.4.0
- PostgreSQL Version 12.5
- Elixir & Erlang/OTP Versions (`elixir --version`) OTP 23, Elixir 1.11.2

Previously on v9 migration, as checked through
```sql
SELECT description
FROM pg_class
LEFT JOIN pg_description ON pg_description.objoid = pg_class.oid
LEFT JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
WHERE pg_class.relname = 'oban_jobs'
AND pg_namespace.nspname = 'public'
```

Running migration with

```elixir
defmodule MyProject.Storage.Repo.Migrations.UpgradeObanJobsToV10 do
  use Ecto.Migration

  defdelegate up, to: Oban.Migrations
  defdelegate down, to: Oban.Migrations
end
```

### Current Behavior

The v10 migration is not executed.

### Expected Behavior

The v10 migration is executed.

I see fd8e9e6642e4076c442083b64830700f24fcea28 changed
```elixir
    if initial <= version do
```
to
```elixir
    if initial < version do
```

I'm not sure why this change was made, but it seems to be the issue, as `initial` is my current version (9 + 1) and `version` the current one (10).

**Comment by sorentwo** [comment]
Thanks for the report. There are details in the commit that closed this. The tl;dr is that the comparison changed because the previous logic was _also_ broken, but in a more subtle way.

**Comment by tcitworld** [comment]
Thanks for the fix and the details!

**Comment by sorentwo** [comment]
Writing up the CHANGELOG for v2.4.1 right now 👍
