### ISSUE TITLE
Tests failing when removing `queues: false` from config

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#414]
### Environment

- Oban Version: 2.4.0
- PostgreSQL Version: 13.1
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.11.3, OTP 23.2.3

### Current Behavior

The changelog states that when using version 2.4.0 you can safely remove the `queues: false` from test environments.

> The lack of polling also means there is no need to set `queues: false` in your test environment. Disabling plugins with `plugins: false` will eliminate all intermittent activity while testing.

However, when removing `queues: false` and continuing to set `plugins: false` in `config/test.exs` we're seeing tests using `assert_enqueued` fail.

```
 Expected a job matching:
     
     %{
       args: %{ ... },
       worker: MyProject.DoWork
     }
     
     to be enqueued in the "core" schema within 3000ms
```

When adding `queues: false` back to `config/test.exs` all tests run successfully.

### Expected Behavior

Tests should not fail when removing `queues: false` from `config/test.exs`.

**Comment by sorentwo** [comment]
Thanks for the report. I've removed that suggestion from the CHANGELOG 👍
