### ISSUE TITLE
Show overridden names for DynamicCron jobs on Oban Web

### ISSUE THREAD

**Issue by iautom8things** [sorentwo/oban#416]
### Is your feature request related to a problem? Please describe.

I have a fair number of DynamicCron jobs that reuse the same Oban.Worker, with different arguments. Oban Web's index view prominently shows the name of the worker and the args.  Since these jobs share the same Oban.Worker it is difficult to differentiate these just off of the arguments.

### Describe the Solution You'd Like

Since these all reuse the same Oban.Worker, I am providing a name to differentiate them.  It would be great if I could see the name of the cron job instead, or along with, the Oban.Worker module name.  This would be nice to be able to search against, as well.

This would be lagniappe, but it'd also be helpful to maybe see the crontab rule, only when you click into the job for details.  Just so I can easily see the rule that caused that job to trigger.

### Describe Alternatives You've Considered

I have considered duplicating this data in the `:meta` argument, which would help with searching.  But would be less than ideal.

**Comment by sorentwo** [comment]
In the short term Pro can inject the schedule name into the job's meta. For the longer term a dedicated DynamicCron view is definitely planned. (Surfacing those plans in a broad roadmap is also on the near horizon).

Slating the name->meta injection for the next Pro release.

**Comment by iautom8things** [comment]
Perfect, thank you.
