### ISSUE TITLE
Queue not processing

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#418]
### Environment

- Oban Version - 2.4.2
- PostgreSQL Version - 13.1
- Elixir & Erlang/OTP Versions (`elixir --version`) - Elixir 1.11.3 (compiled with Erlang/OTP 21)

### Current Behavior

NOTE: We're not using Oban Web.

We have a queue that seems to be stuck and we don't know why. The queue has 10 workers and currently contains 9 jobs that don't seem to be doing anything. When we manually update the `scheduled_at` value as described in #417 and nothing changes.

We also have a instrumenter listening for `[:oban, :circuit, :trip]` that sends data to Sentry which never gets trigged.

### Expected Behavior

Jobs should be processed.

**Comment by sorentwo** [comment]
Will you please share your config and more details about the stuck jobs? The details for just one of the jobs is plenty.

**Comment by anthonator** [comment]
Here is our config.

```
config :our_app, Oban, plugins: [{ Oban.Plugins.Pruner, [] }]

config :our_app, Oban, prefix: "our_app"

config :our_app, Oban, queues: [events: 10]

config :our_app, Oban, repo: OurAppRepo
```

Here's a job that won't process.

```
%Oban.Job{
  __meta__: #Ecto.Schema.Metadata<:loaded, "our_app", "oban_jobs">,
  args: %{ ... },
  attempt: 0,
  attempted_at: nil,
  attempted_by: nil,
  cancelled_at: nil,
  completed_at: nil,
  discarded_at: nil,
  errors: [],
  id: 97,
  inserted_at: ~U[2021-02-01 16:32:55.719533Z],
  max_attempts: 20,
  meta: %{},
  priority: 0,
  queue: "events",
  replace_args: nil,
  scheduled_at: ~U[2021-02-01 16:32:55.719533Z],
  state: "available",
  tags: [],
  unique: nil,
  unsaved_error: nil, 
  worker: "OurApp.Workers.UpdateOrder"
}
```

**Comment by sorentwo** [comment]
Nothing strange looking there. A few follow ups:

1. Are you running multiple Oban instances, or just the one with the "our_app" prefix?
2. Are there other queues running jobs?
3. Are any jobs inserted into that queue, or is it just those 10 jobs?

**Comment by anthonator** [comment]
1. We're running just one instance of Oban for this app. However, the app is clustered and running on multiple nodes.
2. We only have the one `events` queue.
3. We haven't inserted any new jobs since we discovered the issue yesterday.

**Comment by anthonator** [comment]
Just to note. We weren't having issues before upgrading to 2.4.

**Comment by sorentwo** [comment]
> Just to note. We weren't having issues before upgrading to 2.4.

Prior to 2.4 each queue polled frequently to check for new jobs. Now the stager plugin does that and uses notifications to alert queues that there are jobs to process. Somehow that process isn't working as expected and the queue isn't notified to start processing.

If you message me on IRC/Slack I can try to step through and diagnose the issue more easily.

**Comment by sorentwo** [comment]
Followup: This was caused by use of pg_bouncer in transaction pooling mode. The stager (along with many other features) use pg notifications to communicate, but those don't work with transaction pooling. The work around is to use a plugin that simulates polling per-producer. An example is here: https://gist.github.com/sorentwo/5a6d1207f79def7ea49c82d76f7c316f, though it isn't "official".

**Comment by zacksiri** [comment]
@sorentwo I'm having the same problem however I'm running Oban 2.3.4, Postgresql 13

**Comment by sorentwo** [comment]
@zacksiri This is was specifically due to changes in v2.4, namely the use of notifications to trigger job fetching. If jobs aren't running in v2.3 then it is another issue. Typically this comes up in development or an environment where queues get set to `false`. If you have more questions please ask in #oban on Slack.

**Comment by zacksiri** [comment]
@sorentwo my bad, there was a problem in my setup. I've resolved the issue.
