### ISSUE TITLE
Setting up Oban Web on the umbrella applications

### ISSUE THREAD

**Issue by blisscs** [sorentwo/oban#426]
### Is your feature request related to a problem? Please describe.

We are trying to integrate oban_pro and oban_web into our existing umbrella application.
Currently, our umbrella app looks like below ->

app A -> phoenix 1.14 (currently without liveview)
app B-> has oban, with the process name `A.Oban`
app C-> has oban, with the process name `B.Oban`

And the umbrella app is deployed on 2-3 nodes, we are using elixir 1.8.2 and currently, everything is working as expected.

What we want is we want to use oban web feature on want it to hook into app A(which is has phoenix running).

### Describe the Solution You'd Like

We would like to know what would be the recommended way to setup oban_web for the current running oban running in apps as described in the above setup.

**Comment by sorentwo** [comment]
This was also asked in the #oban channel on Slack and I've answered there. The short version is:

A — run `Oban` with the `Oban.Web.Plugins.Stats` plugin and no queues:

```elixir
config :my_app_a, Oban,
  repo: MyApp.Repo,
  queues: [],
  plugins: [Oban.Web.Plugins.Stats]
```

B / C — run `Oban` with the same queues and the `Oban.Pro.Plugins.Lifeline` plugin:

```elixir
config :my_app_b, Oban,
  repo: MyApp.Repo,
  queues: [a: 10, b: 10, c: 10],
  plugins: [Oban.Pro.Plugins.Lifeline]
```

* This assumes they all share the same database and prefix

**Comment by blisscs** [comment]
Thanks, @sorentwo I will read and continue the conversation on there.
