### ISSUE TITLE
Restart job after restart server

### ISSUE THREAD

**Issue by MeterSoft** [sorentwo/oban#429]
i have a long job. I stop server when job started. After restart server now job has "executing" state and not run anymore?

**Comment by sorentwo** [comment]
@MeterSoft This is a natural byproduct of apps shutting down. Oban tries to pause queues and let executing jobs finish, but that doesn’t always work. With other job processors the job would just be gone forever and you wouldn’t know it was ever attempted.

The immediate fix is to manually change the state back to `available` in the db. The Lifeline plugin in Pro does that automatically, along with activity tracking for the UI.

This is a recurring question that I'll try to address in the docs.
