### ISSUE TITLE
Start periodic jobs at the beginning of the minute

### ISSUE THREAD

**Issue by railsmechanic** [sorentwo/oban#435]
### Current implementation
When I get the code right, the current implementation of the scheduler checks for job executions every 60 seconds through a `Process.send_after` "ticker". This (only) ensures that a job is started every 60 seconds, which should be sufficient for most requirements, but I think it can lead to problems when someone (like me) has the requirement that a job is started "at the beginning of a minute". I've noticed that most Linux systems might run cronjobs at the beginning of the minute, as the execution is logged for e.g. at 10:00:01. So it would be great to have a corresponding behaviour within oban.

### Future implementation
To imitate the behavior of linux cron, tasks in oban should also be started "at the beginning of a minute". As the cron GenServer is started asynchronous, a simple delay of the `Process.send_after`,  for the amount of seconds to the next full minute, might already work.

### Possible change
Currently the `schedule_evaluate` function is implemented as followed:

```elixir
defp schedule_evaluate(state) do
    timer = Process.send_after(self(), :evaluate, state.interval)

    %{state | timer: timer}
end
```

A possible implementation (in pseudo code) could look like this:

```elixir
defp schedule_evaluate(state) do
    # Delay start
    Time.utc_now()
    |> diff_to_next_fullminute_in_seconds()
    |> :timer.seconds()
    |> Process.sleep()
    
   # Start ticker
    timer = Process.send_after(self(), :evaluate, state.interval)

    %{state | timer: timer}
end
```

What do you think? Furthermore, many thanks for this great job processing package. :+1:

**Comment by sorentwo** [comment]
Love it! This is a great proposal that hasn't been brought up in quite a while.

**Comment by sorentwo** [comment]
This was a quick one to fit in. There are more details about the implementation in the commit message. Please note, the cron plugin only _inserts_ new jobs, it doesn't execute them in-process. That means jobs are inserted at the top of the minute, but they may be executed later depending on how busy your queues are.

**Comment by railsmechanic** [comment]
Great solution... 👍
Many thanks for implementing this.
