### ISSUE TITLE
Queues stopped being processed after upgrading from 2.3.4 to 2.4.0

### ISSUE THREAD

**Issue by bartblast** [sorentwo/oban#436]
### Environment

- Oban Version: 2.4.0 (the problem occurs in 2.4.*)
- PostgreSQL Version: 12.2
- Elixir & Erlang/OTP Versions (`elixir --version`): 1.11.3 / 23.2.5

### Current Behavior

After upgrading from 2.3.4 to 2.4.0, Oban stopped processing queues in my tests.
I use the following code to start Oban in tests (in the setup blocks):

```
opts = Application.get_env(:segmetric, Oban)
start_supervised!({Oban, opts})
```

Oban is started, but the queues are not being processed. When I call Oban.check_queue/2 it says that the queue is running (is not paused), but the jobs are not being processed (status available, no attempts).

Example job not being processed:

```
  %Oban.Job{
    __meta__: #Ecto.Schema.Metadata<:loaded, "oban_jobs">,
    args: %{
      "bucket" => "segmetric-test-collector-1-primary",
      "bucket_role" => 0,
      "filename" => "1614002955843_dd95354b-f284-4e06-9296-a9e3e04f65be",
      "provider" => 1
    },
    attempt: 0,
    attempted_at: nil,
    attempted_by: nil,
    cancelled_at: nil,
    completed_at: nil,
    discarded_at: nil,
    errors: [],
    id: 24,
    inserted_at: ~U[2021-02-22 14:09:08.465802Z],
    max_attempts: 20,
    meta: %{},
    priority: 0,
    queue: "collector_messages",
    replace_args: nil,
    scheduled_at: ~U[2021-02-22 14:09:08.465802Z],
    state: "available",
    tags: [],
    unique: nil,
    unsaved_error: nil,
    worker: "Segmetric.Collectors.Consumer"
  }
```

Example check_queue output:

```
%{
  limit: 10,
  node: "Barts-MacBook-Pro",
  nonce: "r387o6et",
  paused: false,
  queue: "collector_messages",
  running: [],
  started_at: ~U[2021-02-22 14:09:09.956121Z]
}
```

When Oban is run in dev environment and started through application.ex it works correctly.

### Expected Behavior

Oban processes the queues, when started in test env with start_supervised!/2.

**Comment by sorentwo** [comment]
This is due to notifications getting swallowed in sandbox mode. The recently added, but unreleased, [Repeater plugin](https://github.com/sorentwo/oban/commit/296fa5fe7ee002bdc0a078d676e0796de29ea194) will restore the ability to run jobs in sandbox mode.

Sorry for the inconvenience—I didn't realize people purposefully ran queues in test mode.

**Comment by bartblast** [comment]
Got it, do you plan to make the Repeater plugin available in the next release?

**Comment by sorentwo** [comment]
> Got it, do you plan to make the Repeater plugin available in the next release?

Absolutely. Working on the next release currently. It should be a day or two.

**Comment by bartblast** [comment]
Great, thanks!
