### ISSUE TITLE
Error in changelog migration instructions.

### ISSUE THREAD

**Issue by abstractcoder** [sorentwo/oban#439]
The migration in the changelog from version 9 to version 10 is as follows.

```
defmodule MyApp.Repo.Migrations.UpdateObanJobsToV10 do
  use Ecto.Migration

  def up do
    Oban.Migrations.up(version: 10)
  end

  def down do
    Oban.Migrations.down(version: 9)
  end
end
```

The migration up works properly, but the migration down rolls back to version 8.

In order to rollback to version 9 the migration should be

```
defmodule MyApp.Repo.Migrations.UpdateObanJobsToV10 do
  use Ecto.Migration

  def up do
    Oban.Migrations.up(version: 10)
  end

  def down do
    Oban.Migrations.down(version: 10)
  end
end
```

**Comment by sorentwo** [comment]
Nice catch, thanks for pointing this out. Fixed in the upcoming (yet unreleased) CHANGELOG.

**Comment by jordi-chacon** [comment]
This issue happened again with the [upgrade instructions to v2.11](https://hexdocs.pm/oban/v2-11.html#run-oban-migrations-for-v11).

```
def down, do: Oban.Migrations.down(version: 10)
```
should be:
```
def down, do: Oban.Migrations.down(version: 11)
```

With that said, really appreciate all the work you are doing with Oban @sorentwo! 🙏

**Comment by sorentwo** [comment]
@jordi-chacon Thank you! Fixed now.
