### ISSUE TITLE
Can't view emails sent from a Job

### ISSUE THREAD

**Issue by crbelaus** [sorentwo/oban#44]
First of all sorry if it is not the place to put this issue. I really don't know whether it belongs here or to [the Bamboo repository][1], but I can move it without any problem.

I have a Oban job which sends a notification email. In my local environment I am using the `Bamboo.LocalAdapter` to catch the emails and see them in my Phoenix server.

The job code is really simple:

```elixir
defmodule MyApp.ObanEmail do
  use Oban.Worker, queue: "notifications"

  alias MyApp.Mailer

  def perform(_args) do
    Bamboo.Email.new_email()
    |> Bamboo.Email.from("from@example.com")
    |> Bamboo.Email.to("to@example.com")
    |> Bamboo.Email.subject("Test Email")
    |> Mailer.deliver_now()
  end
end
```

And the mailer is configured as:

```elixir
# lib/myapp/mailer.ex
defmodule MyApp.Mailer do
  use Bamboo.Mailer, otp_app: :my_app
end

# config/dev.exs
config :my_app, MyApp.Mailer, adapter: Bamboo.LocalAdapter
```

Turns out that when I call the `perform` function directly, I can see the sent email. When I enqueue the job and Oban runs it, it succeeds and gets marked as completed, but I can not see the email. Any clue on why there would be that difference?

[1]: https://github.com/thoughtbot/bamboo/issues

**Comment by crbelaus** [comment]
There does not seem to be any difference between letting Oban automatically run the queue and send the emails or running it manually with `Oban.drain_queue/1`. I can not see the sent emails in any case.

**Comment by sorentwo** [comment]
What version of Erlang and Elixir are you using? If you are on Erlang 20 the Oban supervisor will fail to start, which would prevent your jobs from being run entirely.

**Comment by crbelaus** [comment]
I am using Elixir 1.9.0 on Erlang 22.0.5.

The jobs seem to run fine, since they are marked as completed in the `oban_jobs` table. But somehow there seems to be a difference that makes emails viewable when I run the job manually but not when it is automatically run by Oban.

**Comment by sorentwo** [comment]
I’m not familiar with the LocalAdapter in bamboo, but I have a hunch this is due to how it stores the emails.

If the adapter uses the calling process’s pid to isolate the delivered emails from other processes then you would only be able to see them from within the same process. Calling perform manually or calling drain will execute the job in the same process as your shell or test. Executing the job normally will run it in an isolated process, so you won’t be able to see if from your shell.

This isn’t really an Oban or Bamboo issue. Fundamentally this is a process isolation issue.

**Comment by crbelaus** [comment]
Well turns out that I had an typo in my Mailer configuration :man_facepalming: 

Everything works good now and I can send mail notifications from jobs and see them in the development adapter. Thank you for your help and sorry for the inconvenience.
