### ISSUE TITLE
README - Is performance note regarding index on args still valid?

### ISSUE THREAD

**Issue by bblaszkow06** [sorentwo/oban#440]
Hi! I think I've found an outdated part of README:

### Environment

- Oban Version - 2.4.3

### Current Behavior

The [README](https://github.com/sorentwo/oban/tree/master#performance-note) says

> Performance Note
>If your application makes heavy use of unique jobs you may want to add an index on the args column of the oban_jobs table. The other columns considered for uniqueness are already covered by indexes.

However it seems migration v10 added that index
https://github.com/sorentwo/oban/blob/219375bb159b83e761e0394d9ac59813f2cd8dba/lib/oban/migrations/v10.ex#L39

Doesn't that render the `Performance Note` obsolete? 

### Expected Behavior

Performance Note removed from readme

**Comment by sorentwo** [comment]
You're correct, it does render the performance note obsolete. A PR to correct the docs is welcome!
