### ISSUE TITLE
Setting a dynamic repo breaks transaction behavior

### ISSUE THREAD

**Issue by al2o3cr** [sorentwo/oban#442]
### Environment

- Oban 2.2.0
- PostgreSQL 11
- Elixir 1.11.2 / OTP 23

We're currently using dynamic repos to ensure that a glut of jobs can't starve our Phoenix handlers of connections.

### Current Behavior

When Oban is configured to use a dynamic repo (via the `get_dynamic_repo` setting), calling `Oban.insert` uses THAT repo instead of the caller's.

This is a problem when the caller has a transaction open; the writes to `Oban.Job` are visible immediately and do not roll back with the containing transaction.

### Expected Behavior

Functions like `Oban.insert` that are used by client code should not switch the dynamic repo, to prevent splitting writes across multiple connections.

**Comment by sorentwo** [comment]
This is a bit tricky because `insert` and `insert_all` are used by client code as well as plugins, e.g. Cron. It would be appropriate not to switch repos for client calls, but it still needs to switch for plugins.

Perhaps the `with_dynamic_repo` function in `Oban.Repo` can use `in_transaction?` to check whether there is already a transaction in progress and skip switching?

Any additional advice, investigation or a PR is welcome.

**Comment by al2o3cr** [comment]
@sorentwo agreed - it's going to be tricky to sort out some of those callers. I'll continue investigating.

For the immediate fix, we've copied the couple functions from `Oban` that we use in application code to our `Repo` and modified them to clear the `get_dynamic_repo` value before calling the functions from `Oban.Query` (similar to how `Oban.Query.fetch_or_insert_job/4` [overrides `repo`](https://github.com/sorentwo/oban/blob/2ee44412f8ed3b5940017131eb29bf5296a7cf55/lib/oban/query.ex#L59)). This is obviously Not Good from a maintainability standpoint, but it should stop the phantom jobs. 👻

**Comment by al2o3cr** [comment]
One immediate thing that jumped out - the typing in `Oban.Repo` is a little weird; `Oban.Repo.config` is:
```
  @type config :: %{
          :repo => module,
          optional(:get_dynamic_repo) => (() -> pid | atom),
          optional(:log) => false | Logger.level(),
          optional(:prefix) => binary(),
          optional(any) => any
        }
```

but the functions that take it as an argument actually pass in an `Oban.Config` struct where `get_dynamic_repo` is either `nil` or a function. 🤔

**Comment by al2o3cr** [comment]
One thing I'm thinking about: is `Oban.Repo` the right place to call `put_dynamic_repo`? That's a process dictionary entry under the hood, so it's odd to change it at the function level. 

Alternatively, we could call the function in `get_dynamic_repo` in the `init` function of Oban processes and set it once for the whole process. Functions in `Oban.Repo` wouldn't change it at all. 

The function passed to `get_dynamic_repo` would get called at different times, though that should be 100% fine for cases where `get_dynamic_repo` is returning a constant atom. Need to think about the case where it's returning a PID.

**Comment by sorentwo** [comment]
> One immediate thing that jumped out - the typing in Oban.Repo is a little weird

That's true. I believe that was an in-progress change that was left intact. It can be swapped out for `Config.t()` instead.

> One thing I'm thinking about: is Oban.Repo the right place to call put_dynamic_repo? That's a process dictionary entry under the hood, so it's odd to change it at the function level.

Many different places make calls to `Oban.Repo`, and it may change even within a running process. That is why there is an `after` block to ensure that the repo is restored to whatever it was initially.
