### ISSUE TITLE
Oban + k8s

### ISSUE THREAD

**Issue by MeterSoft** [sorentwo/oban#443]
How Oban works with cluster pods? Is it will run on all pods?

**Comment by v0idpwn** [comment]
It will run independently on all pods. They will operate concurrently and won't interact with each other.

**Comment by sorentwo** [comment]
@v0idpwn's answer is correct.

Please ask these types of questions on a platform like the Elixir Forum, Elixir Slack or IRC. Issues are meant for bug reports and feature discussions.

**Comment by MeterSoft** [comment]
@v0idpwn so if all pods use one database it can be run 1 task on all pods?
