### ISSUE TITLE
Support passing nonce values for content security policy

### ISSUE THREAD

**Issue by justincjohnson** [sorentwo/oban#447]
### Is your feature request related to a problem? Please describe.

In order to get oban web to work with a web app that has a content security policy, I need to add the following to the `content-security-policy` header.

```
def call(conn, _opts) do
  csp_header_value =
    """
    ... \
    font-src 'self' data:; \
    script-src 'self' 'unsafe-inline'; \
    ... \
    """

  conn
  |> put_resp_header("content-security-policy", csp_header_value)
end
```

I'm fine with the `font-src` change, but not the `script-src` change.

### Describe the Solution You'd Like

The way I secure `script-src` for other parts of my app is to generate a `nonce` value in my CSP plug that is then injected in the CSP header and assigns like...

```
def call(conn, _opts) do
  nonce =
    :crypto.strong_rand_bytes(128)
    |> Base.url_encode64(padding: false)

  csp_header_value =
    """
    ... \
    script-src 'self' 'nonce-#{nonce}'; \
    ... \
    """

  conn
  |> assign(:csp_nonce, nonce)
  |> put_resp_header("content-security-policy", csp_header_value)
end
```

...and inject into script tags like...

```
<script nonce="<%= assigns[:csp_nonce] %>">
...
</script>
```

Would you be open to supporting something along these lines?  I'm open to other ideas on how to do this more cleanly.

Thanks.

**Comment by justincjohnson** [comment]
See https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.Router.html#live_dashboard/2 for how LiveDashboard handles nonces.

**Comment by sorentwo** [comment]
@justincjohnson Thank you! That's really helpful because the oban dashboard mounts in a similar way to the live dashboard.

**Comment by justincjohnson** [comment]
@sorentwo for my planning purposes, do you by chance know when this change will be available?  I ask because I'm planning on delaying the use of the admin console until then.  Thanks.

**Comment by sorentwo** [comment]
@justincjohnson I'm planning on making/releasing the change this week. A few things to polish up before a mega oss/web/pro release 🚀

**Comment by justincjohnson** [comment]
Fabulous!  Thank you.
