### ISSUE TITLE
Guaranteeing successful ordering (i.e. block subsequent jobs on failure)

### ISSUE THREAD

**Issue by danturn** [sorentwo/oban#456]
Not sure if this is already possible but i would like to be able to create a queue for updates to a user (with id as the queue name or similar) and add jobs for that queue, if a job fails I want to stop the queue there and retry from the failure next time round. 

We use oban to talk to a 3rd party and can see network failures, but the delivery order is essential for us so we need to be able to guarantee that a subsequent job wont succeed before a previous job

**Comment by sorentwo** [comment]
@danturn With a single node (or global concurrency), job hooks and pausing that is definitely possible. However, this isn't an "issue" really. For general help and advice please start a thread on the Elixir Forum or in the #oban channel on Slack. Thanks!
