### ISSUE TITLE
"executing" state is not showing correctly in the Web UI

### ISSUE THREAD

**Issue by joshuataylor** [sorentwo/oban#457]
### Environment

- Oban Version: 2.6.1, oban pro: 2.6, oban pro: 0.7.1
- PostgreSQL Version: 13.2
- Elixir & Erlang/OTP Versions (`elixir --version`): OTP24, Elixir master

### Current Behavior

1. Execute a job
2. The job fails to run and errors, and is rescheduled (good!)
3. The UI shows "executed" with a number that isn't true (scheduled is).
![image](https://user-images.githubusercontent.com/225131/114153766-417cd480-9952-11eb-9754-aeac3c277610.png)

### Expected Behavior

Executed should be 0.

**Comment by dvic** [comment]
I'm seeing this as well.

**Comment by jaimeiniesta** [comment]
Me too, both for `executing` and `available` states. Jobs seem to work fine, but counters seem stuck.

I'm using:

* Oban v2.6.1
* Oban.Web v2.6.0
* Oban.Pro v0.7.1
* Elixir 1.10.4
* Heroku

![Captura de pantalla 2021-04-09 a las 16 50 41](https://user-images.githubusercontent.com/2629/114198604-cf0cf400-9953-11eb-8089-0c60329ff585.png)

![Captura de pantalla 2021-04-09 a las 16 50 49](https://user-images.githubusercontent.com/2629/114198631-d46a3e80-9953-11eb-8621-8663a04af9df.png)

**Comment by sorentwo** [comment]
Thanks for the report. I've found the issue and will have a fix soon.

**Comment by jaimeiniesta** [comment]
Not sure if it can be related to this, but I've seen several times jobs stuck in `available` state for hours, with 0 attempts. Restarting the app fixes the issue, but I don't know what can be causing this:

![Captura de pantalla 2021-04-16 a las 19 15 41](https://user-images.githubusercontent.com/2629/115061001-d8b0d180-9ee8-11eb-9e5f-612885f3accc.png)

**Comment by sorentwo** [comment]
The fix is in for this. Expect a patch release with this fix on Friday.

**Comment by jaimeiniesta** [comment]
Was this fix finally released? We're in Oban 2.6.1 and still see wrong counters in our app in Heroku.

**Comment by sorentwo** [comment]
@jaimeiniesta No, that release was held up by some unrelated changes. Sorry for the delay. Expect a release today or tomorrow.
