### ISSUE TITLE
Access to discard reason in telemetry helper

### ISSUE THREAD

**Issue by maltoe** [sorentwo/oban#459]
Hello again 👋 

### Is your feature request related to a problem? Please describe.

We're currently trying to discard a job in an exceptional situation but without retries. Returning `{:discard, reason}` with a string reason would be sufficient, however we would also like this reason to be reported to out error monitoring tool.

This however is not as easy as expected as the discarded job does not emit an `exception` telemetry event but an ordinary `stop` one which does not carry the `exec`'s error information -> https://github.com/sorentwo/oban/blob/be75e2dc2f22bbacd810d9a163b9d9659cbf4459/lib/oban/queue/executor.ex#L149-L152 and https://github.com/sorentwo/oban/blob/be75e2dc2f22bbacd810d9a163b9d9659cbf4459/lib/oban/queue/executor.ex#L231-L240

### Describe the Solution You'd Like

Perhaps the least intrusive solution would be to simply include the `kind`, `error`, `stacktrace` fields in the `meta` map for discarded jobs. A bit obscure in terms of documentation I guess ("stop events don't have them unless it's a discarded job") but the least amount of work required.

Otherwise it would also be possible to update the `job` in the `meta` map after it has been updated by the engine. This could perhaps be a general behaviour change that might be ok in terms of backwards compatibility. Not sure.

### Describe Alternatives You've Considered

I'm aware that a "typical" and also straightforward solution would be to simply manually log an error within the job implementation and don't try to log from the telemetry handler. However, of course we have some additional instrumentation set up in the handler and it would be nice to just use the same logic as for the `exception` event.

Also, since the job has been persisted already when the telemetry event is emitted, we could reload the job from the database in the telemetry handler (for `state: :failure` ones), but this feels wrong to me since we had this information available just a few stackframes above.

Thanks a lot for considering!

best,
malte

**Comment by sorentwo** [comment]
Thanks for the report.

Jobs have an [`unsaved_error`](https://hexdocs.pm/oban/Oban.Job.html#t:t/0) field that is set when a job errors or is discarded. However, it was only passed to the query function and not through to the telemetry handler. I've pushed up a fix that makes things more consistent 👍
