### ISSUE TITLE
Oban.drain_queue(queue: :somequeue, with_recursion: true) is slow

### ISSUE THREAD

**Issue by joshuataylor** [sorentwo/oban#460]
### Environment

- Oban Version: 2.6.1, oban pro: 2.6, oban pro: 0.7.1
- PostgreSQL Version: 13.2
- Elixir & Erlang/OTP Versions (elixir --version): OTP24, Elixir master

### Current Behavior

When using `with_recursion: true`, it can take many seconds (I've observed 30+) to finish the reducer:
```
    new_acc =
      conf
      |> fetch_available(args.queue)
      |> Enum.reduce(old_acc, fn job, acc ->
        IO.inspect "reduce"
        result =
          conf
          |> Executor.new(job)
          |> Executor.put(:safe, args.with_safety)
          |> Executor.call()

        Map.update(acc, result, 1, &(&1 + 1))
      end)

```

To show the IO.inspect of "reduce", it can take a few seconds to run this.

I'm running this in a smallish workflow.

### Expected Behavior

It runs faster :-).

**Comment by sorentwo** [comment]
There shouldn't be any delays between reductions if the jobs are finishing quickly. Can you share some more about what jobs you are reducing?

* How many jobs are running?
* Do they all pass?
* Is it part of a pro workflow, and if so, did you change any of the configuration?

**Comment by joshuataylor** [comment]
I'm doing the following (this is in a test):

1. Using a workflow, I build all the jobs then do an Oban.insert_all()
2. In my test, I do a Oban.drain_queue to process this workflow (and any jobs inside of it)

Before the jobs inside the workflow even run, it seems to take a while in the reduce, these jobs aren't actually running as nothing inside the job fires. The jobs run after the reduce has ran.

**Comment by joshuataylor** [comment]
It seems to be with deps, as removing the deps it's instant.

I think instead of adding additional items to a workflow that is in progress, having multiple workflows setup would be better.

So the usecase I have is that I download items from a third party but don't know how many items there are (so we need to download those chunks), and then do post processing on those results. A single workflow that tracked these would have been ideal.

**Comment by sorentwo** [comment]
Having unknown deps or deps that haven't finished would definitely do that. A workflow worker's `perform/1` function waits on deps and doesn't call `process/1` until they are ready, which would make it look like the job wasn't running yet if you were waiting on `puts` or something from inside the jobs.

If you have more questions about modeling your use case please ask on Slack or the forum. Thanks!
