### ISSUE TITLE
Invalid content in Readme?

### ISSUE THREAD

**Issue by andyduong1920** [sorentwo/oban#462]
### Precheck

https://hexdocs.pm/oban/Oban.html#module-configuring-queues

### Environment

- Oban Version 2.6.1

### Expected Behavior

![image](https://user-images.githubusercontent.com/11751745/114493138-2a84fd80-9c44-11eb-8b24-d3073c1cdc7d.png)

**Comment by sorentwo** [comment]
Thanks for the report. That referenced some outdated docs 👍
