### ISSUE TITLE
How can be oban used together with GridEngine

### ISSUE THREAD

**Issue by zhangzhen** [sorentwo/oban#465]
I develop bioinformatics pipelines as my job. Sun GridEngine(SGE) is used to dispatch computation intensive jobs of a pipeline to a cluster of compute nodes. Currently, I am trying to build a mini-tool that is able to detect dna sequencing is done, demultiplex sequencing data, launch an analytical pipeline, and generate a report. All these are associated with background job processing, so I want to use oban as the building block.

I hope oban is able to handle submitting a job via qsub as a kind of background job processing, and poll SGE to determine if a job is completed.

**Comment by sorentwo** [comment]
The issue tracker is reserved for bug reports and feature discussions. Please ask for help or suggestions on the Elixir Forum or in the #oban channel on the Elixir Slack.
