### ISSUE TITLE
Keyboard accessibility of Oban Web

### ISSUE THREAD

**Issue by angelikatyborska** [sorentwo/oban#468]
### Environment

The bug can be observed on the demo website: https://getoban.pro/oban

- Oban v2.6.1
- Oban.Web v2.6.0
- Oban.Pro v0.7.2

### Current Behavior

The Web UI in its current state isn't keyboard-accessible. A lot of features aren't available without a mouse.

I managed to identify 5 separate issues at a first glance (there might be more issues apparent when those get fixed).

#### 1. Lack of visible focus state

When I start navigating thought the UI by pressing tab, I have no idea where the current focus is. The list elements under "nodes", "states", and "queues" do not have a visible focus state. It even gets removed on purpose by applying a CSS class called `.outline-none`. After tabbing through the lists blindly, I finally get to the checkboxes and search input, which do have a visible focus state, so that I know that the tabbing, in general, works.

This gif shows me tabbing until I find the first element in the UI with a visible focus state:

![2021-04-20 11 59 31](https://user-images.githubusercontent.com/7852553/115377579-0db27200-a1d0-11eb-9089-6937ecf74424.gif)

#### 2. Activation not possible by pressing enter

After I use the web tools to disable the styles applied by the `.outline-none` CSS class so that I can see the focus state of the list elements under "states" and "queues", I try the keyboard navigation again. When the list item for a specific state or queue is focused and I attempt to activate it by pressing enter, nothing happens.

![2021-04-20 12 02 58](https://user-images.githubusercontent.com/7852553/115378047-77328080-a1d0-11eb-8793-0ca9d57867f6.gif)

(This gif was recorder with the `.outline-none` class disabled)

#### 3. Elements revealed on mouse hover do not get revealed on focus or cannot be focused

When hovering over the list items under "queues", some buttons get revealed. Those buttons can be focused when navigating with the keyboard, but they do not get revealed at all.

When hovering over a list header (e.g. "queues"), a collapse/expand button gets revealed. When using the keyboard navigation, this button cannot be reached at all (doesn't get focused).

![2021-04-20 12 04 11](https://user-images.githubusercontent.com/7852553/115378327-bcef4900-a1d0-11eb-950b-7f5bd3411057.gif)

(This gif was recorder with the `.outline-none` class disabled)

#### 4. Job list items aren't focusable at all

In the jobs list, it's possible to click on the job itself to go to job details. This is not possible with the keyboard in any way. The only two focusable elements in a job list item are the "toggle" button (that looks like a checkbox) and the "search for jobs with same worker" button, but not the job list item itself.

![2021-04-20 12 10 12](https://user-images.githubusercontent.com/7852553/115379319-b4e3d900-a1d1-11eb-82e8-83e18cfdd01e.gif)

(This gif was recorder with the `.outline-none` class disabled)

#### 5. Invisible elements get focus

When no jobs are selected and I tab between the search input with the goal to reach the first job on the list, some elements get focused that aren't visible to me at all. I'm guessing those are the "retry" and "delete" buttons that appear after selecting at least one job.

You can see on the gif that it takes more than one tab press to get to the first checkbox.

![2021-04-20 12 07 11](https://user-images.githubusercontent.com/7852553/115379977-5d923880-a1d2-11eb-9e3b-675800168267.gif)

(This gif was recorder with the `.outline-none` class disabled)

### Expected Behavior

- Every UI element that can be clicked with a mouse can also be focused (tab) and activated (enter) with the keyboard.
- Every focusable UI element has visible focus state.
- Every button that is revealed to a mouse user on hover needs to be revealed to a keyboard user on focus.
- It needs to be possible to go to job details with the keyboard only.
- Elements that are not visible at all cannot be focused.

**Comment by sorentwo** [comment]
Thank you for a fantastic issue description!

This will really help us improve the A11Y of Oban Web. I'll share any progress updates here 👍

**Comment by sorentwo** [comment]
Everything is fixed (I think) for the release this week. Thanks again 💛
