### ISSUE TITLE
Testing Crontab

### ISSUE THREAD

**Issue by andreasknoepfle** [sorentwo/oban#471]
### Problem

Since the general recommendation is to set `plugins: false` in the tests, there is no easy way to see if all the entries in `crontab:` are correct, since the config is just `false` in the test environments.

Sometimes somebody misspells a worker name and we can't catch this at all in the CI environment, since the tests are all fine about it. Usually we write test for the worker itself, so that part is covered, but the crontab sits there and is untested up until we deploy to a staging environment, where everything suddenly breaks. 

### Possible Solutions

Maybe this could be solved by a separate `mix` task, that one can add to the CI env, that runs `Oban.Cron.validate!`? 
On the other hand, this requires us to compile again in `dev` or `prod` during a CI run, which will add a lot of time. A better alternative could be to make the config somehow available in the test environment and add test assertion helpers for it, which would be awesome.

**Comment by sorentwo** [comment]
This is a great suggestion. It's technically possible to test your Oban config and the Cron plugin using obscure/undocumented functions, as you noted for `Oban.Plugins.Cron.validate!`.

I agree that something is needed that formalizes a testing approach, or at least guides people on how to test these things. Ideally this would just work and you wouldn't need to do anything extra.

**Comment by andreasknoepfle** [comment]
Great 🎈 . Let me know if I can be of any help.

> It's technically possible to test your Oban config 

I tried to do this in one of our projects, until I realised that the config in our test env is just set to `false` for the tests, so if you have a nice idea on how one could configure Oban in a way, that the plugins are disabled, but the `crontab` config is still around it would already at least be possible to test this via `Oban.Plugins.Cron.validate!` 😊 .

**Comment by milmazz** [comment]
> I tried to do this in one of our projects, until I realised that the config in our test env is just set to `false` for the tests, so if you have a nice idea on how one could configure Oban in a way, that the plugins are disabled, but the `crontab` config is still around it would already at least be possible to test this via `Oban.Plugins.Cron.validate!`

Certainly, this is an interesting problem.

If you're running Elixir 1.11.0 or greater, you can extract your `crontab` configuration for production into a module/function helper, let's say:

```elixir
defmodule MyApp.CronConfigHelper do 
  def get do
    [
      crontab: [
         {"* * * * *", MyApp.MinuteWorker},
         {"0 * * * *", MyApp.HourlyWorker, args: %{custom: "arg"}},
         {"0 0 * * *", MyApp.DailyWorker, max_attempts: 1},
         {"0 12 * * MON", MyApp.MondayWorker, queue: :scheduled, tags: ["mondays"]},
         {"@daily", MyApp.AnotherDailyWorker}
       ],
       timezone: "Etc/UTC"
     ]
  end
end
```

Then you leave the `config/test.exs` as-is.

In your `config/runtime.exs` you can set:

```elixir
import Config

if config_env() == :prod do
  config :my_app, Oban, plugins: [{Oban.Plugins.Cron, MyApp.CronConfigHelper.get()}]
end
```

So far, you keep your production configuration as you wanted, but the good thing is that now, you can access your cron configuration from the test environment. How?

Well, you could do something like:

```elixir
test "crontab configuration is valid" do
  assert :ok = Oban.Plugins.Cron.validate!(MyApp.CronConfigHelper.get())
end
```

HTH

**Comment by andreasknoepfle** [comment]
Sounds like a great workaround 👍  

Thank you 💚

**Comment by bitwalker** [comment]
Another option is to use `Config.Reader.read!("path/to/config/file.exs", env: :dev, imports: [], target: :host)`. Assuming you aren't doing things in your configuration file that affect the global environment (which you shouldn't be if you have  a config setup as described in the Elixir docs!), this will return a keyword list containing all configuration represented in that file and it's imports.

Whether that works for you or not will be dependent on your configuration setup, but it is another option.

**Comment by sorentwo** [comment]
@bitwalker That's a great option.

This seems like a problem solved with documentation rather than more code. I'll fold the great suggestions here into the upcoming testing guide (and ElixirConf talk). In the meantime, I'm closing this.
