### ISSUE TITLE
Queue management functions (scale_queue/2, start_queue/2, etc.) don't work

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#472]
### Environment

- Oban Version - 2.6.1
- PostgreSQL Version - 13.1
- Elixir & Erlang/OTP Versions (`elixir --version`) - 1.11.4, 23.3.1

### Current Behavior

Running `scale_queue/2`, `start_queue/2` have no effect. Queues are not scaled, started, stopped, etc. Still get back `:ok` from these functions.

We are connecting to our database through pgbouncer using a transaction pool.

### Expected Behavior

Queues scale/start/stop as expected.

**Comment by anthonator** [comment]
Looks like this may be related.

**Comment by anthonator** [comment]
Also, using the `:local_only` option has no effect.

**Comment by sorentwo** [comment]
This is entirely because of pgbouncer in transaction mode. Without PG pubsub none of the start/stop/cancel/scale/pause functions will work.

You'll have to run in session mode or wait for an alternate pubsub implementation, as you referenced.
