### ISSUE TITLE
Oban Pro docs invalid link

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#478]
https://hexdocs.pm/oban/dynamic_cron.html#using-and-configuring

In the sentence

*For more details about periodic jobs and cron expressions see the documentation on Periodic Jobs.*

Periodic Jobs links to 

`https://hexdocs.pm/oban/oban.html#module-periodic-jobs`

but it should be

`https://hexdocs.pm/oban/Oban.html#module-periodic-jobs` (capital letter O)

**Comment by sorentwo** [comment]
Fixed and published soon. Thanks for the report 💛
