### ISSUE TITLE
Oban Pro DynamicCron plugin does not work with :timestamptz

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#479]
### Environment

- Oban Version 2.6.1
- PostgreSQL Version 13
- Elixir & Erlang/OTP Versions 1.11 OTP 23

### Current Behavior

I configure in my config

```
config :my_app, MyApp.Repo,
  migration_timestamps: [type: :timestamptz]
```

And use a migration

```elixir
defdelegate change, to: Oban.Pro.Migrations.DynamicCron
```

Then I get the following error:

`(DBConnection.EncodeError) Postgrex expected %DateTime{}, got ~N[2021-05-06 10:55:22]. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.`

### Expected Behavior
I expected the plugin to work with `DateTime` so that `:timestamptz` in Postgres is supported as well. 

Otherwise, the migration should look as follows (this is the workaround I currently use)

```elixir
    create table(:oban_crons, primary_key: false, prefix: prefix) do
      add :name, :text, primary_key: true, null: false
      add :expression, :text, null: false
      add :worker, :text, null: false
      add :opts, :map, null: false
      add :paused, :boolean, null: false, default: false
      add :lock_version, :integer, default: 1

      timestamps(type: :utc_datetime_usec)
    end

    unique_index(:oban_cron, :name, prefix: prefix)
```

**Comment by sorentwo** [comment]
Thanks for the report and tracking down a solution. This is fixed and will be in the next Pro release.
