### ISSUE TITLE
Web: Ability to scale and pause/resume queues per-node

### ISSUE THREAD

**Issue by dmarkow** [sorentwo/oban#481]
### Is your feature request related to a problem? Please describe.

Our app generally runs on a single node -- we have a cpu-bound file processing queue, but it is very low traffic and not worth the cost of a second server. But sometimes we have to process large projects, so I move file processing to a second server temporarily and pause the file processing queue on the main server to avoid web request slowdowns.

Right now, when you click to edit a queue, the only option is a "per node limit".  And when you pause/resume, it seems to only work globally.

### Describe the Solution You'd Like

In addition to global settings, it would be great to have separate options per node when pausing/resuming/scaling.

### Describe Alternatives You've Considered

For now, the alternative seems to be using the console to manually calling `Oban.pause_queue`, `Oban.scale_queue`, etc. with the `local_only` flag.

**Comment by sorentwo** [comment]
_🤫 Don't tell anybody, but a dedicated queue page where you can pause and scale each node separately is in the works currently_

Labeled this as a feature to keep track of it publicly.
