### ISSUE TITLE
Optionally return an error tuple when inserting a duplicate job

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#483]
### Is your feature request related to a problem? Please describe.

Users frequently ask how to tell if a unique job was inserted or if its a job that already existed in the database. Calls to `Oban.insert` will always return `{:ok, job}` whether it inserted or not.

### Describe the Solution You'd Like

Add an option to `unique` that allows the end user to control whether they get an `{:ok, job}` tuple or an error tuple indicating that the job already exists. Putting the option into `unique` opts is backward compatible and easily detected at the insertion point.

### Describe Alternatives You've Considered

Directing users to use other values, or the `replace` syntax to change things when they are updated.

**Comment by chasers** [comment]
Thanks for this ... yes for me understanding explicitly if a job was added or not is useful and returning an error tuple if a job was not added felt better.

After digging, it looks like `inserted_at` is `nil` if a job is new so I have that for now!

**Comment by chasers** [comment]
Mentioned by someone else is Slack ... returning `{:duplicate, job}` which I also like better.

**Comment by capitalist** [comment]
>After digging, it looks like inserted_at is nil if a job is new so I have that for now!
This is a useful workaround, thanks for adding it here.

**Comment by sorentwo** [comment]
Closing in favor of the PR. Thanks all!
