### ISSUE TITLE
oban_pro and oban_web changelogs

### ISSUE THREAD

**Issue by doughsay** [sorentwo/oban#485]
Hey there, here's a snippet of output from `mix hex.outdated`:

```
oban                               2.6.1    2.6.1    Up-to-date
oban_pro                           0.7.2    0.7.3    Update possible
oban_web                           2.6.1    2.6.2    Update possible
```

We're already on the latest version of oban, but there are two patch updates to oban_pro and oban_web.  I can't seem to find any public changelog on these two packages, so I don't know what's going into these updates.  Are there changelogs somewhere that I can get to?

Thanks!

**Comment by doughsay** [comment]
Hah, I'm sorry, I guess I really didn't look hard enough...

I looked here first: https://github.com/sorentwo/oban/blob/master/CHANGELOG.md
Then just found the same copy of it here: https://hexdocs.pm/oban/changelog.html#content

 and then asked my coworker who usually has more interaction with you, and he also didn't know...

Sorry for the useless ticket!  But as a suggestion: I think links at the top of the oban changelog (https://github.com/sorentwo/oban/blob/master/CHANGELOG.md) could help

**Comment by sorentwo** [comment]
@doughsay Links added! Thanks for the suggestion 💛
