### ISSUE TITLE
Support calling `Oban.Testing.all_enqueued` without any opts

### ISSUE THREAD

**Issue by vereis** [sorentwo/oban#487]
### Is your feature request related to a problem? Please describe.

Perhaps this is a strange usecase, or I'm going about this incorrectly, but when testing my code I want to be able to call `all_enqueued/2` without any options provided.

### Describe the Solution You'd Like

The issue is that `Oban.Testing` defines the function `all_enqueued/2` as:

```elixir
def all_enqueued(repo, [_ | _] = opts) do
  {prefix, opts} = extract_prefix(opts)

  Repo.all(
    %{prefix: prefix, repo: repo},
    opts |> base_query() |> order_by(desc: :id)
  )
end
```

A simple solution would be to change this to:

```elixir
def all_enqueued(repo, opts \\ []) when is_list(opts) do
  {prefix, opts} = extract_prefix(opts)

  Repo.all(
    %{prefix: prefix, repo: repo},
    opts |> base_query() |> order_by(desc: :id)
  )
end
```

I believe the other functions in `Oban.Testing` also have this behaviour, but in the case of `assert_enqueued/2` and `refute_enqueued/2` this makes more sense since (I believe) `worker` is a required option.

### Describe Alternatives You've Considered

In my tests, I'm working around the issue currently by wrapping the call in a function which effectively does this:

```elixir
assert_enqueued([something: :random])
```

Which I'd like to avoid having to do 😅

### Additional Context

If you think this is a reasonable change, I'm happy to make a PR when I get a spare moment, otherwise if you think I'm using Oban incorrectly and that there is a better alternative I'm happy to hear about alternate options!

Thanks!

**Comment by sorentwo** [comment]
@vereis Great suggestion. Once I looked into it, I noticed some refactoring opportunities, and I took care of the change.

**Comment by vereis** [comment]
> @vereis Great suggestion. Once I looked into it, I noticed some refactoring opportunities, and I took care of the change.

Awesome! Thank you for your super fast response ❤️
