### ISSUE TITLE
Pro/web links in the changelog lead to 404

### ISSUE THREAD

**Issue by angelikatyborska** [sorentwo/oban#494]
The Changelog starts with this paragraph:
```
🌟 Looking for changes to Web or Pro? Check the Oban.Pro Changelog or the Oban.Web Changelog.
```

The two links are:
- https://github.com/sorentwo/oban/blob/master/pro-changelog.html
- https://github.com/sorentwo/oban/blob/master/web-changelog.html

Both result in a 404 for me. Am I doing something wrong or are those links simply broken? I'm not sure where to find those changelogs.

**Comment by jaimeiniesta** [comment]
Yep they're broken - here are the correct links:

* https://hexdocs.pm/oban/pro-changelog.html#content
* https://hexdocs.pm/oban/web-changelog.html#content

Both are linked from the top menu at https://getoban.pro/

**Comment by jaimeiniesta** [comment]
Related PR https://github.com/sorentwo/oban/pull/495
