### ISSUE TITLE
Oban web dashboard stats query performance 

### ISSUE THREAD

**Issue by zillou** [sorentwo/oban#496]
### Environment

- Oban: 2.7.1
- Oban_web:  2.7.0

### Current Behavior

Oban Web queries job status with the following SQL every 1s per one Oban web dashboard session.

```SQL
SELECT o0."queue", o0."state", count(o0."id") 
FROM "public"."oban_jobs" AS o0 
WHERE (o0."state" IN ('available', 'executing')) 
GROUP BY o0."queue", o0."state" 
UNION 
(
SELECT null, o0."state", count(o0."id") 
FROM "public"."oban_jobs" AS o0 
WHERE (NOT (o0."state" IN ('available', 'executing'))) 
GROUP BY o0."state"
)
```

If there are sizable records in the Oban jobs table, the query will cost a lot of CPU in the PostgreSQL. Because 

1. there is no composite index on "queue" and "state" columns by default;
2. there is a `NOT IN` operator in the query which cannot take advantage of index.

### Expected Behavior

1. Change the `NOT IN` clause to `WHERE o0."state" in ('scheduled', 'retryable', 'completed', 'discarded', 'cancelled')`
2. Remind users to add the composite index in the installation guide.
3. (Nice to have) Share the stats data among different Oban dashboard sessions.

**Comment by sorentwo** [comment]
@zillou I would _love_ to optimize that query, and hope to minimize its impact in the future. However, it isn't as simple as it sounds:

1. There _is_ a composite index on queue and state columns. They are the first two parts of the primary composite index, and are usable by relevant queries (including the first part of that union query).
2. The `NOT IN` operator isn't preventing index usage, it's the number of the `completed` jobs that slow down the query.
3. Stats are shared by all dashboard sessions and are lazy—they're only computed if one or more people are using the dashboard.

Reducing the overall CPU load from the dashboard is a definite priority. Thanks for taking the time to look into solutions and report your thoughts.
