### ISSUE TITLE
Specify `oban_jobs` table primary key as bigserial

### ISSUE THREAD

**Issue by arfl** [sorentwo/oban#5]
All of our migration primary keys are of type uuid. So we specified it with `config :app, App.Repo, migration_primary_key: [type: :binary_id]`, but Oban needs the `id` to be a bigserial. So Oban should explicitely specify the type of the id like that: 
```elixir
create_if_not_exists table(:oban_jobs, primary_key: false) do
      add(:id, :bigserial, primary_key: true)
```

**Comment by sorentwo** [comment]
This has been fixed in 242b4e3 (which was nearly a complete copy paste of your suggestion). Thanks for the report!
