### ISSUE TITLE
Apply jitter to queue refresh intervals

### ISSUE THREAD

**Issue by sorentwo** [sorentwo/oban#504]
### Is your feature request related to a problem? Please describe.

Queues all start around the same time, which means they'll refresh around the same time too. This can tie up multiple Ecto connections and starve the pool, leading to timeouts and errors.

### Describe the Solution You'd Like

Apply broad jitter to the refresh time to space `refresh` calls apart.

### Describe Alternatives You've Considered

There isn't an alternative to spacing the refresh interval.

**Comment by v0idpwn** [comment]
Should it be configurable or a small default jitter is enough?

**Comment by hez** [comment]
@v0idpwn we are looking at adding ~5k queues at boot up, which means a small jitter might not be enough if they all try and call `refresh` on a set interval.

**Comment by sorentwo** [comment]
I'm looking for a large jitter that never exceeds the interval. Meaning if you set a jitter of 60s, it may fire after 30s but never longer than 60s.

@hez the interval will be configurable, so you'll be able to set something like 5-10 minutes. That gives a much wider variance in refresh timing.

**Comment by hez** [comment]
That would work perfectly 👍

**Comment by v0idpwn** [comment]
Looks good, will try to adjust my PR for this scenario
