### ISSUE TITLE
Oban.Testing.perform_job/3 makes incorrect assumption about args type

### ISSUE THREAD

**Issue by jmnsf** [sorentwo/oban#506]
### Environment

- Oban Version: 2.7.2

### Current Behavior

The [`perform_job/3` function](https://github.com/sorentwo/oban/blob/v2.7.2/lib/oban/testing.ex#L208) has a guard on the `args` argument forcing a map, but then forwards the given args to the worker's `new/2` function. This is incompatible with an overriden `new/2` function that accepts different types of args and converts those into a map.

Given this `new/2` function:

```elixir
def new({:user_joined_team, %User{} = user, channel}, opts) when is_binary(channel) do
  super(
    %{
      event: :user_joined_team,
      client_id: user.client_id,
      user_id: user.id,
      channel: channel
    },
    opts
  )
end
```

This worker is no longer testable with `perform_job/3` because if the right args are passed the guard check fails, but if a map is passed instead the inner `new/2` call fails.

### Expected Behavior

I should be able to call `perform_job/3` with whatever arguments provided they end up valid for the job after `new/2`. I guess the guard shouldn't be there, instead the map format should be tested after the `new/2` function is called within `perform_job/3`.

**Comment by sorentwo** [comment]
@jmnsf Thanks for the report. Changed for the next release 💛
