### ISSUE TITLE
oban_web contains invalid symlink

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#507]
I've encountered an issue in our CI pipeline that involves `oban_web`. Upon further investigation I found that `oban_web` (version 2.6.1 in our case) contains an invalid symbolic link https://github.com/earthly/earthly/issues/1067.

In `/lib/oban/web` there is `oban_web -> ../../oban_web/lib/oban_web`, which does not point to a valid folder.

**Comment by janwillemvd** [comment]
In addition to the above, the problem also exists in `oban_web 2.7.1` (in combination with `oban_pro 0.8.1`).

**Comment by sorentwo** [comment]
@dvic Thanks for the report. That was a remnant of the original integration setup. It's removed with the commit above 💛

**Comment by dvic** [comment]
We don't see the commits above ;) but I assume this will be included in the next release?

**Comment by sorentwo** [comment]
@dvic Correct. The linked commit wasn't released yet.
