### ISSUE TITLE
Clarification of precedences between overrides in the DynamicPruner plugin

### ISSUE THREAD

**Issue by crbelaus** [sorentwo/oban#509]
### Is your feature request related to a problem? Please describe.

I am having doubts about the precedences between the different overrides that can be configured in the `DynamicPruner` plugin: queue, worker and state overrides.

Imagine that I have a `queue_overrides`, `worker_overrides` and `state_overrides` and a worker that fits all three of them. Which one would take precedence over the others?

### Describe the Solution You'd Like

A section in the [`DynamicPruner` docs](https://hexdocs.pm/oban/dynamic_pruner.html#providing-overrides), explaining how the different overrides interact between them.

### Describe Alternatives You've Considered

I suppose that I could understand how the overrides interact between them by trial and error. Having jobs and modifying the configuration to se how it behaves.

### Additional Context

No additional context required.

**Comment by sorentwo** [comment]
Great suggestion! There isn't anything in there that explains the precedence. Here's how the precedence works now:

Overrides are applied sequentially, in this order:

1. Queue
2. State
3. Worker
4. Default

```elixir
plugins: [{
  Oban.Pro.Plugins.DynamicPruner,
  mode: {:max_age, {7, :days}},
  queue_overrides: [events: {:max_age, {10, :minutes}}],
  worker_overrides: ["MyApp.SecretWorker": {:max_age, {1, :second}}],
  state_overrides: [discarded: {:max_age, {2, :days}}]
}]
```

Using the example above, jobs in the `events` queue are deleted first, followed by jobs in the `discarded` state, then the `MyApp.SecretWorker` worker, and finally any other jobs older than 7 days that **weren't covered by any overrides**.

With the way it works currently, you can't retain a worker for longer than the queue it is in if you provided a queue override.

**Comment by sorentwo** [comment]
The Pro docs are updated to clarify precedence. Let me know if there are any more questions 💛
