### ISSUE TITLE
Allow binary data to accompany Job

### ISSUE THREAD

**Issue by fireproofsocks** [sorentwo/oban#512]
### Is your feature request related to a problem? Please describe.

It would be nice if there were a way to send some arbitrary binary data along with the `%Oban.Job{}`, i.e. data that is _not_ JSON encoded.  I really wanted to send captured functions and keyword lists and structs to my worker because that would make it the most flexible.

However, if the Job args include captured functions, structs, tuples, keyword lists or the like, the job insert will fail because the encoding protocol isn't implemented for those things.  E.g. the following job creation fails:

```
%{
        f: fn -> IO.puts("hi") end,
        tuple: {:ok, "this", "that"},
        atom: :test,
        keyword: [a: "yes", b: "no"],
        struct: ~U[2020-06-15 18:00:44Z]
    }
|> MyWorker.new()
|> Oban.insert()
# ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for ...
```

However, Erlang does have its own handy way to serialize and unserialize 
```
args = %{
        f: fn -> IO.puts("hi") end,
        tuple: {:ok, "this", "that"},
        atom: :test,
        keyword: [a: "yes", b: "no"],
        struct: ~U[2020-06-15 18:00:44Z]
}

result = args |> :erlang.term_to_binary()  |> :erlang.binary_to_term()
result == args  # true
```
You can't stash the erlang-seriliazed data inside JSON because it contains invalid UTF-8 characters.  So instead of sending the _exact_ data in the Job, I have to simplify the Job and do some laborious string-to-atom conversions et al in the worker.

### Describe the Solution You'd Like

It would be nice if the `oban_jobs` table included a `text` field to store arbitrary binary data associated with a job. E.g. a `meta` field.

### Describe Alternatives You've Considered

An alternative solution is to add our own database migrations to create a `oban_jobs_meta` table (or similar) with a foreign key pointing back to the original job and a text field where I can store arbitrary binary data.  However, this requires a separate database lookup and it might cause problems when jobs are deleted (?)

### Additional Context

I read through the blog post https://elixirforum.com/t/oban-reliable-and-observable-job-processing/22449/2 that discussed the thought process behind JSONB vs binary, and I thought: "why not support both?"  JSONB has certain benefits (like search-ability and easy checks for uniqueness), but it also has some limitations (e.g. UTF-8 encoding).  Adding a binary field would allow users to leverage which-ever field best supports their needs.

**Comment by sorentwo** [comment]
Sending pids, refs, functions, structs, and other non JSON serializable data is an anti-pattern because it isn't portable across systems or deploys. However, if you really want to send that type of data you can use a combination of `:erlang.binary_to_term/2` and `Base.encode64` as part of the JSON payload. There are examples of doing that to pass pids around in the integration tests, if you're interested.

There are viable workarounds and we won't be adding an alternate text column for binary data. Thanks for your sharing your thoughts!

**Comment by fireproofsocks** [comment]
Makes sense.  Thank you for the prompt response!
