### ISSUE TITLE
Postgrex.Error: ERROR XX000 (internal_error) cache lookup failed for type

### ISSUE THREAD

**Issue by dwalintukan** [sorentwo/oban#517]
### Environment

- Oban Version: 2.7.2
- PostgreSQL Version: 10.15
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.12.1 (compiled with Erlang/OTP 22) Erlang/OTP 23

### Current Behavior

Running in Kubernetes, we receive a ton of these errors. On EC2 instances this error does not happen. Could it be related to k8s?

```
Postgrex.Error: ERROR XX000 (internal_error) cache lookup failed for type 403280
  File "lib/ecto/adapters/sql.ex", line 751, in Ecto.Adapters.SQL.raise_sql_call_error/1
  File "lib/ecto/adapters/sql.ex", line 684, in Ecto.Adapters.SQL.execute/5
  File "lib/oban/plugins/stager.ex", line 87, in anonymous fn/1 in Oban.Plugins.Stager.lock_and_stage/1
  File "lib/ecto/adapters/sql.ex", line 1027, in anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  File "lib/db_connection.ex", line 1512, in DBConnection.run_transaction/4
  File "lib/oban/plugins/stager.ex", line 70, in anonymous fn/2 in Oban.Plugins.Stager.handle_info/2
  File "/root/repo/deps/telemetry/src/telemetry.erl", line 272, in :telemetry.span/3
  File "lib/oban/plugins/stager.ex", line 69, in Oban.Plugins.Stager.handle_info/2
```

### Expected Behavior

To not receive any of these errors.

**Comment by sorentwo** [comment]
Typically this happens during blue/green deployment when a migration changes a type that a connected node is using.  In this case, the specific type would be `oban_jobs_state`, which changed in the V9 migration. Since you are on a Postgres version less than 12, the migration couldn't use `ALTER TYPE`; instead, it had to drop and recreate the type.

Did this happen once during a migration, or does it keep happening? If it keeps happening, are you running migrations on staging instances or something?

**Comment by dwalintukan** [comment]
Thanks for the quick reply! This happens a lot on our staging/sandbox environment. We get massive amounts of errors thrown.

The staging and multiple sandbox environments are all connected to a persistent RDS Postgres DB. So, the Oban migration has already successfully ran before and isn't being run over and over again.

In our staging/sandbox environments, we often redeploy a new container/pod when a new commit gets pushed up. Could this error possibly surface when the previous pod is being destroyed and the new one is being initialized? Appreciate the help!

**Comment by sorentwo** [comment]
The only type that Oban defines is the `state` that I mentioned before. My hunch is that somehow the type is changing, maybe through a migration. That's the only time I have heard of this issue—otherwise I'm not sure what's going on.

Do you automatically run migrations on boot? Are you using different prefixes? Can you upgrade to PG 12+?

**Comment by dwalintukan** [comment]
We are running on Postgres 11.10 on RDS for this environment with issues. Is there known compatibility issues with this version?

Considering we are using the same persistent DB for staging/sandbox, the Oban migration had only run once previously and shouldn't be running again.

Do we need to run ` Oban.Migrations.up()` more than once as the schema changes?

**Comment by sorentwo** [comment]
> We are running on Postgres 11.10 on RDS for this environment with issues. Is there known compatibility issues with this version?

There isn't an incompatibility with 11.0. Oban works on 9.6+, but the `ALTER TYPE` function wasn't added until 12.0 and that's what is changing the type out from under you.

> Do we need to run ` Oban.Migrations.up()` more than once as the schema changes? According to our current version, we are at version 10.

Version 10 is current and you don't need to run the migrations more than that. From my understanding, the only way to encounter this error is by changing a type, function, or another database object that's referenced by an OID. The **only** time that Oban does that is when the migrations run.

**Comment by dwalintukan** [comment]
Just an update: we updated the library to the latest version 2.7.2, but we didn't run the migration again (since 2 months ago) so I am hoping running the migration the second time will fix this issue. Will keep you posted.

**Comment by dwalintukan** [comment]
So everything seems to be all working in order after running the migration. Thanks for the help and great library!
