### ISSUE TITLE
sql_error_code = 01000 WARNING: you don't own a lock of type ShareLock

### ISSUE THREAD

**Issue by seanwash** [sorentwo/oban#52]
Context: I have a nightly task that spins up a bunch of jobs that calculate/set a value on rows in one of my tables. I don't have any sort of batching implemented for it as of right now, so that task spins up a good number of jobs quickly, I estimate around 90k jobs. Since swapping out my redis job setup w/ Oban, I've noticed a bunch of `sql_error_code = 01000 WARNING: you don't own a lock of type ShareLock` in my DB's console (I'm on Heroku fwiw). This seems limited to only one of my queues, `email`. I manually changed the queue on a few of the jobs from `email` to `default` and the jobs were immediately completed.

Any ideas here? I did notice a closed issue #4 but I'm not entirly sure if this issue is related.

**Comment by sorentwo** [comment]
The warning is coming from a producer attempting to unlock jobs that weren't locked by the current session. It is noisy and annoying, but can safely be ignored.

This is a shortcoming of using advisory locks and is among the primary reasons that I'm investigating an alternative tracking mechanism for executing jobs.

**Comment by eteubert** [comment]
I currently get thousands of lines of `WARNING:  you don't own a lock of type ShareLock` per second, which leads to the log file growing rapidly to unhealthy sizes. 

I can reproduce this on my local machine and it also happens on staging, where the disk ran out of space. Is there anything I can do to mitigate this besides disabling logs or reducing log retention?

**Comment by sorentwo** [comment]
There are changes in master which eliminate the use of advisory locks entirely. I’ve been running master for the past week without any issue, but I haven’t released 0.8 yet.

Feel free to test master on your staging server and report back. I’d really appreciate any feedback.

If that isn’t an option and you’d prefer to wait, you can reduce your Ecto pool size which will reduce the number of warnings.

**Comment by eteubert** [comment]
I had an issue with the migration (#61) but apart from that it's running smoothly on my local machine so far 👍🏻
