### ISSUE TITLE
Way to enqueue jobs without starting supervisors

### ISSUE THREAD

**Issue by arnodirlam** [sorentwo/oban#520]
We sometimes open an iex session to our production app to do some ad-hoc tasks. On Heroku, this is done by starting a new VM that connects to the production database. We make sure that these don't run any worker processes.

Currently we can't enqueue jobs from this session, because the supervisor is not  started. From the Oban source code, it looks to me like the supervisor is also responsible for initially storing the config you pass to it as supervisor argument to a Registry.

It would be nice to be able to store the config in order to be able to enqueue jobs, but not start workers or maintenance plugins such as the pruner. That way, we could always initialize the config, but only run workers on the worker VM.

Not sure though if anything else needs to be started under a supervisor in order to enqueue jobs.

Thanks a lot for considering, and for the great work on Oban!

**Comment by v0idpwn** [comment]
You can conditionally start a queue-less and plugin-less oban, I think that's the common approach to do what you want to achieve. This guide should help you: https://hexdocs.pm/oban/splitting-queues.html

**Comment by sorentwo** [comment]
@arnodirlam There are a couple of options available:

1. Only use Ecto — Oban is using `Ecto.Repo.insert` and `Ecto.Repo.insert_all` under the covers. If you don't need unique support, which Oban handles, then you can insert a job as you would any other changeset.
2. Start without Queues or Plugins — This is a common thing to do in environments like Heroku where a console is a whole new node. Here is one way to skip running queues or plugins from IEx:

```elixir
  defp oban_config do
    opts = Application.get_env(:my_app, Oban)

    if Code.ensure_loaded?(IEx) && IEx.started?() do
      opts
      |> Keyword.put(:plugins, false)
      |> Keyword.put(:queues, false)
    else
      opts
    end
  end
```

One caveat of note with the second option: it won't run jobs in development if you use `iex -S mix phx.server`. You can either use `mix phx.server` by itself or use something like an environment variable.

**Comment by arnodirlam** [comment]
Thanks for the quick and helpful replies.
