### ISSUE TITLE
Allow simple dependency injection to simplify testing

### ISSUE THREAD

**Issue by MMore** [sorentwo/oban#523]
Thank you for this great library!

### Is your feature request related to a problem? Please describe.

I usually have `perform` functions that do some harder work. But how to _easily_ test these without actually doing the hard work? Sure for sending email, calling webservices you could mock it. But how do you handle other jobs in an _easy_ way?

### Describe the Solution You'd Like

Currently can just add an optional parameter to

```elixir
def perform(
        %Oban.Job{
          args: %{
            "test" => input_parameter
          }
        },
        hard_work_fn \\ &HardWork.do_it/1 # like this
      ) do
        
    hard_work_fn.(input_parameter)
  end
```

The existing `perform_job/3` function very helpful and makes testing easier. But it can't pass values to optional parameters like above to `hard_work_fn`. What about adding a parameter to this function to simplify testing via dependency injection?

**Comment by sorentwo** [comment]
There are a couple of ways to do dependency injection for your workers:

1. Don't use `perform_job/2,3` and call `perform/2` directly, passing whatever you want as an argument. You won't have the return checking or other niceties of `perform_job/2,3`, but you'll have complete control.
2. Stuff the function capture into `meta`, which isn't serialized to and from JSON by `perform_job/2,3`.

Option #1 is a perfectly valid approach, and #2 is a slight hack. If you want to use `meta` to smuggle in a function, it will look like this:

```elixir
perform_job(MyWorker, args, meta: %{hard_work_fn: &HardWork.do_it/1})
```

A PR to document these testing approaches/alternatives is welcome 💛

**Comment by MMore** [comment]
Thanks for your reply.
Definitely I prefer option 1, but I was hoping to improve `perform_job/2,3` in a way which keeps all the niceties of it ;-)

**Comment by sorentwo** [comment]
I'm 👎 on augmenting `perform_job/2,3` to work with additional arities of `perform` because there is only a callback for `perform/1`. Passing arbitrary data through `meta` strikes a decent balance, IMO.
