### ISSUE TITLE
Reliable scheduled jobs, documentation error

### ISSUE THREAD

**Issue by sebasortiz-dev** [sorentwo/oban#536]
In the documentation  
https://hexdocs.pm/oban/reliable-scheduling.html version 2.8.0 the example is where the pattern match on attempt is using `1`, when the attemps start from `0`, 

Example code in docs,

```
 @impl true
  def perform(%{args: %{"email" => email} = args, attempt: 1}) do
    args
    |> new(schedule_in: @one_day)
    |> Oban.insert!()

    Mailer.deliver_email(email)
  end
```

Inspect of a job args,

```
%Oban.Job{
  __meta__: #Ecto.Schema.Metadata<:built, "oban_jobs">,
  args: %{"account_id" => "7049121c-c359-4158-af8b-ed5ef5c3752d"},
  attempt: 0,
  attempted_at: nil,
  attempted_by: nil,
  cancelled_at: nil,
  completed_at: nil,
  conf: nil,
  conflict?: false,
  discarded_at: nil,
  errors: [],
  id: nil,
  inserted_at: nil,
  max_attempts: 20,
  meta: %{},
  priority: 0,
  queue: "default",
  replace: nil,
  scheduled_at: nil,
  state: "available",
  tags: [],
  unique: nil,
  unsaved_error: nil,
  worker: nil
}
```

**Comment by sorentwo** [comment]
Thanks for the report!

When a job is inserted, attempts start at 0. However, the `attempt` is incremented when a job is processed, and `perform/1` is never called with an `attempt` less than 1.

**Comment by sebasortiz-dev** [comment]
@sorentwo I got it, but  when writing the tests for this, the job is never attempted, so the way to test is forcing the "attempt:1" when calling the `process`. I think this would be helpful in the docs about testing this jobs.

**Comment by sorentwo** [comment]
Ah, I see what you're saying now. Are you using `perform_job` for testing? If so, perhaps `perform_job` can default to `attempt: 1`. WDYT?

**Comment by sebasortiz-dev** [comment]
Because i'm using this in a Workflow I cannot use the perform_job, so i'm calling Worker.perform directly. Is there any other recommend way to test Workflows?

**Comment by sorentwo** [comment]
Ah, if it is in a workflow, you can use the hidden (read, lacking a guide) `Oban.Pro.Testing.process_job` function instead. Like this:

```elixir
import Oban.Pro.Testing
```

Then test worker logic in isolation:

```elixir
assert :ok = process_job(MyApp.ProWorker, %{"id" => 1})
```

A guide and some updates are coming for the `Testing` module in the next Pro release.

**Comment by sebasortiz-dev** [comment]
Thanks, I've change my asserts and it's working.
