### ISSUE TITLE
Default attempt on perform_job/3

### ISSUE THREAD

**Issue by rodrigo-sp17** [sorentwo/oban#539]
### Is your feature request related to a problem? Please describe.

We had a little confusion during our last deployment due to the way the functions `perform_job/3` and `drain_queue/2` are implemented. Since the former performs a job by default on attempt 0, and the latter performs like Oban would normally do, that is on attempt 1, we ended up implementing the necessary actions on attempt 0 instead of 1, and that passed the tests due to the aforementioned behavior.

### Describe the Solution You'd Like

Refactor `perform_job/3` to use attempt: 1 as default, since this is the behaviour Oban will use during runtime.

### Describe Alternatives You've Considered

Improve the documentation to clearly state this fact and avoid similar confusions in the future.

**Comment by sorentwo** [comment]
Great catch, thanks for the report! Fixed up for the next release 👍
