### ISSUE TITLE
Oban Web doesn't wrap text for job failures

### ISSUE THREAD

**Issue by sadachar** [sorentwo/oban#543]
### Environment

- Oban 2.6.1 and Oban Pro 0.7
- PostgreSQL Version 11
- Elixir 1.12 and OTP 24.0

### Current Behavior

In the Oban Pro UI, when an oban job fails and the error message is too long, it doesn't wrap text. This makes it a bit difficult to inspect what the entire error was.

<img width="1435" alt="Screen Shot 2021-09-02 at 9 45 06 AM" src="https://user-images.githubusercontent.com/8871457/131884818-46f8bbcf-344b-4fe7-b700-c5629ed4cb4f.png">

### Expected Behavior

It'd be awesome if the error message was fully visible in one glance.

**Comment by sorentwo** [comment]
@sadachar Thanks for the report. This is a known problem, and I'll have a fix for it in the next release 👍
