### ISSUE TITLE
Issue with prefixes when calling cancel_job in Oban 2.9

### ISSUE THREAD

**Issue by williamgelhar-validere** [sorentwo/oban#547]
### Environment

- Oban 2.9.0
- Postgresql 10
- Elixir 1.12.1, OTP 24

### Current Behavior

We're using a prefix for Oban configured through:

```
config :our_app, Oban,
  prefix: "oban",
```

When upgrading from Oban 2.8 to Oban 2.9, we're getting an error when calling this code:

```
    from(
      job in Oban.Job,
      where: job.worker == ^@job_worker,
      where: job.state not in ["completed", "discarded"],
      select: job.id
    )
    |> Repo.all(prefix: @oban_prefix)
    |> Enum.each(fn job_id -> :ok = Oban.cancel_job(job_id) end)
``` 

The error:

```
   ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "oban_jobs" does not exist

         query: UPDATE "oban_jobs" AS o0 SET "state" = 'cancelled', "cancelled_at" = $1 WHERE (o0."id" = $2) AND (NOT (o0."state" IN ('completed','discarded','cancelled')))
```

"oban_jobs" does not exist as a table, but the table "oban.oban_jobs" (using our prefix "oban") does.

### Expected Behavior

In 2.8 this code worked, and we've worked around it by calling: 

```
    from(
      job in Oban.Job,
      where: job.worker == ^@job_worker,
      where: job.state not in ["completed", "discarded"]
    )
    |> put_query_prefix(@oban_prefix)
    |> Oban.cancel_all_jobs()
```

instead, which works because we're putting the prefix in the query we're passing to `cancel_all_jobs`. 

The new `cancel_all_jobs` works better for our case anyway, but it seems like `Oban.cancel_job(...)` may have a regression now if you're using prefixes for your sql table names. 

In Oban 2.8, `Oban.cancel_job` would call `Repo.update_all(conf, query, updates)`, which adds the prefix to the query by calling `query_opts`. Oban 2.9's `Oban.cancel_job` calls `cancel_all_jobs` which uses `Repo.transaction`, which calls `default_opts` instead of `query_opts` and does not add the prefix.

**Comment by sorentwo** [comment]
Thanks for the report. That's a gotcha with `Multi` that gets me all the time!
