### ISSUE TITLE
[Doc] Use Case: Silencing Initial Notifications for Flaky Services

### ISSUE THREAD

**Issue by linomassarani** [sorentwo/oban#552]
### Environment

- Oban Version: v2.9.0

### Current Behavior

As discussed in [Slack channel](https://elixir-lang.slack.com/archives/CRDGH1XCM/p1632249054133300), seems that the example in documentation "[Use Case: Silencing Initial Notifications for Flaky Services](https://hexdocs.pm/oban/expected-failures.html#use-case-silencing-initial-notifications-for-flaky-services)" wouldn't work, because `meta.job.worker` is a BitString, so it'll always falls to `Any` protocol implementation.

Even if we do `Oban.Worker.from_string/1` it will be an `atom` so, it will always fall on `Any` again. 

### Expected Behavior

The only way I can see the example working would be adding in worker `defstruct []` before implementing the protocol
and in the error reporter, trying to retrieve a struct from the module name, this way we could dispatch to that struct implementation.

But I'm not sure if it's a nice solution either, maybe using macros would be better.

We could do something like below to get the struct:

```elixir
def maybe_get_struct_for_worker(worker) do
    try do
      Elixir
      |> Module.safe_concat(worker)
      |> struct()
    rescue
      UndefinedFunctionError -> worker
    end
  end

```

Thanks!

**Comment by linomassarani** [comment]
Possible changes to keep using protocols:

## Use Case: Silencing Initial Notifications for Flaky Services

One solution for reducing noisy error notifications is to start reporting only after a job has failed several times. Oban uses [Telemetry](https://github.com/beam-telemetry/telemetry) to make reporting errors and exceptions a simple matter of attaching a handler function. In this example we will extend [Honeybadger](https://www.honeybadger.io/) reporting from the `Oban.Telemetry` documentation, but account for the number of processing attempts.

To start, we'll define a `Reportable` [protocol](https://hexdocs.pm/elixir/Protocol.html) with a single `reportable?/2` function:

```elixir
defprotocol MyApp.Reportable do
  @fallback_to_any true
  def reportable?(worker, attempt)
end

defimpl MyApp.Reportable, for: Any do
  def reportable?(_worker, _attempt), do: true
end
```

The `Reportable` protocol has a default implementation which always returns `true`, meaning it reports all errors. Our application has a `FlakyWorker` that's known to fail a few times before succeeding. We don't want to see a report until after a job has failed three times, so we'll add an implementation of `Reportable` within the worker module:


```elixir
defmodule MyApp.Workers.FlakyWorker do
  use Oban.Worker

  defstruct []

  defimpl MyApp.Reportable do
    @threshold 3

    def reportable?(_worker, attempt), do: attempt > @threshold
  end

  @impl true
  def perform(%{args: %{"email" => email}}) do
    MyApp.ExternalService.deliver(email)
  end
end
```

The final step is to call `reportable?/2` from our application's error reporter, passing in the worker module and the attempt number:

```elixir
defmodule MyApp.ErrorReporter do
  alias MyApp.Reportable

  def handle_event(_, _, meta, _) do
    if Reportable.reportable?(maybe_get_worker_struct(meta.job.worker), meta.job.attempt) do
      context = Map.take(meta.job, [:id, :args, :queue, :worker])

      Honeybadger.notify(meta.reason, context, meta.stacktrace)
    end
  end

  def maybe_get_worker_struct(worker) do
    try do
      worker
      |> Oban.Worker.from_string()
      |> struct()
    rescue
      UndefinedFunctionError -> worker
    end
  end
end
```

Attach the failure handler somewhere in your `application.ex` module:

```elixir
:telemetry.attach("oban-errors", [:oban, :job, :exception], &ErrorReporter.handle_event/4, nil)
```

With the failure handler attached you will start getting error reports **only after the third error**.

**Comment by linomassarani** [comment]
Possible changes to use macros instead:

## Use Case: Silencing Initial Notifications for Flaky Services

One solution for reducing noisy error notifications is to start reporting only after a job has failed several times. Oban uses [Telemetry](https://github.com/beam-telemetry/telemetry) to make reporting errors and exceptions a simple matter of attaching a handler function. In this example we will extend [Honeybadger](https://www.honeybadger.io/) reporting from the `Oban.Telemetry` documentation, but account for the number of processing attempts.

To start, we'll define a `Reportable` module with a `reportable?/1` function that will be injected when another module [`use`](https://hexdocs.pm/elixir/Kernel.html#use/2) the module:

```elixir
defmodule MyApp.Reportable do
  @threshold 2

  defmacro __using__(opts) do
    threshold = Keyword.get(opts, :threshold, @threshold)

    quote do
      @spec reportable?(non_neg_integer()) :: boolean()
      def reportable?(attempt), do: attempt > unquote(threshold)
    end
  end

  @spec reportable?(String.t(), non_neg_integer()) :: boolean()
  def reportable?(worker, attempt) do
    with {:ok, worker_module} <- Oban.Worker.from_string(worker),
        true <- function_exported?(worker_module, :reportable?, 1) do
      worker_module.reportable?(attempt)
    else
      _ -> attempt > @threshold
    end
  end
end
```

The `Reportable` module has a default threshold which will always returns `true`, when threshold is greater than `2`. Our application has a `FlakyWorker` that's known to fail a few times before succeeding. We don't want to see a report until a job has failed three times, so we'll `use` the `Reportable` within the worker module:


```elixir
defmodule MyApp.Workers.FlakyWorker do
  use Oban.Worker
  use MyApp.Reportable, threshold: 3

  @impl true
  def perform(%{args: %{"email" => email}}) do
    MyApp.ExternalService.deliver(email)
  end
end
```

The final step is to call `reportable?/2` from our application's error reporter, passing in the attempt number:

```elixir
defmodule MyApp.ErrorReporter do
  alias MyApp.Reportable

  def handle_event(_, _, meta, _) do
    if Reportable.reportable?(meta.job.worker, meta.job.attempt) do
      context = Map.take(meta.job, [:id, :args, :queue, :worker])

      Honeybadger.notify(meta.reason, context, meta.stacktrace)
    end
  end
end
```

Attach the failure handler somewhere in your `application.ex` module:

```elixir
:telemetry.attach("oban-errors", [:oban, :job, :exception], &ErrorReporter.handle_event/4, nil)
```

With the failure handler attached you will start getting error reports **only after the third error**.

**Comment by sorentwo** [comment]
@linomassarani Thank you for opening the issue and exploring the various options. I went with the `defstruct` approach, it is least invasive and seemed most sensible.
