### ISSUE TITLE
pg_try_advisory_xact_lock, log: false still logs

### ISSUE THREAD

**Issue by joenoon** [sorentwo/oban#556]
I can't seem to prevent this log, even with log: false.  Is there any workaround?

https://github.com/sorentwo/oban/blob/2054f8f25412f4174aeae7a0f80b06dc7858092c/lib/oban/query.ex#L213

**Comment by sorentwo** [comment]
@joenoon Which version of Oban are you using? According to the code, and from my local testing, that doesn't log:

```
iex(1)> Logger.configure(level: :debug)

iex(2)> conf = Oban.Config.new(repo: Oban.Test.Repo)

iex(3)> Oban.Repo.query(%{conf | log: :debug}, "select pg_try_advisory_xact_lock($1)", [12345678], [])

08:38:12.633 [debug] QUERY OK db=1.2ms queue=1.6ms idle=1955.2ms
select pg_try_advisory_xact_lock($1) [12345678]
{:ok,
 %Postgrex.Result{
   columns: ["pg_try_advisory_xact_lock"],
   command: :select,
   connection_id: 83319,
   messages: [],
   num_rows: 1,
   rows: [[true]]
 }}

iex(4)> Oban.Repo.query(%{conf | log: false}, "select pg_try_advisory_xact_lock($1)", [12345678], [])
{:ok,
 %Postgrex.Result{
   columns: ["pg_try_advisory_xact_lock"],
   command: :select,
   connection_id: 83311,
   messages: [],
   num_rows: 1,
   rows: [[true]]
 }}
```

The query uses the `Repo` module, which wraps Ecto and ensures the prefix and log are applied to each query https://github.com/sorentwo/oban/blob/master/lib/oban/repo.ex#L109

Can you share some logs or reproduce the issue?

**Comment by joenoon** [comment]
I'm locked to 2.8.0 and will try upgrading tonight.

Here is the log if I just let iex sit idle while a job executes and reschedules itself every 20 seconds:

```
[debug] QUERY OK db=0.1ms
SELECT pg_try_advisory_xact_lock($1) [54623483]
[debug] schedule_lazy 20
[debug] QUERY OK db=0.1ms
SELECT pg_try_advisory_xact_lock($1) [54623483]
[debug] QUERY OK db=0.1ms
SELECT pg_try_advisory_xact_lock($1) [54623483]
[debug] schedule_lazy 20
[debug] QUERY OK db=0.1ms
SELECT pg_try_advisory_xact_lock($1) [54623483]
```

Strange, because `log: false` obviously works everywhere else... I was guessing it might have to do with this spot being a Oban.Repo.query, where maybe all other places queries occur run through Oban.Repo.transaction.

**Comment by sorentwo** [comment]
@joenoon The timing there led me to look at the Smart Engine. Alas, it was in Pro. Fixed in the next patch release 👍
