### ISSUE TITLE
Retrieve job original error as elixir structure instead of string

### ISSUE THREAD

**Issue by sezaru** [sorentwo/oban#562]
### Is your feature request related to a problem? Please describe.

Currently when a job returns an error, example: `{:error, "blibs"}`, it will insert something like this into the `errors` field of the `Oban.Job` schema:

```elixir
errors: [
  %{
    "at" => "2021-09-28T18:26:54.951519Z",
    "attempt" => 3,
    "error" => "** (Oban.PerformError) TeachersAid.Workers.Import failed with {:error, \"blibs\"}"
  }
]
```

I want to be able to query the database for failed jobs and retrieve the current error instead of a string as it is today.

### Describe the Solution You'd Like

Basically, the idea is that the error itself is stored as it is returned from the job worker, so, for example, for the above example, I would expect something like this:

```elixir
errors: [
  %{
    "at" => "2021-09-28T18:26:54.951519Z",
    "attempt" => 3,
    "error" => {:error, "blibs"}
  }
]
```

That way I can access the `"error"` field and retrieve the specific error.

**Comment by sorentwo** [comment]
@sezaru Thanks for the suggestion! Error formatting can be a pain. There are a few issues that prevent us from making this change:

1. Changing the way errors are stored would break a long-standing contract.
2. Errors are stored in the database as `jsonb`, which can't serialize arbitrary Erlang/Elixir terms, e.g., atoms, tuples, structs, pids.

The best we could do here is to provide an error serialization callback on the worker to let you control the format in your app, but you still couldn't store the original error.

Instead, I suggest defining your own exceptions and optionally implementing the [blame callback](https://hexdocs.pm/elixir/Exception.html#c:blame/2) to enhance the error message.
