### ISSUE TITLE
Getting Certificate Expired when using mix hex.organization auth oban

### ISSUE THREAD

**Issue by mitcheaton1** [sorentwo/oban#564]
### Environment

- Oban Version - pro is 0.8, and web  is 2.7 
- PostgreSQL Version - 13
- Elixir & Erlang/OTP Versions (`elixir --version`) - 1.12.2 and OTP 24

### Current Behavior
we cant seem to run this mix task any longer, both locally and in our CI. We are getting a certificate expired issue. 

The command '/bin/sh -c mix hex.organization auth oban --key $OBAN_UI_LICENSE_KEY' returned a non-zero code: 1

16:40:42.579 [info]  TLS :client: In state :certify at ssl_handshake.erl:1882 generated CLIENT ALERT: Fatal - Certificate Expired
{:failed_connect, [{:to_address, {'hex.pm', 443}}, {:inet, [:inet], {:tls_alert, {:certificate_expired, 'TLS client: In state certify at ssl_handshake.erl:1882 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}}]}

### Expected Behavior

We expect the certificate to be valid.

**Comment by sorentwo** [comment]
This is due to a CA root certificate expiring and a Let's Encrypt workaround. There are details in this [Elixir Forum post](https://elixirforum.com/t/psa-preventing-outages-due-to-dst-root-ca-expiry-on-sep-30th/42247?u=sorentwo) and [Voltone's blog](https://blog.voltone.net/post/30).

Quoting from the linked post:

> The safest thing to do is make sure the application is running on Erlang/OTP 23.3.4.5 or later, or 24.0.4.

**Comment by sorentwo** [comment]
I'm pinning this for the time being because this keeps coming up on Slack and in emails.

**Comment by mitcheaton1** [comment]
ah thanks! ill take a look.

**Comment by sorentwo** [comment]
The day of reckoning has passed! (Plus, people kept emailing anyhow 🤷). Closing this.
