### ISSUE TITLE
Oban Web not working anymore with LiveView 0.17

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#573]
I'm getting the following error when using LiveView 0.17: 

`Error on Oban.Web.BulkActionComponent.render/1 with id of :bulk_action. Stateful components must return a HEEx template (~H sigil or .heex extension)`

It's probably the same issue as the one I reported in https://github.com/surface-ui/surface/issues/494

**Comment by ksheurs** [comment]
Thanks for your effort on this @sorentwo! I am trying to get `oban_web` setup for the first time. On `2.7.0` I hit a `bad argument in arithmetic expression` exception in `lib/oban/web/plugins/stats.ex` and on `2.7.4` I hit this `HEEx` issue. Is there a current version I can use in the interim or is it best that I just want for this issue to be resolved? Thank you again 🙌

**Comment by sorentwo** [comment]
Web 2.7.4 doesn’t use heex, which makes it incompatible with LV 0.17 or above. If you pin LV to 0.16 it’ll work fine and you won’t get the heex error.

**Comment by sorentwo** [comment]
The next release is fully LV 0.17 compatible and ready to go this week.
