### ISSUE TITLE
Oban 2.9.2 crashes if `:log` or `:prefix` are not present in config

### ISSUE THREAD

**Issue by simoncocking** [sorentwo/oban#581]
### Environment

- Oban Version 2.9.2
- PostgreSQL Version 14.0
- Elixir 1.12.3, OTP 24.1

### Current Behavior

Our Oban config with Oban 2.8.0:
```
config :myapp, Oban,
  repo: MyApp.Repo,
  plugins: [ ... ],
  queues: [ ... ]
```

After upgrading to Oban 2.9.2, we get the following error when calling `Oban.Repo.one/3`:
```
** (KeyError) key :log not found in: %{plugins: [...], queues: [...], repo: MyApp.Repo}
    (oban 2.9.2) lib/oban/repo.ex:211: Oban.Repo.query_opts/2
    (oban 2.9.2) lib/oban/repo.ex:94: anonymous fn/3 in Oban.Repo.one/3
```

Setting `log: nil` in our config eliminates this error, but then we crash on a missing `:prefix` key.

This appears to have been introduced in [this commit](https://github.com/sorentwo/oban/commit/8fdc314adb369557d7fbca6d75e83c35726afee1) in which `oban/lib/oban/repo.ex` now expects the `:log` and `:prefix` keys to be present on the config at all times:
```
  defp query_opts(conf, opts) do
    opts
    |> Keyword.put(:log, conf.log)
    |> Keyword.put(:prefix, conf.prefix)
  end
```

### Expected Behavior

`:log` and `:prefix` config keys should be optional.

**Comment by sorentwo** [comment]
Both `:log` and `:prefix` are built into `Oban.Config`, which is what should be passed to `Oban.Repo` functions. Prior to that change, the type was unintentionally loose and didn't match config usage throughout the rest of the library.

Where is the call to `Oban.Repo.one/3` coming from in that stacktrace? Is it something from your application that you can share?

Note that you can always get the current config with `Oban.config/0,1` if necessary.

**Comment by simoncocking** [comment]
Ah, that explains it. We're passing a map built from the config itself 🤦‍♀️

**Comment by simoncocking** [comment]
Just confirming that passing the output of `Oban.config/0` resolves this nicely. Thanks for the fast response!
