### ISSUE TITLE
Oban Web: Adding application links on dashboard

### ISSUE THREAD

**Issue by tverlaan** [sorentwo/oban#584]
### Describe the Solution You'd Like

I would like to be able to link to the application from the oban dashboard. This makes it a little bit more integrated with the rest of the application. It could be a simple sidebar component where a few links can be displayed, through configuration or through a callback.

### Describe Alternatives You've Considered

Another option is to make the header clickable and get taken to a destination of the users' choice. Eg `/` or `/admin`. This would be more straightforward though less flexible.

**Comment by sorentwo** [comment]
Thanks for the suggestion! I understand the desire to have the UI more integrated into your application. However, without a comprehensive solution to extensibility, I'm hesitant to add features like this.

If you'd like the UI to be more integrated into your application I recommend displaying it within an iframe. That would give you complete control over links, whether there is a sidebar, etc. without having to inject links into the UI.
