### ISSUE TITLE
Jobs are not executed if using dynamic repo and base repo config is missing some options

### ISSUE THREAD

**Issue by lauriannala** [sorentwo/oban#585]
### Environment

- Oban Version: 
```shell
    {:oban, "~> 2.9.2"},
    {:oban_pro, "~> 0.9", repo: "oban"}
```
- Elixir & Erlang/OTP Versions (`elixir --version`)
```shell
    Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]
    Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

### Current Behavior

Setup description is simplified for the sake of clarity.
 
When application is exclusively using dynamic repositories, a working setup
can omit username and password from the base repo config:

```
config :my_app, MyApp.Repo,
  database: database,
  hostname: hostname,
  port: port,
  pool_size: pool_size
```

The application can then later at runtime register ecto repo instances each having their own configuration
which will eventually have working username and password configured.

When using dynamic_repo-option Oban should use the registered ecto instance which then includes the required options like username and password:
```
config :my_app, Oban,
  prefix: "jobs",
  repo: MyApp.Repo,
  get_dynamic_repo: fn -> dynamic_repo_name end
```
However, it seems to me that Oban is still internally using the base config username and password (on some features) which results in errors on this setup:

```shell
{
  "event": "circuit:trip",
  "message": "{%KeyError{key: :username, message: nil, term: [types: nil, types: Postgrex.DefaultTypes, sync_connect: true, telemetry_prefix: [:my_app, :repo], otp_app: :my_app, timeout: 15000, database: \"database\", hostname: \"hostname\", port: port, pool_size: pool_size]}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 420]}, {Postgrex.Protocol, :startup, 2, [file: 'lib/postgrex/protocol.ex', line: 751]}, {Postgrex.Protocol, :handshake, 2, [file: 'lib/postgrex/protocol.ex', line: 655]}, {Postgrex.Protocol, :connect_endpoints, 6, [file: 'lib/postgrex/protocol.ex', line: 160]}, {Postgrex.Notifications, :connect, 2, [file: 'lib/postgrex/notifications.ex', line: 233]}, {Postgrex.Notifications, :init, 1, [file: 'lib/postgrex/notifications.ex', line: 215]}, {Connection, :init_it, 6, [file: 'lib/connection.ex', line: 424]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}",
  "name": "Elixir.Oban.Notifier",
  "source": "oban"
}
```

In this scenario, no jobs are executed and they are left in Available-state.

### Expected Behavior

User should be able to control at runtime what ecto repo instance or config is used internally by oban.

**Comment by sorentwo** [comment]
This error seems like it is caused by the PG notifier, as it pulls credentials from the repo config when it first connects. However, using an alternative notifier, or overriding the repo's `init` function to retrieve the username and password dynamically, should work.

**Comment by lauriannala** [comment]
Yup, using `init`-function to set creds for default repo works fine. If one defines a separate repo module that is used by oban only this can be a quite clean solution.
