### ISSUE TITLE
Set max number of jobs a node will perform

### ISSUE THREAD

**Issue by LexMalta** [sorentwo/oban#595]
Apologies if there's already a way to do this and I just haven't found it!

### Is your feature request related to a problem? Please describe.

Our Oban jobs either push data downstream or read significant amounts of data from upstream APIs.
Each API we read/post to are hosted on different platforms, and have different performance characteristics.

Because of this, each API needs its own limit on the number of concurrent requests that can be performed at once.
We use Oban queues to do with with a setup that looks something like:
```
queues: [
  general: 30,
  API1: 5,
  API2: 10,
  API3: 1,
  API4, 5
]
```
This works well as a way of rate-limiting calls to external APIs, but it has the side-effect of causing up to 51 jobs to execute on one node at a time, which is too much.

We _could_ solve this problem by reducing the overall number for each queue, but our jobs are quite bursty, so we could end up in a situation where we have 100 API4 jobs backlogged (and nothing else), in which case we'd like to get through those jobs as quickly as possible.

### Describe the Solution You'd Like

The ability to set a maximum number of jobs that a node will execute at any one time. For example a queue definition could look like:

```
queues: [
  general: 30,
  API1: 5,
  API2: 10,
  API3: 1,
  API4, 5,
  max_limit: 30
]
```

In which case the number of jobs executing on a single node at once would be limited to 30, even if the queue definition would allow for 51 jobs to be queued.

**Comment by sorentwo** [comment]
Queues are isolated and unaware of other queues or how many jobs they are running. It isn't possible to build this into queues themselves, but you _could_ approximate it with a plugin and the `scale_queue` command. Writing a plugin within your application would allow you to scale specific queues up and down as needed.

**Comment by LexMalta** [comment]
Sorry, maybe my suggested solution is throwing things off a bit.
I don't think this needs to be built into queues or be made queue aware.

I'm not that familiar with the internals of Oban, I'm trying to read the codebase and wrap my head around everything that's in there, so apologies if my suggestion is dumb or doesn't make sense.

Would it be possible to do this with a GenServer and a change to the queue executor or drainer?

For example, maybe the config looks like:
```
config :myapp, Oban
  max_simultaneous_jobs: 30,
  queues: [
     ...
  ]
```

Then Oban could have a GenServer that keeps track of the total number of jobs currently executing. (e.g. the increments when a job is performing and decrements when a job is done)

Then the executor or drainer could check the number on that GenServer and if it would go above `max_simultaneous_jobs` wait for some time (e.g. 100ms) before trying again?

**Comment by sorentwo** [comment]
This could be possible if queue producers and engines were entirely rewritten. As you can imagine, that is rather  invasive and not something I’m inclined to do. What I suggest instead is a process (plugin) that you control that is aware of the various queues, can monitor their activity (check_queue) and scale them up/down as needed (scale_queue).

The tools are all there, it’s really a matter of building the plugin to manage it.

**Comment by LexMalta** [comment]
Makes sense!

Thank you so much for your time helping me out with this one :)
