### ISSUE TITLE
oban_web breaks mix dependency resolution

### ISSUE THREAD

**Issue by mtarnovan** [sorentwo/oban#601]
#### oban
oban 2.10.1
oban_pro 0.9.3
oban_web 2.7.1
#### elixir & erlang
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
Elixir 1.12.1 (compiled with Erlang/OTP 24)
#### hex
tried with both 1.0.1 and  0.21.0

We are currently using `oban_web` through the hex organisation, but we also tried switching to the self-hosted repo (and switching `mix.exs` to use `repo: "oban"` accordingly)
```bash
$ mix hex.repo list
Name        URL                             Public key                                          Auth key                          
hexpm       https://repo.hex.pm             <redacted>                                    
hexpm:oban  https://repo.hex.pm/repos/oban  <redacted> <redacted>
oban        https://getoban.pro/repo        <redacted> <redacted>
```

### Current Behavior

Hex dependency resolution fails, _unless_ we remove `oban_web` from `mix.exs`

For example:
```
$ mix deps.update mox
Resolving Hex dependencies...
The dependency resolver is taking more than 30 seconds. This typically happens when Hex cannot find a suitable set of dependencies that match your requirements. Here are some suggestions:

  1. Do not delete mix.lock. If you want to update some dependencies, do mix deps.update dep1 dep2 dep3

  2. Tighten up your dependency requirements to the latest version. Instead of {:my_dep, ">= 1.0.0"}, try {:my_dep, "~> 3.6"}

^C^C^C^C
```

```
$ git diff mix.exs
diff --git a/mix.exs b/mix.exs
index 87d9f5c3a..2763cd40c 100644
--- a/mix.exs
+++ b/mix.exs
@@ -120,8 +120,8 @@ defmodule Ypsilon.Mixfile do
       {:appsignal, "~> 2.2"},
       {:appsignal_phoenix, "~> 2.0.0"},
       {:oban, "~> 2.10"},
-      {:oban_pro, "~> 0.9", organization: "oban"},
-      {:oban_web, "~> 2.7", organization: "oban"},
+      {:oban_pro, "~> 0.9", repo: "oban"},
+      # {:oban_web, "2.8.2", repo: "oban"},
       {:sobelow, "~> 0.8", only: [:dev, :test]},
       {:broadway, "~> 0.6.2"},
       {:broadway_sqs, "~> 0.6.0"},

$ mix deps.update mox
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
 ...
Upgraded:
  mox 1.0.0 => 1.0.1
```

Please let me know if you need any other details about our environment

**Comment by sorentwo** [comment]
Do you happen to have a pinned version of Live View? The latest Oban Web release needs LV `~> 0.17.4`

**Comment by mtarnovan** [comment]
> Do you happen to have a pinned version of Live View? The latest Oban Web release needs LV `~> 0.17.4`

We don't depend on LV directly, the two libs that depend on it are `oban_web` and `phoenix_live_dashboard`; but thanks for the hint, I'll see if updating LV solves the issue.

**Comment by mtarnovan** [comment]
After further investigation, it doesn't look like this is a problem cause by `oban_web` specifically. Sorry for the noise. I'll close this for now
