### ISSUE TITLE
[Oban Web Doc] multiple dashboards guide is misleading

### ISSUE THREAD

**Issue by zillou** [sorentwo/oban#604]
### Environment

- Oban Web: 2.8.3

### Current Behavior

The code example about running multiple dashboards listed [here](https://hexdocs.pm/oban/web_installation.html#running-multiple-dashboards) is no longer working with the latest oban web

```elixir
scope "/" do
  pipe_through :browser

  oban_dashboard "/oban", oban_name: Oban, as: :oban_dashboard
  oban_dashboard "/oban/admin", oban_name: MyAdmin.Oban, as: :oban_admin_dashboard
end
```

All routes for `/oban/admin` will be route to the first oban dashboard `/oban/:page`

### Expected Behavior

```diff
  scope "/" do
    pipe_through :browser

-    oban_dashboard "/oban", oban_name: Oban, as: :oban_dashboard
     oban_dashboard "/oban/admin", oban_name: MyAdmin.Oban, as: :oban_admin_dashboard
+    oban_dashboard "/oban", oban_name: Oban, as: :oban_dashboard
  end
```

**Comment by sorentwo** [comment]
@zillou Are you sure you're running Oban Web v2.8.3? This issue was fixed between 2.8.2 and 2.8.3: https://hexdocs.pm/oban/web-changelog.html#v2-8-3-2021-12-19

**Comment by zillou** [comment]
Thanks for looking into this. I created a repo to demo this issue: https://github.com/zillou/multiple-oban-dashbards-demo, I set up 2 oban dashboards as the document suggested. However, if you visit http://localhost:4000/oban/admin , you still see the dashboard for the default oban. And if I switch the order of the 2 dashboards, I can get the expected behaviour.

I think the problem is about the phoenix router.

```
% mix phx.routes
      oban_dashboard_path  GET  /oban                                  Phoenix.LiveView.Plug :home
      oban_dashboard_path  GET  /oban/:page                            Phoenix.LiveView.Plug :index
      oban_dashboard_path  GET  /oban/:page/:id                        Phoenix.LiveView.Plug :show
oban_admin_dashboard_path  GET  /oban/admin                            Phoenix.LiveView.Plug :home
oban_admin_dashboard_path  GET  /oban/admin/:page                      Phoenix.LiveView.Plug :index
oban_admin_dashboard_path  GET  /oban/admin/:page/:id                  Phoenix.LiveView.Plug :show
```

vs 

```
 % mix phx.routes
Compiling 1 file (.ex)
oban_admin_dashboard_path  GET  /oban/admin                            Phoenix.LiveView.Plug :home
oban_admin_dashboard_path  GET  /oban/admin/:page                      Phoenix.LiveView.Plug :index
oban_admin_dashboard_path  GET  /oban/admin/:page/:id                  Phoenix.LiveView.Plug :show
      oban_dashboard_path  GET  /oban                                  Phoenix.LiveView.Plug :home
      oban_dashboard_path  GET  /oban/:page                            Phoenix.LiveView.Plug :index
      oban_dashboard_path  GET  /oban/:page/:id                        Phoenix.LiveView.Plug :show
```

**Comment by sorentwo** [comment]
OK, I see now. When `oban_dashboard` is first the router will see`/oban/admin` as if `admin` is a page. The route should either be `/admin/oban` or `/admin_oban` to prevent the routing issue.

**Comment by sorentwo** [comment]
@zillou Fixed! Thank you for the demo 💛
