### ISSUE TITLE
Public API for parsing Cron expressions 

### ISSUE THREAD

**Issue by fuelen** [sorentwo/oban#607]
I'd like to reuse a logic that is defined in `Oban.Cron.Expression.parse!` (actually, a desired API is a function without a bang). 
It would be great if this API is public, so I could rely on it without worrying that it can be changed/deleted in the future.

**Comment by sorentwo** [comment]
@fuelen There's very little chance of that API changing without any notice because Pro relies on it too. Anyhow, I've started on a non-bang `parse/1` and will get some skeletal docs in there to make it public.

**Comment by sorentwo** [comment]
@fuelen Please take a look at the linked commit. Sorry, it didn't make it into v2.11 😞
