### ISSUE TITLE
Status of the job in Web UI

### ISSUE THREAD

**Issue by fuelen** [sorentwo/oban#609]
Sorry for deleting a template of the issue. The request is to have an ability to set a progress bar and a status message to the job.
Similarly to https://github.com/kenaniah/sidekiq-status

**Comment by sorentwo** [comment]
There's a lot of functionality in that plugin. Can you be more specific about which feature you're looking for? Jobs already show a specific status in the detail view. Is this about displaying progress?

**Comment by fuelen** [comment]
> Is this about displaying progress?

Yes. What I'd like to see is a progress bar and a label which describes the current "subjob" of the job.
There is a screenshot in **Sidekiq Web Integration** section which shows this:
![image](https://user-images.githubusercontent.com/588762/147683984-e21e8f78-9867-4495-a7c2-6592c49ec081.png)
So, mentioned status/label is a text "Processing 1".

**Comment by sorentwo** [comment]
Hmm, I see. In Oban's case does this mean "subjob" within a Batch/Chunk/Workflow, or an arbitrary block of code?

**Comment by fuelen** [comment]
> arbitrary block of code

this

Use case: we periodically (cron) import data from 3rd-party service, which allows only a couple requests per second. It means, that the process can't be parallelized, because we'll have a lot of blocked requests.

**Comment by sorentwo** [comment]
I can envision Batch and Workflow status in the UI more easily than reporting on arbitrary blocks of code. Have you looked at rate limiting + batches for your situation?

**Comment by fuelen** [comment]
> Have you looked at rate limiting + batches for your situation?

Nope, previously we had a genserver which performed operation each X minutes. It was simply moved to Oban.Worker without considering alternative implementations.

**Comment by sorentwo** [comment]
@fuelen Please take a look at rate-limiting + batches and see if that fits your problem. If that works, you'll get visualization eventually, as batch and workflow visualization is on the roadmap for Web 🙂 

Otherwise, I'm not convinced that arbitrary sub-job progress is a good fit for Oban. Tracking progress would require updates to the job row as it executes because, unlike Redis, we can't write arbitrary keys to track changes.
