### ISSUE TITLE
Migration issue (on unreleased master)

### ISSUE THREAD

**Issue by eteubert** [sorentwo/oban#61]
Coming from #52 I switched deps to `{:oban, github: "sorentwo/oban"}` and added a migration file according to the Changelog:

```elixir
  def up do
    Oban.Migrations.up(version: 3)
  end

  def down do
    Oban.Migrations.down(version: 2)
  end
```

Migrating this fails because it does migrations for V2 and V3 and since I am already on V2 it fails with `** (Postgrex.Error) ERROR 42710 (duplicate_object) constraint "worker_length" for relation "oban_jobs" already exists`

I am at V2, which I verified by running the query in `Oban.Migrations.get_current/1` manually.

Looking at `Oban.Migrations.merge_defaults/1` I feel like you are off by one in the range because the first migration you want to run is the one _after_ the current one, right?

```diff
  defp merge_defaults(opts) do
    opts = Map.merge(@default_opts, Map.new(opts))
-   Map.put(opts, :range, get_current(opts.prefix)..opts.version)
+   Map.put(opts, :range, (get_current(opts.prefix)+1)..opts.version)
  end
```

**Comment by sorentwo** [comment]
@eteubert Great catch, thanks for the report. To prevent these issues from coming up again I've added an integration test for the migrations. Those have been a long time coming, as they were virtually impossible to do (cleanly) before prefix support was added.

Fixed with f75e5f2
