### ISSUE TITLE
Timeouts seem to prevent assertions verifying that exceptions are raised?

### ISSUE THREAD

**Issue by sparkertime** [sorentwo/oban#610]
### Environment

- Oban Version: Any Oban release from 2.7.0 onwards
- PostgreSQL Version: n/a
- Elixir & Erlang/OTP Versions (`elixir --version`) Elixir 1..13.1 / OTP 24

### Current Behavior

I created a repo https://github.com/sparkertime/oban_timeout_issue where I can reproduce what seems like strange behavior to me. Starting with Oban 2.7.0, if I define a timeout on my workers, then I cannot `assert_raise` on them any longer in tests.

In that repo, I define two workers - [one with a timeout](https://github.com/sparkertime/oban_timeout_issue/blob/main/lib/worker_with_timeout.ex) and [one without a a timeout](https://github.com/sparkertime/oban_timeout_issue/blob/main/lib/worker_without_timeout.ex). They are otherwise identical, they both immediately raise a `RuntimeError`.

### Expected Behavior

I would expect both to pass the same test which is defined [here](https://github.com/sparkertime/oban_timeout_issue/blob/main/test/oban_timeout_issue_test.exs)
```elixir
  test "worker without timeout raises an exception" do
    assert_raise RuntimeError, fn ->
      perform_job(WorkerWithoutTimeout, %{})
    end
  end

  test "worker with timeout raises an exception" do
    assert_raise RuntimeError, fn ->
      perform_job(WorkerWithTimeout, %{})
    end
  end
  ```
  
However, only WorkerWithoutTimeout is passing the test. I'm not an expert, but I think the error raised by `WorkerWithTimeout` is getting trapped in some fashion which prevents the ExUnit assertion from intercepting it.

AFAICT, this started in 2.7.0. I don't see anything obvious in the release notes though.

**Comment by sorentwo** [comment]
Thanks for the report, it prompted a proper fix for the "wrapped task" issue that I'd been thinking about lately. 💛

**Comment by sparkertime** [comment]
Wow! What a great way to start the new year, thank you so much for the timely fix!
