### ISSUE TITLE
DynamicCron paused state doesn't persist on restart

### ISSUE THREAD

**Issue by hassanRsiddiqi** [sorentwo/oban#618]
### Environment

- Oban Version
```
{:oban, "~> 2.10"},
{:oban_pro, "~> 0.9", repo: "oban"},
{:oban_web, "2.7.1", repo: "oban"}
```
- PostgreSQL Version
` {:postgrex, ">= 0.0.0"},`
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 22 [erts-10.7.2.13] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
```

### Current Behavior
```
config :backend, Oban,
  engine: Oban.Pro.Queue.SmartEngine,
  repo: Backend.Repo,
  queues: [events: 10],
  plugins: [
    {Oban.Pro.Plugins.DynamicPruner, mode: {:max_age, {2, :days}}}, {
    Oban.Pro.Plugins.DynamicCron,
    crontab: [
      {"* * * * *", Backend.Workers.CRFinder, name: "cr_finder",
    ]
  }
]
```
I'm modifying state at run time with
`{:ok, _} = Oban.Pro.Plugins.DynamicCron.update("cr_finder", paused: true)`
upon restart my local server the restored to default state.

### Expected Behavior
Job state should be persistent over server restart.

**Comment by sorentwo** [comment]
This is due to the combination of an upsert and a default pause value.
