### ISSUE TITLE
Oban.Migrations.down generates wrong range

### ISSUE THREAD

**Issue by eteubert** [sorentwo/oban#62]
When I'm on V2 and call `Oban.Migrations.down`, it should use a range of `2..1` but the current implementation generates `2..4`.

Possible implementation (tested):

```elixir
  def up(opts \\ []) when is_list(opts) do
    opts
    |> merge_defaults()
    |> put_range(:up)
    |> change(:up)
  end

  def down(opts \\ []) when is_list(opts) do
    opts
    |> merge_defaults()
    |> put_range(:down)
    |> change(:down)
  end

  defp merge_defaults(opts) do
    Map.merge(@default_opts, Map.new(opts))
  end

  defp put_range(opts, :up) do
    Map.put(opts, :range, (get_initial(opts.prefix) + 1)..opts.version)
  end

  defp put_range(opts, :down) do
    Map.put(opts, :range, get_initial(opts.prefix)..1)
  end
```

**Comment by sorentwo** [comment]
Another good catch, I missed that one. Your solution is close, but the `:down` migration still needs to respect a user supplied version. If it always rolled back to `1` then attempting to migrate down to `2` would mistakenly migrate to `1` and drop the `oban_jobs` table by mistake.

In f944b39 I've added a new test for the default versions used by up and down migrations. Thanks again 💛
