### ISSUE TITLE
Oban.Plugins.Stager plugin notification query efficiency for multi-node setup with large job queue

### ISSUE THREAD

**Issue by svistoi** [sorentwo/oban#620]
### Is your feature request related to a problem? Please describe.

I noticed this in 2.7.2, so I'm referencing some of that code, but I believe this may still work the same way in 2.10.1

Oban.Plugins.Stager plugin is [scheduled](https://github.com/sorentwo/oban/blob/8140eccf2ecab7286f5f9d9dc49c382ae2fb27d5/lib/oban/config.ex#L115) on every node running Oban, and therefore every node is [querying for available jobs](https://github.com/sorentwo/oban/blob/a406a5de72b8ecc1ab14718e8c41336a382e18e6/lib/oban/plugins/stager.ex#L128) every second by default.

This becomes a problem in setup where some nodes are meant to only schedule jobs https://github.com/sorentwo/oban/issues/82, and their count can get quite large, even though the worker pod count is much smaller.  In the end all nodes that run Oban are running the Stager plugin.

When the job queue gets large, and large portion of the jobs are in the `available` state, Postgres effectively scans the entire table (indexes are no longer relevant based on the query plan) at rate of X nodes/second.

### Describe the Solution You'd Like

A single cluster-wide `Stager.notify_queues` query execution.

### Describe Alternatives You've Considered

I wanted to confirm whether in addition to `queues: false` (https://github.com/sorentwo/oban/issues/82#issuecomment-543762609) on non-worker nodes, the following long delay for the stager works to mitigate the problem somewhat `Keyword.merge(config, queues: false, poll_interval: 2_629_746_000)`.  The multiple oban pods still issue the query at a high rate.

**Comment by sorentwo** [comment]
> A single cluster-wide Stager.notify_queues query execution.

Already done! As of #606 plugins, like the stager, will only run on the leader node.

> When the job queue gets large, and large portion of the jobs are in the available state, Postgres effectively scans the entire table (indexes are no longer relevant based on the query plan) at rate of X nodes/second.

Which version of Postgres are you running? On PG 12+ (I believe), the query planner is able to use the compound index and the query plan should look like this (ran on a production instance with ~1m jobs):

```
 Unique  (cost=0.42..2.05 rows=1 width=7) (actual time=0.052..0.053 rows=0 loops=1)
   ->  Index Only Scan using oban_jobs_state_queue_priority_scheduled_at_id_index on oban_jobs  (cost=0.42..2.05 rows=1 width=7) (actual time=0.052..0.052 rows=0 loops=1)
         Index Cond: ((state = 'available'::oban_job_state) AND (queue IS NOT NULL))
         Heap Fetches: 2
 Planning Time: 0.471 ms
 Execution Time: 0.090 ms
```

**Comment by svistoi** [comment]
Thanks for the quick reply, looking forward to upgrading to the new plugin.

Yeah weird it's not using any indices on mine.  Could be the older version, but I'm not seeing which index I'm missing even if I was on v2.10.1, and the query except for pg_notify still looks identical (except for minor `|> select([j], %{queue: j.queue})` difference)

Postgres 13, `pg_stat_statements` reports this query (still at 2.7.2):
```
SELECT pg_notify($1, json_build_object($2, s0."queue")::text) FROM (SELECT DISTINCT so0."queue" AS "queue" FROM "oban"."oban_jobs" AS so0 WHERE (so0."state" = $3) AND (NOT (so0."queue" IS NULL))) AS s0
```

I filled in the arguments to run analysis - don't think I messed those up enough to skip using index?
```
EXPLAIN ANALYZE SELECT pg_notify('oban.oban_insert', json_build_object('default', s0."queue")::text) FROM (SELECT DISTINCT so0."queue" AS "queue" FROM "oban"."oban_jobs" AS so0 WHERE (so0."state" = 'available'::oban.oban_job_state) AND (NOT (so0."queue" IS NULL))) AS s0;
                                                            QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------
 Subquery Scan on s0  (cost=9383.44..9383.50 rows=2 width=4) (actual time=1649.929..1649.994 rows=2 loops=1)
   ->  HashAggregate  (cost=9383.44..9383.46 rows=2 width=8) (actual time=1649.893..1649.922 rows=2 loops=1)
         Group Key: so0.queue
         Batches: 1  Memory Usage: 24kB
         ->  Seq Scan on oban_jobs so0  (cost=0.00..9122.88 rows=104225 width=8) (actual time=0.027..827.734 rows=120491 loops=1)
               Filter: ((queue IS NOT NULL) AND (state = 'available'::oban.oban_job_state))
               Rows Removed by Filter: 486
 Planning Time: 0.355 ms
 Execution Time: 1650.096 ms
```

The index seems to be from [v09](https://github.com/sorentwo/oban/blob/02fce6c3589cf4dcf22a3b620ed30d6e50e4bc86/lib/oban/migrations/v09.ex#L49).  I noticed your naming is a bit different based on name ordering `oban_jobs_state_queue_priority_scheduled_at_id_index`
```
CREATE INDEX IF NOT EXISTS oban_jobs_queue_state_priority_scheduled_at_id_index
    ON oban.oban_jobs USING btree
    (queue COLLATE pg_catalog."default" ASC NULLS LAST, state ASC NULLS LAST, priority ASC NULLS LAST, scheduled_at ASC NULLS LAST, id ASC NULLS LAST)
    TABLESPACE pg_default;
```

**Comment by sorentwo** [comment]
@svistoi Excellent point, the order of fields in the index created in v09 differs from the order within my database. At some point, about a year ago, I manually created a different index for profiling and didn't realize that it differed.

Would you be willing to swap (create and then drop) that index in your application (or in a staging environment) and share the query plan?

```elixir
create index(:oban_jobs, [:state, :queue :priority, :scheduled_at, :id], prefix: "oban")
drop index(:oban_jobs, [:queue, :state :priority, :scheduled_at, :id], prefix: "oban")

execute("vacuum analyze oban.oban_jobs")
```

**Comment by svistoi** [comment]
Thanks!  Confirm index only scan.

```
                                                                                             QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Subquery Scan on s0  (cost=0.42..6978.47 rows=2 width=4) (actual time=0.100..1931.994 rows=2 loops=1)
   ->  Unique  (cost=0.42..6978.43 rows=2 width=8) (actual time=0.073..1931.918 rows=2 loops=1)
         ->  Index Only Scan using oban_jobs_state_queue_priority_scheduled_at_id_index on oban_jobs so0  (cost=0.42..6605.76 rows=149067 width=8) (actual time=0.053..978.373 rows=149080 loops=1)
               Index Cond: ((state = 'available'::oban.oban_job_state) AND (queue IS NOT NULL))
               Heap Fetches: 0
 Planning Time: 0.115 ms
 Execution Time: 1932.069 ms
```

**Comment by sorentwo** [comment]
@svistoi Great, thanks for verifying that uses an index-only scan. I'm going to change the migration and provide a note about swapping the index in the next upgrade guide.
