### ISSUE TITLE
`Oban.Testing.perform_job` does not emit telemetry events for failed jobs

### ISSUE THREAD

**Issue by Efesto** [sorentwo/oban#622]
### Environment

- Oban Version: 2.10.1
- PostgreSQL Version: 10
- Elixir 1.13.1 (compiled with Erlang/OTP 24)

### Current Behavior

By invoking `perform_job` for a worker that fails with an exception, the telemetry event `[:oban, :job, :exception]` is not emitted

### Expected Behavior

By invoking `perform_job` for a worker that fails with an exception, the telemetry event `[:oban, :job, :exception]` is emitted

### Notes

I've checked the code and I see that is an explicit decision to let `perform_job` to raise the exception by setting the `safe` flag to `false`. https://github.com/sorentwo/oban/blob/main/lib/oban/testing.ex#L229
However, there might be scenarios in which one wants to test the correct emission of the expected telemetry events, for which setting the flag to `true` and letting the job proceed would be a preferable way.

`perform_job` is an extremely useful testing function because it allows the synchronous execution of a job, so also following the way of scheduling the job manually with `worker.new` would not be a good enough alternative.

I'd propose to allow the flag to be passed as `true` and skipping the assertion at https://github.com/sorentwo/oban/blob/main/lib/oban/testing.ex#L239. If for the maintainers the solution is acceptable I can proceed with a PR

**Comment by sorentwo** [comment]
@Efesto Nice catch on an edge case, and well-reported too! Fixed 👍
