### ISSUE TITLE
Add ability to configure telemetry_options

### ISSUE THREAD

**Issue by fuelen** [sorentwo/oban#628]
### Is your feature request related to a problem? Please describe.

We've disabled the default ecto logger in order to implement a custom one for development with some nice formatting features. But it logs Oban queries, which is not what we want. Currently, there is no way to distinguish regular queries from our app and queries from Oban in telemetry handler.

### Describe the Solution You'd Like

Add ability to configure `:telemetry_options` parameter here
https://github.com/sorentwo/oban/blob/79b1f17335ecaa8d873ed2aef70a2a359086e002/lib/oban/repo.ex#L209-L213

### Describe Alternatives You've Considered
--

### Additional Context
--

**Comment by sorentwo** [comment]
I'm remiss in adding a new config option specifically for Ecto, but I'm not sure how else to accomplish what you're requesting. Calling the field `telemetry_options` is misleading because one would assume it meant Oban telemetry options. I suppose we could prefix it with `ecto_telemetry_options`. However, that doesn't match `log`, which is also an Ecto option.

**Comment by fuelen** [comment]
Yes, I was thinking about `ecto_` prefix as well. Another option is not to make `:telemetry_options` configurable, but to hardcode it on a library level.

**Comment by sorentwo** [comment]
> Another option is not to make :telemetry_options configurable, but to hardcode it on a library level.

That's a nice option, but I worry it could be a breaking change for people that have metrics in place and expect that Oban is included in their general options.

Oban v2.10, which added customizable telemetry event prefixes, was retired immediately after release and superseded by v2.10.1. This is the note from the CHANGELOG:

> - [Oban.Telemetry] Remove the customizable prefix for telemetry events in favor of workarounds such as `keep/drop` in [Telemetry Metrics](https://hexdocs.pm/telemetry_metrics/Telemetry.Metrics.html#module-filtering-on-metadata)

From my understanding, Ecto's use of multiple prefixes is considered an anti-pattern now, but one that's engrained enough that they can't change it. Do you think a keep/drop mechanism could work in your situation?

**Comment by fuelen** [comment]
Sorry, I don't quite understand how `Telemetry.Metrics` and `keep/drop` can help here. The example by the link is using metadata, but this is what I actually need - something in metadata that indicates that the query is executed by Oban.

**Comment by sorentwo** [comment]
@fuelen That's a fair point—I suppose the only metadata that currently indicates it originates from Oban is the table name(s), and that requires scanning the entire query.

What do you think about hard-coding the current Oban configuration into all repo calls? That encompasses the prefix, node, instance name, etc. all in a single value:

```elixir
telemetry_options: [oban_name: %Oban.Config{...}]
```

**Comment by fuelen** [comment]
> What do you think about hard-coding the current Oban configuration into all repo calls? 

I'm happy with it :slightly_smiling_face:

**Comment by sorentwo** [comment]
@fuelen Done. This will be in the upcoming release.

**Comment by fuelen** [comment]
@sorentwo I noticed that not all queries have oban_conf in metadata.
Here are some metadata examples that I've caught:
```elixir
%{
  options: [],
  params: [],
  query: "commit",
  repo: MyApp.Repo,
  result: {:ok,
   %Postgrex.Result{
     columns: nil,
     command: :commit,
     connection_id: 22693,
     messages: [],
     num_rows: nil,
     rows: nil
   }},
  source: nil,
  type: :ecto_sql_query
}
```
```elixir
%{
  options: [],
  params: [],
  query: "begin",
  repo: MyApp.Repo,
  result: {:ok,
   %Postgrex.Result{
     columns: nil,
     command: :begin,
     connection_id: 22693,
     messages: [],
     num_rows: nil,
     rows: nil
   }},
  source: nil,
  type: :ecto_sql_query
}
```
```elixir
%{
  options: [],
  params: ["completed", ~U[2022-03-02 09:14:01.798351Z], 1196],
  query: "UPDATE \"public\".\"oban_jobs\" AS o0 SET \"state\" = $1, \"completed_at\" = $2 WHERE (o0.\"id\" = $3) RETURNING o0.\"id\", o0.\"attempted_by\"",
  repo: MyApp.Repo,
  result: {:ok,
   %Postgrex.Result{
     columns: ["id", "attempted_by"],
     command: :update,
     connection_id: 23520,
     messages: [],
     num_rows: 1,
     rows: [[1196, ["arch", "6dbe4be2-7f88-499b-8f8e-de3d798baf97"]]]
   }},
  source: "oban_jobs",
  type: :ecto_sql_query
}
```

**Comment by sorentwo** [comment]
@fuelen Those look like they are coming from `multi` blocks in Pro. Each call in a multi needs its own options because they aren't superseded by the `Repo.transaction` options.

I've created an issue to track this and will ensure that the next Pro release uses `telemetry_options` consistently.

**Comment by fuelen** [comment]
> Those look like they are coming from multi blocks in Pro. Each call in a multi needs its own options because they aren't superseded by the Repo.transaction options.

It may be a bug in Ecto.
