### ISSUE TITLE
At least once execution guarantee 

### ISSUE THREAD

**Issue by Zarathustra2** [sorentwo/oban#630]
### Is your feature request related to a problem? Please describe.

I would like to have an at least once job guarantee for cron jobs. So currently we have some jobs which we take longer
but only run not often per day - 1-2 times. If there is ever a downtime it can happen that the job never gets enqueued and as such never executes. It would be cool if `Oban` could have a guarantee that a job executes at least once in a given cron cycle. 

### Describe the Solution You'd Like

Let's take an example config:
```elixir
{"30 12 * * *", MyJob.SlowJob},
```

This job would execute at a fixed time of 12:30. If there is now a downtime between 11:30 - 13:30, the job would never execute as far as I understand. 

One solution would be on startup to check for each cron job that the job executed the last time it was supposed to execute: If there is no record of success in the table `oban_jobs` of the execution it would schedule immediately the job and execute it. 

Possible drawbacks:
- If a user adds a new job it would execute immediately as no previous record will be found

If would be awesome if this could be enabled per job.

### Describe Alternatives You've Considered

Another approach for users would be to run the job more often, so in my case:
```elixir
{"30 12 * * *", MyJob.SlowJob},
```
could be turned into
```elixir
{"30 * * * *", MyJob.SlowJob},
```

so that it executes every hour but in the job itself one can just check the DB table `oban_jobs` whether the job `MyJob.SlowJob` completed in the last 24H once. If that is the case, we can skip the actual job.

**Comment by sorentwo** [comment]
This is something I've thought about before, and I reached the same conclusion about the possible drawbacks. Another possible issue: what if the schedule changes?

Thankfully, it's already possible to do the alternative you're suggesting. Within the crontab entry you can override the uniqueness period, something like this:

```elixir
{"30 * * * *", MyJob.SlowJob, unique: [period: (12 * 60 * 60) - 1]}
```

That way the scheduler will attempt an insert every 30 minutes, but it will only succeed every 12 hours. Note that we're using 12 hours - 1 second to avoid a potential conflict.

If you're up for it, a PR to add this example to the documentation would be welcome 💛
