### ISSUE TITLE
Dynamic Pruner callback

### ISSUE THREAD

**Issue by milmazz** [sorentwo/oban#633]
### Is your feature request related to a problem? Please describe.

The Dynamic Pruner is a really useful plugin to keep the `oban_jobs` table as lean as possible, and it supports a bunch of rules and overrides which make it even cooler. But, I think that it would be nice to offer a callback before proceeding with the deletion. For example, you can store or transfer the records scheduled for deletion into cold storage or somewhere else.

### Describe the Solution You'd Like

A callback before proceeding with the deletion, that way you have the option to do something about those records, like put them into cold storage first.

### Describe Alternatives You've Considered

Currently, we're doing snapshots of the Oban tables using other mechanisms.

**Comment by sorentwo** [comment]
This is a great suggestion for the DynamicPruner. The basic pruner is intentionally limited, and I wouldn't consider adding more callbacks there. I've tagged this for future development 👍
