### ISSUE TITLE
Is the Repeater plugin still necessary if using the PG notifier?

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#642]
The docs seems unclear on this.

`Oban.Plugins.Repeater` states:

> This plugin is only necessary if you're running Oban in an environment where Postgres notifications don't work, notably one of:
>
> * Using a database connection pooler in transaction mode, i.e. pg_bouncer.
> * Integration testing within the Ecto sandbox, i.e. developing Oban plugins

I'd expect`Oban.Plugins.Repeater` isn't necessary when using `Oban.Notifiers.PG` but I don't see anything that confirms that.

If the repeater plugin isn't necessary when using the PG notifier then it might be helpful to document that.

**Comment by sorentwo** [comment]
That's a great point. No, the `Repeater` isn't necessary if you're using the PG notifier. A PR for docs would be appreciated!
