### ISSUE TITLE
Type "oban_job_state" does not exist after updating to Oban 2.11.0

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#643]
### Environment

- Oban Version: 2.11.0
- PostgreSQL Version: 13.3
- Elixir & Erlang/OTP Versions: Elixir 1.13.2, OTP 24.2.1

### Current Behavior

Getting the following error after updating to Oban 2.11.0 and running v11 migrations.

```
(Postgrex.Error) ERROR 42704 (undefined_object) type "oban_job_state" does not exist query: UPDATE "core"."oban_jobs" AS o0 SET "state" = (CASE WHEN o0."attempt" < o0."max_attempts" THEN 'available' ELSE 'discarded' END)::oban_job_state WHERE ((o0."state" = 'executing') AND (o0."attempted_at" < $1))
```

### Expected Behavior

The above error should not be occurring.

**Comment by sorentwo** [comment]
Did you run multiple migrations to get up to v11? If so, do you know where you started? 

The v11 migration only adds a new table, so that doesn’t seem like the culprit.

**Comment by anthonator** [comment]
We ran one migration for the v11 Oban migrations and then another migration for updating the indexes.  The most recent version of the migrations we were on was v10.

**Comment by anthonator** [comment]
Running the following query:

```
select n.nspname as enum_schema,  
       t.typname as enum_name,  
       e.enumlabel as enum_value
from pg_type t 
   join pg_enum e on t.oid = e.enumtypid  
   join pg_catalog.pg_namespace n ON n.oid = t.typnamespace;
```

Gives me the result:

```
      enum_schema       |   enum_name    | enum_value 
------------------------+----------------+------------
 core                   | oban_job_state | cancelled
 core                   | oban_job_state | discarded
 core                   | oban_job_state | completed
 core                   | oban_job_state | retryable
 core                   | oban_job_state | executing
 core                   | oban_job_state | scheduled
 core                   | oban_job_state | available
```

Does anything look off?

**Comment by sorentwo** [comment]
You’re using a prefix, right? Do you have multiple Oban tables?

**Comment by anthonator** [comment]
Yes, we are using a prefix. We have one Oban table in multiple prefixes.

**Comment by anthonator** [comment]
Is it possible the issue could be here.

```
ELSE 'discarded' END)::oban_job_state
```

Notice `oban_job_state` isn't prefixed.

**Comment by anthonator** [comment]
The issue went away after downgrading to 2.10.

**Comment by sorentwo** [comment]
Ah, it's from the change in the case statement in the engine. Working on a fix, should be out tomorrow.

**Comment by sorentwo** [comment]
To be clear, this is a bug in the basic lifeline plugin. You don't need to downgrade to v2.10, just stop using the basic Lifeline plugin until the bugfix is out.

(This bug doesn't exist in the DynamicLifeline plugin from Pro 😉)

**Comment by anthonator** [comment]
Got it. Thank you for jumping on this!

**Comment by anthonator** [comment]
Any updates on this? Anything I can do to help?

**Comment by sorentwo** [comment]
No updates yet. Typecasting to an enum within a namespace is oddly tricky. I'll figure it out eventually! In the meantime, there are two options:

* Stop using the Lifeline plugin (just like running on 2.10 or below)
* Use the DynamicLifeline from Pro

**Comment by anthonator** [comment]
We've disabled the `Lifeline` plugin for now.
