### ISSUE TITLE
Oban pro documentation lost some information

### ISSUE THREAD

**Issue by lauriannala** [sorentwo/oban#644]
2.11.0 docs have lost the section about how you should add oban repo locally: [https://hexdocs.pm/oban/2.11.0/pro_installation.html#prerequisites](https://hexdocs.pm/oban/2.11.0/pro_installation.html#prerequisites)

Old docs included this helpful information: [https://hexdocs.pm/oban/2.10.1/pro_installation.htm](https://hexdocs.pm/oban/2.10.1/pro_installation.html) - `Finally, run the following [mix hex.repo](https://hexdocs.pm/hex/Mix.Tasks.Hex.Repo.html) command:`

(Noticed also seemingly broken link on new docs: `[these instructions][oi]`)

**Comment by sorentwo** [comment]
Fixed and published. Thanks!
