### ISSUE TITLE
Multiple Instances of Oban in an Umbrella Application

### ISSUE THREAD

**Issue by keokilee** [sorentwo/oban#65]
Hi all,

We're already using Oban in one of our umbrella applications. We have another application in the umbrella that uses a separate database (and a separate Repo). I'm trying to add Oban to a second umbrella application, but the supervisor won't start since it's already started in the umbrella.

When I run our tests, this is the output:

```
** (Mix) Could not start application application_a: ApplicationA.Application.start(:normal, []) returned an error: shutdown: failed to start child: Oban
    ** (EXIT) already started: #PID<0.586.0>
```

Is there a better way to do this?

**Comment by keokilee** [comment]
Ah, never mind. Turns out it was in the Hexdocs.

**Comment by sorentwo** [comment]
Glad to see you found the docs about this :+1:

For anybody else that checks issues for this in the future: https://hexdocs.pm/oban/Oban.html#module-isolation

**Comment by keokilee** [comment]
Somewhat related, but the `id` option in the docs doesn't appear to work. I put `id: ObanA` into my test config and I get the following when I run the tests:

```
** (Mix) Could not start application application_a: ApplicationA.Application.start(:normal, []) returned an error: shutdown: failed to start child: Oban
    ** (EXIT) an exception was raised:
        ** (ArgumentError) unknown option provided {:id, ObanA}
            (oban) lib/oban/config.ex:158: Oban.Config.validate_opt!/1
            (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:769: Enum.each/2
            (oban) lib/oban/config.ex:52: Oban.Config.new/1
            (oban) lib/oban.ex:478: Oban.start_link/1
            (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
```

**Comment by sorentwo** [comment]
The config value for Oban would be `:name`, the `:id` is part of overriding the child spec. The syntax is wrong in the docs, it should be a three element tuple.

**Comment by sorentwo** [comment]
@keokilee I'v corrected the Isolation docs. The child spec(s) should look like this:

```elixir
Supervisor.child_spec({Oban, name: ObanA, repo: Repo}, id: ObanA)
```

**Comment by marinakr** [comment]
This `Supervisor.child_spec({Oban, name: ObanA, repo: Repo}, id: ObanA)` is not works
Code
app1 `Supervisor.child_spec({Oban, Application.get_env(:file_router, Oban)}, id: ObanFileRouter)`
app2 `Supervisor.child_spec({Oban, Application.get_env(:care_bridge_web, Oban)}, id: ObanCBWeb)`

Inspect which children: `[{ObanFileRouter, #PID<0.546.0>, :supervisor, [Oban]}]`
Error: `[{ObanFileRouter, #PID<0.546.0>, :supervisor, [Oban]}]`
