### ISSUE TITLE
New row for relation "oban_jobs" violates check constraint "attempt_range"

### ISSUE THREAD

**Issue by hzeus** [sorentwo/oban#652]
### Environment

- Oban Version: 2.11.0 (this version has been running in production for two days until the issue appeared)
- PostgreSQL Version: 13
- Elixir & Erlang/OTP Versions: Elixir 1.13.2 (via `elixir:1.13.2`-Docker image)

### Current Behavior

Hi, and thank you for your work on this amazing library!

We ran into an issue yesterday where the application continuously threw the following exception:

```
GenServer {Oban.Registry, {Oban, {:producer, "default"}}} terminating

Postgrex.Error: ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"

    table: oban_jobs
    constraint: attempt_range

Failing row contains (2698873, executing, default, OurWorkerName, {"id": 452757}, {}, 2, 1, 2022-02-25 13:27:55.324273, 2022-02-25 13:43:00, 2022-02-25 15:46:54.1617, 2022-02-25 13:43:00.27857, {application@ip-xx-x-xx-xxx}, null, 0, {}, {}, null).
  File "lib/ecto/adapters/sql.ex", line 760, in Ecto.Adapters.SQL.raise_sql_call_error/1
  File "lib/ecto/adapters/sql.ex", line 693, in Ecto.Adapters.SQL.execute/5
  File "lib/ecto/repo/queryable.ex", line 219, in Ecto.Repo.Queryable.execute/4
  File "lib/oban/queue/basic_engine.ex", line 124, in anonymous fn/4 in Oban.Queue.BasicEngine.fetch_jobs/3
  File "lib/ecto/adapters/sql.ex", line 1021, in anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  File "lib/db_connection.ex", line 1531, in DBConnection.run_transaction/4
  File "lib/oban/queue/engine.ex", line 230, in anonymous fn/2 in Oban.Queue.Engine.with_span/4
  File "/app/deps/telemetry/src/telemetry.erl", line 293, in :telemetry.span/3
  ```

The exception was thrown multiple times a second, and from both our application servers. Looking at other data, we think that other oban job were started during this time, but it seems that they also crashed (or were killed) as we can see that some HTTP requests were made from these jobs, but we did not process the answer.

When we noticed the error we first restarted the application server; however this did not solve the issue. We then deleted all rows from the `oban_jobs` table which stopped the error, and it has not appeared again since.

### Expected Behavior

Looking at the exception and the source code of `BasicEngine.fetch_job/3`, we assume that the actual error happened before and led to a situation where a row with `state="available"` and `attempt=max_attempts` was inserted or updated into `oban_jobs`; however we have not been able to find more information about this inside our logs - and probably this should not have happened.

Secondly, we think that such a state should not lead to the continuous errors which led to a partial outage of our application - maybe there should be some safeguard in `fetch_jobs/3`?

Please let us know if we can help you with this issue or if we should add more information to this.

**Comment by hzeus** [comment]
Wow, thank you for this incredibly fast and kind reply! Just to be sure that this was really a one off issue;  this is the timeline in which we ran the migrations:

* We installed Oban to our application in `v2.7.2` and ran the migrations via `Oban.Migrations.up()`. 
* We since updated Oban multiple times (most recently to `2.10.1` in November 2021), but we did not any migrations 
* We updated Oban to `2.11.0` on Tuesday, 2022-02-22 and ran the migrations as described in the [upgrade guide](https://hexdocs.pm/oban/v2-11.html) - from what we can see in the logs, running `Oban.Migrations.up(version: 11)` led to `create table if not exists public.oban_peers`; `ALTER TABLE public.oban_peers SET UNLOGGED` and `COMMENT ON TABLE public.oban_jobs IS '11'`  
* The error happened three days after running the migration (2022-02-25); and the row that led to the failure was also inserted on that day.

Do you see any migrations that we have been missing or should have done in the past; and does this timeline match your assumptions? Thanks again for taking your time!

Regarding the safeguard: This was just based on seeing this code snippet and we thought about some safeguard that would set the invalid row to some other failure state and prevent subsequent attempts - but we are totally aware that you know the internals of oban way better than we do.

**Comment by sorentwo** [comment]
Thanks for the follow up!

> The error happened three days after running the migration (2022-02-25); and the row that led to the failure was also inserted on that day.

That is an important bit of news. I’ve re-opened this issue for some more investigation.

**Comment by tomtaylor** [comment]
We're also seeing this issue. It's currently happening 700 times an hour on our system, starting 10am today. I think it's preventing one of our queues from running.

```
(Postgrex.Error ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"

    table: oban_jobs
    constraint: attempt_range
```

**Comment by tomtaylor** [comment]
Deleting the jobs associated with the blocked worker has fixed the queue and other jobs are now running correctly.

**Comment by sorentwo** [comment]
@tomtaylor Sorry to hear that you encountered this so many times. Can you share anything about the job(s)? One of the errors would really help.

I have a hunch that there's some edge case that's falling through the 'exhausted' check during execution, but I can't recreate it locally.

**Comment by tomtaylor** [comment]
Here's a bit of detail about the config:

```
 use Oban.Worker,
    queue: "obfuscated",
    unique: [period: 60 * 59, states: [:available, :scheduled, :executing]],
    max_attempts: 5,
    priority: 0
```

And a full stack trace:

```
Postgrex.Error: ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"

    table: oban_jobs
    constraint: attempt_range

Failing row contains (233232070, executing, adzuna, Obfuscated.Worker, {}, {"{\"at\": \"2022-02-27T10:01:24.405290Z\", \"error\": \"** (DBC..., 6, 5, 2022-02-27 10:00:00.372835, 2022-02-27 10:18:00.175518, 2022-02-27 19:32:30.449138, null, {server@127.0.0.1,256a3313-b279-49d4-8d40-833314de7e28}, null, 0, {}, {}, null).
  File "lib/ecto/adapters/sql.ex", line 760, in Ecto.Adapters.SQL.raise_sql_call_error/1
  File "lib/ecto/adapters/sql.ex", line 693, in Ecto.Adapters.SQL.execute/5
  File "lib/ecto/repo/queryable.ex", line 219, in Ecto.Repo.Queryable.execute/4
  File "lib/oban/pro/queue/smart_engine.ex", line 377, in Oban.Pro.Queue.SmartEngine.fetch_jobs/2
  File "lib/ecto/multi.ex", line 716, in Ecto.Multi.apply_operation/5
  File "lib/enum.ex", line 2396, in Enum."-reduce/3-lists^foldl/2-0-"/3
  File "lib/ecto/multi.ex", line 690, in anonymous fn/5 in Ecto.Multi.apply_operations/5
  File "lib/ecto/adapters/sql.ex", line 1021, in anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
```

This job doesn't fail often, but occasionally hits a timeout on the endpoint it uses and will retry.

**Comment by sorentwo** [comment]
@tomtaylor Do you know if the failure is from an exception or from a crashed process?

**Comment by howleysv** [comment]
To add another data point, we're seeing this too after updating to 2.11.0. We switched to the PG notifier as recommended in the migration guide for BEAM cluster deployments, so I wonder if that is related given that we got a single error from each node other than the one recorded in oban_jobs as being the attempter.

```
[error] GenServer {Oban.Registry, {Oban, {:producer, "queue_name"}}} terminating
** (Postgrex.Error) ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"
    table: oban_jobs
    constraint: attempt_range
Failing row contains (1118905, executing, queue_name, Worker, {args}, {}, 2, 1, 2022-02-28 14:45:02.378891, 2022-02-28 15:00:01, 2022-02-28 15:00:02.646795, null, {node2}, null, 0, {}, {}, null).
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:693: Ecto.Adapters.SQL.execute/5
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4
    (oban 2.11.0) lib/oban/queue/basic_engine.ex:124: anonymous fn/4 in Oban.Queue.BasicEngine.fetch_jobs/3
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4
    (oban 2.11.0) lib/oban/queue/engine.ex:230: anonymous fn/2 in Oban.Queue.Engine.with_span/4
    (telemetry 1.0.0) /home/semaphore/next/server/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
Last message: :dispatch
```

This is how that row looks in the db
```
SELECT * FROM oban_jobs WHERE id = 1118905;
-[ RECORD 1 ]+-----------------------------------------------------------------------------------------------------------
id           | 1118905
state        | completed
queue        | queue_name
worker       | Worker
args         | {args}
errors       | {}
attempt      | 1
max_attempts | 1
inserted_at  | 2022-02-28 14:45:02.378891
scheduled_at | 2022-02-28 15:00:01
attempted_at | 2022-02-28 15:00:02.071178
completed_at | 2022-02-28 15:00:03.338441
attempted_by | {node1}
discarded_at |
priority     | 0
tags         | {}
meta         | {}
cancelled_at |
```

**Comment by hzeus** [comment]
I'm not sure if this helps, but in @howleysv 's message I can see that the error comes a row that has been scheduled to 15 minutes in the future when it was inserted - this is the same in our case.

@sorentwo is there anything else that we might add to our logging that would help to understand the error if it occurred again? At the moment we have set our log level to info, but we could set it to debug to include any sql statements if this would help.

**Comment by sorentwo** [comment]
Scratch that...the updated row will always say "executing" because that's what fetching updates it to.

**Comment by sorentwo** [comment]
> is there anything else that we might add to our logging that would help to understand the error if it occurred again? At the moment we have set our log level to info, but we could set it to debug to include any sql statements if this would help.

@hzeus If you have logging enabled it would be very helpful to see all output for the failing job.

Some separate questions for everybody that's reported:

1. How many nodes are you running?
2. Are you using the SmartEngine?
3. Do you have a lifeline plugin running?

**Comment by howleysv** [comment]
>     1. How many nodes are you running?
3
>     2. Are you using the SmartEngine?
No
>     3. Do you have a lifeline plugin running?
Yes, added when I updated to 2.11

**Comment by sorentwo** [comment]
@howleysv Are you using a custom configuration for the lifeline plugin? Or is it using the default 60-minute time frame?

**Comment by howleysv** [comment]
I'm just using the default config

**Comment by tomtaylor** [comment]
> 1. How many nodes are you running?

2

> 2. Are you using the SmartEngine?

Yes


> 3. Do you have a lifeline plugin running?

Yes, `Oban.Pro.Plugins.DynamicLifeline`, with no provided config.

**Comment by hzeus** [comment]
> How many nodes are you running?

2. They are not connected to each other

> Are you using the SmartEngine?

No.

>Do you have a lifeline plugin running?

No. We are using the `Pruner` and `Cron` plugins

Regarding the logs: I do not have any more useful information for what happened last week, but I will increase the log level to hopefully find more information in case this happens again.

**Comment by sorentwo** [comment]
Thanks for all the info, that's really helpful.

**Comment by howleysv** [comment]
We're also just seeing some jobs get stuck in a state where they're `available` but also at their `max_attempts` threshold. This is causing an infinite loop of failed `fetch_jobs()` on each node.

```
SELECT * FROM oban_jobs WHERE id = 1120069;
-[ RECORD 1 ]+-----------------------------------------------------------------------------------------------------------
id           | 1120069
state        | available
queue        | queue_name
worker       | Worker
args         | {args}
errors       | {}
attempt      | 1
max_attempts | 1
inserted_at  | 2022-02-28 20:00:03.431923
scheduled_at | 2022-02-28 21:00:01
attempted_at | 2022-02-28 21:00:02.353965
completed_at |
attempted_by | {node1}
discarded_at |
priority     | 0
tags         | {}
meta         | {}
cancelled_at |
```

**Comment by nicolasblanco** [comment]
Hey folks.

I'm also getting this constraint exception on my pipeline with sporadic jobs rows that are `state = 'available'` and with `max_attempts = attempt`, even after completely cleaning the table.

I can also confirm that my own code is just inserting jobs, not touching any columns of the jobs table.

I have no more information that was not already provided in this issue.

Do you have an idea if temporary removing the constraint would help in avoiding the whole pipeline to hang?

**Comment by sorentwo** [comment]
> Do you have an idea if temporary removing the constraint would help in avoiding the whole pipeline to hang?

Yes, dropping the constraint will stop the error and prevent the pipeline from hanging.

I'm still investigating and working to recreate the issue. So far we know it can happen:

1. On a job with `max_attempts: 1`
2. There don't need to be any errors
3. The Lifeline plugin doesn't matter
4. The engine doesn't matter

**Comment by nicolasblanco** [comment]
I had jobs with `state = 'available'` and `max_attempts = attempt = 2`, cf. :

<img width="1611" alt="Screenshot 2022-02-26 at 21 36 59" src="https://user-images.githubusercontent.com/12682/156211641-d0bad09c-4f3f-49da-a828-30331d46944c.png">

**Comment by thbar** [comment]
Hi there! I've been conservatively postponing upgrading to 2.11.0 for now, and wondered if the issue is still present for various folks here?

**Comment by hzeus** [comment]
We have not run into this issue a second time; so I'm even not sure anymore if this was related to the version upgrade or a total coincidence.

**Comment by howleysv** [comment]
We rolled back to 2.10.1 since we encountered this issue, so nothing new to report

**Comment by sorentwo** [comment]
@howleysv Did that also include rolling back migrations? If so, can you share a description of your `oban_jobs` table? The full output of `\d+ oban_jobs` would be helpful.

**Comment by howleysv** [comment]
I looked at the v11 migration and concluded it wasn't going to be necessary to roll back since it was only additive changes. We had also made the recommended change to update the index on oban_jobs, and this was also left in place.

This is how our jobs table looks currently:
```
=> \d+ oban_jobs
                                                             Table "public.oban_jobs"
    Column    |            Type             | Collation | Nullable |                Default                | Storage  | Stats target | Description
--------------+-----------------------------+-----------+----------+---------------------------------------+----------+--------------+-------------
 id           | bigint                      |           | not null | nextval('oban_jobs_id_seq'::regclass) | plain    |              |
 state        | oban_job_state              |           | not null | 'available'::oban_job_state           | plain    |              |
 queue        | text                        |           | not null | 'default'::text                       | extended |              |
 worker       | text                        |           | not null |                                       | extended |              |
 args         | jsonb                       |           | not null | '{}'::jsonb                           | extended |              |
 errors       | jsonb[]                     |           | not null | ARRAY[]::jsonb[]                      | extended |              |
 attempt      | integer                     |           | not null | 0                                     | plain    |              |
 max_attempts | integer                     |           | not null | 20                                    | plain    |              |
 inserted_at  | timestamp without time zone |           | not null | timezone('UTC'::text, now())          | plain    |              |
 scheduled_at | timestamp without time zone |           | not null | timezone('UTC'::text, now())          | plain    |              |
 attempted_at | timestamp without time zone |           |          |                                       | plain    |              |
 completed_at | timestamp without time zone |           |          |                                       | plain    |              |
 attempted_by | text[]                      |           |          |                                       | extended |              |
 discarded_at | timestamp without time zone |           |          |                                       | plain    |              |
 priority     | integer                     |           | not null | 0                                     | plain    |              |
 tags         | character varying(255)[]    |           |          | ARRAY[]::character varying[]          | extended |              |
 meta         | jsonb                       |           |          | '{}'::jsonb                           | extended |              |
 cancelled_at | timestamp without time zone |           |          |                                       | plain    |              |
Indexes:
    "oban_jobs_pkey" PRIMARY KEY, btree (id)
    "oban_jobs_args_index" gin (args)
    "oban_jobs_args_index_ccnew" gin (args) INVALID
    "oban_jobs_args_index_ccnew1" gin (args) INVALID
    "oban_jobs_args_index_ccnew2" gin (args) INVALID
    "oban_jobs_meta_index" gin (meta)
    "oban_jobs_meta_index_ccnew" gin (meta) INVALID
    "oban_jobs_meta_index_ccnew1" gin (meta) INVALID
    "oban_jobs_meta_index_ccnew2" gin (meta) INVALID
    "oban_jobs_pkey_ccnew" UNIQUE, btree (id) INVALID
    "oban_jobs_pkey_ccnew1" UNIQUE, btree (id) INVALID
    "oban_jobs_pkey_ccnew2" UNIQUE, btree (id) INVALID
    "oban_jobs_state_queue_priority_scheduled_at_id_index" btree (state, queue, priority, scheduled_at, id) INVALID
Check constraints:
    "attempt_range" CHECK (attempt >= 0 AND attempt <= max_attempts)
    "positive_max_attempts" CHECK (max_attempts > 0)
    "priority_range" CHECK (priority >= 0 AND priority <= 3)
    "queue_length" CHECK (char_length(queue) > 0 AND char_length(queue) < 128)
    "worker_length" CHECK (char_length(worker) > 0 AND char_length(worker) < 128)
Triggers:
    oban_notify AFTER INSERT ON oban_jobs FOR EACH ROW EXECUTE FUNCTION oban_jobs_notify()
Access method: heap
```

The invalid indices seem suspicious.

**Comment by sorentwo** [comment]
@howleysv The `attempt_range` constraint is also still there in your database—I don't think this has to do with the upgrade to v2.11 itself.

> The invalid indices seem suspicious.

Indeed, they do.

That is a lot of `INVALID` indexes, which indicates there were [deadlocks or uniqueness violations](https://www.postgresql.org/docs/14/sql-createindex.html). I recommend running dropping the old indexes and rebuilding them, preferably with `REINDEX INDEX CONCURRENTLY` if you're on a PG 12+.

**Comment by howleysv** [comment]
> @howleysv The `attempt_range` constraint is also still there in your database—I don't think this has to do with the upgrade to v2.11 itself.

I think this constraint has been there a while though since it's part of the v10 migration.

> That is a lot of `INVALID` indexes, which indicates there were [deadlocks or uniqueness violations](https://www.postgresql.org/docs/14/sql-createindex.html). I recommend dropping the old indexes and rebuilding them, preferably with `REINDEX INDEX CONCURRENTLY` if you're on a PG 12+.

Yeah will do. I wouldn't expect missing indices to cause much of an issue since none of them are enforcing uniqueness, but I'm not certain.

**Comment by sorentwo** [comment]
> I think this constraint has been there a while though since it's part of the v10 migration.

That's true, but I've heard on more than one occasion that migrations didn't run when somebody expected them to.

> I wouldn't expect missing indices to cause much of an issue since none of them are enforcing uniqueness, but I'm not certain.

They still impact table performance since they're partially maintained on insert/update.

**Comment by oohnoitz** [comment]
This issue does seem sporadic. I had this same issue happen with records being left at `state = available` and `max_attempts = attempt`. It first happened about a month ago, and then stopped happening after a few days. 

My configuration matches some of the scenarios above:
- 3 nodes
- basic engine
- plugins: cron, lifeline

I only turned on the lifeline plugin about a week ago. The curious bit is that now I have records that are left at `state = discarded` and `max_attempts = attempt` that is returning the same error. The only way I was able to stop those errors was to increase the `max_attempts`.

**Comment by oohnoitz** [comment]
> Are you saying that the lifeline plugin was rescuing discarded jobs? It only looks for executing jobs to transition, so that would be very strange.

It might have been bad timing and jumping to conclusions too early when I went to check on those records that were throwing the error. I added some logging and we can confirm that we can ignore that comment I regarding the lifeline plugin.

**Comment by sorentwo** [comment]
Thanks for the details, everybody!

Without more data or evidence that this is, in fact, an ongoing problem after the v2.11 release and not something temporary from an upgrade/migration, there isn't anything I can do here.

If further evidence or examples emerge I'll reopen this issue.

**Comment by tomtaylor** [comment]
👍 this hasn't reoccurred for us

**Comment by epbarger** [comment]
I had this issue pop up a few weeks ago, and promptly updated to the newest version to get the fix. Unfortunately it just happened again today.

We're on version`2.11.3`. Job entry was entered today. Looks like the job completed successfully (`completed_at` was set), but the state did not get updated to `completed`. The job was set to max_attempts of 1, so on subsequent attempts the constraint failed since the state was still `available`.

Thanks for your work on this great library! Let me know if there are more details that would be helpful to have.

**Comment by sorentwo** [comment]
> We're on version2.11.3. Job entry was entered today. Looks like the job completed successfully (completed_at was set), but the state did not get updated to completed. The job was set to max_attempts of 1, so on subsequent attempts the constraint failed since the state was still available.

Hmm. That tells me that the job was completed (the state and timestamp are set in the same transaction), but something marked it otherwise afterward.

**Comment by epbarger** [comment]
> > We're on version2.11.3. Job entry was entered today. Looks like the job completed successfully (completed_at was set), but the state did not get updated to completed. The job was set to max_attempts of 1, so on subsequent attempts the constraint failed since the state was still available.
> 
> Hmm. That tells me that the job was completed (the state and timestamp are set in the same transaction), but something marked it otherwise afterward.

Interesting. To be clear, we don't have any other code that is intentionally touching the oban tables. The only plugin we're using is the Cron plugin, which creates the majority of our job entries

**Comment by mikeover** [comment]
I replied on another related issue at https://github.com/sorentwo/oban/issues/493#issuecomment-1122700764, I'm seeing this on Oban v2.12.0, Oban.Web v2.9.1

**Comment by swelham** [comment]
Hi

We also just saw this same error in our production app yesterday. We upgraded to the latest versions (see below) about 3 weeks ago, following the upgrade guide and applying the new migrations.

Versions:
Oban - 2.13.4
Oban Pro - 0.12.6
Oban Web - 2.9.5

Unfortunately, we didn't capture any additional logging or error info compared to what has been detailed above. But I can confirm deleting the job unblocked the queue.

Our main concern right now is can this issue reoccur.

**Comment by sorentwo** [comment]
@swelham What version(s) did you upgrade from?

**Comment by swelham** [comment]
@sorentwo We upgraded from and to the following versions.

Oban - 2.10.1 -> 2.13.4
Oban Pro - 0.9.3 -> 0.12.6
Oban Web - 2.8.1 -> 2.9.5

**Comment by sorentwo** [comment]
@swelham Your previous Oban version predated the fix. Please let us know if this comes up again now that you've upgraded.
