### ISSUE TITLE
Oban migrations doc improvements

### ISSUE THREAD

**Issue by thbar** [sorentwo/oban#655]
Opening an issue after discussing this with @sorentwo on Slack:

I wonder if there is an error in the upgrade guide at https://hexdocs.pm/oban/v2-11.html#run-oban-migrations-for-v11

The down states:

```elixir
 def down, do: Oban.Migrations.down(version: 11)
```

But then the doc states (https://hexdocs.pm/oban/Oban.Migrations.html#down/1):

> Run migrations down to a specified version:

Shouldn't we instead replace the "down to 11" to "whatever the previous version was" ?

Also, when Oban is first added to an app, instead of what's recommended here:

https://hexdocs.pm/oban/installation.html

```elixir
Oban.Migrations.up()
```

Shouldn't a precise version be passed explicitly here?

What makes me wonder is that if we run the whole migrations, the "past migration" without a parameter will actually create a different outcome (although it has no impact today).

**Comment by thbar** [comment]
It is also a bit unclear (but probably easy to figure out, I'll dig into the doc) what "migrations" version comes with a given Hex package version.

**Comment by thbar** [comment]
https://github.com/sorentwo/oban/issues/653 could also benefit from this.

**Comment by thbar** [comment]
I believe I have understood that the numbering scheme from the package is separate from the numbering scheme of the migrations.

For instance, here is the tag for Oban v2.7.2:

https://github.com/sorentwo/oban/tree/v2.7.2/lib/oban/migrations

where the migration up to 10 is seen.

Reading the changelog (https://github.com/sorentwo/oban/blob/main/CHANGELOG.md), mentions of that versioning is indeed appearing ^_^

**Comment by sorentwo** [comment]
The package numbering and the migration versions don't correlate. It's entirely coincidental that v2.11 had a v11 migration.
