### ISSUE TITLE
Error testing Workflow jobs via `Oban.Pro.Testing.process_job/2,3`

### ISSUE THREAD

**Issue by dballance** [sorentwo/oban#658]
### Environment

- Oban Version
  ```
  {:oban, "~> 2.11"},
  {:oban_pro, "~> 0.10.2"},
  {:oban_web, "~> 2.9.1"},
  
  # Test config
  config :myapp, Oban,
    prefix: "jobs",
    poll_interval: :timer.minutes(30),
    plugins: false,
    queues: false
  ```
- PostgreSQL Version
  ```
  PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1)
  ```

- Elixir & Erlang/OTP Versions (`elixir --version`)
  ```
  Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
  Elixir 1.13.2 (compiled with Erlang/OTP 22)
  ```

### Current Behavior

Testing workflow jobs does not seem to setup appropriate workflow ids and deps out of the box. Unsure if this is intended or not - but wanted to mention it.

I *must* pass a deps and workflow_id via a `meta` object or `process_job` will fail as the worker is executed.

If my test looks like: 
```
 assert {:ok, result} = process_job(
  MyWorkflow, 
  args
)
```
it will fail, but adding the appropriate meta keys will allow it to complete

```
 assert {:ok, result} = process_job(
  MyWorkflow, 
  args, 
  meta: %{"deps" => [], "workflow_id" => "foo"}
```

#### Stack
  ```
    1) test MyWorkflow.process/1 returns {:ok, result} if successful (MyApp.Test.MyWorkflowTest)
     test/my_workflow_test.exs:32
     ** (MatchError) no match of right hand side value: %{"recorded" => true, "structured" => true}
     code: assert {:ok, result} = process_job(MyWorkflow, args, meta: %{"recorded" => true, "structured" => true})
     stacktrace:
       (oban_pro 0.10.2) lib/oban/pro/workers/workflow.ex:269: Oban.Pro.Workers.Workflow.check_deps/2
       (oban_pro 0.10.2) lib/oban/pro/workers/workflow.ex:210: Oban.Pro.Workers.Workflow.maybe_process/3
       (core 0.1.0) lib/oban/pro/workers/workflow.ex:116: MyApp.MyWorkflow.perform/1
       (oban_pro 0.10.2) lib/oban/pro/testing.ex:24: Oban.Pro.Testing.process_job/3
       test/my_workflow_test.exs:40: (test)

  ```

### Expected Behavior

I think there are a few things here: 
1. The `process_job` method could automatically determine if the job is a Workflow worker and append these params, but this probably just hides the complexity of 2 below
2. Testing workflow workers may require additional documentation - and `process_job` may not be the best way to test them as there could be complex workflow dependency chains to establish to allow a job to process properly. Some insights or thoughts on how to properly test workflow processes that may query dependencies of the workflow would probably be useful.
3. `process_job` does not appear in docs - best I could tell.

**Comment by milmazz** [comment]
> and `process_job` may not be the best way to test them as there could be complex workflow dependency chains to establish to allow a job to process properly. Some insights or thoughts on how to properly test workflow processes that may query dependencies of the workflow would probably be useful.

Did you try inserting the jobs and then calling [`Oban.drain_queue/2`](https://hexdocs.pm/oban/Oban.html#drain_queue/2)? you probably want to include the options `with_recursion: true, with_safety:false, with_scheduled: true`.

Another way that you can try is using the "inline testing" approach suggested by Parker in his talk [Testing Oban Jobs From the Inside Out](https://www.youtube.com/watch?v=PZ48omi0NKU). I recently wrote an article about how you can test your workers with Oban, I describe a little bit the _inline testing technique_ there, you can find that article [here](https://milmazz.uno/article/2022/02/21/oban-testing-your-workers-and-configuration/) in case you're interested. HTH

**Comment by dballance** [comment]
@milmazz - we have not tried `drain_queue` as we have avoided running a full Oban instance during testing so far. But that time may come as we add tests to ensure the entire workflow is handled. 

The issue from the stacktrace is in the `check_deps` section of the workflow worker. 

Essentially - `process_job` uses `worker.new(opts)` and not `worker.new_workflow`. This leaves out the meta keys for the workflow job. 

Aside - we actually did read your post - as it's the best source of documentation here for these issues. No docs yet on the `oban_pro` doc side. I would almost propose that the `oban_pro` docs be pulled into this repo so they can be iterated / added by the community.

**Comment by sorentwo** [comment]
> Essentially - process_job uses worker.new(opts) and not worker.new_workflow. This leaves out the meta keys for the workflow job.

There has been a significant uptick in batch/workflow usage in the past month or two, especially an increase in people _testing_ batches/workflows. As a result, improved testing, and guides about testing, are a much higher priority now.

> Appreciate your effort here - as it's the best source of documentation here for process_job I think. No docs yet on the oban_pro doc side.

The lack of docs on `process_job` is somewhat purposeful because the module is half-baked—there isn't proper support for workflows, batch callbacks, etc.

> I would almost propose that the oban_pro docs be pulled into this repo so they can be iterated/added by the community.

We've considered pulling docs into the main Repo for this exact reason. However, we're switching from a "guides only" approach to a mixture of guides and module docs, and it's more effective to do that when the docs are colocated.

**Comment by dballance** [comment]
I should add - adding the appropriate meta keys does work. You also probably could instantiate a new workflow and utilize the `workflow_id` and and `deps` meta from that workflow job.

```
assert {:ok, result} =
   process_job(
     MyWorkflow,
     args,
     meta: %{
       "recorded" => true,
       "structured" => true,
       "deps" => [],
       "workflow_id" => "foo",
       "name" => "root"
     }
   )
```
