### ISSUE TITLE
Deployment doc links need updating

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#661]
![image](https://user-images.githubusercontent.com/18191/157145184-f49ae226-d241-4472-81cd-48b1367669fb.png)

- [ ] `Docker Images` :arrow_right: `[Docker Images](docker)`
- [ ] `Gigalixir` :arrow_right: `[Gigalixir](gigalixir)`
- [ ] `Heroku` :arrow_right: `[Heroku](heroku)`

**Comment by jc00ke** [comment]
![image](https://user-images.githubusercontent.com/18191/157147189-b35c4dc7-49fd-4746-aeeb-65d66482f6a9.png)

So maybe it's just the docs on getoban.pro?

**Comment by sorentwo** [comment]
All fixed. Thanks @jc00ke!
