### ISSUE TITLE
Recorded jobs fail to parse results in some scenarios

### ISSUE THREAD

**Issue by dballance** [sorentwo/oban#669]
### Environment

- Oban Version
  ```
  {:oban, "~> 2.11"},
  {:oban_pro, "~> 0.10.2"},
  {:oban_web, "~> 2.9.1"},
  
  # Test config
  config :myapp, Oban,
    prefix: "jobs",
    poll_interval: :timer.minutes(30),
    plugins: false,
    queues: false
  ```
- PostgreSQL Version
  ```
  PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1)
  ```

- Elixir & Erlang/OTP Versions (`elixir --version`)
  ```
  Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
  Elixir 1.13.2 (compiled with Erlang/OTP 22)
  ```

### Current Behavior

> Note: I think this is probably 100% "You're holding it wrong" and that is ok - but might help others if we add something to the docs about it.

Encoding / Decoding recorded results uses `:erlang.binary_to_term` and `:erlang.term_to_binary`. If you're building a recorded job that returns non-JSON encoded results to store (something like `%{hey: "you"}`, the above `:erlang` calls will happily and quite effectively parse those back and forth to atom based keys. 

We have our jobs in a "core" module but build all our repo queries in another module focused on persistence layer things. Dependencies are one way here - core depends on persistence but not the other way around.

So, in building a query to rollup workflow results in our persistence layer, we use `Oban.Pro.Utils.decode64` directly to decode the `return` value of the job. We use the "worker" string to find specific job types.

Here's where the edge case behavior creeps in. Because the Job hasn't yet been run on the cluster (it's a manually started job), the atoms contained within the Job haven't been loaded into memory. This means that `Oban.Pro.Utils.decode64` will fail until we run the job once and load those keys into memory.

We worked around this by passing an empty opts list to the decode method, but ONLY if an initial call raises. This allows us to log the job id so if we do ever encounter a production issue where the database has been corrupted we can recover by removing that job.

**However, this affects `oban_web` as well since it doesn't load job modules to decode the job results. If a job has not been executed in the VM atleast once, loading the detailed job view in `oban_web` also fails to decode. There isn't a workaround here that I can tell**

Some thoughts: 
- I don't expect this to ever happen with `MyJob.fetch_recorded` because the atom keys that are being stored *should* be in the module
- This **_could potentially_** be an issue if you have multiple versions of a job stored - and you've removed a key that was there previously?
- We do not want to JSON encode our results right now. Some of the results are `Ecto.Changeset` changes which contain tuples and aren't readily parsed to JSON. We want to show these changes to a user so they can understand what will change in the system if they apply the changesets.
- The `Oban.Web` usecase and error is probably what will drive any changes here.

### Expected Behavior

I think everything is okay - but a short warning in the docs about storing atom based keys might be helpful. 

I also think Web is the more likely the vector that most users may encounter this issue with.

**Comment by dballance** [comment]
Yep - I don't have a strong opinion on which way is best.

For the most part, if an actor has access to the production database to muck with these records, they probably could already take down the VM anyways....

**Comment by sorentwo** [comment]
> For the most part, if an actor has access to the production database to muck with these records, they probably could already take down the VM anyways....

My concern isn't that there is a real attack vector here, it's purely due to automated scanning tools flagging it as a liability. This has come up before from customer's professional audits and we can't backslide on it.
