### ISSUE TITLE
Custom timeouts and other opts in `Oban.insert_all/2`

### ISSUE THREAD

**Issue by pedro-gutierrez** [sorentwo/oban#671]
### Is your feature request related to a problem? Please describe.

This is a question, rather than a bug or a feature request.

### Describe the Solution You'd Like

At the moment, `Oban.insert_all/2` does not allow to pass specific options. Since this will ultimately call `Repo.insert_all/3`, I was wondering if it would make sense in the future to allow `Oban.insert_all/2` to accept certain customisation such as a `:timeout`?

### Describe Alternatives You've Considered

Not sure if this can be achieved with:

```elixir
Repo.transaction(fn ->
  Oban.insert_all(...)
end, timeout: my_custom_timeout)
```

**Comment by sorentwo** [comment]
This is indeed a missing feature and something we should support. It will require a coordinated change because it's part of the engine behaviour. I'll aim for putting in this change before unique `insert_all`.
