### ISSUE TITLE
Heroku OTP compatibility issue

### ISSUE THREAD

**Issue by ludwikbukowski** [sorentwo/oban#673]
Seems there is a bit of requirements conflict between whats suggested for Heroku and whats required.

Currently in the Oban Pro setup instructions, there is a [section dedicated to Heroku environment](https://hexdocs.pm/oban/pro_installation.html#authorizing-on-heroku). It suggests that it supports [Elixir buildpack](https://github.com/HashNuke/heroku-buildpack-elixir). The maximum version supported by buildpack is `23.3.2`(Elixir buildpack versions [here](https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions)). 
On the other heand, due to the Oban [docs](https://hexdocs.pm/oban/pro_installation.html#prerequisites) only Erlang/OTP `v23.3.4.5` and higher versions are supported (due to mentioned CA issue). Seems that the Elixir buildpack does not even support minimal version required by Oban Pro. However Heroku is still being mentioned as supported in docs.

What am I missing here?

**Comment by jaimeiniesta** [comment]
For the record, I'm running Oban Pro 0.10 in Heroku with these versions for the Elixir buildpack:

```
erlang_version=23.3.4.5
elixir_version=1.13.0
```

**Comment by ludwikbukowski** [comment]
Awesome great! thanks @jaimeiniesta

**Comment by sorentwo** [comment]
I can confirm that numerous apps run Web/Pro on Heroku with versions similar to what @jaimeiniesta reported 👍
