### ISSUE TITLE
Pro: def perform_job/3 defines defaults multiple times

### ISSUE THREAD

**Issue by zoedsoupe** [sorentwo/oban#675]
### Environment

- Oban Version: `2.11`
- Oban Pro Version: `0.10`
- PostgreSQL Version: `13.5`
- Elixir & Erlang/OTP Versions (`elixir --version`): `1.13.3 (compiled with Erlang/OTP 24)`

### Current Behavior

When I try to run tests, including jobs tests I receive this compile error:

```elixir
== Compilation error in file test/cobranca/installments_basis/jobs/kobana_billet_test.exs ==
** (CompileError) test/cobranca/installments_basis/jobs/kobana_billet_test.exs:3: def perform_job/3 defines defaults multiple times. Elixir allows defaults to be declared once per definition. Instead of:

    def foo(:first_clause, b \\ :default) do ... end
    def foo(:second_clause, b \\ :default) do ... end

one should write:

    def foo(a, b \\ :default)
    def foo(:first_clause, b) do ... end
    def foo(:second_clause, b) do ... end

    test/cobranca/installments_basis/jobs/kobana_billet_test.exs:3: (module)
    (elixir 1.13.3) lib/kernel/parallel_compiler.ex:455: Kernel.ParallelCompiler.require_file/2
    (elixir 1.13.3) lib/kernel/parallel_compiler.ex:348: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

And the specified line (3), ont he tests file has:

```
use Oban.testing, repo: Cobranca.Repo
```

I tried to debug `oban` and `oban_pro` source file but I only found one clause for `perform_job/3`

### Expected Behavior

Tests should be compiled and run without issues.

**Comment by sorentwo** [comment]
There is only one set of defaults defined for `perform_job/3`—otherwise the Oban test suite would fail!

Maybe you're importing or using the module multiple times?
