### ISSUE TITLE
Calling `Oban.cancel_job` causes dialyzer error 

### ISSUE THREAD

**Issue by Victoria91** [sorentwo/oban#676]
Hello, thanks for the library!

I'm getting dializer errors with  Oban "2.11.2" and Dialixir dialyxir  "1.1.0"
 
Example: 
```elixir
 def cancel_job(job_id) do
    Oban.cancel_job(job_id)
  end

```
produces

```
lib/file.ex:213:no_return
Function cancel_job/1 has no local return.
```

**Comment by sorentwo** [comment]
The `cancel_job` function works, passes dialyzer checks locally, and passes dialyzer checks from other applications. 

Maybe check the input you're passing to `cancel_job`? The signature expects a positive integer as the id, not a binary or a value like `0`.
