### ISSUE TITLE
Oban.Pro Issue querying for other workflow jobs from Workflow worker in test perspective

### ISSUE THREAD

**Issue by jmhossler** [sorentwo/oban#678]
### Environment

- Oban Version
```
* oban 2.11.2 (Hex package) (mix)
  locked at 2.11.2 (oban) 9eaf5db3
  ok
* oban_pro 0.10.2 (Hex package) (mix)
  locked at 0.10.2 (oban/oban_pro) b80492ec
  ok
* oban_web 2.9.1 (Hex package) (mix)
  locked at 2.9.1 (oban/oban_web) 9e63a3be
  ok
```
- PostgreSQL Version
`psql (13.6, server 10.17 (Debian 10.17-1.pgdg90+1))`
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.13.2 (compiled with Erlang/OTP 22)
```
### Current Behavior

I'n unsure if this is actually a bug, but I'm marking it as one just in case the behavior is unexpected. This could also be user error, but I'm unsure. I am trying to write tests for a workflow job that depends on the output of another workflow job (both are also recorded). The `process/1` implementation for this job essentially operates like this:

```
defmodule MyApp.ExampleWorkflowJob do
require Logger
use Oban.Pro.Workers.Workflow, recorded: true, queue: :default, structured: [keys: [:parent_job_name], required: [:parent_job_name]]

def process(job = %Job{args: %__MODULE__{parent_job_name: parent_job_name}}) do 
  with {:ok, [parent_job]} <- Repo.transaction(fn -> job |> stream_workflow_jobs() |> Stream.filter(&(&1.meta["name"] == parent_job_name)) |> Enum.to_list() end), # grabbing the parent job, and let's say in this case we expect one instance
        {:ok, result} <- fetch_recorded(parent_job) do
    Logger.info("doing something with parent job output: #{inspect(result)}")
    :ok
  end
end
```

In our tests, we set up the parent job and then execute the target workflow job (including it in the same workflow as the parent job).

```
use Oban.Testing, repo: MyApp.Repo, prefix: "jobs"
alias MyApp.Repo
alias MyApp.ExampleWorkflowJob

test "gets output of parent job and returns `:ok`" do
  parent_job_name = "some specific name"
  parent_workflow = ParentWorkflowJob.new_workflow()
                                 |> SomeWorkflowJob.add(parent_job_name, ParentWorkflowJob.new(%{}))
  
  for changeset <- parent_workflow.changesets do
    Repo.insert!(changeset, prefix: "jobs")
  end      
  
  assert :ok = perform_job(ExampleWorkflowJob, %{parent_job_name: parent_job_name}, meta: %{"deps" => [parent_job_name], "workflow_id" => parent_workflow.opts.workflow_id})
end
```

There might be some other issues here with how I'm setting up the other jobs, at least, their results. I know there isn't a result yet on the ParentWorkflow job for this test, but I'm getting an error even before that which I wouldn't expect. Our test config looks like this for oban:

```
config :core, Oban,
  prefix: "jobs",
  poll_interval: :timer.minutes(30),
  plugins: false,
  queues: false
```

The key part is that we are using the prefix `"jobs"` for our oban environment in test. However, when I run the test that looks like that, I get this error:

```
 ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.oban_jobs" does not exist

         query: SELECT o0."id", o0."state", o0."queue", o0."worker", o0."args", o0."meta", o0."tags", o0."errors", o0."attempt", o0."attempted_by", o0."max_attempts", o0."priority", o0."attempted_at", o0."cancelled_at", o0."completed_at", o0."discarded_at", o0."inserted_at", o0."scheduled_at" FROM "public"."oban_jobs" AS o0 WHERE (o0."meta" @> $1) ORDER BY o0."id"
```

Considering I set the prefix for the tests to "jobs", our testing config specifies oban jobs should live under the "jobs" prefix, and I inserted the job info into our repo under the prefix "jobs", I would expect this query (which I assume comes from inside the transaction where `stream_workflow_jobs` is called) to also use the prefix "jobs". 

Is there a better way to test workflow jobs that depend on output from other jobs in the same workflow? Do I need to pass additional information to the `perform_job` call to get that used? 

### Expected Behavior

I would expect `stream_workflow_jobs` to use the oban config and use the specified postgres table prefix instead of using the default "public".

**Comment by jmhossler** [comment]
I have attempted to set the config manually from the context of the job by adjusting the query in a couple ways, but neither have helped. I tried to specify the prefix in two ways, but neither had an effect:

```
Repo.transaction(fn -> job |> stream_workflow_jobs() |> Stream.filter(&(&1.meta["name"] == parent_job_name)) |> Enum.to_list() end)
```
modified to
```
Repo.transaction(fn -> job |> stream_workflow_jobs() |> Stream.filter(&(&1.meta["name"] == parent_job_name)) |> Enum.to_list() end, prefix: "jobs")
```
and
```
Repo.transaction(fn -> job |> stream_workflow_jobs(prefix: "jobs") |> Stream.filter(&(&1.meta["name"] == parent_job_name)) |> Enum.to_list() end)
```

The error was the same, though.

**Comment by sorentwo** [comment]
@jmhossler This was a tricky one! It came down to missing the `prefix` within the config injected by `perform_job`.
