### ISSUE TITLE
Set flag in query options to detect oban query

### ISSUE THREAD

**Issue by SteffenDE** [sorentwo/oban#687]
### Is your feature request related to a problem? Please describe.

We're using multi tenancy like in the following Ecto documentation: https://hexdocs.pm/ecto/multi-tenancy-with-foreign-keys.html
and we have the problem that oban queries fail as the repo `expected org_id or skip_org_id to be set`. For migrations there is a check for `:schema_migration`, but as far as I can see oban queries can currently only be detected by looking into the `:telemetry_options`.

### Describe the Solution You'd Like

I'd imagine oban setting a flag like `:oban` to true for oban queries (probably [here](https://github.com/sorentwo/oban/blob/0d4cf0f49ed2a4a0c5e2305f049d2d8320bb85f9/lib/oban/repo.ex#L209)). Adding a note to the documentation about this use case would be great.

### Describe Alternatives You've Considered

I tried adding a new repo module only for oban, but this is clumsy and seems to cause ecto sandbox errors when running tests.

### Additional Context

Currently, I check for `opts[:schema_migration] || get_in(opts, [:telemetry_options, :oban])` which works, but could probably break in the future.

**Comment by sorentwo** [comment]
Oban's `Repo` is a light wrapper around `Ecto.Repo`, and we're limited to the options that it supports. While `Ecto.Repo` might ignore an `oban: true` option now, they could be stricter about the options in a future release, and I don't want to break all of Oban's queries.

On the other hand, `telemetry_options` is officially supported to inject metadata into queries, and it's already used by Oban (as you noted.) You're safe to keep checking for a schema migration or in `telemetry_options`. Our use of `telemetry_options` is here to stay, but it could use some documentation.
