### ISSUE TITLE
Default Unique Period is not Documented

### ISSUE THREAD

**Issue by thiagopromano** [sorentwo/oban#692]
### Is your feature request related to a problem? Please describe.

After spending a long time trying to debug why we had two jobs that should have been unique running at the same time, we found out that if not set explicitly, the default field `period` in `unique` is set to 60 seconds.

Because this job takes more than one minute to execute, we started having two jobs running at the same time due to the `period` being implicitly set to 60 seconds.

### Describe the Solution You'd Like

This "default" unique period is not documented anywhere and 60 seconds seems like an odd choice as a default, if someone is setting the uniqueness fields and not setting the `period`, by default it should be `:infinity`, in other words, don't care about when was the job scheduled as long as it is unique.

To solve this either:

1. Change the default unique period in [here](https://github.com/sorentwo/oban/blob/0d4cf0f49ed2a4a0c5e2305f049d2d8320bb85f9/lib/oban/job.ex#L264), but this may change the behavior in someone's system; or
2. Explicitly document this behavior in the docs.

I personally think that the first option is the better one, I don't think anyone wants to have `period` implicitly set to 60 seconds.

### Additional Context

The use case is the following, we have a job that we want to debounce, the job uniqueness is set as:

```elixir
unique: [
      fields: [:worker, :args],
      states: [:scheduled, :available, :retryable]
    ]
``` 

And to insert a job:

```elixir
MyWorker.new(args,
          replace: [:scheduled_at],
          schedule_in: {10, :minutes}
        )
|> Oban.insert!()
```

The expected behavior is that, if someone tries to insert a job after one minute, the old job is postponed to exactly 10 minutes.

**Comment by sorentwo** [comment]
The default unique period is documented in the "Unique Jobs" section of the home page:

> The number of seconds until a job is no longer considered duplicate. You should always specify a period, otherwise Oban will default to 60 seconds. :infinity can be used to indicate the job be considered a duplicate as long as jobs are retained.

Thanks for the suggestion. Infinity may be more intuitive, but changing the default would be a breaking change and therefore a non-starter for 2.X.
