### ISSUE TITLE
Oban Pro Demo: Lag is greater than refresh rate causing the page to be unresponsive

### ISSUE THREAD

**Issue by sleepiejohn** [sorentwo/oban#695]
### Environment

Oban v2.12.0
Oban.Web v2.9.1
Oban.Pro v0.11.0

### Current Behavior

Opening the Pro demo page, there is the refresh rate interval selector, it currently is set to 1s.
From my location it happens to have a lot of lag from the network (20s for 30 hops on traceroute) which causes any click on the page to become unaccountable and nothing works, I believe it is because it is already waiting for the refresh from the server and a new request for refresh is put on the loop, mad clicking works

### Expected Behavior

The page should be responsive to better represent the software in the demo, I suggest a longer rate interval as default, maybe 15s like phoenix live dashboard.

**Comment by sorentwo** [comment]
@sleepiejohn Thank you for the report. The issue here isn't due to a slow refresh but a quirk with fly+replay+websockets. 

We've put a fix in place and the demo should be working properly now 💛
