### ISSUE TITLE
got "@impl Oban.Pro.Workers.Workflow" for function process/1 but this behaviour does not specify such callback

### ISSUE THREAD

**Issue by leandrocp** [sorentwo/oban#697]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

- Oban Version
oban, 2.12
oban_pro, 0.11
- Elixir & Erlang/OTP Versions (`elixir --version`)
erlang 24.3.3
elixir 1.13.4-otp-24

### Current Behavior

I'm getting the following warning:

```
warning: got "@impl Oban.Pro.Workers.Workflow" for function process/1 but this behaviour does not specify such callback. The known callbacks are:

  * Oban.Pro.Workers.Workflow.add/4 (function)
  * Oban.Pro.Workers.Workflow.all_workflow_jobs/2 (function)
  * Oban.Pro.Workers.Workflow.append_workflow/2 (function)
  * Oban.Worker.backoff/1 (function)
  * Oban.Pro.Worker.fetch_recorded/1 (function)
  * Oban.Pro.Workers.Workflow.gen_id/0 (function)
  * Oban.Worker.new/2 (function)
  * Oban.Pro.Workers.Workflow.new_workflow/1 (function)
  * Oban.Worker.perform/1 (function)
  * Oban.Pro.Worker.process/1 (function)
  * Oban.Pro.Workers.Workflow.stream_workflow_jobs/2 (function)
  * Oban.Worker.timeout/1 (function)
  * Oban.Pro.Workers.Workflow.to_dot/1 (function)
```

In a worker defined as:

```elixir
defmodule MyApp.MyWorkflow do
  use Oban.Pro.Workers.Workflow

  @impl Oban.Pro.Workers.Workflow # or just @impl Workflow
  def process(%Job{} = job) do
    ...
  end
end
```

### Expected Behavior

I'd expect to not see such warning. It was working as expected on Oban 2.10.1 and Oban Pro 0.9.3

**Comment by sorentwo** [comment]
In Pro v0.10 the `process/1` callback moved to `Oban.Pro.Worker` and workflows started to build off that. Somewhat annoyingly, Erlang doesn't allow overlapping behaviours and we had to remove the old `Oban.Pro.Workers.Workflow` callback.

Either switch to `@impl Oban.Pro.Worker` or `@impl true` to reference the correct callback.

**Comment by leandrocp** [comment]
Hi @sorentwo thanks for the feedback! So seems like the docs on https://getoban.pro/docs/pro/workflow.html needs a fix :)
