### ISSUE TITLE
Telemetry and testing questions

### ISSUE THREAD

**Issue by josevalim** [sorentwo/oban#7]
Hi @sorentwo,

Great work on the library! I am really glad to see a database-based library with this robust feature set. I have two quick questions (if there is a better place to post them, please let me know):

1. Regarding telemetry, we have been standardizing around the name `:duration` for the time measurement to execute something. So what do you think about replacing the current `%{timing: timing}` even in favor of `%{duration: timing}`? Other than that, thank you for using telemetry and help us push it as a standard in the community! 🎉 I also like how you structured the events around success and failure.

2. Regarding testing, sometimes I may actually want the jobs to run (for example, during integration tests) because they may do important work that is needed for the continuation of the testing. Is it possible to have a testing function that executes all of the jobs in a given queue? This way I can do some action and execute all enqueued jobs in the test before proceeding.

Thanks!

**Comment by LostKobrakai** [comment]
I just came here to ask about jose's second point as well. I'm looking into building a companion library, which (ab)uses Tasks to be able to yield the result of the Task to allow for e.g. http requests to respond with 200 if things happen in time and with 202 if things take longer than the http request shall wait.

**Comment by LostKobrakai** [comment]
I've managed to get it working with ecto sandbox in shared mode. What through me off a bit is that the options are a keyword list and it's pattern matched in the `init/1` of the supervisor. So you need to have the options in a certain order or they'll fail. Maybe better to convert things to a Map when using pattern matching.

```elixir
  setup %{module: module} do
    conf = Agent.get(Oban.Config, fn conf -> conf end)
    name = Module.concat([conf.name, "Queue"] ++ Module.split(module))
    queue = inspect(module)
    options = [conf: conf, queue: queue, limit: 2, name: name]
    {:ok, _} = start_supervised({Oban.Queue.Supervisor, options}, id: name)
    {:ok, queue: queue, name: name}
  end

  test "success", %{queue: queue, name: name} do
    // Do stuff

    stop_supervised(name)
  end
```

I couldn't get it to work however without shared mode because of a classic chicken/egg problem: Starting the queue supervisor does require the sandbox ownership to be set and the sandbox ownership seems to require the process to be running. This might need custom support in oban to allow for the sandbox setup to happen before running the first query. I also don't really like that the supervisor does need to be stopped in the `test/2`. It seems cleanup of `start_supervised` does happen only after the test process exists and therefore the sandbox ownership ceases to exist before the queue supervisor is stopped.

**Comment by josevalim** [comment]
@LostKobrakai right, that's why I proposed to have a function you can invoke that does the clean-up on the spot and serially, this way you don't have to worry about sandbox stuff, because you are always in the proper process.

**Comment by LostKobrakai** [comment]
Yeah something like `run_queue(queue)` would be quite cool.

Also as advertised above: https://github.com/LostKobrakai/omen

**Comment by sorentwo** [comment]
@josevalim Thank you for the kind words, I really appreciate it!

>     1. So what do you think about replacing the current `%{timing: timing}` even in favor of `%{duration: timing}`?

Changing it to `duration` is fine with me. The more we can standardize things around `telemetry` the better.

>     2\. Is it possible to have a testing function that executes all of the jobs in a given queue?

I love the idea of a function to drain the queue synchronously and from the current process. 👍

That's something I had wondered about and struggled with. Initially I thought about executing jobs within integration tests "inline", but that didn't account for sandbox issues either.

**Comment by sorentwo** [comment]
@LostKobrakai Awesome to see how you built off of Oban. Thanks for sharing the project. That is something I will definitely have use of so I'll be watching it 👍 

> What through me off a bit is that the options are a keyword list and it's pattern matched in the `init/1` of the supervisor. So you need to have the options in a certain order or it'll fail. Maybe better to convert things to a Map when using pattern matching.

That's a fair point, it is rather fragile. I considered everything inside the `Oban.Queue` namespace private, not expecting that anybody would try and build off of an individual queue supervisor. I'll take a look at switching to maps, or at least avoiding order dependency.

**Comment by LostKobrakai** [comment]
> That's a fair point, it is rather fragile. I considered everything inside the Oban.Queue namespace private, not expecting that anybody would try and build off of an individual queue supervisor. I'll take a look at switching to maps, or at least avoiding order dependency.

Sure. I only did so here to experiment with how testing could work. But just because it's internal doesn't mean it does not trip up someone working on internals :)

**Comment by sorentwo** [comment]
Closing with bc5679c4 and in favor of PR #8. Thanks for the suggestions! 👍
