### ISSUE TITLE
Job uniqueness depends on insertion order

### ISSUE THREAD

**Issue by fchabouis** [sorentwo/oban#704]
### Environment

- Oban Version : 2.10
- PostgreSQL Version : 14
- Elixir & Erlang/OTP Versions (`elixir --version`) : Elixir 1.13.3 (compiled with Erlang/OTP 24)

### Current Behavior

Here is a worker:

```elixir
defmodule Transport.Jobs.ObanTest do
  use Oban.Worker,
    unique: [period: 60]

  @impl Oban.Worker
  def perform(%Oban.Job{args: %{"field" => 1}}) do
    :ok
  end

  @impl Oban.Worker
  def perform(%Oban.Job{}) do
    :ok
  end
end
```

And the associated test:

```elixir
  test "oban job uniqueness" do
    %{}
    |> Transport.Jobs.ObanTest.new()
    |> Oban.insert()

    %{field: 1}
    |> Transport.Jobs.ObanTest.new()
    |> Oban.insert()

    assert jobs = all_enqueued()
    assert 2 == length(jobs)
  end
```
This test succeed, but the following fails (I'm changing the insertion order), as only 1 job is enqueued.
```elixir
  test "oban job uniqueness" do
    %{field: 1}
    |> Transport.Jobs.ObanTest.new()
    |> Oban.insert()

    %{}
    |> Transport.Jobs.ObanTest.new()
    |> Oban.insert()

    assert jobs = all_enqueued()
    assert 2 == length(jobs)
  end
```

### Expected Behavior

The doc is not explicit about how the unique feature should behave when an argument key is not present (that's why I was testing it :) ) so I don't know what is the expected behavior.

But I don't expect the "unique" feature to depend on the job insertion order.

**Comment by sorentwo** [comment]
Uniqueness _always_ depends on the insertion order, as it's checking the database for another matching job. This does expose an inconsistency in how empty args are treated, though. It looks like empty args are considered a match for the `field: 1` args, which isn't intuitive.
