### ISSUE TITLE
Job execution order

### ISSUE THREAD

**Issue by GPrimola** [sorentwo/oban#707]
### The need.

I need a way to setup something like a pipeline of jobs. 

For instance, when a job needs to be run only after the successful execution of another.
To ilustrate:

```mermaid
stateDiagram-v2
[*] --> Job_A
Job_A --> Job_B
Job_B --> Job_C
Job_B --> Job_D
Job_C --> Job_E
Job_D --> Job_E
Job_E --> [*]
```

### Solution You'd Like

What I think would be the best solution is something like:

```elixir
# job batch insertion

Ecto.Multi.new()
|> Oban.insert(:a, JobA.new(job_a_args)
|> Oban.insert(:b, fn %{a: job_a} ->
  JobB.new(job_b_args, after: job_a)
end)
|> Oban.insert(:c, fn %{b: job_b} ->
  JobC.new(job_c_args, after: job_b)
end)
|> Oban.insert(:d, fn %{b: job_b} ->
  JobD.new(job_d_args, after: job_b)
end)
|> Oban.insert(:d, fn %{c: job_c, d: job_d} ->
  JobE.new(job_e_args, after: [job_c, job_d])
end)
|> Repo.transaction()
```

It'd also be fantastic when a job ends with `{:ok, result}` the `result` could be passed on to the dependent jobs.

### Describe Alternatives You've Considered

A possible alternative would be to have a column to store the result of a successful job when it returns `{:ok, result}`, this way the dependent(s) job could be executing but put on `{:snooze, secs}` while the parent job is still executing.
To find the job, we could generate a `pipeline_id` as a job's arguments.

For instance (keep in mind the pipeline structure defined above)

```elixir
pipeline_id = UUID.generate()
job_a_args = Map.put(job_a_args, :pipeline_id, pipeline_id)
job_b_args = Map.put(job_b_args, :pipeline_id, pipeline_id)
job_c_args = Map.put(job_c_args, :pipeline_id, pipeline_id)
job_d_args = Map.put(job_d_args, :pipeline_id, pipeline_id)
job_e_args = Map.put(job_e_args, :pipeline_id, pipeline_id)

# job batch insertion goes here
```

Then on the worker we'd look for the pipeline id.

```elixir
defmodule MyApp.JobBWorker do
  def perform(%Job{args: %{"pipeline_id" => pipeline_id, ...}} = job_b) do
    case MyApp.Jobs.get(pipeline_id: pipeline_id, worker: MyApp.JobAWorker) do
      %{completed_at: nil} = _job_a ->
        {:snooze, 3}
      
      job_a ->
        do_perform(job_a, job_b)
    end
  end
end
```

### Contribution

I'd be glad to contribute with this feature, but I'm checking before to see if it's acceptable.

**Comment by sorentwo** [comment]
Thanks for inquiring! These features all exist in some form within Oban Pro.

Dependency based pipelines are called [Workflows](https://getoban.pro/docs/pro/workflow.html) and piped results are [Recorded](https://getoban.pro/docs/pro/worker.html#recorded-jobs) Jobs.
