### ISSUE TITLE
Version picker issues in Oban Pro/Web docs

### ISSUE THREAD

**Issue by michallepicki** [sorentwo/oban#709]
On https://oban.pro/docs/pro/overview.html there is a version picker with 0.10.2 version but clicking on it in Firefox causes a CORS issue in Firefox, and I think a 404 or something in Chrome. In general when loading the page, there is a javascript console log about failed loading for the docs_config.js file which should be used to provide the versions (I am guessing you modified the HTML by hand or something like that).

If you need help setting this up I should be able to help. There might have been some changes [since adding this feature to ex_doc](https://github.com/elixir-lang/ex_doc/pull/970), but I think the [docs](https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html#module-additional-javascript-config) should be up to date. Because the config is a JS file and not a JSON file, you should be able to debug it locally by opening HTML files from the static doc directories that are mirroring what's on your server.

**Comment by michallepicki** [comment]
The [default config path](https://github.com/elixir-lang/ex_doc/blob/main/lib/ex_doc/config.ex#L27) right now is `docs_config.js`. I think you could set it e.g. to `../docs_config.js` to have only one file for all versions in the parent directory. Docs for each version will need to be regenarted with this config value.

**Comment by michallepicki** [comment]
So I would probably not follow how hexdocs does it, but set the config path to a full URL, e.g. `https://oban.pro/docs/pro/docs_config.js`. Then you can simply have the file in one place.

To have "current" version without version in URL (if you want to do that, you could simply change the URLs, there probably are not that many of them floating around the internet) its doc files could be simply directly in the `pro/` directory, alongside the `docs_config.js` file and older versions directories. Then when there's a newer version, move them to a sub directory (and modify docs_config.js` appropriately)

**Comment by sorentwo** [comment]
Thanks for opening this issue and for all of the insight. We've been injecting the configuration into the generated docs, which clearly isn't sustainable or entirely accurate.

I'll follow up here with any questions when I can get started fixing it (it would be fantastic to have your help, but it's split between the private web and pro repos, as well as our private server repo).

**Comment by michallepicki** [comment]
Cool! FYI 0.10.2 docs load by default, not sure if that's intended

**Comment by sorentwo** [comment]
> FYI for the pro package 0.10.2 docs load by default, not sure if that's intended

No, that wasn't intended. Fixed now!

> And there's no way to switch from web https://oban.pro/docs/web/2.9.0/overview.html to 2.9.1

Also not intended and fixed now 🙂
