### ISSUE TITLE
Dequeue custom logic for jobs

### ISSUE THREAD

**Issue by sezaru** [sorentwo/oban#719]
### Is your feature request related to a problem? Please describe.

Right now, AFAIK, the dequeuing logic of Oban queues is FIFO, you can change this a little bit by adding a priority flag to the job.

Now, imagine that you have a queue that will have jobs added by direct request from the users of a system.

Let's say I have users A and B. User A adds 100 jobs to the queue, right after that, user B adds 1 job for that same queue. Also, let's say that each job takes around 1 minute to run, and for the sake of argument, the queue only has 1 worker.

This means that user B's job will only be executed after all the 100 jobs from user A are done, which would take more than 100 minutes in this case.

### Describe the Solution You'd Like

What I want to do is have a dequeue logic that would consider the number of jobs for a user is in the queue and dequeue jobs in a way that would distribute the queue in a more just way between the users.

An example logic could be something like, after dequeuing 5 jobs from user A, check if there is any other job from another user, and if so, deque a max of 5 jobs from that other user, if not, keep dequeuing more 5 jobs from user A.

Is something like this possible to be implemented (maybe via plugins?) in Oban? Or is there a better approach to handle scenarios like these?

**Comment by sorentwo** [comment]
> Right now, AFAIK, the dequeuing logic of Oban queues is FIFO, you can change this a little bit by adding a priority flag to the job.

It's FIFO aside from priority and scheduled_at timestamps.

> What I want to do is have a dequeue logic that would consider the number of jobs for a user in the queue and dequeue jobs in a way that would distribute the queue in a more just way between the users.

What you're describing is partitioning, which is available through rate-limiting in Pro's [SmartEngine](https://getoban.pro/docs/pro/smart_engine.html#partitioned-rate-limiting). Global concurrency partitioning is also underway, and we'll keep your use case of "fair" processing in mind.

> Is something like this possible to be implemented (maybe via plugins?) in Oban? Or is there a better approach to handle scenarios like these?

Plugins only insert (Cron), update (Lifeline), or delete (Pruner) jobs, they never execute them. Only queues execute jobs, and the dispatch logic is controlled by an Engine. The engine is pluggable, which is how the SmartEngine processes jobs differently.
