### ISSUE TITLE
Oban seems to be bringing down my application

### ISSUE THREAD

**Issue by axelson** [sorentwo/oban#72]
I think it happens when the database is unavailable. I see this error in our error monitoring service:
```
no match of right hand side value: {:error, %DBConnection.ConnectionError{message: "tcp connect (ec2-<db-ip>.compute-1.amazonaws.com:5432): connection refused - :econnrefused"}}
```

Which happens for: `"registered_name" => "Elixir.MyAppOban.Notifier.Conn"`

and there's also this at around the same time:
```
FATAL 57P01 (admin_shutdown) terminating connection due to administrator command
```
which happens for `"registered_name" => "Elixir.MyAppOban.Queue.Default.Producer"`

So far I've seen this on Heroku as well as locally. My suspicion is that when the database is inaccessible the `MyAppOban` is restarting fast enough to overwhelm `MyApp.Supervisor`.

**Comment by sorentwo** [comment]
After this was reported I asked @axelson a few questions on Slack and diagnosed the issue. There are cascading failures do to how the notifier manages its connection, and how the producers rely on establishing listeners on start up.

I have a set of sweeping fixes that I'm working on and aim to have them merged today.

**Comment by axelson** [comment]
Thanks for the update!

**Comment by sorentwo** [comment]
The fix turned out to be rather involved!

I think the resulting architecture is much cleaner though, processes are more isolated and far more resilient. Locally I can stop postgres entirely, watch the circuit breaker messages scroll by for a few minutes, then turn it back on and everything returns to normal after ~30 seconds.

**Comment by axelson** [comment]
@sorentwo Is it possible to get this in a new release soon? (and thanks for the quick fix!)

**Comment by sorentwo** [comment]
@axelson Absolutely. v0.10.0 is published now.

**Comment by axelson** [comment]
Great, thanks!
