### ISSUE TITLE
Workflows and job pruning

### ISSUE THREAD

**Issue by rrrcompagnoni** [sorentwo/oban#722]
### Is your feature request related to a problem? Please describe.

I had some issues with workflows that were difficult to identify at glance. Some jobs were missing in the workflow and the jobs were crashing in here:

```elixir
no case clause matching: %{}
lib/oban/pro/workers/workflow.ex:287
```

Taking a look at this note <https://getoban.pro/docs/pro/workflow.html#implementation-notes>. I could determine that our job pruner was deleting completed jobs before the next job execution and the workflow never completes, just like in the note advice.

This diagram may illustrate better the scenario:

```mermaid
graph LR

Workflow --> Job_1[Job_1 completed]

Job_1 --> Job_2[Job_2 snoozing]

Pruner --delete the job--> Job_1

Job_2 --job execution raise error--> Bad_State["no case clause matching: %{} workflow.ex:287"]
```

I have increased the pruner max-age policy to an age greater than my expectation to finish the workflow. That may reduce the risk of having upstream jobs deleted but I think it can help only when you know the workflow is going to finish.

The risk increases when you have snoozing jobs happening inside the workflow, especially those you can't determine how many snoozing attempts you are going to have.

You can define a strategy like

job max-age: 3 days
job snoozing: undetermined, keep snoozing

After 3 days with the workflow alive and some of the jobs snoozing, the job pruner will delete the upstream jobs, and the workflow never complete requiring manual intervention.

I can configure my snoozing strategy to not go over the pruner max-age time, but it requires implementing this strategy in every workflow I have with snoozing jobs. That's something I wish I could avoid.

### Describe the Solution You'd Like

Do you have a better strategy or ideas on how to avoid that kind of problem?

In that match clause error, would that be possible to make the error more specific? Something saying some dependency jobs are missing.

### Describe Alternatives You've Considered

Would that be possible in the future to have some override configuration in the job pruner to not delete jobs from uncompleted workflows?

### Additional Context

I'm using the dynamic pruner plugin.

Appreciate your time!

**Comment by sorentwo** [comment]
Thank you for the well-composed issue. This issue has recently come up a couple of times and deserves a proper fix. I think both of the solutions you've proposed are valid:

1. Modify the workflow query to handle a missing (deleted) dependency gracefully. For example, the answer could include a new option called `ignore_deleted`, which would match `ignore_discarded` and `ignore_cancelled`. It would stop the workflow from completing because of missing dependencies unless `ignore_deleted` were enabled.
2. Make the pruner "workflow aware" to prevent it from deleting dependences for in-progress workflows.

**Comment by sorentwo** [comment]
@rrrcompagnoni I only went with the first option of the two I listed (`ignore_deleted`). The bug is fixed along with an option that allows workflows to complete with missing dependencies.

Modifying the pruner to make it workflow/batch aware was too computationally expensive.
