### ISSUE TITLE
All peers can set lock using global

### ISSUE THREAD

**Issue by lud** [sorentwo/oban#724]
### Environment

- Oban Version 2.12.1
- PostgreSQL Version 13 and 14
- Elixir & Erlang/OTP Versions (`elixir --version`) Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Current Behavior

It looks like the `Oban.Peer.Global` modules attempts to acquire a lock with the key defined as this:

```
defp key(state), do: {:oban, state.conf.name}
```
On my machine, if I start two nodes, both can acquire the lock and both are `leader? == true`. If I understand correctly it is because with the default instance, the `LockRequesterId` passed to `global:set_lock/3` will be `{:oban, Oban}` on both nodes. As it is the same id in both nodes, :global will return true. I think that `{Oban, node()}` would work though (`{state.conf.name, node}`).

### Expected Behavior

Only one of two connected nodes can be the leader at the same time.

**Comment by sorentwo** [comment]
Nicely spotted. Fixed now 👍

**Comment by lud** [comment]
Cool thanks!
