### ISSUE TITLE
Oban.Testing.with_testing_mode :manual doesn't work with SmartEngine

### ISSUE THREAD

**Issue by dsdshcym** [sorentwo/oban#728]
### Current Behavior

https://github.com/sorentwo/oban/blob/4218b594c56fb4dbb4235e9fdd276748a1f9d45c/lib/oban/testing.ex#L389-L396

L392 defaults to BasicEngine

This means that I cannot test job results recording using `with_testing_mode :manual`

A workaround is to set `testing: :manual` in `config/test.exs`,
and use `with_testing_mode :inline` for other tests

### Expected Behavior

`with_testing_mode/2` should use the same `engine` config as other environments (prod, dev)

I'm setting `engine: Oban.Pro.Queue.SmartEngine` in `config/config.exs`

So I think changing L392 to something like below would work?
```elixir
    :manual -> Oban.Config.new().engine
```

But I'm not sure if it's the best fix, nor how to add a test for it
So I'm opening this issue instead of a PR

**Comment by sorentwo** [comment]
Closed with the linked commit.
