### ISSUE TITLE
Problem with unique period config

### ISSUE THREAD

**Issue by isavita** [sorentwo/oban#731]
### Environment

- Oban Version
**2.12.1**
- PostgreSQL Version
**PostgreSQL 13.5** 
- Elixir & Erlang/OTP Versions (`elixir --version`)
**Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]**
**Elixir 1.12.3 (compiled with Erlang/OTP 24)**

### Current Behavior
I have the following worker with **unique: [period: 82_800]**
```elixir
defmodule MyService.SendEmailWorker do
  use Oban.Worker,
    queue: :email,
    tags: ["email"],
    # unique for 23 hours
    unique: [period: 82_800],
    max_attempts: 12,
    priority: 3

  @impl Oban.Worker
  def perform(%{args: params}) do
     ...
  end
end
```
When I schedule the job as follow
```elixir
params = %{"user_id" => 42, "email" => "test@examlple.com"}
job = MyService.SendEmailWorker.new(params)
Oban.insert(job)
```
The job stays as completed in the postgres table `oban_jobs` only for ~ 1 minute after which I can schedule the job again.

### Expected Behavior
I would expect because of **unique: [period: 82_800],**  setting not to be able to schedule the job in the next 23 hours after schedule it and run it once.
Is this bug or I have something misconfigured?

**Comment by sorentwo** [comment]
How is your `Pruner` configured? To enforce uniqueness for 23 hours you need to retain historic jobs for at least 23 hours.

**Comment by isavita** [comment]
@sorentwo Thank you!!! 
I changed my config to and everything works as expected.
```elixir
config :my_service, Oban,
  repo: MyService.Repo,
  plugins: [{Oban.Plugins.Pruner, max_age: 82800}],
  queues: [email: 5]
```
