### ISSUE TITLE
Support default query option for multi tenancy with foreign keys

### ISSUE THREAD

**Issue by nallwhy** [sorentwo/oban#732]
### Is your feature request related to a problem? Please describe.

I made a repo following https://hexdocs.pm/ecto/multi-tenancy-with-foreign-keys.htm.
With that repo, `Oban` doesn't work because it can't be set up like `skip_org_id` options for the queries.
Bypass that problem, I made another repo and use this for `Oban`.

### Describe the Solution You'd Like

I default query option can be set up, another repo is not needed.

### Describe Alternatives You've Considered

-

### Additional Context

-

**Comment by sorentwo** [comment]
Making a dedicated Repo just for Oban, as you did, is the correct solution. Oban uses too many internal queries to accept a default option like that.

**Comment by nallwhy** [comment]
@sorentwo What about this way?

https://github.com/tompave/fun_with_flags#ecto-multi-tenancy

They added `:fun_with_flags` option to all queries by `FunWithFlags`.

**Comment by sorentwo** [comment]
@nallwhy Done! Now that I've seen how the options are passed through, I realize you can look for `telemetry_options: [oban_conf: _]` already. However, after the next release, you can look for `oban: true` instead 👍

**Comment by nallwhy** [comment]
@sorentwo OMG!! Thanks a lot!!!
