### ISSUE TITLE
Stager cannot access schemas/modules from app

### ISSUE THREAD

**Issue by atavistock** [sorentwo/oban#733]
### Environment

- Oban Version: **2.10**
- PostgreSQL Version:  **14.2, but have also seen this on our staging environment with 12.X**
- Elixir & Erlang/OTP Versions: 
  **Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]**
  **Elixir 1.13.4 (compiled with Erlang/OTP 24)**

### Current Behavior

We frequently get errors from the Oban Stager, which can go into a repeating cycle and eventually _**shutdown the BEAM VM**_.  We see this in dev, staging, and production environments

The error is (with app naming changed):
```
[error] GenServer {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Stager}}} terminating
** (UndefinedFunctionError) function MyApp.Partners.ensure_partner_in_query/2 is undefined (module MyApp.Partners is not available)
    (my_app 0.1.0) MyApp.Partners.ensure_partner_in_query(#Ecto.Query<from j0 in Oban.Job, join: j1 in subquery(from j0 in Oban.Job,
  where: j0.state in ["scheduled", "retryable"],
  where: not is_nil(j0.queue),
  where: j0.scheduled_at <= ^~U[2022-07-07 22:54:56.916124Z],
  order_by: [asc: j0.id],
  limit: ^5000,
  lock: "FOR UPDATE SKIP LOCKED"), on: j0.id == j1.id, update: [set: [state: ^"available"]]>, [telemetry_options: [oban_conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Queue.BasicEngine, get_dynamic_repo: nil, log: false, name: Oban, node: "devhost", notifier: Oban.Notifiers.Postgres, peer: Oban.Peers.Postgres, plugins: [Oban.Plugins.Pruner, Oban.Plugins.Stager], prefix: "public", queues: [default: [limit: 10], mailers: [limit: 20], sms: [limit: 20]], repo: MyApp.Repo, shutdown_grace_period: 15000, testing: :disabled}], prefix: "public", log: false])
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:203: Ecto.Repo.Queryable.execute/4
    (oban 2.12.1) lib/oban/plugins/stager.ex:114: anonymous fn/1 in Oban.Plugins.Stager.check_leadership_and_stage/1
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
    (oban 2.12.1) lib/oban/plugins/stager.ex:99: anonymous fn/2 in Oban.Plugins.Stager.handle_info/2
    (telemetry 1.1.0) ${user}/my_app/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
    (oban 2.12.1) lib/oban/plugins/stager.ex:98: Oban.Plugins.Stager.handle_info/2
    (stdlib 3.17.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :stage
State: %Oban.Plugins.Stager.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Queue.BasicEngine, get_dynamic_repo: nil, log: false, name: Oban, node: "devhost", notifier: Oban.Notifiers.Postgres, peer: Oban.Peers.Postgres, plugins: [Oban.Plugins.Pruner, Oban.Plugins.Stager], prefix: "public", queues: [default: [limit: 10], mailers: [limit: 20], sms: [limit: 20]], repo: MyApp.Repo, shutdown_grace_period: 15000, testing: :disabled}, interval: 1000, limit: 5000, name: {:via, Registry, {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Stager}}}}, timer: #Reference<0.20445475.433586179.159614>}
```

So...  I know where this is from.  In our project Repo we leverage the method `prepare_query` to ensure that schemas that require multi-tenancy include the partner id in a query.  In most cases that method returns the original query unaltered, only when the schema is a multi-tenant schema does anything get changed.

Our `repo.ex` looks like:
``` 
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :my_app,
    adapter: Ecto.Adapters.Postgres

  require Ecto.Query

  @impl Ecto.Repo
  def prepare_query(_operation, query, opts) do
    MyApp.Partners.ensure_partner_in_query(query, opts)
  end
end
```

So when the `Stager` runs, its loading our `MyApp.Repo` as it should, but then it cannot find `MyApp.Partners` presumably because is not loaded there.

### Expected Behavior

I expect it to be able to complete the scheduled jobs.  More importantly I really don't want it to ever crash the VM.

**Comment by sorentwo** [comment]
You see this from the stager, but it would apply to all other plugins. There isn't anything we can do about it in Oban, short of rescuing all exceptions and catching all exits for each plugin. That would cause visibility issues and hinder debugging (it is how the queue producers used to operate, which was the source of *much* confusion and bug reports).

There are three potential options to address your issue:

1. Ensure `MyApp.Partners` is available and loaded for each of your environments.
2. Use a separate, dedicated Ecto repo for Oban.
3. Make the Oban supervisor transient and let it crash entirely. That's not a great option, but it would prevent the rest of the application from crashing. `Supervisor.child_spec({Oban, oban_opts}, restart: :transient)`
