### ISSUE TITLE
Oban Web Demo Page refresh slower than interval

### ISSUE THREAD

**Issue by zbruhnke** [sorentwo/oban#737]
### Precheck

This has been reported here and you also reported putting in a fix but I did not see what it was or if it was a specific version, so I apologize in advance if this has already been answered - see the previous comment here: https://github.com/sorentwo/oban/issues/695#issuecomment-1108974224

### Environment

- Oban v2.12.1
- Oban.Web v2.9.2
- Oban.Pro v0.11.1
- PostgreSQL 10.8
- elixir 1.13.3-otp-24 
- erlang 24.3.4

### Current Behavior

The page is in a constant state of reloading meaning I cannot interact with it at all see video here https://go.hmb.la/F9aK36

### Expected Behavior

ability to interact with the page, I realize I could just try changing the default refresh rate but since the other ticket mentioned its a specific websocket problem I thought it might be worth learning what that was to see if something else might be wrong here as well in our deployment

**Comment by sorentwo** [comment]
There doesn't appear to be any load on the instance or connection issues that I can see. A few questions:

1. Where are you located?
2. What browser are you using?
3. Do you see any errors in the console or in the network tab?

**Comment by sorentwo** [comment]
The issue title says Web Demo, which doesn’t have any client configuration. Are you referring to a local installation of Oban Web?

**Comment by zbruhnke** [comment]
oh sorry I should not have left demo in the title, this is a server side installation of Oban

**Comment by zbruhnke** [comment]
I believe this is because we're using a custom path in or staging and production setups, locally this is working fine `/live` is responding without issue however in our staging environment we're forwarding all traffic to this port through `/admin` Phoenix live dashboard is connecting correctly using `/admin/live/websocket` but Oban is not and is instead failing to connect using `live/websocket`

**Comment by sorentwo** [comment]
> I believe this is because we're using a custom path in or staging and production setups, locally this is working fine /live is responding without issue however in our staging environment we're forwarding all traffic to this port through /admin Phoenix live dashboard is connecting correctly using /admin/live/websocket but Oban is not and is instead failing to connect using live/websocket

You can customize the path and other parts of the socket connection Oban Web uses: https://getoban.pro/docs/web/mounting.html#customizing-the-socket-connection

**Comment by zbruhnke** [comment]
That should do it I think, thank you for the quick responses!

**Comment by esambo** [comment]
I am experiencing this same _problem_ when using **Safari** (17.5 on macOS Sonoma 14.5). It _works_ just fine in **Google Chrome**.

- Oban Versions
  - oban: 2.17.12
  - oban_pro: 1.4.10
  - oban_web: 2.9.7
