### ISSUE TITLE
Allow for telemetry handlers to be associated with a specific Oban queue

### ISSUE THREAD

**Issue by carterza** [sorentwo/oban#739]
We have quite a bit of code that depends on Oban, and this code serves vastly different functions.

As we've gone with the recommended approach suggested by Oban for using telemetry to handle events and errors that arise during the execution of a job / workflow, we now have some telemetry handlers which handle all Oban events and all Oban errors respectively. We'd like to be able to further segregate these events and be able to do so by discriminating against which queue they arose from.

### Describe the Solution You'd Like

In the Oban telemetry configuration, where we can do something like:

`:telemetry.attach("oban-job-event", [:oban, :job, :stop], &Event.handle_event/4, nil)` we'd also like to be able to provide a queue name so something like :

`:telemetry.attach("oban-job-event", [:oban, :job, :my_queue_name, :stop], &Event.handle_event/4, nil)`

### Describe Alternatives You've Considered

Adding overloads in our handlers which pattern match on the specific type of event / error we'd like to handle.

**Comment by sorentwo** [comment]
Namespacing events is considered an anti-pattern (we did it briefly and then immediately reverted once the Telemetry metrics team learned of it). Your current approach of filtering within the handler is correct!
