### ISSUE TITLE
[Question] Chaining jobs

### ISSUE THREAD

**Issue by sweco-semtne** [sorentwo/oban#74]
Hi! 
Thanks for a great software!
I'm wondering on a pattern for chaining jobs, my use case is a file download from an FTP server and database imports of multiple files when the data has been downloaded. 
I was thinking on creating a job that does the file download and create a Task to check whether the file download has completed and that task enqueues a multiple import jobs. 
The problem I was seeing with that approach was what would happen if the Task fails for some reason? 
Any suggestions on the how a pattern like this should/could be implemented?

Br,
Mats

**Comment by sorentwo** [comment]
> I was thinking on creating a job that does the file download and create a Task to check whether the file download has completed and that task enqueues a multiple import jobs.

There isn't any need to make a separate task to do this, you can wait for the download to complete in the job itself. The job won't timeout, and you are guaranteed that it will run again if it gets killed by an error or during shutdown.

The issue I see here is in importing the downloaded files. If they are large you'll need to store them somewhere temporarily while you wait for them to be processed. Depending on the number of files, and the size, I'd _probably_ favor uploading them to something like S3 and then spawn a separate job for each of the downloaded files.

The second part of this could be considered a batch job, so this post may be helpful: [Oban Recipes Part 5: Batch Jobs](https://sorentwo.com/2019/09/17/oban-recipes-part-5-batch-jobs.html)

Note, in the future please use the Elixir Forum for these type of general pattern questions. That way you're more likely to get a quick response from other community members.
