### ISSUE TITLE
Unable to pull pro package

### ISSUE THREAD

**Issue by nodeit** [sorentwo/oban#749]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

- Oban Version 0.6.1
- PostgreSQL Version 13
- Elixir & Erlang/OTP Versions (`elixir --version`) 1.12.2

### Current Behavior

 > [build  8/17] RUN HEX_HTTP_CONCURRENCY=2 HEX_HTTP_TIMEOUT=120 mix do deps.get, deps.compile:
#17 1.302 Failed to fetch record for 'hexpm:oban/oban_pro' from registry (using cache instead)
#17 1.302 This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
#17 1.306 ** (Mix) Unknown package oban_pro in lockfile

### Expected Behavior

Should be able to pull oban pro from registry

**Comment by sorentwo** [comment]
It looks like you’re trying to pull from the old private hex repo, which was deprecated April 2021 and retired April 2022.

If you follow the [instructions to set up private hosting](https://getoban.pro/docs/pro/installation.html) you’ll be able to pull again!

**Comment by sineed** [comment]
We started to experience something similar in our CI recently:

```
#23 [fetch-elixir-deps 3/5] RUN --mount=type=secret,id=oban_key --mount=type=secret,id=oban_fp   mix hex.repo add oban https://getoban.pro/repo   --fetch-public-key $(cat /run/secrets/oban_fp)   --auth-key $(cat /run/secrets/oban_key)
#23 15.72 Downloading public key failed
#23 15.72 :timeout
```

It works well when running the same command from the local machine.

**Comment by sorentwo** [comment]
@sineed You're experiencing a different issue. The original report was for accessing the `hexpm:oban` repo, which isn't officially supported anymore.

**Comment by sineed** [comment]
I agree, the reason is different. I just thought it's not that great to create another issue as it might be something specific in my case (network issues, custom rate limits or something else).

Currently it randomly fails by timeout. Could you please explain what can be a reason of such unpredictable behavior? It was noticed a couple of weeks ago first time but it didn't happen again since today.

If there is nothing to tell on your end then it probably a network issue...

**Comment by sorentwo** [comment]
On our end, `public_key` responses are sub 100µs across the board, and we don't apply broad rate limiting. I suspect it is network related. I wish I could help more!
