### ISSUE TITLE
The key type of job args field may not be the same

### ISSUE THREAD

**Issue by oo6** [sorentwo/oban#756]
### Environment

- Oban Version
  - oban: 2.13.1
  - oban_pro: 0.12.3
- PostgreSQL Version
  14.4
- Elixir & Erlang/OTP Versions (`elixir --version`)
  - Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
  - Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Current Behavior

According to the following steps:

1. use `Oban.Engines.Basic`
2. add worker
```elixir
defmodule MyApp.Worker do
  use Oban.Pro.Worker,
    queue: :default,
    unique: [period: :infinity]

  def process(_job) do
    :ok
  end
end
```
3. insert job, the return job args is string key
```elixir
iex(1)> MyApp.Worker.new(%{id: 1}) |> Oban.insert()
{:ok,
 %Oban.Job{
   __meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">,
   args: %{"id" => 1},
   attempt: 0,
   attempted_at: nil,
   attempted_by: nil,
   cancelled_at: nil,
   completed_at: nil,
   conf: nil,
   conflict?: false,
   discarded_at: nil,
   errors: [],
   id:1,
   inserted_at: ~U[2022-08-11 09:47:14.622326Z],
   max_attempts: 20,
   meta: %{"uniq_key" => 26161549},
   priority: 0,
   queue: "default",
   replace: nil,
   scheduled_at: ~U[2022-08-11 09:47:14.622326Z],
   state: "available",
   tags: [],
   unique: nil,
   unsaved_error: nil,
   worker: "MyApp.Worker"
 }}
```
4. insert job with same args, the return job args is atom key.
```elixir
iex(2)> MyApp.Worker.new(%{id: 1}) |> Oban.insert()
{:ok,
 %Oban.Job{
   __meta__: #Ecto.Schema.Metadata<:built, "oban_jobs">,
   args: %{id: 1},
   attempt: 0,
   attempted_at: nil,
   attempted_by: nil,
   cancelled_at: nil,
   completed_at: nil,
   conf: nil,
   conflict?: true,
   discarded_at: nil,
   errors: [],
   id: 1,
   inserted_at: nil,
   max_attempts: 20,
   meta: %{:uniq_key => 26161549},
   priority: 0,
   queue: "default",
   replace: nil,
   scheduled_at: nil,
   state: "available",
   tags: [],
   unique: %{
     fields: [:args, :queue, :worker],
     keys: [],
     period: :infinity,
     states: [:scheduled, :available, :executing, :retryable, :completed]
   },
   unsaved_error: nil,
   worker: "MyApp.Worker"
 }}
```

The result of `insert_all` with `Oban.Pro.Queue.StartEngine` is also the same as above.

### Expected Behavior

Returns consistent job args field regardless of conflict.
I'm not sure the job unique field should also be consistent?

**Comment by sorentwo** [comment]
The type spec for `args` is `map()`, with no mention of the key type. Encoding and decoding args through `Jason` would make the return type consistent, but I'm hesitant to do that purely for consistent results from unique jobs. Stringifying the return type could be a breaking change for some applications too.

Additionally, the `unique` field is virtual and an implementation detail that you shouldn't rely upon.
