### ISSUE TITLE
Cannot rely on callbacks when using the `:structured` option

### ISSUE THREAD

**Issue by caioeps** [sorentwo/oban#757]
### Environment

- Oban Version
```
* oban 2.12.1 (Hex package) (mix)
  locked at 2.12.1 (oban) 9b1844c2
* oban_pro 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (oban/oban_pro) 53a4d5df
* oban_web 2.9.1 (Hex package) (mix)
  locked at 2.9.1 (oban/oban_web) 9e63a3be
* opentelemetry_oban 0.2.0-rc.5 (Hex package) (mix)
  locked at 0.2.0-rc.5 (opentelemetry_oban) 34b91e44
```

- PostgreSQL Version

```
postgres:12.5-alpine
```

- Elixir & Erlang/OTP Versions (`elixir --version`)

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
```

### Current Behavior

Composing `BatchWorker` with `structured` results in callback events not being issued.

```elixir
# lib/oban.ex
defmodule Workers.StructuredFoo do
  use Oban.Pro.Workers.Batch, max_attempts: 5, structured: [keys: [:ids], required: [:ids]]

  @impl Batch
  def process(%Job{args: %__MODULE__{ids: ids}}) do
    {:ok, Enum.sum(ids)}
  end

  @impl Batch
  def handle_exhausted(%Job{} = job) do
    IO.inspect(job)
    IO.inspect("Exhausted")

    :ok
  end
end

defmodule Workers.Foo do
  use Oban.Pro.Workers.Batch, max_attempts: 5

  @impl Batch
  def process(%Job{args: %{"ids" => ids}}) do
    {:ok, Enum.sum(ids)}
  end

  @impl Batch
  def handle_exhausted(%Job{} = job) do
    IO.inspect(job)
    IO.inspect("Exhausted")

    :ok
  end
end
```

Enqueueing jobs:
```elixir
Enum.chunk_every(0..200, 50)
|> Enum.map(fn batch -> %{"ids" => batch} end)
|> Workers.Foo.new_batch()
|> Oban.insert_all()

Enum.chunk_every(0..200, 50)
|> Enum.map(fn batch -> %{"ids" => batch} end)
|> Workers.StructuredFoo.new_batch()
|> Oban.insert_all()
```

Verify that there is a handle_exhausted event for `Workers.Foo` but not for `Workers.StructuredFoo`.

### Expected Behavior

An exhausted callback event should have been issued for the structured worker.

**Comment by sorentwo** [comment]
This is trickier than it may seem because the expected behavior isn't apparent. The problem is that callbacks are just jobs with some extra `meta` and run through `process/1` just like a regular job.

The only workaround for avoiding this error is to skip `structured` for callback handlers. That works, but you wouldn't be able to enforce keys in the `handle_` callbacks and would be back to string keys.

The best alternative I can think of is to document, and potentially enforce, using a different worker for batch callbacks when `structured` is in use. WDYT?

**Comment by davidarmstronglewis** [comment]
Oh! The callback worker is re-using the Batch worker type inserted to schedule the callback for.

You can confirm this by running the following which can override the args given to the callback worker.
```elixir
Enum.chunk_every(0..200, 50)
|> Enum.map(fn batch -> %{"ids" => batch} end)
|> Workers.StructuredFoo.new_batch(batch_callback_args: %{"ids" => nil})
|> Oban.insert_all()
```

Or, like @sorentwo suggests, you can override the worker used to run the callback like this:
```elixir
Enum.chunk_every(0..200, 50)
|> Enum.map(fn batch -> %{"ids" => batch} end)
|> Workers.StructuredFoo.new_batch(batch_callback_worker: Workers.Foo)
|> Oban.insert_all()
```

I love that you can override the job used but I think the docs could be a bit clearer on this behavior.

From the docs:
> After jobs in the batch are processed the BatchManager may insert callback jobs for the same worker.

**Comment by sorentwo** [comment]
@caioeps @davidarmstronglewis Any feelings about whether documentation is enough here?

**Comment by caioeps** [comment]
Thank you for stepping in, @sorentwo ! Maybe documentation should be enough for now but if the solution may be too complex, doing this should be a must in the future IMO

> The best alternative I can think of is to document, and potentially enforce, using a different worker for batch callbacks when structured is in use. WDYT?

Would raising an informative error be enough for now?

**Comment by sorentwo** [comment]
> Would raising an informative error be enough for now?

There isn't a clear place that I can see to raise an error. I'll investigate a little more and see if there is a place to give more guidance.

**Comment by sorentwo** [comment]
@caioeps Please see the linked commit message for the chosen solution.
