### ISSUE TITLE
Pool vs DynamicSupervisor

### ISSUE THREAD

**Issue by anthonator** [sorentwo/oban#76]
I think it would be helpful to spell out whether queues use a pool of processes or create processes on-demand. That may change the approach people take when deciding how big they want their queues to be.

**Comment by sorentwo** [comment]
Interesting, I'm curious how the mechanism for running processes would change the number of concurrent processes people want to run. Either way there is a guarantee that a queue will run at _most_ `N` concurrent jobs in `N` separate processes.

FWIW, there are some huge advantages to creating processes on-demand:

1. No need to trap exits or try to rescue from errors. If a job's process crashes in any way we can count it as a failure.
2. Garbage collection is done per-processes. Running each job in its own process means that we get automatic memory cleanup when the process exits.
3. Job processes don't need to track any state. With a pool of job processes we need to send a message to each process to tell it what to run. That means we either have a custom receive loop running in each process, or we make each process a GenServer. That is a lot more complex than using `Task.start_link/3` to spin up a new job process.

**Comment by sorentwo** [comment]
I’m closing this for now. If there is further discussion we can re-open it.
