### ISSUE TITLE
Clicking Cancel navigates to Executing (Web)

### ISSUE THREAD

**Issue by cadebward** [sorentwo/oban#760]
Thanks for Oban, we love it to death!

### Environment

- Oban Version: Oban v2.13.1, Oban.Web v2.9.4, Oban.Pro v0.12.3

### Current Behavior

From within a _cancelled_ job detail page, clicking the `cancelled` link on the left sidebar takes you to `executing`. `executing` is now the active tab, but `cancelled` has the background highlighted. 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3212589/186727333-d7296ec7-fcf9-4576-b6cb-cea74b594fb4.png">

<img src="https://user-images.githubusercontent.com/3212589/186729395-63d6b248-366b-4897-882e-2ad17be1bebd.gif" width="320" height="314" />

### Expected Behavior

Clicking on `cancelled` should go to the `cancelled` page.

`href` when on detail page: `href="/oban/jobs?sort_dir=desc"` (should have `state=cancelled`)
`href` when not on detail page: `href="/oban/jobs?sort_dir=desc&state=cancelled"`

**Comment by cadebward** [comment]
Actually, this might be the case for everything? While on a detail page of a state, that state's nav bar has no state on the `href`, leading you to default to the `executing` state.

**Comment by sorentwo** [comment]
Thanks for the report. Is this after every navigation, or only after loading a detail page directly?

**Comment by cadebward** [comment]
Only after loading a detail page

**Comment by cadebward** [comment]
@sorentwo your comment makes more sense now. I opened up #761 to address the situation of "loading a detail page directly".

**Comment by sorentwo** [comment]
This was actually fixed long ago along with #761!
