### ISSUE TITLE
The new `insert` breaks the Dialyzer

### ISSUE THREAD

**Issue by LeoLeiteSC** [sorentwo/oban#762]
### Environment

- Oban Version: 2.13.2
- PostgreSQL Version: 14.4
- Elixir & Erlang/OTP Versions (`elixir --version`): 1.12.3, erlang 24

### Current Behavior
 
The last change on the `insert` function is breaking the Dialyzer. 

The problem is in the `insert/3` function with a custom Oban name, but when sending it without the opts parameter defined. Because of that, Dialyzer thinks that I'm making a request to the first `insert/2` function, that just receive the changeset parameter.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/26944512/186946435-2ae61e8c-5081-48fc-8e13-a3fa08989262.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/26944512/186946503-7bbdda5a-b7ce-4812-a079-eddb925a10ef.png">

As a workaround, I put an empty `opts` when calling the function, forcing the Dialyzer to understand that I'm using the right one.

### Expected Behavior

Dialyzer shouldn't confuse which functions I'm referring to.

**Comment by sorentwo** [comment]
This regressed after the function clause fix. To prevent another regression, we need a module that both exercises all of the function arities _and_ gets checked by dialyzer. An additional module in `test/support` with full function coverage and dialyzer coverage will do it.
