### ISSUE TITLE
Oban.insert/1 returns {:error, changeset} where changeset.valid? is true

### ISSUE THREAD

**Issue by jordi-chacon** [sorentwo/oban#764]
### Environment

- Oban Version: 2.13.2
- PostgreSQL Version: 14.4
- Elixir & Erlang/OTP Versions (`elixir --version`): 1.13.4

### Current Behavior

On Aug 22nd we upgraded from Oban 2.13.1 to Oban 2.13.2. Immediately after that release, we started seeing a specific call to `Oban.insert/1` return `{:error, changeset}`, something we hadn't seen in the weeks prior to this change. This is the call:
```
MyWorker.new(%{license_id: license_id}, [queue: "q1"]) |> Oban.insert()
```

That line above is run thousands of times per day and it only fails around ~100 times per day.

This is the worker definition:
```
  use Oban.Worker,
    priority: 0,
    max_attempts: 20,
    unique: [period: :infinity, states: [:available, :scheduled, :retryable]]
```

And this is the `changeset` returned in `{:error, changeset}`:
```
#Ecto.Changeset<
  action: nil,
  changes: %{
    args: %{license_id: 108536},
    queue: "q1",
    unique: %{
      fields: [:args, :queue, :worker],
      keys: [],
      period: :infinity,
      states: [:available, :scheduled, :retryable]
    },
    worker: "Distru.Workers.Metrc.WorkOneMetrcActivity"
  },
  errors: [],
  data: #Oban.Job<>,
  valid?: true
>
```

The changeset has `valid?: true` and `errors: []`, which is confusing.

### Expected Behavior

We weren't expecting `Oban.insert/1` to fail for the given worker, and if it fails, we would expect the returned changeset to have some errors in it.

@sorentwo Looking at the [diff between Oban 2.13.1 and 2.13.2](https://github.com/sorentwo/oban/compare/v2.13.1...v2.13.2) we couldn't find anything obvious that would explain this potential bug. We aren't 100% sure this is a bug in Oban itself though. Let us know if we should provide any additional info.

Thank you so much!

**Comment by sorentwo** [comment]
This is fixed for the next Pro release, sometime today or tomorrow. Here's the commit message from the fix:

> Treat xact locked jobs as dupes without new jobs
> 
> This is an odd circumstance that will only occur during concurrent,
> single insert attempts when no duplicates were found. It's impossible to
> replicate this within automated tests because the sandbox connection
> already owns the xact lock. The tiny script below will reproduce the
> issue:
> 
> ```elixir
> defmodule ObanTestWorker do
>   use Oban.Worker,
>     queue: :default, unique: [states: [:scheduled], period: :infinity]
> 
>   def perform(_), do: :ok
> end
> 
> insert = fn _ ->
>   %{id: 1}
>   |> ObanTestWorker.new()
>   |> Oban.insert!()
> end
> 
> 1..2
> |> Task.async_stream(insert, max_concurrency: 2)
> |> Stream.run()
> ```
