### ISSUE TITLE
Max attempts option being ignored

### ISSUE THREAD

**Issue by alexandre-pedroza-h65** [sorentwo/oban#765]
First of all, thank you for your work on this library, it's so so helpful.

### Environment

- Oban Version: 2.13.2
- PostgreSQL Version: 12.5
- Elixir & Erlang/OTP Versions: 1.13.4/25.0.4

### Current Behavior

The workers are being created, passing the `max_attempts` option, like so:

```elixir

defmodule MyApp.MyWorker do
  use Oban.Worker,
    queue: :default,
    max_attempts: 3,
    tags: ["user"],
    unique: [fields: [:args, :worker]]

```

However, when the job actually runs, the `max_attempts` column has the default value of 20.

```json
{
  "id": 5075,
  "state": "retryable",
  "queue": "default",
  "worker": "...",
  "args": "...",
  "errors": "...",
  "attempt": 20,
  "max_attempts": 20,
  "inserted_at": "2022-09-05T13:25:52.587Z",
  "scheduled_at": "2022-09-05T15:51:18.811Z",
  "attempted_at": "2022-09-05T14:36:36.144Z",
  "completed_at": null,
  "attempted_by": "...",
  "discarded_at": null,
  "priority": 0,
  "tags": "{}",
  "meta": "{}",
  "cancelled_at": null
}
```

### Expected Behavior

I expected the `max_attempts` column to have a value of 3 that I specified, so that my jobs wouldn't run over and over again in case of failure.

**Comment by sorentwo** [comment]
@alexandre-pedroza-h65 Can you show how you're inserting the job? Did you add uniqueness after running the job previously? Neither `max_attempts` nor `tags` are represented in the job you shared, which leads me to believe that it is an older version of the job.

Regardless, `max_attempts` is a fundamental part of Oban that isn't broken. I see you've asked about this in Slack, and I'll give you some guidance there.
