### ISSUE TITLE
Failing to download public key in Github actions

### ISSUE THREAD

**Issue by davydog187** [sorentwo/oban#774]
Hello, thanks for the great project! I am a user of Oban, as well as a paying member of Oban Pro/Web. 

My project follows [my own guide](https://davelucia.com/blog/deploying-oban-pro-with-docker-and-fly) on deploying Oban using Docker/fly.io. However, today the deployment started failing due to a timeout fetching the public key inside the Docker image. I've tried wiping the cache, running `fly deploy --no-cache`, etc, but the problem is persisting.

I'm not expecting anyone to debug my CI pipeline, but just in case this is some sort of CDN issue, I wanted to share here.

```
#14 [builder  5/18] RUN --mount=type=secret,id=OBAN_KEY_FINGERPRINT     --mount=type=secret,id=OBAN_LICENSE_KEY     mix hex.repo add oban https://getoban.pro/repo     --fetch-public-key "$(cat /run/secrets/OBAN_KEY_FINGERPRINT)"     --auth-key "$(cat /run/secrets/OBAN_LICENSE_KEY)"
#14 16.09 Downloading public key failed
#14 16.10 :timeout
#14 ERROR: executor failed running [/bin/sh -c mix hex.repo add oban https://getoban.pro/repo     --fetch-public-key "$(cat /run/secrets/OBAN_KEY_FINGERPRINT)"     --auth-key "$(cat /run/secrets/OBAN_LICENSE_KEY)"]: exit code: 1
------
 > [builder  5/18] RUN --mount=type=secret,id=OBAN_KEY_FINGERPRINT     --mount=type=secret,id=OBAN_LICENSE_KEY     mix hex.repo add oban https://getoban.pro/repo     --fetch-public-key "$(cat /run/secrets/OBAN_KEY_FINGERPRINT)"     --auth-key "$(cat /run/secrets/OBAN_LICENSE_KEY)":
#14 16.09 Downloading public key failed
#14 16.10 :timeout
------
Error failed to fetch an image or build from source: error building: executor failed running [/bin/sh -c mix hex.repo add oban https://getoban.pro/repo     --fetch-public-key "$(cat /run/secrets/OBAN_KEY_FINGERPRINT)"     --auth-key "$(cat /run/secrets/OBAN_LICENSE_KEY)"]: exit code: 1
```

**Comment by davydog187** [comment]
I can reproduce the issue on my local machine as well, looking further

**Comment by davydog187** [comment]
Can confirm that running on my machine has the same issue, so its not a Github actions issue

```
 => ERROR [builder  7/18] RUN mix deps.get --only prod                                                                                           16.4s
------                                                                                                                                                 
 > [builder  7/18] RUN mix deps.get --only prod:                                                                                                       
#16 16.36 Failed to fetch record for 'oban/oban_web' from registry (using cache instead)                                                               
#16 16.36 :timeout
#16 16.37 ** (Mix) Unknown package oban_web in lockfile
------
Error failed to fetch an image or build from source: error building: executor failed running [/bin/sh -c mix deps.get --only $MIX_ENV]: exit code: 1
```

**Comment by sorentwo** [comment]
@davydog187 Our logs don't show any errors or timeouts, and your key is functioning for me locally. Can you confirm that you have the repo added and authenticated locally (`mix hex.repo list`)?

**Comment by sorentwo** [comment]
@davydog187 Please email, message on Elixir Slack, or on the Elixir forum if you’re still having trouble.

**Comment by davydog187** [comment]
I can confirm that it also works locally for me, but not inside docker. I wonder if the build image has a certificate issue.

I'll reach out on another channel later today

**Comment by davydog187** [comment]
For the next person, I was able to fix this issue by deleting my fly builder app, and then redeploying.

Sorry for the false alarm @sorentwo, and I'll reach out on other channels next time.
