### ISSUE TITLE
Split `oban_jobs` into multiple tables

### ISSUE THREAD

**Issue by Billzabob** [sorentwo/oban#775]
Our Oban table is becoming a bit of a bottleneck for us due to the “FOR UPDATE” lock that it takes out when looking for jobs for its workers to take on. With so many different types of jobs being written to that table, one way we might alleviate that congestion is for us to have multiple Oban tables.

The Oban documentation talks about ways to have multiple database schemas be in play (and by extension, that’ll allow for multiple tables since tables belong to a schema). It would be nice if we didn’t have to go through the schema route to accomplish this. It would be great if we could just define table names like, “oban_rewards_jobs” or “oban_company_events”.

Is there a reason Oban isolates by schema instead of by table? If not then it would be a great feature to have.

**Comment by sorentwo** [comment]
> Our Oban table is becoming a bit of a bottleneck for us due to the “FOR UPDATE” lock that it takes out when looking for jobs for its workers to take on. With so many different types of jobs being written to that table, one way we might alleviate that congestion is for us to have multiple Oban tables.

The `FOR UPDATE SKIP LOCKED` option means that queries will immediately skip any rows selected by another query. It isn't a "lock" in the standard sense, where other queries wait on the resource to be released. `queue` is the unit Oban selects by, not `worker`, so the number of distinct `worker` types has no impact on the number of concurrent fetches from the jobs table.

Do you have any queries, explains, or other information illustrating how your table is becoming a bottleneck? Some information about the Oban version you're using and the PostgreSQL version could really help.

> Is there a reason Oban isolates by schema instead of by table? If not then it would be a great feature to have.

Unlike `prefix`, `table` is baked into a schema, and there isn't an easy mechanism to override it per query or per migration. To support multiple `tables` we'd have to provide a generator or macro that built various Job schemas, and that would add complexity throughout the codebase.

**Comment by Billzabob** [comment]
Here's what our DB admin is saying about the table:
The FOR UPDATE lock is occurring so often that the Postgres internal VACUUM jobs are not able to get a hold of routine maintenance tasks to be performed on this table.  Frequent updates leave a lot of dead tuples and Postgres should be able to perform VACUUM tasks on this table, but the FOR UPDATE lock is preventing these maintenance tasks.
```
2022-08-30 20:42:17 UTC::@:[35228]:LOG: skipping vacuum of "oban_jobs" --- lock not available
2022-08-30 20:42:19 UTC::@:[35045]:LOG: skipping vacuum of "oban_jobs" --- lock not available
2022-08-30 20:42:30 UTC::@:[35507]:LOG: skipping vacuum of "oban_jobs" --- lock not available
```
Postgres is not able to perform VACUUM on this table as VACUUM and FOR UPDATE locks are mutually exclusive.

**Comment by sorentwo** [comment]
`FOR UPDATE SKIP LOCKED` doesn't block VACUUM on a table like `LOCK TABLE` does. For a demonstration, you can start two separate `psql` sessions. Start the following loop in the first session:

```sql
begin;
do $$
begin
  for i in 1..1000 loop
    update oban_jobs
    set state = 'executing'
    where id in (
      select id oban_jobs
      where state = 'available'
      limit 1
      for update skip locked
    );
  end loop;
end$$;
rollback;
```

While running in the first session, execute `vacuum oban_jobs;` in the second. You'll see that the vacuum completes immediately without hanging. However, if you replicate the experiment using `lock oban_jobs in share mode;` in the first session, you'll see that the `vacuum` hangs until the lock is released in the second.

Something is blocking your vacuums, but it isn't the use of `for update`.
