### ISSUE TITLE
A way to manually retry a discarded job?

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#78]
If there's not already a way, it'd be nice to have a way to manually trigger a retry even after the max attempts have been reached.

**Comment by sorentwo** [comment]
There isn't currently a way to explicitly retry a job. It is definitely something that will be helpful, and something I have marked for inclusion in the UI. All you really need to do is change the state to `available`, the attempts are ignored when fetching jobs.

**Comment by jc00ke** [comment]
Changing the state to `available` will work for now, thanks!
