### ISSUE TITLE
Expand docs for how the Job.new/2 :schedule_in interacts with Stager default :interval

### ISSUE THREAD

**Issue by tom-con** [sorentwo/oban#780]
### Is your feature request related to a problem? Please describe.

Jobs that I was scheduling for 1 second in the future using recursive jobs and the `schedule_in` option were not being attempted until roughly a second after the `scheduled_at` time on the created job record. I tracked it down to the Stager default polling interval being set to 1 second, so the jobs were only being picked up on the next tick. This behavior is documented, but it was difficult for me to find.

### Describe the Solution You'd Like

It would be helpful to have brief "notes" or "warnings" or even a dedicated section in the documentation about scheduling jobs on very short intervals. E.g:

> Be aware: To ensure accurate job execution attempted_at times when scheduling jobs in the very-near future (`<= 1` second), be sure that the `Oban.Plugins.Stager` `:interval` configuration is appropriately set so that the polling interval will pickup new job records as close to the desired time as possible.

### Describe Alternatives You've Considered

I may have completely missed the point and my solution of decreasing the Stager interval may not be a pattern that the community wants to suggest or encourage because of performance reasons.

### Additional Context

Obviously it's not ideal to have a job that is consistently scheduled for 1 second in the future (and needs to start as close to that second as possible), but unfortunately the demands of my situation require it.

I am happy to put a PR up for some potential documentation additions, but wanted to provide this context first, as I'm sure the maintaining team will have valuable insight.

**Comment by sorentwo** [comment]
Thanks for this thoughtfully reasoned issue!

As you discovered, polling more frequently than once a second is possible, but it isn’t recommended due to load on the database. That said,  expanding the docs on staging with “notes” like you shared is entirely welcome.

**Comment by sorentwo** [comment]
Closed with #781
