### ISSUE TITLE
Batch worker doesn't consider cancelled state for exhausted callback

### ISSUE THREAD

**Issue by cichacz** [sorentwo/oban#784]
### Environment

- Oban Version 2.13.4 (Pro 0.12.6)
- PostgreSQL Version 11.3
- Elixir & Erlang/OTP Versions (`elixir --version`) 1.14 OTP 24.3

### Current Behavior

```
defp callback_ready?("exhausted", batch_states, existing) do
    "exhausted" not in existing and Map.keys(batch_states) -- ~w(completed discarded) == []
end
```

Right now if batch contains `cancelled` jobs this callback won't be inserted because list won't be empty

### Expected Behavior

Assuming that "exhausted" comes from "all jobs exhausted all retries" I believe condition should also take into account `cancelled` jobs.

```
defp callback_ready?("exhausted", batch_states, existing) do
    "exhausted" not in existing and Map.keys(batch_states) -- ~w(completed discarded cancelled) == []
end
```

**Comment by sorentwo** [comment]
Thanks for the report. Fixed for the next release!
