### ISSUE TITLE
Question: Gossip in a multi-node environment

### ISSUE THREAD

**Issue by thiamsantos** [sorentwo/oban#785]
Hello, I'm running oban in a multi-node environment but they are not connected in a cluster.
While reading the docs I was really uncertain if I should use the [`Gossip`](https://hexdocs.pm/oban/Oban.Plugins.Gossip.html) plugin or not. 

Should I be using the `Gossip` plugin? What I lose if I don't use it?

**Comment by sorentwo** [comment]
The gossip plugin is only needed to run the Oban Web dashboard. It is purely informational and doesn't control clustering or job dispatching.

In the future, please ask general questions on the Elixir Forum or in Elixir Slack.
