### ISSUE TITLE
Restrict search operations

### ISSUE THREAD

**Issue by dmolnar99** [sorentwo/oban#793]
### Is your feature request related to a problem? Please describe.
Searching among jobs on the dashboard is a slow, DB intense operation. Given millions of jobs the search can use considerable amount of DB resources.

### Describe the Solution You'd Like
To avoid degrading the DB, it would be nice to restrict the search capabilities, e.g. one should not be able to search completed jobs.

### Describe Alternatives You've Considered
I tired to look for [customization options](https://hexdocs.pm/oban/2.11.0/web_customizing.html) to not to be able to see the completed jobs tab, but it seems there aren't any (ofc one could still change the query in the url). Is there another way to ensure that the search is not using a lot of DB resources even with a high amount of jobs?

**Comment by sorentwo** [comment]
> Is there another way to ensure that the search is not using a lot of DB resources even with a high amount of jobs?

No, there isn't any mechanism to restrict searching currently. We're collecting search improvement notes and requests and will consider this.

**Comment by sorentwo** [comment]
A variant of this is ready to go for the upcoming Web release.

**Comment by dmolnar99** [comment]
> A variant of this is ready to go for the upcoming Web release.

Thanks for the update @sorentwo! When is the new release expected?

**Comment by sorentwo** [comment]
@dmolnar99 We're hoping for a release in the next month.
