### ISSUE TITLE
Batch.handle_discarded no triggered when job is cancelled

### ISSUE THREAD

**Issue by dmolnar99** [sorentwo/oban#799]
### Is your feature request related to a problem? Please describe.

[Oban.Pro.Workers.Batch.handle_discarded](https://hexdocs.pm/oban/2.11.0/batch.html#handler-callbacks) not triggered when jobs cancelled.

### Describe the Solution You'd Like

We are using `handle_discarded` to know if the batch cannot succeed. Given the new recommended state `:cancel` to end a job manually, this callback is not triggered. We'd expect a callback method to be triggered when any jobs of the batch has been _discarded or cancelled_.

### Describe Alternatives You've Considered

Keep using soft-deprecated `:discard` state to manually end a job.

**Comment by sorentwo** [comment]
Thanks for the report! This is fixed but not yet released. Look for Pro v0.12.7 later this week, likely Friday.
