### ISSUE TITLE
Oban Pro DynamicCron Documentation Fix

### ISSUE THREAD

**Issue by atonse** [sorentwo/oban#802]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

I'd submit a pull request but I think this repo is private :-)

Oban Pro Documentation (0.12.6): https://getoban.pro/docs/pro/dynamic_cron.html

### Current Behavior

The documentation for this migration needs to be fixed to say `prefix: "private"`

```elixir
defmodule MyApp.Repo.Migrations.AddObanCron do
  use Ecto.Migration

  def change, do: Oban.Pro.Migrations.DynamicCron.change("private")
end
```

### Expected Behavior

```elixir
defmodule MyApp.Repo.Migrations.AddObanCron do
  use Ecto.Migration

  def change, do: Oban.Pro.Migrations.DynamicCron.change(prefix: "private")
end
```

**Comment by sorentwo** [comment]
You're correct, the repo is private, and you can't contribute a PR. Fixed now! Thanks 💛
