### ISSUE TITLE
A way remember how many items have been processed so far

### ISSUE THREAD

**Issue by ally9335** [sorentwo/oban#804]
Let's say, in a DB I have a million of records which I want to process on daily basis. And I have oban jobs that run hourly.
An oban job is able to process, let's say, 100k per hour, on average. But it's unknown in advance how many it really will each time.

Is there a way for an Oban job to save in itself some additional information? I'd then save the "total_records_processed_for_far" in it.

I could do in in a DB. But I'd create a new table with ... 1 column and 1 record. This won't be right.

Is Oban capable of remembering info like this?

---

Alternatively, is there a way for Oban to split records in chunks, to then process a new part each time an Oban job runs? Once everything has been processed, the next time a job runs it'll start from the 1st record

**Comment by sorentwo** [comment]
Storing telemetry data is outside the scope of what Oban handles. However, ample [telemetry data](https://hexdocs.pm/oban/Oban.Telemetry.html) is available, and you can easily hook into that to track metrics locally, with a live dashboard, through Prometheus or any other metrics toolkit.

Regarding chunks, that's precisely what [Pro's Chunk worker](https://getoban.pro/docs/pro/Oban.Pro.Workers.Chunk.html) provides!

**Comment by sorentwo** [comment]
You’re asking about measuring the number of jobs executed in a particular window of time. That’s exactly the kind of metrics question telemetry can help you answer.

**Comment by ally9335** [comment]
@sorentwo no, I'm not asking about that.

**Comment by sorentwo** [comment]
@ally9335 Sorry, then I don't understand what you're asking. All of Oban's introspection and instrumentation come from telemetry, whether it's internal or otherwise.

```elixir
counter = :counters.new(1, [:write_concurrency])

defmodule MyCounter do
  def handle(_event, _measure, _meta, counter) do
    :counters.add(counter, 0, 1)
  end
end

:telemetry.attach("counter", [:oban, :job, :stop], &MyCounter.handle/4, [counter])
```

**Comment by ally9335** [comment]
I've asked about "pieces of data" that have been processed and a capacity to store a counter for it, somewhere. Not the amount of jobs being executed.
