### ISSUE TITLE
Compilation error against Phoenix 1.7.0-rc.0

### ISSUE THREAD

**Issue by simoncocking** [sorentwo/oban#805]
### Environment

- Oban `2.13.4`, Oban Web `2.9.5`
- Phoenix `1.7.0-rc.0`, Phoenix live view `0.18.2`
- Elixir `1.14.0`, Erlang `25.0.4`

### Current Behavior

Compiling Oban web:
```
warning: undefined module attribute @view_resource, please remove access to @view_resource or explicitly set it before access
  lib/oban/web/views/dashboard_view.ex:2: Oban.Web.DashboardView (module)

warning: undefined module attribute @view_resource, please remove access to @view_resource or explicitly set it before access
  lib/oban/web/views/layout_view.ex:2: Oban.Web.LayoutView (module)3
== Compilation error in file lib/oban/web/views/dashboard_view.ex ==
** (CompileError) lib/oban/web/views/dashboard_view.ex:1: undefined function render_template/2 (expected Oban.Web.DashboardView to define such a function or for it to be imported, but none are available)
```

**Comment by sorentwo** [comment]
@simoncocking Thanks for the report. Phoenix 1.7 has a number of breaking changes for Oban Web, and we're working through them now.

**Comment by simoncocking** [comment]
FWIW @sorentwo we're also currently blocked building our containers by the following: 
![image](https://user-images.githubusercontent.com/1700927/201004132-a90f12e7-65dd-469e-ae43-c24209257677.png)
IIRC this occurred a couple of days ago as well.

**Comment by sorentwo** [comment]
The Pro 0.12.7 package was "touched" inadvertently by our new package release mechanism. The touch is reverted and fixed now.

**Comment by sorentwo** [comment]
Fixed for the upcoming release.

**Comment by dvic** [comment]
For those encountering problems on the latest phoenix rc: just set `helpers: true` in your `MyWeb` module (so that the legacy router helper module is generated) and it will work :)
