### ISSUE TITLE
Support CockroachDB 

### ISSUE THREAD

**Issue by lessless** [sorentwo/oban#806]
Hi,

I'm not sure how feasible this is, but I still want to ask if there is a chance that, in any observable timeframe, Oban to work with CockroachDB. 

Thanks.

**Comment by sorentwo** [comment]
It's unclear which parts of Oban are incompatible with CocroachDB, even after reading "[How compatible is CockroachDB with PostgreSQL?](https://cockroachlabs.com/blog/why-postgres/#how-compatible-is-cockroachdb-with-postgresql)"

If there are minor syntax issues, then there is a chance it could happen sometime soon. However, if there are more fundamental incompatibilities, it would require an alternate engine with new callbacks, which won't be ready soon.
