### ISSUE TITLE
Oban Web UI shows incorrect queue time for jobs inserted with scheduled_at in the past

### ISSUE THREAD

**Issue by edennis** [sorentwo/oban#811]
### Environment

- Oban Version: 2.13.6
- PostgreSQL Version: 12.7
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 24 [erts-12.3.2.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

### Current Behavior

Oban Web shows the "Queue Time" as the difference between `attempted_at` and `scheduled_at`. When a job gets inserted with a `scheduled_at` timestamp in the past, the resulting queue time is incorrectly longer than it should be.

### Expected Behavior

I would expect the queue time to represent exactly how long the job was in the queue, regardless of when it was scheduled to run. If I insert a job at 8:00am and `scheduled_at` is set to 6:00am, oban will execute it immediately. The job was only queued briefly and not 2+ hours as the UI indicates. Comparing `attempted_at` with the `max()` of `inserted_at` and `scheduled_at` would return the results I would expect.

**Comment by sorentwo** [comment]
@edennis Nice catch. It'll be fixed in the next patch release.
