### ISSUE TITLE
meta not usable anymore for dependency injection

### ISSUE THREAD

**Issue by MMore** [sorentwo/oban#820]
Hey,

due to a [recent change in v2.13.5](https://github.com/sorentwo/oban/blob/v2.13.6/CHANGELOG.md#v2135--2022-11-14) `meta` is not usable anymore for simple testing with dependency injection as recommended [here](https://github.com/sorentwo/oban/issues/523#issuecomment-891322774). Is there an alternative way to pass function references? Thank you and Merry Christmas!

**Comment by sorentwo** [comment]
Sorry that the `meta` change broke your DI workflow. Fixing a bug with unserialized/unvalidated meta had an unforeseen consequence. Anyhow, here are a few ways you can still pass data through:

1. Encode/Decode — Use `:erlang.term_to_binary` to serialize data and then `:erlang.binary_to_term` to deserialize it within the function body.
2. Process Dictionary — Use `Process.put` to stash the dependency for the test process
3. Persistent Term — If you're testing across multiple processes, you can use `:persistent_term.put` 
4. Application Env — Use `Application.put_env` for the test

I hope one of those is viable for you!
