### ISSUE TITLE
Sometimes my oban process stops working

### ISSUE THREAD

**Issue by RodolfoSilva** [sorentwo/oban#821]
### Environment

- Oban Version: `2.13.3`
- PostgreSQL Version: `12` on RDS
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir: `1.14.2`, Erlang: `25.1.2`

### Current Behavior

Sometimes my Oban process stops working and only starts working again after restarting the application. I've observed this behavior when the database connection fails for a brief moment. But everything else in the app works. But Oban Cron and queue no longer work until app restart.

### Expected Behavior

Does we have some way to do a sanity check to know if the  Oban is proper working and a way to auto recovery.

**Comment by sorentwo** [comment]
There is a comprehensive fix to this issue in main, as described in #769.

**Comment by RodolfoSilva** [comment]
Thank you so much @sorentwo for building this amazing library.
I have a question about the fix, it will be included in the next stable release, right? Does Oban have a release roadmap somewhere?

For now I think we can switch to use the main branch version.

**Comment by sorentwo** [comment]
That will be in the next big release. You’re welcome to run from main (unless you have Pro, because there are incompatibilities). Alternatively, you can use the repeater plug-in to force polling every 1 second.

**Comment by RodolfoSilva** [comment]
Thanks again @sorentwo, I'll use the Repeater Plug-in.
