### ISSUE TITLE
Batch.handle_exhausted is called without callback args sometimes

### ISSUE THREAD

**Issue by dmolnar99** [sorentwo/oban#831]
### Environment

- Oban Version: 2.13, Oban Pro Version: 0.12
- PostgreSQL Version: 13
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.13.4, Erlang/OTP 24

### Current Behavior
`Batch.handle_exhausted` is _sometimes_ called without the arguments defined in `batch_callback_args`.

### Expected Behavior
Batch callback worker should always receive the callback arguments.

**Comment by sorentwo** [comment]
A few questions to help diagnose:

* Are you generating and potentially re-using batch ids?
* Are you dynamically appending to a batch?
* Are you manually canceling jobs, e.g. with `cancel_job` or `cancel_all_jobs`?
* Do you know what the final job states are when `handle_exhausted` doesn't receive the arguments?

**Comment by lucasaas98** [comment]
Hello, I can answer some of the questions for my colleague.

> Are you generating and potentially re-using batch ids?

We are using the `job_id` as the `batch_id`, the `job_id` is generated using `Ecto.UUID.generate()` so I don't think we would be reusing batch_ids.

> Are you dynamically appending to a batch?

We are inserting all the batch workers at once so not dynamically. When we insert them we set `batch_callback_args` to be similar to `%{"id" => "some_id"}` but we are getting `%{}` in the worker

> Are you manually canceling jobs, e.g. with cancel_job or cancel_all_jobs?

While we do sometimes do that, in this case we did not do any `cancel_job` or `cancel_all_jobs` so I don't think that would be an explanation for this.

> Do you know what the final job states are when handle_exhausted doesn't receive the arguments?

I've checked some of the failed callback workers and checked the workers from those batches. Usually we have something like 1 completed and 2 discarded in 3 total jobs. 


Let us know if there is something you would like for us to try!

**Comment by sorentwo** [comment]
One more question comes to mind; can you verify that the `meta` for all jobs in the failed batches are identical?

**Comment by lucasaas98** [comment]
I just took a peek at some examples and yes, they seem to be identical. 
```
[
  {
    "batch_id": "d6ad298a-e1ba-43f8-90fb-32fec835a756",
    "batch_callback_args": {
      "integration_id": "61031fd4a85400001cedfb36",
      "next_start_time": "2023-01-20T10:56:11.136136Z",
      "current_start_time": "2022-03-16T15:05:09.147066Z",
      "schedule_update_in": 86400
    },
    "batch_callback_worker": "Elixir.Integrations.Workers.PartnerRequestBatchCallbackWorker"
  },
  {
    "batch_id": "d6ad298a-e1ba-43f8-90fb-32fec835a756",
    "batch_callback_args": {
      "integration_id": "61031fd4a85400001cedfb36",
      "next_start_time": "2023-01-20T10:56:11.136136Z",
      "current_start_time": "2022-03-16T15:05:09.147066Z",
      "schedule_update_in": 86400
    },
    "batch_callback_worker": "Elixir.Integrations.Workers.PartnerRequestBatchCallbackWorker"
  },
  {
    "batch_id": "d6ad298a-e1ba-43f8-90fb-32fec835a756",
    "batch_callback_args": {
      "integration_id": "61031fd4a85400001cedfb36",
      "next_start_time": "2023-01-20T10:56:11.136136Z",
      "current_start_time": "2022-03-16T15:05:09.147066Z",
      "schedule_update_in": 86400
    },
    "batch_callback_worker": "Elixir.Integrations.Workers.PartnerRequestBatchCallbackWorker"
  }
]
```

**Comment by sorentwo** [comment]
A few more diagnostic questions:

1. How long are you retaining jobs, i.e. what is your pruning schedule?
2. Are you using structured workers?
3. Will you share the args/meta for one of the failed batches?

Use this query to get the callbacks for a batch:

```elixir
Oban.Job
 |> where([j], fragment("? @> ?", j.meta, %{batch_id: YOUR_BATCH_ID}))
 |> where([j], fragment("? \\? ?", j.meta, "callback"))
 ```

**Comment by dmolnar99** [comment]
Hey @sorentwo!

1. Our prune schedule is `{:max_age, {10, :days}}`
2. Not yet
3. Example: it consists of 3 workers (from which one completed, two got discarded) with similar args:
```
{
  "path": "/path",
  "method": "POST",
  "params": {},
  "service": "service",
  "update?": true,
  "base_url": "https://example.com",
  "resource": "resource",
  "auth_type": "auth_type",
  "company_id": "id_1",
  "pagination": null,
  "integration_id": "id_2"
}
```
meta:
```
{
  "batch_id": "uuid_1",
  "batch_callback_args": {
    "integration_id": "id_2",
    "next_start_time": "2023-01-24T09:12:39.563408Z",
    "current_start_time": "2021-12-22T13:59:17.437033Z",
    "schedule_update_in": 86400
  },
  "batch_callback_worker": "Elixir.Workers.BatchCallbackWorker"
}
```
The `discarded` callback has been called with the correct `batch_callback_args` and has the following meta:
```
{
  "batch_id": "uuid_1",
  "callback": "discarded",
  "uniq_key": 93242472
}
```
However the exhausted callback was called with empty args and following meta:
```
{
  "batch_id": "uuid_1",
  "callback": "exhausted",
  "uniq_key": 121830789
}
```

**Comment by dmolnar99** [comment]
@sorentwo Do you have any clue?

**Comment by sorentwo** [comment]
No, I don’t see any reason this is happening or a way to reproduce it. Now that the latest OSS/Pro minor versions are out I can focus on diagnosing this issue more.

**Comment by sorentwo** [comment]
@dmolnar99 Some more questions:

1. Are you setting `batch_callback_worker` to a different worker, or is it the same one as the batch jobs?
2. Are the discards from a manual `:discard` call, or from running out of retry attempts? If it's from exhausting retries, what is the error that caused it?
4. Have you upgraded to Oban v2.14.1? If so, does this issue still happen?

**Comment by dmolnar99** [comment]
Hey @sorentwo!

1. Yes, we have a separate worker for the callback.
2. I just checked one example: 3 batch workers, 1 completed, 2 discarded with manual `:discard`. -- We haven't updated this logic yet to use `:cancel` since the telemetry handlers weren't including this state at that time.
3. We are at 2.13. We can try to upgrade.

**Comment by dmolnar99** [comment]
Hey @sorentwo! We update to the latest oban versions and we are still experiencing the same issue.

**Comment by sorentwo** [comment]
@dmolnar99 Thank you for the update. That's disappointing but not surprising. I haven't forgotten about this issue!

**Comment by dmolnar99** [comment]
@sorentwo Thanks for keeping our issue on your radar. We will look for an alternative to `handle_exhausted` for now, but are really looking forward to have this issue resolved.

We appreciate your hard work on this project, your availability and willingness to always improve the library! 💪🏼

**Comment by sorentwo** [comment]
@dmolnar99 Can you share the complete database rows for a batch of jobs (including callbacks) where the exhausted callback is missing args? Also, if you have logging enabled, any logs around those jobs are helpful too.

You're welcome to send an email or DM on Slack if you'd prefer not to share those here.
