### ISSUE TITLE
Jobs stuck

### ISSUE THREAD

**Issue by nathanl** [sorentwo/oban#832]
(scratch this, I can reproduce and will re-open if I have better info)

**Comment by sorentwo** [comment]
@nathanl Thanks for opening this issue, `pg_notify` issues have been a consistent source of frustration. Good news—the upcoming 2.14 release modifies job dispatching to gracefully fall back to polling mode when the notifier isn't working.

**Comment by nathanl** [comment]
I closed this because I saw the problem occur in prod again, so I thought I could figure out what the fix was. But Nothing I had tried previously got things working again. 😕 Will look for that new release or maybe use `main`. Thank you!

**Comment by sorentwo** [comment]
The new release is slated for this week, if that helps 🙂
