### ISSUE TITLE
Unknown package version oban_pro 0.13.1 in lockfile

### ISSUE THREAD

**Issue by dvic** [sorentwo/oban#837]
Is something wrong in the pro registry with `0.13.1`? It seems that 0.13.1 can't be found when using `mix deps.get` but it did somehow get in the lock file (probably during `mix deps.update --all`)

**Comment by dvic** [comment]
Also, when I run `mix deps.update oban_pro` repeatedly it alternates between upgrading from `0.13.0` to `0.13.1` and downgrading from `0.13.1` to `0.13.0` 😅, not sure if this is a bug in hex itself?

**Comment by sorentwo** [comment]
@dvic Sorry for the trouble. There isn't a bug in hex; a cache-invalidation race condition between our servers causes this. I've refreshed the cache and fixed the source of the bug to prevent this from cropping up in the future.
