### ISSUE TITLE
Run job in transaction

### ISSUE THREAD

**Issue by hfjallemark** [sorentwo/oban#84]
I really like the idea of storing jobs in the db so that you can schedule jobs atomically together with your data (e.g. user signing up I can save the user and schedule welcome email atomically so if either fails, nothing is saved).

However, I haven’t found a way to save my data atomically with my job succeeding. There may be good reasons for this but would I can’t think of any. My use case is that I want to get some data from an external rest api and store the result in the database, could I do this within a transaction together with the job so that if it fails the data will never be stored unless the entire job succeeds?

**Comment by sorentwo** [comment]
> However, I haven’t found a way to save my data atomically with my job succeeding. There may be good reasons for this but would I can’t think of any. My use case is that I want to get some data from an external rest api and store the result in the database, could I do this within a transaction together with the job so that if it fails the data will never be stored unless the entire job succeeds?

There isn't anything built in that does this automatically, but you can easily handle it within your job. This example uses a private function from the [Oban.Query module](https://github.com/sorentwo/oban/blob/master/lib/oban/query.ex#L152). All it is doing is setting the state to `completed` and recording a `completed_at` timestamp.

```elixir
def perform(args, job) do
  changeset =
    args
    |> MyApp.RestAPI.get()
    |> MyApp.Record.changeset()

  MyApp.Repo.transaction(fn repo ->
    repo.insert!(changeset)
    Oban.Query.complete_job(Oban.config(), job)
  end)
end
```

If you happen to have multiple repos you can inject the transaction's repo into the config:

```elixir
config = %{Oban.config() | repo: repo}
```

Alternately, if you'd rather not use Oban internals at all, you can make a changeset:

```elixir
repo.update(Ecto.Changeset.change(job, state: "completed", completed_at: DateTime.utc_now()))
```

**Comment by hfjallemark** [comment]
Got it! So calling `Oban.Query.complete_job` is basically what Oban would do after my `perform` function and if I do it inside the function it won't cause any other issues?

**Comment by sorentwo** [comment]
Exactly. Oban will mark complete a second time

**Comment by hfjallemark** [comment]
Great, thanks for clarifying!
