### ISSUE TITLE
Oban Web sorting by time doesn't work in the `cancelled` queue view

### ISSUE THREAD

**Issue by JesseHerrick** [sorentwo/oban#840]
### Environment

* oban 2.14.1 (Hex package) (mix)
  locked at 2.14.1 (oban) 6c368b5f
* oban_pro 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (oban/oban_pro) d50ef065
* oban_web 2.9.6 (Hex package) (mix)
  locked at 2.9.6 (oban/oban_web) be7917e9
* erlang 25.2
* elixir 1.14.3-otp-25
* postgres 14.5

### Current Behavior

Hello 👋, I'd like to report a very strange bug that we've run into. When looking at the Oban Web UI for cancelled jobs, the jobs are not sorted by datetime, even though sorting by time is selected. The funny thing is that this sorting works great for every other state view - cancelled jobs are the only ones that aren't sorted properly.

![Screenshot 2023-02-07 at 22 00 08](https://user-images.githubusercontent.com/3150092/217418065-1809d108-deae-4984-a9c7-8a87539b8beb.png)

### Expected Behavior

Cancelled jobs in the Oban Web UI should be ordered by datetime when ordering by time is selected.

Let me know if you need any more details from me! Thanks so much!

**Comment by jaimeiniesta** [comment]
I can confirm that, it also happens in our case with:

Oban v2.13.6 Oban.Web v2.9.5 Oban.Pro v0.12.9

![Captura de pantalla 2023-02-08 a las 11 37 49](https://user-images.githubusercontent.com/2629/217506282-ea032652-1d8e-4c86-b184-b78122d445d6.png)

**Comment by sorentwo** [comment]
Thanks for the report and the confirmation. It'll be fixed soon 👍
