### ISSUE TITLE
Stuck jobs

### ISSUE THREAD

**Issue by nathanl** [sorentwo/oban#842]
## Versions

- Oban Version: ~2.13.6~ correction, 2.14.1
- PostgreSQL Version: 14.6
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.14.2, Erlang/OTP 25

## Issue

Despite the fix in #769, I see jobs that have been waiting for hours in `SELECT id, worker, args FROM oban_jobs;`
I've investigated somewhat and would appreciate any help you can give.
I don't know if this is a misconfiguration on our part or a bug, but I can investigate whatever seems useful.

### State

`Supervisor.which_children(MyApp.Supervisor)` finds `{Oban, #PID<0.3741.0>, :supervisor, [Oban]}` among its children.

`Supervisor.which_children(pid("0.3741.0"))` finds `{Oban.Stager, #PID<0.3745.0>, :worker, [Oban.Stager]}` among the Oban supervisor's children.

`:sys.get_state(pid("0.3745.0"))` finds this state for the stager:

```elixir
%Oban.Stager.State{
  conf: %Oban.Config{
    dispatch_cooldown: 5,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    log: false,
    name: Oban,
    node: "myapp@[ip_redacted]",
    notifier: Oban.Notifiers.Postgres,
    peer: Oban.Peers.Postgres,
    plugins: [{Oban.Plugins.Pruner, []}],
    prefix: "public",
    queues: [default: [limit: 10]],
    repo: MyApp.Repo,
    shutdown_grace_period: 15000,
    stage_interval: 1000,
    testing: :disabled
  },
  name: {:via, Registry, {Oban.Registry, {Oban, Oban.Stager}}},
  timer: #Reference<0.383720447.3091202049.243950>,
  interval: 1000,
  limit: 5000,
  mode: :global,
  ping_at_tick: 60,
  swap_at_tick: 65,
  tick: 13
}
```

Seeing that it's in `:global` mode (listening for PG notifications), as an experiment I force it into `:local` mode (thinking that will make it poll) by doing:

```elixir
:sys.replace_state(pid("0.3745.0"), fn state -> Map.put(state, :mode, :local) end)
```

Calling `:sys.get_state(pid("0.3745.0"))` confirms that the `:mode` is now `:local`.

However, when `:tick` reaches `60`, I see state switch back to `:global`, and the app logs include "[info] Oban job staging switched back to global mode."

The `oban_jobs` entries remain unprocessed.

### PostgreSQL

The following succeeds:

```sql
LISTEN foo;
SELECT pg_notify('fo' || 'o', 'pay' || 'load');
```

producing

```sql
pg_notify
-----------

(1 row)

Asynchronous notification "foo" with payload "payload" received from server process with PID 82192.
```

`\df+ oban_jobs_notify()` shows a blank in `Access privileges`. I'm not sure, but I think this means `PUBLIC`, and in any case, `\du+` shows only two users, both superusers, so presumably they can execute any function?

### Clustering

We do have a two-node cluster - `Node.list()` shows the other node. `SELECT * FROM oban_peers` shows only the node I'm connected to. `Node.ping/1` to the other node works.

**Comment by sorentwo** [comment]
You reported that Oban is version v2.13.6, but the global/local stager is only in v2.14+. Did you report the wrong version?

Here are a few questions to help diagnose the issue:

1. Did any jobs process when you flipped the stager to `:local` mode?
2. What queue(s) are your stuck workers in? Your config only shows a `default` queue running.

**Comment by nathanl** [comment]
My mistake - the version in `mix.lock` is `2.14.1`; I was looking at the wrong branch when I reported `2.13.6`.

> Did any jobs process when you flipped the stager to :local mode?

No.

> What queue(s) are your stuck workers in? Your config only shows a default queue running.

We only have one queue right now. Our whole Oban config in dev/prod is:

```elixir
config :myapp, Oban,
  repo: MyApp.Repo,
  plugins: [Oban.Plugins.Pruner],
  queues: [default: 10]
```

**Comment by sorentwo** [comment]
That’s the queue that you’re running. What queue are your workers in, though? What do you get if you `select queue` in the database?

**Comment by spectator** [comment]
I'll chime in if that's all right while Nathan is offline.

@sorentwo did you mean `select queue from oban_jobs;` ? here is what I got

```
select queue from oban_jobs;
  queue
---------
 default
 default
 default
 default
 default
 default
 default
 default
 default
(9 rows)
```

**Comment by sorentwo** [comment]
Thank you for confirming the queue matches what you’re running. The next step to see if there is something wrong with staging, run the jobs synchronously by draining.

Do the jobs execute if you run `Oban.drain_queue(queue: “default”)`?

**Comment by nathanl** [comment]
`SELECT DISTINCT queue FROM oban_jobs` finds only `default`.

**Comment by nathanl** [comment]
Running that has no effect.

```elixir
Oban.drain_queue(queue: "default")
%{cancelled: 0, discard: 0, failure: 0, snoozed: 0, success: 0}
```

**Comment by nathanl** [comment]
🤦‍♂️The jobs are running, they're just failing, for reasons that are our fault.

Sorry for the noise.

**Comment by sorentwo** [comment]
If draining doesn’t run anything it’s definitely not a staging issue. There’s some misconfiguration or mismatch going on.

Do you have multiple databases or separate prefixes? Do you get any jobs back if you run `Oban.Repo.all(Oban.config(), Oban.Job)`?

**Comment by jotaviobiondo** [comment]
Hey! Not sure if I should open a new issue or not (let me know please), but I faced a similar issue, but in my case it was not a problem with errors in the job.

My previous config was Oban 2.13 with the tcp keepalive options commented here https://github.com/sorentwo/oban/issues/493#issuecomment-1251063561. It was working fine, then I update it to Oban 2.14 and was experiencing the jobs becoming stuck in available again (still using the tcp keepalive options). 

It happened 1 or possibly 2 times (we got a report one time but couldn't see the problem live). The other time we had more or less 30 jobs in the available state and none executing. It stopped executing jobs for around 3 hours and then it got back on track without any interference. This was last week and we didn't experience any other problems since then.

Unfortunately I don't have any debug info from the day it happened, but I wanted to inform you about this possible bug. Let me know if I can obtain more info on this, or if this is a known problem :)

Thanks!

**Comment by sorentwo** [comment]
> Unfortunately I don't have any debug info from the day it happened, but I wanted to inform you about this possible bug. Let me know if I can obtain more info on this, or if this is a known problem

If this happens again please check your logs for messages from the stager about switching modes. If it has switched to `local` mode and still no jobs are running, then the problem isn’t related to staging.

**Comment by jotaviobiondo** [comment]
Hey! We don't see any logs related to Oban, but this is what the config looks like when we notice the jobs stoping executing:

```elixir
%Oban.Stager.State{
  conf: %Oban.Config{
    dispatch_cooldown: 5,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    log: false,
    name: ImporterOban,
    node: "importer@98d32458032e",
    notifier: Oban.Notifiers.Postgres,
    peer: Oban.Peers.Postgres,
    plugins: [
      {Oban.Plugins.Lifeline, []},
      {Oban.Plugins.Pruner, [max_age: 86400]}
    ],
    prefix: "importer",
    queues: [processing_queue: [limit: 5]],
    repo: NL.Repo,
    shutdown_grace_period: 15000,
    stage_interval: 1000,
    testing: :disabled
  },
  name: {:via, Registry, {Oban.Registry, {ImporterOban, Oban.Stager}}},
  timer: #Reference<0.2693710710.2351955970.149646>,
  interval: 1000,
  limit: 5000,
  mode: :global,
  ping_at_tick: 60,
  swap_at_tick: 65,
  tick: 46
}
```

And this is the config when we notice jobs starting executing again:

```elixir
%Oban.Stager.State{
  conf: %Oban.Config{
    dispatch_cooldown: 5,
    engine: Oban.Engines.Basic,
    get_dynamic_repo: nil,
    log: false,
    name: ImporterOban,
    node: "importer@98d32458032e",
    notifier: Oban.Notifiers.Postgres,
    peer: Oban.Peers.Postgres,
    plugins: [
      {Oban.Plugins.Lifeline, []},
      {Oban.Plugins.Pruner, [max_age: 86400]}
    ],
    prefix: "importer",
    queues: [processing_queue: [limit: 5]],
    repo: NL.Repo,
    shutdown_grace_period: 15000,
    stage_interval: 1000,
    testing: :disabled
  },
  name: {:via, Registry, {Oban.Registry, {ImporterOban, Oban.Stager}}},
  timer: #Reference<0.2693710710.2353790978.154106>,
  interval: 1000,
  limit: 5000,
  mode: :global,
  ping_at_tick: 60,
  swap_at_tick: 65,
  tick: 27
}
```

So seems that the mode hasn't changed, right?

Any other thing we can do that might help us find the issue here?

**Comment by sorentwo** [comment]
The issue clearly isn't with the stager. I don't have any other guesses right now, but I'd look out for crashes reports or unusual errors in related processes. Considering your previous issues with TCP keepalive, I strongly recommend switching to `Oban.Notifiers.PG` if possible.
