### ISSUE TITLE
Pruner plugin fails on the Sqlite Engine

### ISSUE THREAD

**Issue by mindreframer** [sorentwo/oban#844]
Hey @sorentwo, thanks for the Sqlite engine! Just started to play with it and hit this bug. Did not dig deeper into it. maybe you'll get the root cause from the error. 

### Environment

- Oban Version: 2.14.1
- Sqlite: exqlite - 0.13.2
- Elixir & Erlang/OTP Versions (`elixir --version`)
- `Elixir 1.14.2 (compiled with Erlang/OTP 25`

### Current Behavior
```elixir
[error] GenServer {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Pruner}}} terminating
** (ArgumentError) JOINS are not supported on DELETE statements by SQLite
    (ecto_sqlite3 0.9.1) lib/ecto/adapters/sqlite3/connection.ex:233: Ecto.Adapters.SQLite3.Connection.delete_all/1
    (ecto_sqlite3 0.9.1) lib/ecto/adapters/sqlite3.ex:176: Ecto.Adapters.SQLite3.prepare/2
    (ecto 3.9.4) lib/ecto/query/planner.ex:182: Ecto.Query.Planner.query_without_cache/4
    (ecto 3.9.4) lib/ecto/query/planner.ex:152: Ecto.Query.Planner.query_prepare/6
    (ecto 3.9.4) lib/ecto/query/planner.ex:127: Ecto.Query.Planner.query_with_cache/8
    (ecto 3.9.4) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
    (oban 2.14.1) lib/oban/plugins/pruner.ex:164: Oban.Plugins.Pruner.delete_jobs/3
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
    (oban 2.14.1) lib/oban/plugins/pruner.ex:118: anonymous fn/2 in Oban.Plugins.Pruner.handle_info/2
    (telemetry 1.2.1) /Users/roman/Desktop/work/gigs-my/mojkmet_all/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.14.1) lib/oban/plugins/pruner.ex:117: Oban.Plugins.Pruner.handle_info/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :prune
State: %Oban.Plugins.Pruner.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Lite, get_dynamic_repo: nil, log: false, name: Oban, node: "Romans-Air", notifier: Oban.Notifiers.PG, peer: Oban.Peers.Isolated, plugins: [{Oban.Plugins.Pruner, []}], prefix: false, queues: [default: [limit: 10]], repo: Mojkmet.Repo, shutdown_grace_period: 15000, stage_interval: 1000, testing: :disabled}, name: {:via, Registry, {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Pruner}}}}, timer: #Reference<0.571617750.3134193665.201228>, interval: 30000, max_age: 60, limit: 10000}
```

### Expected Behavior

Pruner Pluigin should work with Sqlite

Thanks , 
Roman

**Comment by mindreframer** [comment]
Hmm.. That's the guy: 
- https://github.com/sorentwo/oban/blob/main/lib/oban/plugins/pruner.ex#L162
```elixir
subquery =
      Job
      |> or_where([j], j.state == "completed" and j.attempted_at < ^time)
      |> or_where([j], j.state == "cancelled" and j.cancelled_at < ^time)
      |> or_where([j], j.state == "discarded" and j.discarded_at < ^time)
      |> limit(^limit)
      |> lock("FOR UPDATE SKIP LOCKED")

    query =
      Job
      |> join(:inner, [j], x in subquery(subquery), on: j.id == x.id)
      |> select([_, x], map(x, [:id, :queue, :state, :worker]))

    {pruned_count, pruned} = Repo.delete_all(conf, query)

```


Maybe we do not need to lock the table in Sqlite, since it is single-writer only? Wdyt?

**Comment by mindreframer** [comment]
Here is a quick and dirty working version for Sqlite

```elixir
defp delete_jobs(conf, seconds, limit) do
  time = DateTime.add(DateTime.utc_now(), -seconds)

  select_query =
    Job
    |> or_where([j], j.state == "completed" and j.attempted_at < ^time)
    |> or_where([j], j.state == "cancelled" and j.cancelled_at < ^time)
    |> or_where([j], j.state == "discarded" and j.discarded_at < ^time)
    |> limit(^limit)
    |> select([:id])

  res = Repo.all(conf, select_query)
  ids = Enum.map(res, & &1.id)
  del_query = from(j in Job, where: j.id in ^ids, select: [:id, :queue, :state, :worker])
  {pruned_count, pruned} = Repo.delete_all(conf, del_query)

  %{pruned_count: pruned_count, pruned_jobs: pruned}
end
```

It seems to work and returns the deleted jobs. Maybe have a prunner module for Sqlite (Oban.Plugin.PrunerLite, with this function and delegating the rest to Oban.Plugin.Prunner?

**Comment by sorentwo** [comment]
Thanks for reporting the issue and digging in to find a potential solution! The join is partially for locking and reporting the original state of the pruned jobs for accurate telemetry metadata.

My original plan was to add a `prune_jobs` engine callback to push this down to the adapter layer. Then the pruner plugin is responsible for coordinating pruning, not running the actual queries. Here are the options I see:

1. Introduce a `prune_jobs/2` engine callback (👍)
2. Make a new plugin for lite pruning (👎, it duplicates a lot of logic and complicates config)
3. Put a conditional in the pruner (👎, that doesn't play nicely with Pro or other engines in the future)

I'm exploring the first option now.

**Comment by mindreframer** [comment]
@sorentwo Whatever works best longterm! I'll use my workaround until there is an official solution for that issue. And yes, the `prune_jobs` callback is much more maintainable, since every adapter (I saw there is demand for MySQL support 😃  ) would  take that responsibility. 

What I like about the Plugin approach, is that I could plug my own workaround without hacking anything. It's just a copy-pasted module that is useful in my app. When this functionality happens on the adapter level, it will be probably harder to go off the beaten path when needed... Just food for thought. 

```elixir
  ... 
  plugins: [{Ext.Oban.Plugins.Pruner, max_age: 10}],
  queues: [default: 10]
```

Have a nice Sunday!

**Comment by sorentwo** [comment]
The callback/adapter approach is for the standard pruner plugin. Both the callback and the plugin are optional—you can always use your own custom pruner plugin.

**Comment by mindreframer** [comment]
Very good! Then `prune_jobs/2` engine callback is the way to go. Thanks for the clarification!

**Comment by mindreframer** [comment]
Thanks!

**Comment by carterbryden** [comment]
Sorry to ressurect this, but is there a prune_jobs/2 callback now in 2.14.2? I'm not seeing anything in the docs.

Otherwise I can go with mindreframer's copy pasted engine solution. 

I ran into this issue with a fresh install of oban and sqlite following the docs so I imagine everyone who runs oban on sqlite is running into this right now.

**Comment by sorentwo** [comment]
That fix isn’t released yet. It will be in the upcoming 2.15, due out next week.
