### ISSUE TITLE
Dependency resolution failed with Oban web and live view 0.18.16

### ISSUE THREAD

**Issue by Arp-G** [sorentwo/oban#859]
### Environment

- Oban Version - 2.14
- Elixir & Erlang/OTP Versions - Elixir 1.14.2 (compiled with Erlang/OTP 24)

### Current Behavior

We were trying to upgrade live view in a project which is also using oban web.
With `mix.exs` having

```
{:phoenix_live_view, "~> 0.18.16"}
{:oban_web, "~> 2.9", repo: "oban"}
```

FYI, its a umberalla app so 2 of the other apps has oban in its mix file like `{:oban, "~> 2.14"}`

Dependency resolution fails with the following error
```
❯ mix deps.get                 

11:42:47.149 [info] Develop app env detected, app version: 1.49.1-dev
Resolving Hex dependencies...
Resolution completed in 0.769s
Because the lock depends on oban/oban_web 2.9.1 which depends on phoenix_live_view ~> 0.17.4, the lock requires phoenix_live_view ~> 0.17.4.
And because your app depends on the lock, phoenix_live_view ~> 0.17.4 is required.
So, because your app depends on phoenix_live_view ~> 0.18.16, version solving failed.
** (Mix) Hex dependency resolution failed
```

This is preventing us from upgrading to the latest version of live view while also using Oban dashboard. Would really appreciate some help regarding this. Thanks!

### Expected Behavior

Successfully use oban web with the latest version of phoenix live view.

**Comment by sorentwo** [comment]
There are [newer releases of Web](https://getoban.pro/docs/web/2.9.6/changelog.html#v2-9-5-2022-09-23) that add support for LiveView v0.18. Upgrade `oban_web` to v2.9.5 or greater; you won't have those resolution issues 😄

**Comment by Arp-G** [comment]
Thanks a lot for your quick response :pray: This indeed solved the issue.
