### ISSUE TITLE
handle_cancelled not triggered for batch workers

### ISSUE THREAD

**Issue by dmolnar99** [sorentwo/oban#863]
### Environment

- Oban Version: 2.14.2, Oban Pro Version: 0.13.2
- PostgreSQL Version: 13
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.13.4, Erlang/OTP 24

### Current Behavior

`handle_cancelled` batch callback function is not called when one of the batch workers ends with `{:cancel, :some_reason}`.

### Expected Behavior

`handle_cancelled` batch callback function to be called.

**Comment by sorentwo** [comment]
That's surprising—there are tests for that specific behavior! I'm investigating.

**Comment by sorentwo** [comment]
@dmolnar99 Found and fixed. tl;dr don't trust limited property tests to cover edge cases!

**Comment by dmolnar99** [comment]
Thanks @sorentwo! Is the fix included in a patch already?

**Comment by sorentwo** [comment]
Not yet. I’ll release a new patch sometime today :+1:
