### ISSUE TITLE
Expose job completion ACK `retry_timeout` to config to allow for stronger exactly-once guarantees

### ISSUE THREAD

**Issue by eprothro** [sorentwo/oban#865]
Currently, if Oban cannot ACK to the job DB (e.g. connection error) after the `perform` or `process` function completes, it retries 10 times and the orphans the job.

It would be excellent to be able to configure this via another [Twiddly Option](https://hexdocs.pm/oban/Oban.html#start_link/1-twiddly-options)
* `:repo_retry_timeout` -  the number of milliseconds to continue retrying queries to the repo while processing a job. This is important when updating the job record of completion of an attempt, where an orphan will be created if we're not able to successfully update the record due to connection issues. Defaults to `:infinity`.

Separately from exposing this as a configuration option, I would prefer / expect to see the default for this option to be `:infinity`. Currently a infrastructure issue like connection pool starvation will result in orphaned jobs that will execute successfully more than once when rescued. The worse the root issue, the more we'll see the side-effect of more-than-once execution of our jobs. 

IMO a more natural / useful behavior is infinite retry that results in backpressure and a side-effect of reduced job throughput.

**Comment by sorentwo** [comment]
@eprothro After far too much deliberation, I opted for the infinite retry approach. The commit message summarizes this discussion and explains my rationale.

**Comment by eprothro** [comment]
🙌🏼
