### ISSUE TITLE
Oban Web fails when router helpers are disabled

### ISSUE THREAD

**Issue by jfpedroza** [sorentwo/oban#877]
### Precheck

It was previously reported in this [comment](https://github.com/sorentwo/oban/issues/805#issuecomment-1415998699), but I think it should be a separate issue.

### Environment

- Oban Version: 2.14.2
- Oban Web Version: 2.9.6

### Current Behavior

When disabling router helpers after updating to Phoenix 1.7

```elixir
  def router do
    quote do
      use Phoenix.Router, helpers: false
      ...
    end
  end
```

Oban Web throws an error like so:

    Server: localhost:4000 (http)
    Request: GET /admin/oban
    ** (exit) an exception was raised:
        ** (UndefinedFunctionError) function nil.oban_dashboard_path/3 is undefined
            nil.oban_dashboard_path(#Phoenix.LiveView.Socket<id: "phx-F1EHRTSfWfbYJxoB", endpoint: AppWeb.Endpoint, view: Oban.Web.DashboardLive, parent_pid: nil, root_pid: nil, router: AppWeb.Router, assigns: %{__changed__: %{}, flash: %{}, live_action: :home}, transport_pid: nil, ...>, :index, :jobs)
            (oban_web 2.9.6) lib/oban/web/components/layout_component.ex:66: anonymous fn/3 in Oban.Web.LayoutComponent.tabs/1
            (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
            (oban_web 2.9.6) lib/oban/web/components/layout_component.ex:64: anonymous fn/2 in Oban.Web.LayoutComponent.tabs/1
            (oban_web 2.9.6) .../deps/oban_web/lib/oban/web/dashboard_live.ex:47: Oban.Web.DashboardLive.render/1
            ...

### Expected Behavior

Oban Web should work even with router helpers disabled or mention in the docs that is a requirement.

**Comment by sorentwo** [comment]
Thanks for the prompt. The upcoming Web version won't require helpers, and in the meantime, I've updated the installation guides to mention that they're required for 1.6/1.7 compatibility: https://getoban.pro/docs/web/2.9.6/installation.html#mounting-the-dashboard
