### ISSUE TITLE
Pruning beats separately from jobs

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#88]
### Is your feature request related to a problem? Please describe.

Our beats table is growing very quickly, and for the time being we're not pruning any completed or discarded jobs in the jobs table. Is it safe to prune the beats w/o negatively affecting the jobs?

### Describe the Solution You'd Like

A sweeper that's independent of the pruner.

### Describe Alternatives You've Considered

`DELETE FROM oban_beats;`

**Comment by sorentwo** [comment]
> Is it safe to prune the beats w/o negatively affecting the jobs?

It is safe to prune beats that are more than a minute old. The UI relies on beats for a lot of what it displays, but it will recover after a few seconds if you delete _all_ the beats.

> A sweeper that's independent of the pruner.

Separate configuration for this could work. Currently beat pruning isn't configurable at all, which may be an issue for limited databases (i.e. entry tier heroku which only allows 10,000 rows).

If you were to enable pruning with a really long history (months, years) you would retain all of the jobs and get the automatic beat pruning.

**Comment by jc00ke** [comment]
Yeah, we're on the hobby Heroku plan and we're about to hit the 10M record limit. Enabling a long history should do the trick. Thanks!

**Comment by sorentwo** [comment]
Glad that will work!

If there is somewhere in the docs you'd have liked/expected to see this info, let me know (or open a PR 💛).
