### ISSUE TITLE
`Oban.insert_all` spec is ambiguous

### ISSUE THREAD

**Issue by sega-yarkin** [sorentwo/oban#880]
### Environment

- Oban Version: 2.14.2
- PostgreSQL Version: N/A
- Elixir & Erlang/OTP Versions (`elixir --version`): Elixir 1.14.2, Erlang/OTP 25

### Current Behavior

When Dialyzer's `missing_return` warning is enabled, it starts complain about that `Ecto.Multi.t()` return from `Oban.insert_all` is not handled, even though changeset wrapper (`Workflow`) is used (so it's expected that return would be `[Job.t()]`).

I've looked if that's possible to split the spec into two separate and clear paths, like:
```elixir
@spec insert_all(multi(), multi_name(), Keyword.t() | changesets_or_wrapper_or_fun()) :: multi()
@spec insert_all(name(), changesets_or_wrapper(), Keyword.t() | changesets_or_wrapper_or_fun()) :: [Job.t()]
```

but both `name()` and `multi_name()` are type of `any()` (the most broad type) which triggers `overlapping_contract` error.

Looks like this would work fine (when `changesets_or_wrapper()` and `name()` are swapped):
```elixir
@spec insert_all(multi(), multi_name(), Keyword.t() | changesets_or_wrapper_or_fun()) :: multi()
@spec insert_all(changesets_or_wrapper(), name(), Keyword.t() | changesets_or_wrapper_or_fun()) :: [Job.t()]
```
but this is most likely an API breaking change.

### Expected Behavior

No complains from Dialyzer

**Comment by sorentwo** [comment]
@sega-yarkin I've enabled `missing_return` and expanded the compiled `insert_all` tests. While `missing_return` caught a few issues, I don't see an `overlapping_contract` error. Can you share an example of the code that dialyzer is flagging?

As an aside, changing the argument order is _definitely_ a breaking change and not viable.

**Comment by sega-yarkin** [comment]
Sorry, I should include the problem output in the first place, for example:
```elixir
@spec test() :: [Job.t()]
def test() do
  Oban.Pro.Workers.Workflow.new() |> Oban.insert_all()
end
```
Dialyzer would say something like:
```elixir
________________________________________________________________________________
lib/test.ex:20:missing_range
The type specification is missing types returned by function.

Function:
Test.test/0

Type specification return types:
[
  %Oban.Job{...}
]

Missing from spec:
%Ecto.Multi{
  :names => %MapSet{:map => MapSet.internal(_), :version => _},
  :operations => [{_, {_, _} | {_, _, _} | {_, _, _, _}}]
}

```

`overlapping_contract` happens when I tried to update spec to that I suggested above. Thank you!

**Comment by sorentwo** [comment]
@sega-yarkin Will you see if the same warning exists with the latest Pro v0.14 release?

**Comment by sega-yarkin** [comment]
@sorentwo looks like nothing has changed, same warning:
```elixir
Missing from spec:
%Ecto.Multi{
  :names => %MapSet{:map => MapSet.internal(_), :version => _},
  :operations => [{_, {_, _} | {_, _, _} | {_, _, _, _}}]
}
```

```elixir
# grep '"oban' mix.lock | cut -c -50
  "oban": {:hex, :oban, "2.15.0", "27b9c2845cdff30
  "oban_pro": {:hex, :oban_pro, "0.14.0", "1ff5416
```

**Comment by sorentwo** [comment]
The dialyzer issues appear to be from your typespec, not from Oban itself. There's no way for dialyzer to determine whether the result will be a list or a multi, so you need to spec the return as a union:

```elixir
  @spec insert_all_test() :: Ecto.Multi.t() | [Oban.Job.t()]
  def insert_all_test do
    Oban.Pro.Workers.Workflow.new() |> Oban.insert_all()
  end
```

The `insert_all` API is a bit overloaded, but any changes would break backward compatibility. You'll need to use a looser type-spec in your application.
