### ISSUE TITLE
Structured jobs fail when using {:array, :uuid}

### ISSUE THREAD

**Issue by jfpedroza** [sorentwo/oban#887]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

- Oban Version: 2.15.0
- Oban Pro Version: 0.14.0

### Current Behavior

Doing

```elixir
args_schema do
  field :some_ids, {:array, :uuid}
end
```

Fails to construct job with the following error:

     ** (UndefinedFunctionError) function :uuid.cast/1 is undefined (module :uuid is not available)
     code: perform_job(MyWorker, %{
     stacktrace:
       :uuid.cast("6e6c3b28-1000-4fe8-965b-334357ae0d67")
       (ecto 3.9.5) lib/ecto/type.ex:1250: Ecto.Type.array/4
       (ecto 3.9.5) lib/ecto/changeset.ex:600: Ecto.Changeset.cast_field/9
       (ecto 3.9.5) lib/ecto/changeset.ex:560: Ecto.Changeset.process_param/8
       (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.9.5) lib/ecto/changeset.ex:538: Ecto.Changeset.cast/6
       (oban_pro 0.14.0) lib/oban/pro/stages/structured.ex:61: Oban.Pro.Stages.Structured.gather_changes/2
       (oban_pro 0.14.0) lib/oban/pro/stages/structured.ex:30: Oban.Pro.Stages.Structured.before_new/3
       (oban_pro 0.14.0) lib/oban/pro/worker.ex:665: anonymous fn/2 in Oban.Pro.Worker.before_new/2

Changing to `{:array, :string}` works correctly.

### Expected Behavior

Should support a list of UUIDs.

**Comment by sorentwo** [comment]
Thanks for the report! Fixed on main, but you're safe to use `{:array, :string}` in the meantime.
