### ISSUE TITLE
Incompatibility with Ecto 3.10.1

### ISSUE THREAD

**Issue by ViseLuca** [sorentwo/oban#890]
### Precheck
When I try to upgrade to Ecto 3.10.1 I am receiving the following error:

### Environment

- Oban Version: 2.15.0
- PostgreSQL Version: 11.6
- Elixir & Erlang/OTP Versions: 1.14.4-otp25

### Current Behavior

he following arguments were given to Ecto.Adapters.Postgres.Connection.limit/2:
     
         # 1
         #Ecto.Query<from j0 in Oban.Job, where: j0.state in ^..., where: j0.worker == ^... and (j0.queue == ^... and (fragment("? @> ?", j0.args, ^...) and ^...)), limit: 1, select: j0>
     
         # 2
         {{[[34, "public", 34], 46, [34, "oban_jobs", 34]], [111 | "0"], Oban.Job}, []}
     
     Attempted function clauses (showing 2 out of 2):
     
         defp limit(%{limit: nil}, _sources)
         defp limit(%{limit: %Ecto.Query.QueryExpr{expr: expr}} = query, sources)

Dependabot also opened the PR https://github.com/sorentwo/oban/pull/884 but it's now showing a similar error, so I preferred to open in issue :) Thank you!

**Comment by sorentwo** [comment]
PR #884 isn't failing after a few other dependency upgrades (`mix deps.update ecto_sql` fixed it for that branch). Give that a try and you should be good!

**Comment by ViseLuca** [comment]
> PR #884 isn't failing after a few other dependency upgrades (`mix deps.update ecto_sql` fixed it for that branch). Give that a try and you should be good!

In my branch I'm trying to update Ecto to 3.10.1 and as soon as I try to run test it is going to brake with that errors

**Comment by ViseLuca** [comment]
@sorentwo I am still receving error, this one with ecto 3.10.1 and same with ecto_sql 3.10.1. I tried to update both ma nothing seems to fix it

```
** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.Connection.cte_expr/3

     The following arguments were given to Ecto.Adapters.Postgres.Connection.cte_expr/3:
     
         # 1
         {"subset", %{}, #Ecto.Query<from j0 in Oban.Job, where: j0.state == "available", where: j0.queue == ^..., order_by: [asc: j0.priority, asc: j0.scheduled_at, asc: j0.id], limit: ^..., lock: "FOR UPDATE SKIP LOCKED", select: %{id: [:id].id}>}
     
         # 2
         {{[[34, "public", 34], 46, [34, "oban_jobs", 34]], [111 | "0"], Oban.Job}, {nil, [102 | "1"], nil}, []}
     
         # 3
         #Ecto.Query<from j0 in Oban.Job, join: f1 in fragment("\"subset\""), on: true, where: j0.id == f1.id, update: [set: [state: ^..., attempted_at: ^..., attempted_by: ^...], inc: [attempt: ^...]], select: j0>
         |> with_cte("subset", materialized: nil, as: #Ecto.Query<from j0 in Oban.Job, where: j0.state == "available", where: j0.queue == ^..., order_by: [asc: j0.priority, asc: j0.scheduled_at, asc: j0.id], limit: ^..., lock: "FOR UPDATE SKIP LOCKED", select: %{id: [:id].id}>)
     
     Attempted function clauses (showing 1 out of 1):
     
         defp cte_expr(-{name, cte}-, sources, query)
     
     code: assert %{success: 1, failure: 0} = Oban.drain_queue(queue: :scheduled_emails, with_scheduled: true)
     stacktrace:
       (ecto_sql 3.9.2) Ecto.Adapters.Postgres.Connection.cte_expr/3
       (ecto_sql 3.9.2) lib/ecto/adapters/postgres/connection.ex:1381: Ecto.Adapters.Postgres.Connection.intersperse_map/4
       (ecto_sql 3.9.2) lib/ecto/adapters/postgres/connection.ex:406: Ecto.Adapters.Postgres.Connection.cte/2
       (ecto_sql 3.9.2) lib/ecto/adapters/postgres/connection.ex:153: Ecto.Adapters.Postgres.Connection.update_all/2
       (ecto_sql 3.9.2) lib/ecto/adapters/postgres.ex:127: Ecto.Adapters.Postgres.prepare/2
       (ecto 3.10.1) lib/ecto/query/planner.ex:182: Ecto.Query.Planner.query_without_cache/4
       (ecto 3.10.1) lib/ecto/query/planner.ex:152: Ecto.Query.Planner.query_prepare/6
       (ecto 3.10.1) lib/ecto/query/planner.ex:127: Ecto.Query.Planner.query_with_cache/8
       (ecto 3.10.1) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
       (oban 2.15.0) lib/oban/engines/basic.ex:117: anonymous fn/4 in Oban.Engines.Basic.fetch_jobs/3
       (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
       (oban 2.15.0) lib/oban/queue/drainer.ex:67: Oban.Queue.Drainer.fetch_available/2
       (oban 2.15.0) lib/oban/queue/drainer.ex:44: Oban.Queue.Drainer.drain/3
```

**Comment by sorentwo** [comment]
That stack trace shows `ecto_sql 3.9.2`, not `3.10.1`. Are you sure you upgraded?

Oban definitely works with `3.10.1`. Here are all the ecto packages as listed in Oban's `mix.lock` file currently:

```elixir
  "ecto": {:hex, :ecto, "3.10.1", ...
  "ecto_sql": {:hex, :ecto_sql, "3.10.1", ...
  "ecto_sqlite3": {:hex, :ecto_sqlite3, "0.10.0", ...
```

**Comment by ViseLuca** [comment]
> That stack trace shows `ecto_sql 3.9.2`, not `3.10.1`. Are you sure you upgraded?
> 
> Oban definitely works with `3.10.1`. Here are all the ecto packages as listed in Oban's `mix.lock` file currently:
> 
> ```elixir
>   "ecto": {:hex, :ecto, "3.10.1", ...
>   "ecto_sql": {:hex, :ecto_sql, "3.10.1", ...
>   "ecto_sqlite3": {:hex, :ecto_sqlite3, "0.10.0", ...
> ```

I tried to update ecto and ecto_sql in different branches and not together, it works ty!
