### ISSUE TITLE
Add first-class support for reliable execution guarantees to DynamicCron 

### ISSUE THREAD

**Issue by eprothro** [sorentwo/oban#892]
### Is your feature request related to a problem? Please describe.

Depending on process restart timing or infrastructure downtime, periods scheduled for job staging via `DynamicCron` can be missed. 

### Describe the Solution You'd Like

Currently, `DynamicCron`  crons only stage on the first edge (minute) of the active period. 

I'd like to see the default behavior of DynamicCron be that a job is staged any time (e.g. on startup or every beginning of minute thereafter) during the active period if a cron of that name has not been staged for that period. 

Another way of describing this desired default behavior is that the cron period expires when the next period begins. An option along these lines could be created to allow overriding the default period expiration implied by the cron expression. The current behavior could be described as `period_expires: 0` since the staging period effectively expires immediately.

### Describe Alternatives You've Considered

Currently, we can force a somewhat similar behavior by configuring the cron expression for every 1 minute, and set our actual preferred period using the uniqueness period as discussed in #630. However, we lose the ability to specify the cron schedule of the job. Would prefer to see something less opaque for first-class support of reliable crons.

This can also be achieved with a convention of a scheduled job that stages a scheduled job for the next period. This is both more fragile and more opaque that preferred.

My preference is to have the schedule of my crons declared both clearly and in one place within my codebase.

#### separate history

I'd prefer to see this behavior be durable across deletions of crons. If I delete and/or upsert a cron, I see this as a configuration change and would like the history taken into account not be affected.

This implies a separate table like a `oban_cron_stages` that keeps track of the most recent stage per cron name. 

#### schedule changes

#630 mentioned the problem of schedule changes. 

The default behavior described above matches what I would expect through a schedule change. If the last run is within the currently defined period, there is nothing to stage. If this is not the desired behavior of a cron entry author, then the cron can be deleted and inserted with a new name, creating a new cron with a fresh history beginning now.

```
{"0 0 * * 1", MyApp.DomainResource.Action, name: "weekly action",  delete: true},
{"0 0 * * *", MyApp.DomainResource.Action, name: "daily action"},
```

**Comment by sorentwo** [comment]
Thanks for opening this issue with additional context. As shown with #630 and discussed separately, this is something I'd like to support. I'll follow up before starting on this effort.

**Comment by eprothro** [comment]
We have implemented DynamicCron as a replacement tech for our scheduled jobs in one environment to see how the lack of this feature may or may not affect us. We see that a decent percentage of our deployments result in a dropped job (scheduled for each minute). These are heartbeat jobs responsible for reporting to an uptime service, so we see extra operational noise as a side effect. 

Our assumption was that this would rarely happen as old worker processes (Peer set A) would have to shut down just before the minute boundary (to miss the cron minute eval and thus not queue the cron job) and new worker processes (peer set B) would have to start up after the minute boundary (to miss the cron minute eval). 

Since this environment has serial restarts (e.g. not rolling / blue-green deployments), and with a total restart time of 15 seconds (shutdown, code loading, start up), this explains the dropped minutely jobs on something like 10-20% of deployments.

Wanted to share as an anecdote here and in case others see similar. Excited to see this feature!

**Comment by eprothro** [comment]
Any update on the priority of this? We're evaluating what we're going to do with the ops noise we're experiencing with this. Thanks!

**Comment by sorentwo** [comment]
There hasn't been any progress on this because we were focused on Pro v1.0 and Web improvements. You can expect this in Pro v1.1.

**Comment by eprothro** [comment]
Fantastic, thanks for the update!-Evan ProthroSent from my mobileOn Jul 4, 2023, at 12:35, Parker Selbert ***@***.***> wrote:﻿
There hasn't been any progress on this because we were focused on Pro v1.0 and Web improvements. You can expect this in Pro v1.1.
