### ISSUE TITLE
Allow configuration for default priority

### ISSUE THREAD

**Issue by eprothro** [sorentwo/oban#893]
### Is your feature request related to a problem? Please describe.

High priority jobs (e.g. a heartbeat job) can't be easily elevated above other default priority jobs, as the default priority is the highest priority allowed.

### Describe the Solution You'd Like

Allow global configuration for the default priority of a job (currently 0).

### Describe Alternatives You've Considered

Explicitly setting priority for every oban job, using application configuration to set to this to a default value. 

### Other context

We'd like to run with job priorities aligning to  `high`, `normal`, `low`, and `background`, with a default of `normal`.

**Comment by sorentwo** [comment]
Default priority is defined in the jobs table. The easiest way to change it for all jobs is to change the column default:

```elixir
alter table("oban_jobs") do
  modify :priority, :integer, default: 1
end
```

Alternatively, you could set a compile time value in your application and reference it in each worker. Oban doesn't define any global values and worker definitions live entirely in your application.

**Comment by eprothro** [comment]
perfect, thank you!

**Comment by eprothro** [comment]
While implementing, realized that the [Oban.Job schema](https://github.com/sorentwo/oban/blob/main/lib/oban/job.ex#L137) defines a default value of 0 for `priority`.

So, we don't have a way to globally set the default to 1 without modifying the code of every worker.

Can this Ecto schema default be removed since the DB schema defines a default?

**Comment by sorentwo** [comment]
Yes, the schema default can be removed. A PR is welcome!
