### ISSUE TITLE
Oban.Migration queries do not emit `schema_migration: true` in telemetry metadata

### ISSUE THREAD

**Issue by halostatue** [sorentwo/oban#898]
### Environment

- Oban 2.15.0
- PostgreSQL 13.5
- Elixir 1.14.4 (OTP 24)

### Current Behavior

This is half-way between a bug report and a feature request. It’s a feature request in the sense that this telemetry metadata is not documented and is only indirectly tested, but it is a part of the telemetry protocol for Ecto.Migration…and calling `Oban.Migration.up/1` or `Oban.Migration.down/2` causes query telemetry that does not include that as part of the telemetry options.

### Expected Behavior

Queries executed with Ecto.Migration send telemetry metadata that looks like this:

```elixir
%{
   cast_params: nil,
   options: [schema_migration: true],
   params: [],
   query: "…",
   repo: MyApp.Repo,
   result: {:ok, %Postgrex.Result{…}},
   source: nil,
   stacktrace: nil,
   type: :ecto_sql_query
 }
```

Oban queries send telemetry metadata like this:

```elixir
%{
   cast_params: nil,
   options: [],
   params: [],
   query: "…",
   repo: MyApp.Repo,
   result: {:ok, %Postgrex.Result{…}},
   source: nil,
   stacktrace: nil,
   type: :ecto_sql_query
 }
```

They should have `options: [schema_migration: true]`.

I’d open a PR, but I’m not *quite* sure where the extension to `telemetry_options` should go for the migration execution.

**Comment by sorentwo** [comment]
The `schema_migration: true` telemetry data is new to me. I'll dig into `ecto_sql` and see if/how to shim it into Oban's migrations.

Note: I'm following along with the Elixir discussion around auto-generating SQL from Ecto migrations. Migrations in Pro are _much_ simpler (there isn't any versioning necessary), and I'm happy to provide pure SQL alternatives if requested.

**Comment by halostatue** [comment]
I’ve had to put that investigation to the side for a bit, but I had been getting generally positive results. If I can get a couple more telemetry events added (probably just even a `:telemetry.span/4`, which adds two more vents), I think that I can get this working as a *simple* wrapper around `Mix.Task.run("ecto.migrate", args)`.

**Comment by sorentwo** [comment]
@halostatue Is this still necessary?

**Comment by halostatue** [comment]
I don‘t know that it was *necessary*, but if `schema_migration: true` were added to your own telemetry metadata when running those, all. Oban migrations could be captured using the approach I was looking at with telemetry and just filtering on cases where `schema_migration` is present. Otherwise, a migration capture (which I still plan on doing, but haven’t had time to finish) will need to sort of manually handle these.

**Comment by sorentwo** [comment]
After some investigation, it looks like the use of `schema_migration: true` is more nuanced. Any `execute/1` call, within Oban's migrations or not, doesn't include `schema_migrations`. There isn't a clause of `execute/2` that allows passing in additional options such as telemetry.

Changing all use of `execute/1` is too invasive for my taste, and since this isn't a bug in Oban, I'm going to close this.

**Comment by halostatue** [comment]
Fair enough. It may be worth exploring a migration wrapper function that would add this automatically add this for any executes that are called inside it. But that’s something to explore on the Ecto repos.
