### ISSUE TITLE
Required postgres version for running Oban

### ISSUE THREAD

**Issue by axelson** [sorentwo/oban#9]
From the readme I can see that *developing* Oban requires PostgreSQL 10+, does running Oban require PostgreSQL 10+ as well or is there a lower version requirement?

**Comment by sorentwo** [comment]
@axelson Technically PostgreSQL 9.5+ includes `FOR UPDATE SKIP LOCKED`, which is the newest feature I know of. I had initially planned on using native partitioning for pruning but backed off on that. 

So, if you're running 9.5+ it should work for you. Please let me know if that isn't the case!

I'll make this clear in the docs.

**Comment by axelson** [comment]
We're on 9.6 so that'll work for us! Thanks!

**Comment by sorentwo** [comment]
I've documented the minimum PG, Elixir and Erlang versions. Thanks @axelson 👍

**Comment by axelson** [comment]
Great, thanks!

**Comment by manukall** [comment]
Hey there. I noticed that the referenced commit mentions 9.6 as the minimum required PG version, while above you're talking about 9.5.

We're still stuck with 9.5 and were planning to switch to Oban. Do we need to wait until we can upgrade our Postgres servers?

**Comment by sorentwo** [comment]
@manukall There are a few changes since this issue that made 9.6 the minimum version. So sadly yes, you need to wait until you can upgrade PG.

**Comment by manukall** [comment]
@sorentwo Alright, thanks.
