### ISSUE TITLE
Oban.Pro.Queue.SmartEngine doesn't put oban telemetry metadata

### ISSUE THREAD

**Issue by fuelen** [sorentwo/oban#903]
### Environment

- Oban Version oban: 2.15.1, oban_pro: 0.14.1

### Current Behavior

I see the following logs with https://github.com/fuelen/ecto_dev_logger
```elixir
[debug] QUERY OK source="oban_jobs" db=0.9ms
UPDATE "public"."oban_jobs" AS o0 SET "state" = 'retryable', "scheduled_at" = '2023-05-18 10:10:09.291582Z', "errors" = array_append(o0."errors", '{"at":"2023-05-18T10:08:47.291613Z","attempt":6,"error":"** (Oban.PerformError) MY ERROR"}') WHERE (o0."id" = 196)
↳ Oban.Pro.Queue.SmartEngine.transaction/3, at: lib/oban/pro/queue/smart_engine.ex:745
```
it uses the following check to filter out Oban queries:
```elixir
not is_nil(metadata[:options][:oban_conf])
```
Currently, options are empty.

### Expected Behavior

Have something in metadata[:options][:oban_conf]

**Comment by sorentwo** [comment]
Thanks for the report. All fixed now.

Side note—I'd like to make an `Oban.Multi` alternative similar to `Oban.Repo` that automatically injects configuration options.
