### ISSUE TITLE
Invalid jobs are gracefully inserted but corrupted upon Oban.insert_all of a workflow

### ISSUE THREAD

**Issue by naserca** [sorentwo/oban#908]
### Environment

- Oban Version: `2.15.1`
- Oban Pro Version: `0.14.2`
- PostgreSQL Version: `14.5`
- Elixir & Erlang/OTP Versions (`elixir --version`):
  ```
  Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
  Elixir 1.14.3 (compiled with Erlang/OTP 25)
  ```

### Current Behavior

Workflow jobs that are invalid upon insert (due to should-be-failing `args_schema` validation) are gracefully inserted but corrupted, leading to (at least in one case) a failure to `fetch_recorded` its recorded value.

```elixir
defmodule Repro.StepOneWorker do
  use Oban.Pro.Workers.Workflow, queue: :default_queue, recorded: true

  args_schema do
    field :string_arg, :string, required: true
  end

  @impl true
  def process(_job) do
    {:ok, "recorded value"}
  end
end

defmodule Repro.StepTwoWorker do
  use Oban.Pro.Workers.Workflow, queue: :default_queue

  @impl true
  def process(job) do
    [step_one_job] = all_workflow_jobs(job, names: [:step_one])
    # this raises a `MatchError` since it returns `{:error, :missing}`
    {:ok, _value} = Repro.StepOneWorker.fetch_recorded(step_one_job)
    :ok
  end
end

defmodule Repro.Enqueuer do
  def call! do
    Repro.StepOneWorker.new_workflow()
    |> Repro.StepOneWorker.add(
      :step_one,
      Repro.StepOneWorker.new(%{
        string_arg: :oops_atom
      })
    )
    |> Repro.StepOneWorker.add(
      :step_two,
      Repro.StepTwoWorker.new(%{})
    )
    |> Oban.insert_all()
  end
end

Repro.Enqueuer.call!()
```

Interestingly the `meta` of the `Repro.StepOne` job _includes_ the `"return"` value:

```json
{"deps": [], "name": "step_one", "return": "g20AAAAOcmVjb3JkZWQgdmFsdWU", "workflow_id": "f4cf7f14-b6eb-46f8-85be-7167ffcd6508"}
```

but because the `"recorded": true` kv is missing, the value fails to be retrieved later.

### Expected Behavior

If a workflow job is invalid upon attempted insert, it should (I think!) error (raise is fine!) upon `Oban.insert_all`.

**Comment by naserca** [comment]
Personally I think reusing the `insert_all` naming (and functionality) while the actual arg is (at least in most cases) a single `%Oban.Pro.Workers.Workflow{}` struct (and not a bare list of entries as `Repo.insert_all` expects) begets something like `Oban.insert_workflow` or even reusing `Oban.insert` and `Oban.insert!`. Curious what you think!

**Comment by sorentwo** [comment]
Oban is isolated and unaware that Pro exists. We can't add Pro-specific functions to the core Oban module, and Elixir doesn't allow monkey patching (thankfully). Adding an `insert_all!/3` variant is a potential alternative.

**Comment by naserca** [comment]
`insert_all!` seems reasonable! similarly my other suggestions were attempts to avoid "use this function but you have to add this option to avoid a bug" in favor of just "use this completely different function."

**Comment by sorentwo** [comment]
@naserca Ultimately, I opted for a centralized change to `Job.to_map/1` to handle this consistently across all engines. Now all job changesets are validated during `insert_all`, and it's not possible to mistakenly insert an invalid changeset.

Note that previously sending a value like `max_attempts: 0`, `priority: -1`, `queue: ""`, etc. would have raised a Postgrex error rather than an Ecto error. Yes, this may raise in some unexpected situations, but it's more consistent than before.

**Comment by naserca** [comment]
thanks @sorentwo! makes sense.
