### ISSUE TITLE
dynamic queue's

### ISSUE THREAD

**Issue by jesuiswu** [sorentwo/oban#91]
Is there a way to create dynamic queues? on forehand I don't know the queues, I would like to create and queues on the fly ..

**Comment by sorentwo** [comment]
There isn't a built-in way to start new queues. I've seen this as a feature of some other libraries, but I've never understood the use case. Can you explain more about the queues you want to create?

1. How many dynamic queues would be created? 1, 5, 50?
2. How long are they expected to last? If you create a queue dynamically and something happens to the system then your jobs won't be rescued when the system starts back up.

There are a couple of ways to achieve dynamic queues, and it could be a possible feature, but I would like to understand the use cases first.

**Comment by jesuiswu** [comment]
my use case is, I do a ton of api calls to specific endpoints. 
for each endpoint I want to define a queue, how many concurrent workers there are etc.
now I have the configuration stored for each endpoint I a db.

I think I will reach about 300 queues?

**Comment by sorentwo** [comment]
Woah, that is a lot of queues! I think I understand the rationale now. Loading queues from the database on startup could work, but then you would be stuck if a new API endpoint is added while the system is running.

I'm still curious, why are you running a separate queue for each worker? Is it for rate limiting?

**Comment by jesuiswu** [comment]
multiple workers for a single queue, for example .. doing 5 calls at the same time for that specific endpoint, kind of rate limiting .. 

why would be stuck if a new API endpoint is added while running?

**Comment by sorentwo** [comment]
Sorry, I wasn't clear about the term "stuck". I meant that if you used this flow:

1. Start the system without oban
2. Read the queue info from the database
3. Start oban with the list of queues pulled from the database

That will work. However, you won't be able to start newly defined queues after the system has started.

I imagine you need one additional step:

4. Start a new queue when additional API endpoints are added while the system is running.

Does that sound right?

**Comment by jesuiswu** [comment]
that's correct :)

**Comment by sorentwo** [comment]
Update: I started work on adding `Oban.start_queue/2` and `Oban.stop_queue/2`. There is a lot happening right now though, so progress is slow.

**Comment by sorentwo** [comment]
@jesuiswu Dynamic queue start/stop added 👍

**Comment by jesuiswu** [comment]
🚀 thanks :)

**Comment by lud** [comment]
Hello @sorentwo , as far as I know, this does not work with `drain_queue`. Is it expected, or am I doing something wrong?

I am calling it like that : 

```
Oban.drain_queue(queue_prefix(account_id), with_safety: false, with_recursion: true)
```

And this is what I get:

```
** (RuntimeError) no config registered for ac:c5f54a52-fd43-4024-a52d-172626a7fbbd instance, is the supervisor running?
```

If this is not supported, Starting the queue and stopping it after a while is fine for me, I just want to know. Thank you.

**Comment by sorentwo** [comment]
@lud Draining is supported, but your syntax is wrong. The first argument is the Oban supervisor's name, `Oban` by default. As long as the supervisor is running you can drain like this:

```elixir
Oban.drain_queue(queue: queue_prefix(account_id), with_safety: false, with_recursion: true)
```

Note that I changed it to `queue: queue_prefix(account_id)`. If you need more help please ask on the Elixir Slack, Elixir Forum, or Elixir IRC.

**Comment by lud** [comment]
> If you need more help please ask on the Elixir Slack, Elixir Forum, or Elixir IRC.

Yes, sorry, I thought this could be a bug related to that feature.

But indeed my syntax was wrong! Thank you.
