### ISSUE TITLE
Faktory / Sidekiq Style Dashboard

### ISSUE THREAD

**Issue by chadfennell** [sorentwo/oban#93]
### Problem

I'd like to capture job states and failures through a UI of some kind e.g. like ![faktory](https://raw.githubusercontent.com/contribsys/faktory/master/docs/webui.png)

### Solution

I can imagine something sort of like Faktory's UI, but obviously Oban works a little differently (e.g. tends to keep many, many more jobs around for a lot, lot longer).

### Alternatives

I did a cursory search and didn't see anything like this out there for Oban, but I could have *totally* missed that effort. 

### Additional Comments

I'm pretty new to Elixir and have been poking at Oban as a replacement for a Ruby / Sidekiq project just for fun. I'd be really interested in working on some sort of UI on top of Oban (maybe a web UI, maybe even something on the terminal?) if it seems like something of interest - or maybe pitching in with an existing project.

Thoughts?

Thanks for all the work on this project, I'm really enjoying working with Oban so far.

**Comment by sorentwo** [comment]
@chadfennell There is an Oban UI available as a beta, and a website to facilitate signup will be up in the next couple of days.

A few more items that may be of interest:

- There was a similar issue tracking the UI progress for a while, see #28
- The [announcement post on the ElixirForum](https://elixirforum.com/t/oban-ui-private-beta/26182) has details about the UI and how to join the beta
- You can play with the UI demo here: https://oban.dev/oban

**Comment by chadfennell** [comment]
Oh cool! I will definitely sign-up for the beta. 

I think licensing the UI is a great idea and I totally support the effort if it helps make the OSS parts more sustainable!

Thanks again.
