### ISSUE TITLE
Clear ccnew indexes

### ISSUE THREAD

**Issue by thiamsantos** [sorentwo/oban#939]
### Is your feature request related to a problem? Please describe.

Hello, in our database we are getting some "phantom ccnew" indexes on the oban jobs.
It probably appears because we run the `Oban.Plugins.Reindexer` frequently.

![image](https://github.com/sorentwo/oban/assets/13632762/a1d9aa96-6ff2-42ab-9a35-7be60b1eaa87)

According the PostgreSQL docs:

> If the index marked INVALID is suffixed ccnew, then it corresponds to the transient index created during the concurrent operation, and the recommended recovery method is to drop it using DROP INDEX, then attempt REINDEX CONCURRENTLY again. If the invalid index is instead suffixed ccold, it corresponds to the original index which could not be dropped; the recommended recovery method is to just drop said index, since the rebuild proper has been successful.

https://www.postgresql.org/docs/current/sql-reindex.html

### Describe the Solution You'd Like

Would make sense to include on the Reindexer plugin a step to drop those `ccnew` indexes that could be added from previous runs?

### Describe Alternatives You've Considered

I thought about creating a recurrent job on my application to run the same logic. As it seems to be caused by the runs of the reindexer, makes sense to me to be a part of the plugin.

**Comment by taka41s** [comment]
Seems to still have a problem on this. The plugin runs but isn't reindexing the oban_jobs table.

**Comment by sorentwo** [comment]
> Seems to still have a problem on this. The plugin runs but isn't reindexing the oban_jobs table.

Does it work if you manually execute the reindex commands in your database?

**Comment by taka41s** [comment]
> > Seems to still have a problem on this. The plugin runs but isn't reindexing the oban_jobs table.
> 
> Does it work if you manually execute the reindex commands in your database?

Yes it does. I have created a custom plugin to reindex oban_jobs table.

**Comment by sorentwo** [comment]
> Yes it does. I have created a custom plugin to reindex oban_jobs table.

Are there any fixes or changes you can upstream from that?

**Comment by taka41s** [comment]
I made a few changes on the original reindex plugin and they're here.

```# lib/perimeter/oban/plugins/custom_reindexer.ex
defmodule Perimeter.Oban.CustomReindexer do
  @moduledoc """
  Custom reindex plugin
  """
  @behaviour Oban.Plugin

  use GenServer

  alias Oban.{Cron, Plugin, Repo, Validation}

  require Logger

  defstruct [
    :conf,
    schedule: "* * * * *",
    timeout: :timer.minutes(30),
    timezone: "America/Sao_Paulo"
  ]

  @impl Plugin
  def start_link(opts) do
    {name, opts} = Keyword.pop(opts, :name)
    GenServer.start_link(__MODULE__, struct!(__MODULE__, opts), name: name)
  end

  @impl Plugin
  def validate(opts) do
    Validation.validate_schema(opts,
      conf: :ok,
      name: :ok,
      schedule: :schedule,
      timeout: :timeout,
      timezone: :timezone
    )
  end

  @impl Plugin
  def format_logger_output(_conf, _meta), do: %{}

  @impl GenServer
  def init(state) do
    Process.flag(:trap_exit, true)

    :telemetry.execute([:oban, :plugin, :init], %{}, %{conf: state.conf, plugin: __MODULE__})

    Cron.schedule_interval(self(), :reindex, state.schedule, state.timezone)

    {:ok, state}
  end

  @impl GenServer
  def handle_info(:reindex, state) do
    meta = %{conf: state.conf, plugin: __MODULE__}

    :telemetry.span([:oban, :plugin], meta, fn ->
      case reindex(state) do
        :ok ->
          Logger.info("[CustomReindexer] ✓ Reindex done")
          {:ok, meta}

        {:error, error} ->
          Logger.error("[CustomReindexer] ✗ Error: #{inspect(error)}")
          {:error, Map.put(meta, :error, error)}
      end
    end)

    {:noreply, state}
  end

  def handle_info(message, state) do
    Logger.warning("[CustomReindexer] Error: #{inspect(message)}")
    {:noreply, state}
  end

  defp reindex(state) do
    query = "REINDEX TABLE CONCURRENTLY oban_jobs"

    Logger.info("[CustomReindexer] Running: #{query}")

    case Repo.query(state.conf, query, [], timeout: state.timeout) do
      {:ok, _} -> :ok
      {:error, _} = error -> error
    end
  end
end
```


Removed the Peer leader check and a few things to always run the reindex on oban_jobs table. Also instead of running 

`"REINDEX INDEX CONCURRENTLY #{prefix}.#{index}" `


I choose to run 

`"REINDEX TABLE CONCURRENTLY oban_jobs"` 

and it worked well.

**Comment by hez** [comment]
> FWIW, I don't suggest using the `Reindexer` unless you've identified bloat in your `args` or `meta` columns. The plugin was added to address a problem with some older PG versions accumulating bloat when indexing empty args/meta, and it shouldn't be necessary for most apps.

Do you have any ver number os Postgres for this?  What ver would you not run the reindexer plugin any more?

**Comment by taka41s** [comment]
> > FWIW, I don't suggest using the `Reindexer` unless you've identified bloat in your `args` or `meta` columns. The plugin was added to address a problem with some older PG versions accumulating bloat when indexing empty args/meta, and it shouldn't be necessary for most apps.
> 
> Do you have any ver number os Postgres for this? What ver would you not run the reindexer plugin any more?

Not anymore. The root cause was some dead indexes created by oban soo we had the original index and 3 other. I just runned a drop on those indexes and it worked. But I dont know how they were created.

**Comment by freemer** [comment]
> > FWIW, I don't suggest using the `Reindexer` unless you've identified bloat in your `args` or `meta` columns. The plugin was added to address a problem with some older PG versions accumulating bloat when indexing empty args/meta, and it shouldn't be necessary for most apps.
> 
> Do you have any ver number os Postgres for this? What ver would you not run the reindexer plugin any more?

@sorentwo Any guidance you can offer here?

**Comment by sorentwo** [comment]
> @sorentwo Any guidance you can offer here?

The original fix was for Postgres v14, which was fixed in subsequent patches. By default, the Reindexer only rebuilds the `args` and `meta` GIN indexes, it doesn't touch anything else. Those indexes are still prone to some bloat and there is some value to rebuilding.

As of Pro v1.7 (not OSS), we recommend dropping the `args` and `meta` indexes entirely, which makes the Reindexer a no-op by default.
