### ISSUE TITLE
Oban Web - User Authorization

### ISSUE THREAD

**Issue by chatamov** [sorentwo/oban#944]
Hi, Thank you so much for the amazing platform!
I have one point that I would appreciate help with
I want to use Oban.Web.Resolver for security
fetch the jwt from the conn to get the right user,
I put the oban-web as an iframe inside our admin app,
 For the first load, it works because I send to token in the header to get the iframe content,
On the first load, it works fine because the token is found but in all the other clicks I have no control over the requests that are sent and on the resolve_user function it falls
My question is why does every click open a new socket? Wouldn't it be more effective to open one socket and use it to perform all communication?
Do you have a solution that can help me?

**Comment by sorentwo** [comment]
Each click shouldn't open a new socket. Can you verify that the live socket connects and it isn't erroring out?

**Comment by chatamov** [comment]
<img width="936" alt="Screen Shot 2023-08-29 at 23 09 21" src="https://github.com/sorentwo/oban/assets/54079738/46188eac-ac95-424f-93ce-6cca567899bb">

**Comment by chatamov** [comment]
Each socket works until the next click which opens a new socket

**Comment by sorentwo** [comment]
Which version of Oban Web are you using? Will you try this with the latest v2.10.0-rc.2?

**Comment by chatamov** [comment]
oban-web 2.9.7

**Comment by chatamov** [comment]
I updated to the latest version - v2.10.0-rc.2
And the problem is solved
Thank you!!

**Comment by sorentwo** [comment]
That's great to hear!
