### ISSUE TITLE
Adding a blocking option in resolve_access

### ISSUE THREAD

**Issue by chatamov** [sorentwo/oban#947]
### Is your feature request related to a problem? Please describe.

In our system, the permissions types include an option of blocking (no permission to view or edit)
In the Oban.web.resolver in the `resolve_access` function, it is not possible to add a blocking option 

### Describe the Solution You'd Like

Adding a blocking option in resolve_access

**Comment by sorentwo** [comment]
Great suggestion. This exact feature was added after RC2 and will be in the next release 😁
