### ISSUE TITLE
Oban.cancel_job does not trigger batch callback handlers

### ISSUE THREAD

**Issue by eprothro** [sorentwo/oban#949]
### Environment

- Oban 2.15.1, Oban Pro 0.14.0
- Postgre 15
- Elixir 1.13.4 (compiled with Erlang/OTP 23)

### Current Behavior

Calling `Oban.cancel_job` results in batch callbacks not being fired when the cancelled job is the last job in a batch.

### Expected Behavior

It was not clear to us based on docs for `cancel_job` that callbacks would not be fired in this case. We expected that they would.

### Context

We're using a sentinel job inserted into a batch to keep it "open" until we're sure all jobs have been inserted. 

At that point we query for the sentinel job and cancel it. We prefer to do this over using an external resource (e.g. a record in the transactional schema or other store) to isolate orchestration mechanisms to Oban.

```elixir
def remove_sentinel(batch_id) do
   Oban.Job
    |> where([j], fragment("? @> ?", j.meta, ^%{batch_id: batch_id}))
    |> where([j], j.worker == "MyApp.Sentinel")
    |> MyApp.JobsRepo.all()
    |> Enum.each(fn sentinel_job ->
      Oban.cancel_job(sentinel_job)
    end)
   
  :ok
end
```

### Workaround

```elixir
def remove_sentinel(batch_id) do
   Oban.Job
    |> where([j], fragment("? @> ?", j.meta, ^%{batch_id: batch_id}))
    |> where([j], j.worker == "MyApp.Sentinel")
    |> MyApp.JobsRepo.all()
    |> Enum.each(fn sentinel_job ->
      sentinel_job
      |> Ecto.Changeset.change(%{args: %{batch_closed: true}})
      |> ListingEngine.JobsRepo.update()
    end)
   
  :ok
end
  ```

**Comment by sorentwo** [comment]
Thanks for the report. Fixed for the next release 👍
