### ISSUE TITLE
Question - Customizing Table Name

### ISSUE THREAD

**Issue by ryanpager** [sorentwo/oban#952]
So I've spent a few hours looking through the code, and looking through the config options. Maybe I'm struggling a bit here -- but is there a way to customize the table name for oban? If not, its not the end of the world, but Id rather not schema prefix it if possible.

**Comment by sorentwo** [comment]
No, there isn't any way to customize the table name(s). The Ecto schemas expect tables named `oban_jobs` and `oban_peers`. If you need multiple distinct tables then you must use separate prefixes.
