### ISSUE TITLE
Cron jobs are not compatible with Ecto 3.1.x 

### ISSUE THREAD

**Issue by sztosz** [sorentwo/oban#96]
### Environment

- Oban Version: **{:oban, "~> 0.11.0"}**
- PostgreSQL Version: **psql (PostgreSQL) 11.5** 
- Elixir & Erlang/OTP Versions (`elixir --version`) :
  **Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
  Elixir 1.9.1 (compiled with Erlang/OTP 22)**

### Current Behavior

Having jobs in crontab
```
config :merchant, Oban,
  repo: Merchant.Repo,
  queues: [queue: 10],
  verbose: :debug,
  crontab: [
    {"0 01 25 * *", Merchant.MonthlyJob},
  ]
```
Oban.Sheduler is terminating with error
```
GenServer Oban.Scheduler terminating
** (FunctionClauseError) no function clause matching in Ecto.Repo.Transaction.transaction/4
    (ecto) lib/ecto/repo/transaction.ex:5: Ecto.Repo.Transaction.transaction(Merchant.Repo, Merchant.Repo, #Function<1.128120480/1 in Oban.Crontab.Scheduler.lock_and_enqueue/1>, [log: :debug, timeout: 60000])
    (oban) lib/oban/crontab/scheduler.ex:95: Oban.Crontab.Scheduler.lock_and_enqueue/1
    (oban) lib/oban/crontab/scheduler.ex:70: Oban.Crontab.Scheduler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start} 
State: %Oban.Crontab.Scheduler.State{circuit: :enabled, circuit_backoff: 30000, conf: %Oban.Config{crontab: [{%Oban.Crontab.Cron{days: [25], hours: [1], minutes: [0], months: [:*], weekdays: [:*]}, Merchant.MonthlyJob, []}], name: Oban, node: "arch-ryzen", poll_interval: 1000, prefix: "public", prune: :disabled, prune_interval: 60000, prune_limit: 5000, queues: [billing: 10], repo: Merchant.Repo, rescue_after: 60, rescue_interval: 60000, shutdown_grace_period: 15000, verbose: :debug}, poll_interval: 60000, poll_ref: nil}
```

### Expected Behavior

Oban.Sheduler should not terminate with `no function clause matching in Ecto.Repo.Transaction.transaction/4` error

This problem is specific to ecto 3.1.7 and probably earlier versions. After upgrading ecto to 3.2.5 everything works correctly. It may be possible that's because upgrading ecto also upgrades ecto_sql.

I can't update Ecto at this moment due to issues not connected to Oban.

**Comment by sorentwo** [comment]
Thanks for the error report! The issues came from using a one-arity function instead of a zero-arity version, which was added by this PR: https://github.com/elixir-ecto/ecto/pull/3088. I didn't realize that was a new addition because it isn't listed in the Ecto CHANGELOG.

I've pushed a tiny fix (two characters) and I'll release v0.11.1 shortly.
