### ISSUE TITLE
Oban Web: Unable to filter by meta.workflow_id

### ISSUE THREAD

**Issue by cadebward** [sorentwo/oban#962]
Heyo! Enjoying the new UI. Thanks for all the good oban stuff!

### Environment

- Oban Web Version: 2.10.0-rc.3
- PostgreSQL Version: 15.2
- Elixir & Erlang/OTP Versions (`elixir --version`)

### Current Behavior

Querying by `meta.workflow_id` does not return any results. Manually querying database returns results as expected.

<img width="1011" alt="image" src="https://github.com/sorentwo/oban/assets/3212589/7d9d1caa-2a7b-437a-ba81-91b3b96c6b57">

### Expected Behavior

It should return results.

**Comment by sorentwo** [comment]
Thanks for the report. Working on a fix now.

**Comment by sorentwo** [comment]
Fixed for the next RC or patch 👍
