### ISSUE TITLE
Docs: Oban Pro wrong configuration instructions

### ISSUE THREAD

**Issue by mindreframer** [sorentwo/oban#966]
### Environment

- Oban Version: Oban Pro 1.1.4

### Current Behavior

https://getoban.pro/docs/pro/1.1.4/adoption.html
```elixir
  config :my_app, Oban,
+   engine: Oban.Pro.Engines.Smart,
    repo: MyApp.Repo
```

### Should be: 

```elixir
  config :my_app, Oban,
+   engine: Oban.Pro.Queue.SmartEngine,
    repo: MyApp.Repo
```

**Comment by sorentwo** [comment]
The guide is correct. As of Pro v1.0 the `SmartEngine` was renamed: https://getoban.pro/docs/pro/1.1.4/Oban.Pro.Engines.Smart.html

**Comment by mindreframer** [comment]
Well... Not sure what is going on then... 
This is what I have locally: 
Oban.Pro version: 0.14.3

Top part of the file for the smart engine: 

```elixir
defmodule Oban.Pro.Queue.SmartEngine do
  @moduledoc false

  @behaviour Oban.Engine
```

Filename: 
```bash 
$ find .|grep smart
./lib/oban/pro/queue/smart_engine.ex
```

`Oban.Pro.Engines.Smart` module does not exist in the latest Oban.Pro version. 
Are you sure the guide is correct? It seems not to match the 0.14.3 Oban.Pro code. 
Maybe I'm doing something weird? 

Cheers,
Roman

**Comment by sorentwo** [comment]
Pro v0.14.3 has `Oban.Pro.Queue.SmartEngine` and shows the correct engine in the [adoption guide](https://oban.pro/docs/pro/0.14.3/adoption.html). Pro v1.1.4 has `Oban.Pro.Engines.Smart` and shows the right engine in the [adoption guide](https://oban.pro/docs/pro/1.1.4/adoption.html).

My guess is that there's a mismatch between your local Pro version and the guide version you're looking at.

**Comment by mindreframer** [comment]
@sorentwo You are right! My fault. I was blindingly following the installation guide here: 
- https://oban.pro/docs/pro/1.1.4/installation.html

```elixir
{:oban_pro, "~> 0.13", repo: "oban"}
```

Guess this would be the place to update the docs then. 😄 

Thanks for the clarification!
