### ISSUE TITLE
Regression in `all_enqueued` handling of timestamp time zones

### ISSUE THREAD

**Issue by vlymar** [sorentwo/oban#977]
### Environment

- Oban Version: regression pinpointed to `f8e5785a60fd9d509a8a5c5456703d3ad53910d3`
- PostgreSQL Version: 11.16
- Elixir & Erlang/OTP Versions (`elixir --version`): Erlang/OTP 25, Elixir 1.14.5 (compiled with Erlang/OTP 25)
- `config :our_app, :oban, testing: :manual, log: :debug`

### Current Behavior

Hello, I think that https://github.com/sorentwo/oban/commit/f8e5785a60fd9d509a8a5c5456703d3ad53910d3 may have introduced a regression to time zone handling in `all_enqueued`'s matchers. Some of our tests broke while updating Oban, so I dug into the changeset and found the exact commit where the tests started failing. (note: afaict the tests also fail on the latest version of Oban so the regression has not been fixed).

I believe the simplest repro test case would insert a scheduled job with scheduled_at=X, then call `all_enqueued` and provide 
the `scheduled_at` value X shifted to another timezone.

### Detailed Logging

That commit changes how `all_enqueued` generates queries, so I added some debugging code:

```
❯ git diff
diff --git a/lib/oban/testing.ex b/lib/oban/testing.ex
index 76ffb9d..c515757 100644
--- a/lib/oban/testing.ex
+++ b/lib/oban/testing.ex
@@ -275,6 +275,9 @@ defmodule Oban.Testing do
   def all_enqueued(repo, opts) when is_list(opts) do
     {conf, opts} = extract_conf(repo, opts)

+    base_query(opts)
+    |> dbg
+
     Repo.all(conf, base_query(opts))
   end
```

I've included two sets of test output: the failing output from the newer commit and the passing output from the parent commit.
The output shows debug logs of oban inserting the row for the job and also the `dbg` output of the base query. You can see that in the failure case the dates are formatted as `#DateTime<... America/NewYork>` and in the passing cases they are UTC datetimes. I'm somewhat new to elixir and oban so I can't quite trace the problem past this point. I do notice that in in my pg query logs it seems like Oban / Ecto are not converting the time zone to UTC, I've included those params as well.

### Failing (after regression)

commit: `f8e5785a60fd9d509a8a5c5456703d3ad53910d3`

`all_enqueued` does not find job, test fails

```
[2023-10-23 15:33:20.686] [debug] QUERY OK db=1.1ms
INSERT INTO "workflow_scheduled_jobs" ("environment_id","recipient_gid","schedule_id","scheduled_oban_job_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT ("schedule_id","recipient_gid") DO UPDATE SET "scheduled_oban_job_id" = EXCLUDED."scheduled_oban_job_id","updated_at" = EXCLUDED."updated_at" [<<69, 244, 21, 149, 231, 45, 69, 226, 144, 127, 27, 165, 235, 34, 40, 84>>, "gid://Object/$users/5377ed7b-8647-4ebd-867b-e9f67edd30b6", "2XBRHj3kR0LbPf9cEkh7G3V6hfx", 80, ~U[2023-10-23 22:33:20.683987Z], ~U[2023-10-23 22:33:20.683987Z]] 
[2023-10-23 15:33:20.688] [debug] QUERY OK db=1.2ms
commit [] 
[lib/oban/testing.ex:279: Oban.Testing.all_enqueued/2]
base_query(opts) #=> #Ecto.Query<from j0 in Oban.Job, where: j0.state in ["available", "scheduled"],
 where: j0.worker == ^"Switchboard.Notifier.WorkflowExecutor",
 where: fragment(
  "? BETWEEN ? AND ?",
  j0.scheduled_at,
  ^#DateTime<2023-10-30 08:29:59-04:00 EDT America/New_York>,
  ^#DateTime<2023-10-30 08:30:01-04:00 EDT America/New_York>
),
 order_by: [desc: j0.id]>
```

query logs parameters: `$2 = '2023-10-30 08:29:59', $3 = '2023-10-30 08:30:01'` ❗ 

### Passing (before regression)

commit: `9ed1abaf5fb4d696de852c398e336db9dcad399b`

`all_enqueued` does find job, test passes.

```
[2023-10-23 15:38:21.413] [debug] QUERY OK db=0.7ms
INSERT INTO "workflow_scheduled_jobs" ("environment_id","recipient_gid","schedule_id","scheduled_oban_job_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT ("schedule_id","recipient_gid") DO UPDATE SET "scheduled_oban_job_id" = EXCLUDED."scheduled_oban_job_id","updated_at" = EXCLUDED."updated_at" [<<243, 210, 157, 7, 152, 90, 77, 126, 164, 240, 84, 113, 4, 220, 143, 175>>, "gid://Object/$users/355ddd63-035c-4e63-9268-42762a95b1f0", "2XBRtYIuklnLMvk54KzDOpYG663", 81, ~U[2023-10-23 22:38:21.411393Z], ~U[2023-10-23 22:38:21.411393Z]] 
[2023-10-23 15:38:21.414] [debug] QUERY OK db=0.3ms
commit [] 
[lib/oban/testing.ex:279: Oban.Testing.all_enqueued/2]
base_query(opts) #=> #Ecto.Query<from j0 in Oban.Job, where: j0.state in ["available", "scheduled"],
 where: fragment(
  "? BETWEEN ? AND ?",
  j0.scheduled_at,
  ^~U[2023-10-30 12:29:59.000000Z],
  ^~U[2023-10-30 12:30:01.000000Z]
),
 where: j0.worker == ^"Switchboard.Notifier.WorkflowExecutor",
 order_by: [desc: j0.id]>
```

query log parameters: `$1 = '2023-10-30 12:29:59', $2 = '2023-10-30 12:30:01',`

The postgres server timezone is UTC:
```
# show timezone;
 TimeZone
----------
 Etc/UTC
(1 row)
```

### Expected Behavior

We expect `all_enqueued` to find jobs regardless of `scheduled_at`'s TZ.

Sorry for the super long ticket. Happy to provide more debug info if needed!

**Comment by sorentwo** [comment]
Thanks for the long ticket; details are always appreciated.

As stated in the docs, scheduling is _always_ in UTC, and time zones should be shifted before scheduling. We can't shift timezones in Oban itself because tz databases are optional, and attempting to shift would break tests in any application without a tz database.

Would you be able to share the relevant parts of your failing test?

**Comment by vlymar** [comment]
> As stated in the docs, scheduling is always in UTC, and time zones should be shifted before scheduling.

@sorentwo thanks for the response. Unfortunately there's a lot of abstraction in the code that enqueues the jobs and the code that wraps `all_enqueued` so I don't think sharing it would be helpful. 

It does seem to me that somewhere along the way the timezone is being shifted when the job is scheduled. In my test if I print the scheduled_at parameter passed to our enqueue logic I see `"2023-10-30T08:30:00-04:00"`, an iso8601 EST timestamp. The logic then enqueues an oban job with the UTC shifted timestamp: `~U[2023-10-30 12:30:00.000000Z]`. 

```
INSERT INTO "public"."oban_jobs" (..."scheduled_at","...) VALUES (...) ON CONFLICT DO NOTHING RETURNING ... [... ~U[2023-10-30 12:30:00.000000Z], ...] 
```

Nothing about the insert logic changed between the two oban commits I pointed out. The issue is that`all_enqueued` changed to no longer correctly handle non-utc `scheduled_at` values for querying. 

If non-utc timestamps were never intended to be supported, I'd understand that and the workaround on our end is simple - we just shift `scheduled_at` to UTC before calling all_enqueued and things go back to working.

**Comment by sorentwo** [comment]
The insert params were the missing link, thanks!
