### ISSUE TITLE
Oban Crontab : make sure that the module exist and is a job

### ISSUE THREAD

**Issue by AntoineAugusti** [sorentwo/oban#978]
### Is your feature request related to a problem? Please describe.

This is related to an issue we just had https://github.com/etalab/transport-site/pull/3558. We refactored some code, renamed a job and forgot to update it in our `runtime.exs` therefore the module was not found at boot time.

### Describe the Solution You'd Like

Would it be possible to declare the Oban crontab configuration is a safer way, ensuring that modules exist and are `Oban.Job`s like [`perform_job/3`](https://hexdocs.pm/oban/Oban.Testing.html#perform_job/3) does?

Maybe we should register jobs through a function to validate arguments?

```elixir
config :my_app, Oban,
  plugins: [
    {Oban.Plugins.Cron,
     crontab: [
       Oban.cron({"* * * * *", MyApp.MinuteWorker}),
       Oban.cron({"0 * * * *", MyApp.HourlyWorker, args: %{custom: "arg"}}),
       Oban.cron({"0 0 * * *", MyApp.DailyWorker, max_attempts: 1}),
       Oban.cron({"0 12 * * MON", MyApp.MondayWorker, queue: :scheduled, tags: ["mondays"]}),
       Oban.cron({"@daily", MyApp.AnotherDailyWorker})
     ]}
  ]
```

**Comment by sorentwo** [comment]
The Cron plugin [already validates the existence of a module and that it's a worker](https://github.com/sorentwo/oban/blob/main/lib/oban/plugins/cron.ex#L222). In your case, the issue appears to be that the [crontab isn't configured outside of production](https://github.com/etalab/transport-site/blob/master/config/runtime.exs#L98).

The standard advice is to define the same config for all environments, including `test`, so tests automatically validate it. Eliminate [the conditional and configure the queues and plugins regardless](https://github.com/etalab/transport-site/blob/master/config/runtime.exs#L169); only set `testing: :manual` for the `test` environment.
