### ISSUE TITLE
assert_enqueued: Testing for scheduled_at, allow delta

### ISSUE THREAD

**Issue by maltoe** [sorentwo/oban#98]
Hello @sorentwo,

### Problem

I'd like to verify that my worker enqueued with `MyWorker.new(schedule_in: 60)` is really enqueued in 60 seconds. Strict matching on `scheduled_at` does not allow for time deltas.

```elixir
in_a_minute = DateTime.add(DateTime.utc_now(), 60, :second)

assert_enqueued(
  worker: "MyWorker",
  scheduled_at: in_a_minute
)

==> 

# line breaks for readability
Expected a job matching [
  worker: "MyWorker", 
  scheduled_at: ~U[2019-11-14 13:35:50.884648Z]
] to be enqueued. Found: [
  %{
    args: %{}, 
    scheduled_at: ~U[2019-11-14 13:35:50.875375Z], 
    worker: "MyWorker"
  }
]
```

### Possible Solution

If `scheduled_at` option is given to `assert_enqueued`, build a `BETWEEN` select clause with a (configurable) delta.

### Current workaround

```
  defp assert_scheduled_in(seconds) do
    actual =
      all_enqueued(worker: "EveryworksCalendar.PollEventStatusWorker")
      |> Enum.sort_by(& &1.inserted_at)
      |> List.first()
      |> Map.get(:scheduled_at)
      |> DateTime.to_unix()

    expected = 
      DateTime.utc_now()
      |> DateTime.add(seconds, :second)
      |> DateTime.to_unix()

    assert_in_delta actual, expected, 2
  end
```

I'd be glad to help out on this one, if you agree with the solution outlined.

cheers,
malte

**Comment by sorentwo** [comment]
Agreed! Matching on the exact `scheduled_at` timestamp is futile. I like the idea of using a `BETWEEN` with a delta, but I'm not sure if it needs to be customizable. The minimum resolution that Oban supports is one second, maybe we just support that? The timestamp could either be truncated or use a small delta.

I'd love some help if you're still up for it 👍
