### ISSUE TITLE
Consider allowing name in `Oban.insert/4` to be a string.

### ISSUE THREAD

**Issue by st23am** [sorentwo/oban#99]
### Problem
When trying to insert multiple jobs of the same worker type using Ecto.Muti in a single transaction
ie something like 
 ```
   jobs
    |> Enum.reduce(Ecto.Multi.new(), fn {name, job}, acc ->
      Oban.insert(acc, String.to_atom(name), job)
    end)
    |> Repo.transaction()
```
name currently is guarded to only match on an atom. It must also be uniq. (https://github.com/sorentwo/oban/blob/master/lib/oban.ex#L625) 

 Forcing uniqueness on an atom can in some cases result in growing the atom table. ie `String.to_atom/1` here

### Desired Feature

Currently `Ecto.Muti.insert/4` does not enforce / guard that the name() type in its definition to be an atom and allows for strings (https://github.com/elixir-ecto/ecto/blob/v3.2.5/lib/ecto/multi.ex#L133).

Doing the same for `Oban.insert/4` would allow for safer and easier naming of operations.

### Alternatives

To get around this I one could use `Ecto.Multi.insert/4` in place of `Oban.insert/4` however, this would not allow for use of the uniqueness feature I believe.

---
If I am mistaken in any of this I apologize. If this is acceptable I am willing to submit a pull request that implements this feature. 

Thank you for your time and for Oban!

**Comment by novaugust** [comment]
fyi, the ecto type for a multi name is
```ex
name() :: any()
```

**Comment by sorentwo** [comment]
Thanks for reporting this. You were absolutely right, there wasn't any reason to enforce that the name is an atom. 💛 

> If this is acceptable I am willing to submit a pull request that implements this feature.

I didn't notice that you offered to open a PR until after I pushed up the fix!

**Comment by st23am** [comment]
Thank you so much for getting to this so quickly!
