### ISSUE TITLE
Unstable test durations when using `Oban.Pro.Testing.run_workflow/2`

### ISSUE THREAD

**Issue by thiagopromano** [sorentwo/oban#991]
Considering a test case where a workflow of a job + 30 jobs depending on the first, running `Oban.Pro.Testing.run_workflow/2` takes inconsistently long, sometimes over 30 seconds.

After digging through the source code, I found out that the reason it takes so long is that `Oban.Pro.Testing.drain/3` takes only one job randomly at a time, making it a lottery for which one is picked.

Setting `with_limit` to a large value fixes the problem, as all jobs are executed in a round-robin fashion instead of randomly.

**Comment by sorentwo** [comment]
Thanks @thiagopromano. Increasing the parallelism via `with_limit` is the correct way to handle this, though not always desirable as a default, so I've documented setting a higher limit in the `run_workflow` docs.
